Repository siderolabs/talos, pull requests merged in 2019-08, with the labels that each got.

#936 fix: create overlay mounts after install
  internal/app/machined/main.go
Labels: kind/bug

#937 chore: run CI jobs on CI nodes
  .drone.yml
Labels: kind/cicd

#941 fix: mount the owned partitions in cloud platforms
  internal/app/machined/internal/platform/cloud/aws/aws.go
  internal/app/machined/internal/platform/cloud/azure/azure.go
  internal/app/machined/internal/platform/cloud/googlecloud/googlecloud.go
  internal/app/machined/internal/platform/cloud/vmware/vmware.go
  internal/pkg/mount/manager/owned/owned.go
  internal/pkg/mount/options.go
Labels: kind/bug

#968 chore: Wait a little after cluster comes up
  .drone.yml
  hack/test/conformance.sh
  hack/test/e2e-integration.sh
  hack/test/e2e-runner.sh
  hack/test/osctl-cluster-create.sh
Labels: [zube]: In Review

#966 chore: remove GitHub action workflow
  .github/main.workflow
Labels: [zube]: In Review

#967 chore: build drone YAML via jsonnet
  .drone.yml
  Dockerfile
  Makefile
  hack/drone.jsonnet
  hack/test/azure-setup.sh
  hack/test/basic-integration.sh
  hack/test/capi.sh
  hack/test/gce-setup.sh
  hack/test/osctl-cluster-create.sh
Labels: [zube]: In Review

#938 docs: add project layout standards
  docs/community/project-layout.md
Labels: [zube]: In Review, kind/documentation

#982 fix: enclose server address is bracks if IPv6
  cmd/osctl/pkg/client/client.go
  pkg/net/net.go
Labels: area/networking

#977 chore: refactor the Jsonnet file
  .drone.yml
  Makefile
  hack/drone.jsonnet
Labels: kind/cicd

#992 chore: add image test step
  .drone.yml
  Makefile
  hack/drone.jsonnet
Labels: kind/cicd

#997 fix(proxyd): do not pre-bracket IPv6 backend addrs
  internal/app/proxyd/internal/frontend/frontend.go
Labels: area/networking, kind/bug

#975 chore: add kernel parameters doc for bare-metal
  docs/content/guides/bare_metal.md
Labels: kind/documentation

#1011 feat: upgrade Linux to v5.2.8
  Dockerfile
Labels: area/kernel

#1023 feat(proxyd): Add gRPC server
  Dockerfile
  internal/app/proxyd/internal/reg/reg.go
  internal/app/proxyd/internal/reg/reg_test.go
  internal/app/proxyd/main.go
  internal/app/proxyd/proto/api.proto
  pkg/constants/constants.go
Labels: kind/feature

#1022 fix: verify installation definition
  cmd/osctl/cmd/install_linux.go
  internal/app/machined/internal/platform/baremetal/baremetal.go
  internal/app/machined/internal/platform/iso/iso.go
  internal/app/machined/internal/platform/packet/packet.go
  internal/pkg/installer/installer.go
  internal/pkg/installer/installer_test.go
  internal/pkg/installer/manifest/manifest.go
  internal/pkg/installer/manifest/manifest_test.go
  internal/pkg/installer/manifest/verify.go
  internal/pkg/installer/manifest/verify_test.go
Labels: kind/bug

#1045 feat: mount /sys/fs/bpf
  internal/app/machined/internal/phase/rootfs/mount_bpffs.go
  internal/app/machined/internal/phase/rootfs/mount_cgroups.go
  internal/app/machined/main.go
  internal/pkg/mount/manager/bpffs/bpffs.go
  internal/pkg/mount/manager/bpffs/bpffs_test.go
Labels: area/networking, kind/feature

#1089 fix: leave etcd when upgrading control plane node
  internal/app/machined/internal/phase/upgrade/leave_etcd.go
  internal/app/machined/internal/sequencer/v1alpha1/types.go
Labels: kind/bug
