Repository siderolabs/talos, pull requests merged in 2019-09, with the labels that each got.

#1116 fix: prevent EBUSY when unmounting system disk
  internal/app/machined/internal/phase/kubernetes/tasks.go
  internal/app/machined/internal/phase/rootfs/unmount_pod_mounts.go
  pkg/kubernetes/kubernetes.go
Labels: area/upgrades, kind/bug

#1125 feat: allow network interface to be ignored
  internal/app/machined/internal/phase/network/network.go
  internal/app/networkd/main.go
  internal/app/networkd/pkg/networkd/netconf.go
  internal/app/networkd/pkg/nic/nic.go
  internal/app/networkd/pkg/nic/options.go
  internal/pkg/kernel/kernel.go
  pkg/constants/constants.go
  pkg/userdata/networking.go
Labels: area/networking, kind/feature

#1147 feat: set expiry of certificates to 24 hours
  internal/app/machined/internal/phase/userdata/pki.go
  pkg/crypto/x509/x509.go
  pkg/userdata/userdata.go
Labels: area/security, kind/feature

#1151 fix: enable slub_debug=P
  hack/dev/qemu-boot.sh
  internal/pkg/kernel/kernel.go
  internal/pkg/kernel/kspp/kspp.go
Labels: area/kernel, area/security

#855 docs: add machine configuration proposal
  docs/proposals/20190708-MachineConfig.md
Labels: [zube]: In Review, area/machineconfig, kind/design

#1183 chore: fix AWS image dependency
  .drone.yml
  hack/drone.jsonnet
Labels: status/needs-cherry-pick

#1187 fix(machined): add nil checks to metal initializer
  internal/app/machined/internal/runtime/initializer/metal/metal.go
Labels: status/needs-cherry-pick

#1189 feat: upgrade Kubernetes to v1.16.0
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/golang/update-go-modules.sh
  hack/test/basic-integration.sh
  hack/test/conformance.sh
  internal/app/machined/pkg/system/services/kubeadm/kubeadm_test.go
  internal/pkg/installer/manifest/manifest_test.go
  pkg/constants/constants.go
  pkg/userdata/download/download_test.go
  pkg/userdata/userdata_test.go
Labels: status/needs-cherry-pick

#1192 fix: add kerenel config required by Cilium
  Dockerfile
Labels: status/needs-cherry-pick

#1195 fix: generate CA certificates with 1 year expiration
  pkg/userdata/generate/generate.go
  pkg/userdata/v1alpha1/generate/generate.go
Labels: status/needs-cherry-pick

#1199 fix: generate CA certificates with 10 year expiration
  pkg/userdata/generate/generate.go
  pkg/userdata/v1alpha1/generate/generate.go
Labels: status/needs-cherry-pick
