Repository siderolabs/talos, pull requests merged in 2019-10, with the labels that each got.

#1236 docs: Add machine config docs
  docs/content/configuration/masters.md
  docs/content/configuration/osd.md
  docs/content/configuration/v0-reference.md
  docs/content/configuration/v0-usage.md
  docs/content/configuration/v1alpha1-reference.md
  docs/content/configuration/v1alpha1-usage.md
  docs/content/configuration/workers.md
Labels: status/needs-cherry-pick

#1252 fix: create etcd data directory
  internal/app/machined/pkg/system/services/etcd.go
Labels: kind/bug

#1250 fix: ignore case in install platform check
  cmd/osctl/cmd/install_linux.go
Labels: kind/bug

#1258 fix: set target if specified on command line
  cmd/osctl/cmd/root.go
Labels: area/cli, kind/bug

#1260 fix: set kubelet-preferred-address-types to prioritize InternalIP
  go.mod
  go.sum
Labels: kind/bug

#1239 feat: add retry package
  internal/app/machined/pkg/system/services/etcd.go
  internal/pkg/mount/mount.go
  pkg/blockdevice/blockdevice.go
  pkg/blockdevice/probe/probe.go
  pkg/config/download.go
  pkg/kubernetes/kubernetes.go
  pkg/retry/constant.go
  pkg/retry/constant_test.go
  pkg/retry/exponential.go
  pkg/retry/exponential_test.go
  pkg/retry/linear.go
  pkg/retry/linear_test.go
  pkg/retry/options.go
  pkg/retry/options_test.go
  pkg/retry/retry.go
Labels: [zube]: In Review

#1273 fix: generate admin client certificate with 10 year expiration
  pkg/config/types/v1alpha1/generate/generate.go
Labels: area/cli, kind/bug

#1277 fix: Use correct names for kubelet config
  internal/app/machined/pkg/system/services/kubelet.go
  internal/app/machined/pkg/system/services/osd.go
  pkg/constants/constants.go
  pkg/kubernetes/kubernetes.go
Labels: kind/bug

#1271 fix: Make updating cert sans an append operation
  pkg/config/types/v1alpha1/cluster_config.go
  pkg/config/types/v1alpha1/machine_config.go
Labels: kind/bug

#1282 fix: retry endpoint discovery
  internal/app/machined/pkg/system/services/osd.go
Labels: kind/bug

#1286 fix: check if cluster network config is nil
  pkg/config/types/v1alpha1/cluster_config.go
Labels: kind/bug

#1291 fix: add slub_debug=P to ISO kernel args
  hack/installer/entrypoint.sh
Labels: status/needs-cherry-pick

#1111 fix: run only essential services in container mode
  internal/app/machined/internal/phase/services/start_services.go
Labels: [zube]: In Review, status/do-not-merge

#1366 feat: lock down container permissions
  go.mod
  internal/app/machined/pkg/system/runner/containerd/containerd.go
  internal/app/machined/pkg/system/services/apid.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/app/machined/pkg/system/services/networkd.go
  internal/app/machined/pkg/system/services/ntpd.go
  internal/app/machined/pkg/system/services/osd.go
  internal/app/machined/pkg/system/services/trustd.go
Labels: area/security

#1382 docs: add VMware docs to menu
  docs/website/content/v0.3.en.json
  docs/website/content/v0.3/en/guides/cloud/aws.md
  docs/website/content/v0.3/en/guides/cloud/digitalocean.md
  docs/website/content/v0.3/en/guides/cloud/vmware.md
Labels: kind/documentation

#1378 docs: add customization guide
  Dockerfile
  Makefile
  docs/website/assets/css/main.css
  docs/website/content/v0.3.en.json
  docs/website/content/v0.3/en/customization/index.md
  docs/website/content/v0.3/en/customization/kernel.md
Labels: kind/documentation
