Repository siderolabs/talos, pull requests merged in 2019-02, with the labels that each got.

#333 docs: improve the README
  README.md
Labels: docs

#334 feat: disable session tickets
  internal/pkg/grpc/tls/tls.go
Labels: enhancement

#335 feat: upgrade Kubernetes to v1.13.3
  Dockerfile
  Makefile
  go.mod
  go.sum
  internal/pkg/constants/constants.go
Labels: enhancement

#345 fix: add libblkid to the rootfs
  Dockerfile
Labels: bug

#378 fix: add iptables to rootfs
  Dockerfile
Labels: bug

#382 fix: ensure DNS works in early boot
  internal/app/init/main.go
Labels: bug

#395 feat: upgrade containerd to v1.2.4
  Dockerfile
  go.mod
  go.sum
Labels: enhancement

#401 feat: upgrade musl to 1.1.21
  Makefile
Labels: enhancement

#402 feat: upgrade linux to v4.19.23
  Makefile
Labels: enhancement

#404 feat: add route printing to osctl
  internal/app/osctl/cmd/routes.go
  internal/app/osctl/internal/client/client.go
  internal/app/osd/internal/reg/reg.go
  internal/app/osd/proto/api.proto
Labels: enhancement

#414 refactor(init): Make baremetal consume install package
  internal/app/init/internal/platform/baremetal/baremetal.go
  internal/app/init/internal/platform/cloud/aws/aws.go
  internal/app/init/internal/platform/cloud/googlecloud/googlecloud.go
  internal/app/init/internal/platform/cloud/vmware/vmware.go
  internal/app/init/main.go
Labels: enhancement

#413 feat: add config flag to osctl
  internal/app/osctl/cmd/config.go
  internal/app/osctl/cmd/dmesg.go
  internal/app/osctl/cmd/kubeconfig.go
  internal/app/osctl/cmd/logs.go
  internal/app/osctl/cmd/ps.go
  internal/app/osctl/cmd/reboot.go
  internal/app/osctl/cmd/reset.go
  internal/app/osctl/cmd/restart.go
  internal/app/osctl/cmd/root.go
  internal/app/osctl/cmd/routes.go
  internal/app/osctl/cmd/stats.go
  internal/app/osctl/cmd/version.go
  internal/app/osctl/internal/client/client.go
  internal/app/osctl/internal/client/config/config.go
Labels: enhancement

#416 fix: write config changes to specified config file
  internal/app/osctl/cmd/config.go
  internal/app/osctl/internal/client/config/config.go
Labels: bug

#406 feat: add automated PKI for joining nodes
  docs/configuration/index.xml
  docs/configuration/masters/index.html
  docs/configuration/osd/index.html
  docs/configuration/workers/index.html
  docs/index.json
  docs/index.xml
  go.mod
  go.sum
  internal/app/blockd/main.go
  internal/app/init/internal/rootfs/mount/mount.go
  internal/app/init/internal/rootfs/rootfs.go
  internal/app/init/main.go
  internal/app/init/pkg/system/services/blockd.go
  internal/app/init/pkg/system/services/kubeadm.go
  internal/app/init/pkg/system/services/osd.go
  internal/app/osd/main.go
  internal/app/trustd/internal/reg/reg.go
  internal/app/trustd/main.go
  internal/app/trustd/proto/api.proto
  internal/pkg/crypto/x509/x509.go
  internal/pkg/grpc/gen/gen.go
  internal/pkg/grpc/middleware/auth/basic/basic.go
  internal/pkg/install/install.go
  internal/pkg/install/prepare.go
  internal/pkg/userdata/userdata.go
  web/content/configuration/masters.md
  web/content/configuration/osd.md
  web/content/configuration/workers.md
Labels: enhancement

#422 feat: add TALOSCONFIG env var
  internal/app/osctl/cmd/root.go
  internal/pkg/constants/constants.go
Labels: enhancement

#424 feat: create certificates with all non-loopback addresses
  internal/app/proxyd/internal/frontend/frontend.go
  internal/pkg/net/net.go
  internal/pkg/userdata/userdata.go
Labels: enhancement

#425 feat: allow user specified IP addresses in SANs
  internal/app/init/internal/rootfs/rootfs.go
  internal/pkg/grpc/gen/gen.go
  internal/pkg/userdata/userdata.go
Labels: enhancement

#426 fix: distribute PKI from initial master to joining masters
  internal/app/init/pkg/system/services/kubeadm.go
  internal/pkg/grpc/gen/gen.go
Labels: bug

#427 feat: add DHCP client
  go.mod
  go.sum
  hack/installer/entrypoint.sh
  internal/app/init/internal/rootfs/etc/etc.go
  internal/app/init/main.go
  internal/app/init/pkg/network/network.go
Labels: enhancement

#428 docs: remove ip=dhcp flag from documentation
  docs/examples/index.xml
  docs/examples/xen/index.html
  docs/index.json
  docs/index.xml
  web/content/examples/xen.md
Labels: docs
