Repository siderolabs/talos, pull requests merged in 2019-06, with the labels that each got.

#748 chore: don't run tests in parallel across packages
  hack/golang/test.sh
Labels: [zube]: In Progress, kind/test

#740 feat(osctl): implement 'cp' to copy files out of the Talos node
  cmd/osctl/cmd/cp.go
  cmd/osctl/pkg/client/client.go
  internal/app/init/internal/reg/reg.go
  internal/app/init/proto/api.proto
  internal/app/osd/internal/reg/init_client.go
  internal/pkg/archiver/archiver.go
  internal/pkg/archiver/archiver_test.go
  internal/pkg/archiver/tar.go
  internal/pkg/archiver/tar_test.go
  internal/pkg/archiver/walker.go
  internal/pkg/archiver/walker_test.go
Labels: area/api, kind/feature

#749 refactor(osctl): use UserHomeDir to detect user home directory
  Dockerfile
  cmd/osctl/cmd/root.go
Labels: [zube]: In Progress, area/cli, kind/refactor

#757 chore: tidy modules and verify module tidyness on build
  Dockerfile
  go.mod
  go.sum
Labels: kind/cicd

#736 feat: e2e testing and conformance
  .drone.yml
  hack/dev/manifests/coredns.yaml
  hack/test/e2e.sh
  hack/test/osctl-docker-create.sh
Labels: kind/test

#762 chore: update floating IPs for E2E test
  Makefile
  hack/test/basic-integration.sh
  hack/test/e2e-integration.sh
  hack/test/osctl-cluster-create.sh
Labels: kind/bug, kind/cicd, kind/test

#763 chore: fix drone make command for basic and E2E integration tests
  .drone.yml
Labels: kind/cicd

#764 chore: remove ready plugin from CoreDNS
  hack/dev/manifests/coredns.yaml
Labels: area/conformance, kind/bug

#756 feat(osd): extend Routes API
  cmd/osctl/cmd/routes.go
  go.mod
  go.sum
  internal/app/osd/internal/reg/reg.go
  internal/app/osd/internal/reg/reg_test.go
  internal/app/osd/proto/api.proto
Labels: area/api, kind/feature

#769 chore: disable e2e
  .drone.yml
Labels: kind/cicd

#761 feat: add support for upgrading init nodes
  Makefile
  go.mod
  go.sum
  internal/app/init/internal/rootfs/rootfs.go
  internal/app/init/main.go
  internal/app/init/pkg/system/services/proxyd.go
  internal/app/proxyd/internal/frontend/frontend.go
  internal/app/proxyd/main.go
  internal/pkg/constants/constants.go
  internal/pkg/proc/proc.go
  internal/pkg/upgrade/upgrade.go
  pkg/userdata/generate/controlplane.go
  pkg/userdata/kubeadm.go
  pkg/userdata/upgrade.go
Labels: area/upgrades, kind/feature

#770 docs: move docs repo to talos repo
  docs/content/components/_index.md
  docs/content/components/containerd.md
  docs/content/components/init.md
  docs/content/components/kernel.md
  docs/content/components/kubeadm.md
  docs/content/components/networkd.md
  docs/content/components/ntpd.md
  docs/content/components/osctl.md
  docs/content/components/osd.md
  docs/content/components/proxyd.md
  docs/content/components/trustd.md
  docs/content/components/udevd.md
  docs/content/configuration/_index.md
  docs/content/configuration/masters.md
  docs/content/configuration/osd.md
  docs/content/configuration/userdata.md
  docs/content/configuration/workers.md
  docs/content/guides/_index.md
  docs/content/guides/aws.md
  docs/content/guides/bare_metal.md
  docs/content/guides/gcloud.md
  docs/content/guides/getting_started.md
  docs/content/guides/kvm.md
  docs/content/guides/xen.md
  docs/content/talos.md
Labels: kind/documentation

#772 docs: rename Google Cloud to GCP
  docs/content/guides/gcp.md
Labels: kind/documentation

#773 docs: refresh getting started guide
  docs/content/guides/getting_started.md
Labels: kind/documentation

#774 docs: improve description and layout
  README.md
  docs/content/community/index.md
  docs/content/components/_index.md
  docs/content/configuration/_index.md
  docs/content/guides/_index.md
  docs/content/talos.md
Labels: kind/documentation

#775 docs: update menu
  docs/content/talos.md
Labels: kind/documentation

#776 fix(proxyd): Use local apiserver endpoint
  internal/app/proxyd/internal/frontend/frontend.go
Labels: kind/bug

#782 fix(proxyd): remove self-hosted label in listwatch
  internal/app/proxyd/internal/frontend/frontend.go
Labels: kind/bug

#783 feat: enable debug in udevd service
  internal/app/init/pkg/system/services/udevd.go
Labels: kind/feature

#786 docs: add use cases section
  docs/content/talos.md
  docs/content/use_cases/_index.md
  docs/content/use_cases/edge.md
  docs/content/use_cases/multi-cloud.md
  docs/content/use_cases/serverless.md
Labels: kind/documentation

#787 docs: update getting started guide
  docs/content/guides/getting_started.md
Labels: kind/documentation

#790 fix(proxyd): Add support for dropping broken backends
  internal/app/proxyd/internal/frontend/frontend.go
Labels: kind/bug

#791 docs: target developers in the README and users in the docs
  README.md
  docs/content/community/index.md
  docs/content/faqs/index.md
  docs/content/guides/getting_started.md
  docs/content/talos.md
  docs/content/use_cases/multi-cloud.md
Labels: kind/documentation

#794 fix: move to crypto/rand for token gen
  pkg/userdata/generate/generate.go
Labels: [zube]: Accepted, kind/bug, triage/needs-cherry-pick

#797 fix(init): secret data at rest encryption key should be truly random
  internal/app/init/internal/security/cis/cis.go
Labels: kind/bug, triage/needs-cherry-pick

#799 fix(init): secret data at rest encryption key should be truly random [backport]
  internal/app/init/internal/security/cis/cis.go
Labels: kind/bug

#803 chore: add GitHub action to enforce conform policies
  .drone.yml
  .github/main.workflow
Labels: kind/cicd

#804 chore: fix GitHub action
  .github/main.workflow
Labels: kind/cicd

#805 chore: use pull_request event for GitHub action
  .github/main.workflow
Labels: kind/cicd
