Repository siderolabs/talos, pull requests merged in 2019-07, with the labels that each got.

#808 chore: upgrade conform to v0.1.0-alpha.13
  .github/main.workflow
Labels: kind/cicd

#809 chore: publish gce images with releases
  .drone.yml
  Makefile
Labels: kind/cicd, triage/needs-cherry-pick

#811 chore: prepare release v0.1.0-beta.1
  CHANGELOG.md
Labels: triage/needs-cherry-pick

#807 TLS renew
  internal/app/osd/main.go
  internal/pkg/constants/constants.go
  internal/pkg/grpc/tls/cert.go
  internal/pkg/grpc/tls/tls.go
Labels: [zube]: In Progress, area/security, kind/feature

#817 feat(osd): implement CRI inspector for containers
  cmd/osctl/cmd/logs.go
  cmd/osctl/cmd/ps.go
  cmd/osctl/cmd/restart.go
  cmd/osctl/cmd/root.go
  cmd/osctl/cmd/stats.go
  cmd/osctl/pkg/client/client.go
  go.mod
  go.sum
  internal/app/osd/internal/reg/reg.go
  internal/app/osd/proto/api.proto
  internal/pkg/containers/container.go
  internal/pkg/containers/containerd/containerd.go
  internal/pkg/containers/containerd/containerd_test.go
  internal/pkg/containers/containers_test.go
  internal/pkg/containers/cri/client.go
  internal/pkg/containers/cri/cri.go
  internal/pkg/containers/cri/cri_test.go
  internal/pkg/containers/inspector.go
Labels: area/api, area/cli, kind/feature

#818 fix: probe specified install device
  cmd/osctl/cmd/install_linux.go
  internal/pkg/blockdevice/probe/probe.go
  internal/pkg/install/detect.go
  internal/pkg/install/install.go
  internal/pkg/install/mount.go
  internal/pkg/install/prepare.go
Labels: kind/bug, triage/needs-cherry-pick

#820 fix: probe specified install device (#818)
  cmd/osctl/cmd/install_linux.go
  internal/pkg/blockdevice/probe/probe.go
  internal/pkg/install/detect.go
  internal/pkg/install/install.go
  internal/pkg/install/mount.go
  internal/pkg/install/prepare.go
Labels: kind/bug

#825 chore: upgrade conform to v0.1.0-alpha.14
  .github/main.workflow
Labels: kind/cicd

#816 chore: fix GCE image creation
  .drone.yml
  .gitignore
  Makefile
  hack/golang/test.sh
  hack/test/basic-integration.sh
  hack/test/osctl-cluster-create.sh
Labels: triage/needs-cherry-pick

#830 chore: fix GCE image creation
  .drone.yml
Labels: kind/cicd, triage/needs-cherry-pick

#833 chore: create a CHANGELOG.md for each minor version
  CHANGELOG-0.1.md
  CHANGELOG-0.2.md
  CHANGELOG.md
Labels: triage/needs-cherry-pick

#834 chore: fix CHANGELOGs
  CHANGELOG-0.1.md
  CHANGELOG-0.2.md
Labels: triage/needs-cherry-pick

#838 fix: use existing logic to perform reset
  cmd/osctl/pkg/client/client.go
  internal/app/init/internal/reg/reg.go
  internal/app/init/proto/api.proto
  internal/app/osd/internal/reg/init_client.go
  internal/app/osd/internal/reg/reg.go
  internal/app/osd/proto/api.proto
Labels: area/api, kind/bug

#841 fix: append probed block devices
  internal/pkg/blockdevice/probe/probe.go
Labels: kind/bug

#842 fix: append probed block devices
  internal/pkg/blockdevice/probe/probe.go
Labels: kind/bug

#845 fix: use existing logic to perform reset
  cmd/osctl/pkg/client/client.go
  internal/app/init/internal/reg/reg.go
  internal/app/init/proto/api.proto
  internal/app/osd/internal/reg/init_client.go
  internal/app/osd/internal/reg/reg.go
  internal/app/osd/proto/api.proto
Labels: kind/bug

#823 feat(initramfs): Add kernel arg for default interface
  internal/app/init/pkg/network/networkd.go
  internal/app/init/pkg/network/setup.go
  internal/pkg/constants/constants.go
Labels: [zube]: In Progress, area/networking, kind/feature

#848 chore: prepare release v0.2.0-alpha.1
  CHANGELOG-0.2.md
Labels: [zube]: In Progress

#828 feat: Use individual component steps for drone
  .drone.yml
  Dockerfile
  Makefile
Labels: [zube]: Triâge, kind/cicd, triage/needs-research

#852 fix(init): Dont log an error when context canceled
  internal/app/init/pkg/system/services/kubeadm.go
  internal/app/init/pkg/system/services/kubeadm/kubeadm.go
  internal/app/init/pkg/system/services/kubeadm/kubeadm_test.go
  internal/app/init/pkg/system/services/kubeadm/system_test.go
Labels: triage/needs-cherry-pick

#862 feat: add install flag for extra kernel args
  cmd/osctl/cmd/install_linux.go
  internal/app/init/internal/platform/baremetal/baremetal.go
  internal/app/init/internal/platform/cloud/packet/packet.go
  internal/pkg/kernel/kernel.go
  internal/pkg/kernel/kernel_test.go
  pkg/userdata/install.go
Labels: area/machineconfig, kind/feature

#863 fix(init) mount root partition as read-only
  internal/pkg/mount/mount.go
Labels: kind/bug, triage/needs-cherry-pick

#867 fix: return non-nil response in reset
  internal/app/init/internal/reg/reg.go
Labels: triage/needs-cherry-pick

#853 fix(init): Fix routes endpoint
  internal/app/osd/internal/reg/reg.go
Labels: [zube]: Triâge, area/api, area/networking, kind/bug, triage/needs-cherry-pick

#866 feat: use new pkgs for initramfs and rootfs
  .drone.yml
  Dockerfile
  Makefile
  hack/cleanup.sh
  hack/golang/test.sh
  internal/app/init/internal/rootfs/rootfs.go
  internal/app/init/main.go
  internal/app/init/pkg/system/runner/containerd/containerd_test.go
  internal/app/init/pkg/system/runner/process/process_test.go
  internal/app/init/pkg/system/services/kubeadm.go
  internal/app/init/pkg/system/services/osd.go
  internal/app/init/pkg/system/services/proxyd.go
  internal/app/init/pkg/system/services/udevd.go
  internal/app/init/pkg/system/services/udevd_trigger.go
  internal/pkg/containers/containerd/containerd_test.go
  internal/pkg/containers/cri/cri_test.go
  internal/pkg/cri/cri_test.go
Labels: [zube]: In Progress

#822 feat(init): Add azure as a supported platform
  Makefile
  internal/app/init/internal/platform/cloud/azure/azure.go
  internal/app/init/internal/platform/cloud/azure/azure_test.go
  internal/app/init/internal/platform/cloud/azure/register.go
  internal/app/init/internal/platform/platform.go
Labels: [zube]: In Progress, kind/feature

#883 chore: prepare release v0.1.0-rc.0
  CHANGELOG-0.1.md
Labels: [zube]: In Progress, triage/needs-cherry-pick

#889 fix: Only generate pki from trustd if not control plane
  internal/pkg/rootfs/rootfs.go
Labels: kind/bug

#886 fix: make /etc/resolv.conf writable
  internal/app/machined/main.go
  internal/app/machined/pkg/system/services/kubeadm.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/pkg/rootfs/etc/etc.go
Labels: [zube]: In Progress

#869 chore: setup gce for e2e builds
  .drone.yml
  .gitignore
  Makefile
  hack/test/basic-integration.sh
  hack/test/e2e-integration.sh
  hack/test/gce-setup.sh
  hack/test/manifests/capi-secrets.yaml
  hack/test/manifests/gce-cluster.yaml
  hack/test/manifests/provider-components.yaml
  hack/test/osctl-cluster-create.sh
Labels: [zube]: In Progress

#896 feat: attempt to connect to all trustd endpoints when downloading PKI
  internal/pkg/grpc/gen/gen.go
Labels: kind/bug, status/needs-cherry-pick

#904 feat: move df API to init
  cmd/osctl/cmd/df.go
  cmd/osctl/pkg/client/client.go
  internal/app/machined/internal/reg/reg.go
  internal/app/machined/proto/api.proto
  internal/app/osd/internal/reg/init_client.go
  internal/app/osd/internal/reg/reg.go
  internal/app/osd/proto/api.proto
Labels: area/api, kind/refactor

#910 fix: mount cgroups properly
  internal/pkg/mount/cgroups/cgroups.go
Labels: status/needs-cherry-pick

#912 fix: Run cleanup script earlier in rootfs build
  Dockerfile
Labels: kind/bug

#923 chore: prepare release v0.2.0-alpha.4
  CHANGELOG-0.2.md
Labels: kind/cicd

#933 fix: set mtu value regardless of interface state
  internal/pkg/network/setup.go
Labels: area/networking, kind/bug
