Repository siderolabs/talos, pull requests merged in 2020-12, with the labels that each got.

#2856 fix(security): update Containerd to v1.4.3
  .conform.yaml
  Makefile
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2855 fix: use the dtb from kernel pkg for libretech_all_h3_cc_h5
  Dockerfile
  Makefile
  internal/app/machined/pkg/runtime/v1alpha1/board/libretech_all_h3_cc_h5/libretech_all_h3_cc_h5.go
Labels: status/approved

#2860 fix(security): update Containerd to v1.4.3
  .conform.yaml
  Dockerfile
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2864 feat: allow boards to set kernel args
  cmd/installer/pkg/install/install.go
  internal/app/machined/pkg/runtime/board.go
  internal/app/machined/pkg/runtime/v1alpha1/board/bananapi_m64/bananapi_m64.go
  internal/app/machined/pkg/runtime/v1alpha1/board/libretech_all_h3_cc_h5/libretech_all_h3_cc_h5.go
  internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/rpi_4.go
  website/content/docs/v0.8/Single Board Computers/bananapi_m64.md
  website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
  website/content/docs/v0.8/Single Board Computers/rpi_4.md
Labels: status/approved, status/lgtm

#2866 fix: prevent endless loop with DHCP requests in networkd
  internal/app/networkd/pkg/address/dhcp.go
  internal/app/networkd/pkg/nic/netlink.go
  internal/app/networkd/pkg/nic/nic.go
  pkg/provision/providers/vm/dhcpd.go
Labels: status/approved, status/lgtm, status/needs-cherry-pick

#2863 chore: update module dependencies
  go.mod
  go.sum
Labels: status/approved, status/lgtm

#2868 fix: prevent endless loop with DHCP requests in networkd
  internal/app/networkd/pkg/address/dhcp.go
  internal/app/networkd/pkg/nic/netlink.go
  internal/app/networkd/pkg/nic/nic.go
  pkg/provision/providers/vm/dhcpd.go
Labels: status/approved, status/lgtm

#2861 release(v0.7.1): prepare release
  CHANGELOG.md
  website/content/docs/v0.7/Reference/cli.md
Labels: status/approved, status/lgtm

#2859 chore: build SBC images
  .drone.jsonnet
  Makefile
  website/content/docs/v0.8/Single Board Computers/bananapi_m64.md
  website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
  website/content/docs/v0.8/Single Board Computers/rpi_4.md
Labels: status/approved, status/lgtm

#2869 chore: ouput SBC images as compressed raw images
  .drone.jsonnet
  cmd/installer/cmd/image.go
  website/content/docs/v0.8/Single Board Computers/bananapi_m64.md
  website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
  website/content/docs/v0.8/Single Board Computers/rpi_4.md
Labels: status/approved, status/lgtm

#2871 fix: remove value (change to empty) for `NoSchedule` taint
  pkg/kubernetes/kubernetes.go
Labels: status/approved, status/lgtm

#2867 feat: update kubernetes to 1.20.0-rc.0
  Makefile
  go.mod
  go.sum
  hack/test/capi/cluster-aws.yaml
  hack/test/capi/cluster-gcp.yaml
  internal/integration/provision/upgrade.go
  pkg/machinery/constants/constants.go
  website/content/docs/v0.8/Reference/cli.md
  website/content/docs/v0.8/Reference/configuration.md
Labels: status/approved, status/lgtm

#2883 docs: ensure port for vbox and proxmox docs
  website/content/docs/v0.7/Local Platforms/virtualbox.md
  website/content/docs/v0.7/Virtualized Platforms/proxmox.md
  website/content/docs/v0.8/Local Platforms/virtualbox.md
  website/content/docs/v0.8/Virtualized Platforms/proxmox.md
Labels: status/approved

#2884 feat: suggest fixed control plane endpoints in talosctl gen config
  cmd/talosctl/cmd/mgmt/config.go
  internal/integration/cli/gen.go
Labels: status/approved, status/lgtm

#2885 feat: introduce configpatcher package in machinery
  go.sum
  pkg/machinery/config/configpatcher/configpatcher.go
  pkg/machinery/config/configpatcher/configpatcher_test.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved

#2886 fix: defer resolving config context in client code
  pkg/machinery/client/client.go
Labels: status/approved, status/lgtm

#2887 feat: make GenerateConfiguration accept current time as a parameter
  api/machine/machine.proto
  go.mod
  go.sum
  internal/pkg/configuration/configuration.go
  internal/pkg/tui/installer/state.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/config/types/v1alpha1/bundle/bundle.go
  pkg/machinery/config/types/v1alpha1/generate/generate.go
  pkg/machinery/config/types/v1alpha1/generate/generate_test.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  website/content/docs/v0.8/Reference/api.md
Labels: status/approved, status/lgtm

#2890 docs: add openstack docs
  website/content/docs/v0.7/Cloud Platforms/gcp.md
  website/content/docs/v0.8/Cloud Platforms/gcp.md
  website/content/docs/v0.8/Cloud Platforms/openstack.md
Labels: status/approved, status/lgtm

#2872 feat: add TUI for configuring network interfaces settings
  api/machine/machine.proto
  internal/pkg/configuration/configuration.go
  internal/pkg/tui/components/form.go
  internal/pkg/tui/components/formbutton.go
  internal/pkg/tui/components/formlabel.go
  internal/pkg/tui/components/group.go
  internal/pkg/tui/installer/connection.go
  internal/pkg/tui/installer/installer.go
  internal/pkg/tui/installer/state.go
  pkg/machinery/api/machine/machine.pb.go
  website/content/docs/v0.8/Reference/api.md
Labels: status/approved

#2891 fix: node taint doesn't contain value anymore
  pkg/kubernetes/kubernetes.go
Labels: status/approved, status/lgtm

#2894 docs: fix typos
  website/content/docs/v0.8/Introduction/what-is-talos.md
Labels: status/lgtm

#2897 chore: run integration test thrice daily
  .drone.jsonnet
Labels: status/approved, status/lgtm

#2896 fix: make reset work again
  go.mod
  go.sum
Labels: status/approved, status/lgtm

#2898 chore: enable thrice daily pipeline
  .drone.jsonnet
Labels: status/approved

#2899 fix: stabilize serial console on RPi4, add video console
  internal/app/machined/pkg/runtime/v1alpha1/board/bananapi_m64/bananapi_m64.go
  internal/app/machined/pkg/runtime/v1alpha1/board/libretech_all_h3_cc_h5/libretech_all_h3_cc_h5.go
  internal/app/machined/pkg/runtime/v1alpha1/board/rock64/rock64.go
  internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/rpi_4.go
Labels: status/approved, status/lgtm

#2900 fix: make default generate image arch dynamic based on arch
  pkg/machinery/config/types/v1alpha1/generate/options.go
Labels: status/approved, status/lgtm

#2901 chore: publish Rock64 image
  .drone.jsonnet
  Makefile
Labels: status/approved, status/lgtm

#2903 release(v0.8.0-alpha.2): prepare release
  CHANGELOG.md
  Makefile
  website/content/docs/v0.8/Reference/cli.md
Labels: status/approved

#2902 docs: improve SBC documentation
  website/content/docs/v0.8/Single Board Computers/bananapi_m64.md
  website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
  website/content/docs/v0.8/Single Board Computers/rock64.md
  website/content/docs/v0.8/Single Board Computers/rpi_4.md
Labels: status/approved, status/lgtm

#2904 chore: fix conform for releases
  .conform.yaml
Labels: status/approved

#2905 docs: Add docs for network connectivity
  website/content/docs/v0.8/Guides/configuring-network-connectivity.md
Labels: status/approved, status/lgtm

#2911 fix: make interactive installer work without endpoints provided
  cmd/talosctl/cmd/talos/apply-config.go
Labels: status/approved, status/lgtm

#2915 chore: bump dockerfile frontend version
  Dockerfile
Labels: status/approved, status/lgtm

#2913 test: bump defaults for provision tests resources
  hack/test/provision-tests.sh
  internal/integration/provision/provision.go
Labels: status/approved, status/lgtm

#2912 feat: allow disabling NoSchedule taint on masters using TUI installer
  api/machine/machine.proto
  internal/pkg/configuration/configuration.go
  internal/pkg/tui/installer/state.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/config/types/v1alpha1/generate/generate.go
  pkg/machinery/config/types/v1alpha1/generate/init.go
  pkg/machinery/config/types/v1alpha1/generate/options.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  website/content/docs/v0.8/Reference/api.md
  website/content/docs/v0.8/Reference/configuration.md
Labels: status/approved, status/lgtm

#2916 chore: bump Go to 1.15.6
  Makefile
Labels: status/approved, status/lgtm

#2917 chore: limit unit-test run concurrency
  hack/golang/test.sh
Labels: status/approved, status/lgtm

#2923 fix: zero out partitions without filesystems on install
  cmd/installer/pkg/install/manifest.go
Labels: status/approved, status/lgtm

#2928 fix: remove kmsg ratelimiting on startup
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/approved, status/lgtm

#2920 chore: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: status/approved

#2921 test: bump Talos release version for upgrade test to 0.7.1
  Makefile
  internal/integration/provision/upgrade.go
Labels: status/approved

#2918 docs: add guider for custom CAs
  website/content/docs/v0.8/Guides/configuring-certificate-authorities.md
Labels: status/approved

#2892 feat: implement "staged" (failsafe/backup) upgrades
  api/machine/machine.proto
  cmd/installer/pkg/install/install.go
  cmd/talosctl/cmd/talos/upgrade.go
  internal/app/machined/internal/install/install.go
  internal/app/machined/internal/install/options.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/state.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/adv/adv.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/adv/syslinux/syslinux.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/adv/syslinux/syslinux_test.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/adv/syslinux/testdata/adv.sys
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/adv/talos/talos.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/adv/talos/talos_test.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/meta.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/syslinux/syslinux.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_state.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/integration/api/reboot.go
  internal/integration/api/reset.go
  internal/integration/provision/upgrade.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/client/client.go
  website/content/docs/v0.8/Reference/api.md
  website/content/docs/v0.8/Reference/cli.md
Labels: status/approved, status/lgtm

#2924 docs: update Equinix Metal guide
  website/content/docs/v0.8/Bare Metal Platforms/equinix-metal.md
Labels: status/approved

#2933 feat: update Kubernetes to 1.20.0
  Makefile
  go.mod
  go.sum
  hack/test/capi/cluster-aws.yaml
  hack/test/capi/cluster-gcp.yaml
  internal/integration/provision/upgrade.go
  pkg/machinery/constants/constants.go
  website/content/docs/v0.8/Reference/cli.md
  website/content/docs/v0.8/Reference/configuration.md
Labels: status/approved, status/lgtm

#2931 feat: add talosctl config contexts
  cmd/talosctl/cmd/talos/config.go
  internal/integration/cli/config.go
  website/content/docs/v0.8/Reference/cli.md
Labels: status/approved, status/lgtm

#2930 feat: add talosctl merge config command
  cmd/talosctl/cmd/talos/config.go
  internal/integration/cli/config.go
  website/content/docs/v0.8/Reference/cli.md
Labels: status/approved, status/lgtm

#2938 test: add support for mounting ISO in talosctl cluster create
  cmd/talosctl/cmd/mgmt/cluster/create.go
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/qemu/node.go
  pkg/provision/request.go
  website/content/docs/v0.8/Reference/cli.md
Labels: status/approved, status/lgtm

#2935 feat: reset with system disk wipe spec
  api/machine/machine.proto
  cmd/installer/pkg/install/constants.go
  cmd/installer/pkg/install/manifest.go
  cmd/installer/pkg/install/manifest_test.go
  cmd/installer/pkg/install/target.go
  cmd/talosctl/cmd/talos/reset.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_test.go
  internal/integration/api/reset.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/client/client.go
  website/content/docs/v0.8/Reference/api.md
  website/content/docs/v0.8/Reference/cli.md
Labels: status/approved, status/lgtm

#2939 feat: update kernel to 5.9.13, new KSPP requirements
  Makefile
  cmd/installer/cmd/iso.go
  cmd/installer/pkg/install/install.go
  go.mod
  go.sum
  hack/test/digitalrebar/bootenv.yaml
  hack/test/libvirt/matchbox/profiles/controlplane.json
  hack/test/libvirt/matchbox/profiles/default.json
  hack/test/libvirt/matchbox/profiles/init.json
  hack/test/qemu/qemu.sh
  internal/pkg/kernel/kspp/kspp.go
  pkg/machinery/constants/constants.go
  pkg/provision/providers/qemu/node.go
  website/content/docs/v0.8/Bare Metal Platforms/equinix-metal.md
  website/content/docs/v0.8/Bare Metal Platforms/matchbox.md
  website/content/docs/v0.8/Introduction/getting-started.md
  website/content/docs/v0.8/Learn More/upgrades.md
Labels: status/approved, status/lgtm

#2927 test: add ISO test
  .drone.jsonnet
  hack/test/e2e-iso.sh
  internal/app/machined/internal/server/v1alpha1/v1alpha1_cluster.go
Labels: status/approved, status/lgtm

#2941 release(v0.8.0-alpha.3): prepare release
  CHANGELOG.md
  website/content/docs/v0.8/Reference/cli.md
Labels: status/approved, status/lgtm

#2940 test: stabilize upgrade test by running health check several times
  Makefile
  internal/integration/api/events.go
  internal/integration/api/reboot.go
  internal/integration/api/reset.go
  internal/integration/base/errors.go
  internal/integration/provision/upgrade.go
  pkg/cluster/crashdump.go
Labels: status/approved, status/lgtm

#2946 feat: bump pkgs for kernel with CONFIG_USB_XHCI_PLATFORM
  Makefile
Labels: status/approved, status/lgtm

#2943 refactor: remove setup goroutine in etcd service
  internal/app/machined/pkg/system/services/etcd.go
  internal/pkg/containers/image/image.go
Labels: status/approved, status/lgtm

#2947 test: remove provision tests with Cilium CNI
  .drone.jsonnet
Labels: status/approved, status/lgtm

#2944 test: add an extra 'node boot done' health check
  pkg/cluster/check/default.go
  pkg/cluster/check/events.go
Labels: status/approved, status/lgtm

#2952 feat: bump Linux kernel to 5.10.1, add CONFIG_USB_ACM
  Makefile
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2945 chore: add drone pipeline to upload cloud images
  .drone.jsonnet
  Makefile
  hack/cloud-image-uploader.sh
Labels: status/approved

#2949 fix: take the first interface from the bond (packet)
  internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go
Labels: status/approved, status/lgtm

#2955 chore: build ISOs earlier to launch e2e-iso as soon as possible
  .drone.jsonnet
Labels: status/approved, status/lgtm

#2954 chore: lower MTU to 1450 for the tests in the CI
  .drone.jsonnet
  hack/test/e2e-docker.sh
  hack/test/e2e-firecracker.sh
  hack/test/e2e-iso.sh
  hack/test/e2e-qemu.sh
  hack/test/provision-tests.sh
Labels: status/approved

#2953 docs: add fallback to default description if none is set on current page
  cmd/talosctl/cmd/docs.go
  hack/protoc-gen-doc/markdown.tmpl
  website/content/docs/v0.8/Bare Metal Platforms/digital-rebar.md
  website/content/docs/v0.8/Bare Metal Platforms/equinix-metal.md
  website/content/docs/v0.8/Bare Metal Platforms/matchbox.md
  website/content/docs/v0.8/Bare Metal Platforms/sidero.md
  website/content/docs/v0.8/Cloud Platforms/aws.md
  website/content/docs/v0.8/Cloud Platforms/azure.md
  website/content/docs/v0.8/Cloud Platforms/digitalocean.md
  website/content/docs/v0.8/Cloud Platforms/gcp.md
  website/content/docs/v0.8/Cloud Platforms/openstack.md
  website/content/docs/v0.8/Local Platforms/docker.md
  website/content/docs/v0.8/Local Platforms/firecracker.md
  website/content/docs/v0.8/Local Platforms/qemu.md
  website/content/docs/v0.8/Local Platforms/virtualbox.md
  website/content/docs/v0.8/Reference/api.md
  website/content/docs/v0.8/Reference/cli.md
  website/content/docs/v0.8/Reference/configuration.md
  website/content/docs/v0.8/Single Board Computers/bananapi_m64.md
  website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
  website/content/docs/v0.8/Single Board Computers/rock64.md
  website/content/docs/v0.8/Single Board Computers/rpi_4.md
  website/content/docs/v0.8/Virtualized Platforms/proxmox.md
  website/content/docs/v0.8/Virtualized Platforms/vmware.md
  website/src/templates/MarkdownPage.vue
Labels: status/approved, status/lgtm

#2957 fix: properly define shorthand in `talosctl time` command
  cmd/talosctl/cmd/talos/time.go
  website/content/docs/v0.8/Reference/cli.md
Labels: status/approved, status/lgtm

#2959 fix: bump blockdevice library for 2nd partitione entries copy fix
  go.mod
  go.sum
Labels: status/approved, status/lgtm

#2960 feat: bump pkgs for kernel with HZ=250 on amd64
  Makefile
Labels: status/approved, status/lgtm

#2961 fix: don't overwrite PMBR
  go.mod
  go.sum
Labels: status/approved, status/lgtm

#2958 fix: sync RTC in timed, sync time before fetching packet metadata
  go.mod
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/timed.go
  internal/app/timed/pkg/ntp/ntp.go
  internal/app/timed/pkg/ntp/ntp_test.go
  internal/app/timed/pkg/reg/reg.go
Labels: status/approved

#2962 fix: synchronize bootkube timeouts and various boot timeouts
  internal/app/bootkube/main.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  pkg/kubernetes/kubernetes.go
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2964 release(v0.8.0-beta.0): prepare release
  CHANGELOG.md
  website/content/docs/v0.8/Reference/cli.md
Labels: status/approved, status/lgtm

#2966 docs: update Talos release for SBCs
  website/content/docs/v0.8/Single Board Computers/bananapi_m64.md
  website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
  website/content/docs/v0.8/Single Board Computers/rock64.md
  website/content/docs/v0.8/Single Board Computers/rpi_4.md
Labels: status/approved, status/lgtm

#2967 fix: don't run LabelNodeAsMaster in two sequences
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
Labels: status/approved, status/lgtm

#2965 fix: use the correct console on Banana Pi M64
  internal/app/machined/pkg/runtime/v1alpha1/board/bananapi_m64/bananapi_m64.go
Labels: status/approved, status/lgtm

#2970 docs: fix SBC docs to point to beta.0 instead of beta.1
  website/content/docs/v0.8/Single Board Computers/bananapi_m64.md
  website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
  website/content/docs/v0.8/Single Board Computers/rpi_4.md
Labels: status/approved, status/lgtm

#2977 docs: provide AMIs for 0.8.0-beta.0
  website/src/data/cloud-images.json
Labels: status/approved, status/lgtm

#2971 feat: update Kubernetes to 1.20.1
  Makefile
  go.mod
  go.sum
  hack/test/capi/cluster-aws.yaml
  hack/test/capi/cluster-gcp.yaml
  internal/integration/provision/upgrade.go
  pkg/machinery/constants/constants.go
  website/content/docs/v0.8/Guides/upgrading-kubernetes.md
  website/content/docs/v0.8/Introduction/quickstart.md
  website/content/docs/v0.8/Reference/cli.md
  website/content/docs/v0.8/Reference/configuration.md
  website/content/docs/v0.8/Single Board Computers/rock64.md
Labels: status/approved

#2976 feat: support disk image in talosctl cluster create
  .drone.jsonnet
  cmd/talosctl/cmd/mgmt/cluster/create.go
  hack/test/e2e-iso.sh
  hack/test/e2e-qemu.sh
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
  pkg/cluster/apply-config.go
  pkg/provision/access/adapter.go
  pkg/provision/providers/qemu/node.go
  pkg/provision/request.go
  website/content/docs/v0.8/Reference/cli.md
Labels: status/approved

#2982 fix: ignore errors on stopping/removing pod sandboxes
  internal/pkg/cri/pods.go
Labels: status/approved, status/lgtm

#2979 fix: leave etcd for staged upgrades
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/sequencer.go
  internal/app/machined/pkg/runtime/sequencer_test.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
Labels: status/approved, status/lgtm

#2983 feat: add commands to manage/query etcd cluster
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/etcd.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/integration/cli/etcd.go
  pkg/machinery/api/machine/machine.pb.go
  website/content/docs/v0.8/Reference/api.md
  website/content/docs/v0.8/Reference/cli.md
Labels: status/approved, status/lgtm

#2986 fix: ignore pods spun up from checkpoints in health checks
  pkg/cluster/check/kubernetes.go
Labels: status/approved, status/lgtm

#2984 fix: pass disk image flags to e2e-qemu cluster create command
  hack/test/e2e-qemu.sh
Labels: status/approved, status/lgtm

#2988 fix: add more dependencies for bootstrap services
  internal/app/machined/pkg/system/services/bootkube.go
  internal/app/machined/pkg/system/services/cri.go
Labels: status/approved, status/lgtm

#2990 fix: use SetAll instead of AppendAll when building kernel args
  cmd/installer/pkg/install/install.go
  go.mod
  go.sum
Labels: status/approved, status/lgtm

#2989 fix: correctly transport gRPC errors from apid
  Dockerfile
  api/common/common.proto
  api/vendor/google/rpc/status.proto
  internal/app/apid/pkg/backend/apid.go
  pkg/machinery/api/common/common.pb.go
  pkg/machinery/client/reply.go
  pkg/machinery/client/reply_test.go
  pkg/machinery/go.mod
  prototool.yaml
  website/content/docs/v0.8/Reference/api.md
Labels: status/approved, status/lgtm

#2991 fix: backport fixes from 0.9 after 0.8-beta.0
  .drone.jsonnet
  Dockerfile
  Makefile
  api/common/common.proto
  api/machine/machine.proto
  api/vendor/google/rpc/status.proto
  cmd/installer/pkg/install/install.go
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/talos/etcd.go
  go.mod
  go.sum
  hack/test/capi/cluster-aws.yaml
  hack/test/capi/cluster-gcp.yaml
  hack/test/e2e-iso.sh
  hack/test/e2e-qemu.sh
  internal/app/apid/pkg/backend/apid.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/sequencer.go
  internal/app/machined/pkg/runtime/sequencer_test.go
  internal/app/machined/pkg/runtime/v1alpha1/board/bananapi_m64/bananapi_m64.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/system/services/bootkube.go
  internal/app/machined/pkg/system/services/cri.go
  internal/integration/cli/etcd.go
  internal/integration/provision/upgrade.go
  internal/pkg/cri/pods.go
  pkg/cluster/apply-config.go
  pkg/cluster/check/kubernetes.go
  pkg/machinery/api/common/common.pb.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/client/reply.go
  pkg/machinery/client/reply_test.go
  pkg/machinery/constants/constants.go
  pkg/machinery/go.mod
  pkg/provision/access/adapter.go
  pkg/provision/providers/qemu/node.go
  pkg/provision/request.go
  prototool.yaml
  website/content/docs/v0.8/Guides/upgrading-kubernetes.md
  website/content/docs/v0.8/Introduction/quickstart.md
  website/content/docs/v0.8/Reference/api.md
  website/content/docs/v0.8/Reference/cli.md
  website/content/docs/v0.8/Reference/configuration.md
  website/content/docs/v0.8/Single Board Computers/rock64.md
Labels: status/approved, status/lgtm

#2994 release(v0.8.0): prepare release
  CHANGELOG.md
  website/content/docs/v0.8/Reference/cli.md
Labels: status/approved, status/lgtm

#2995 docs: set latest docs to v0.8
  website/gridsome.config.js
  website/src/pages/Index.vue
Labels: status/approved

#3000 docs: update references to 0.8.0, add 0.8.0 AWS AMIs
  website/content/docs/v0.8/Guides/upgrading-talos.md
  website/content/docs/v0.8/Single Board Computers/bananapi_m64.md
  website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
  website/content/docs/v0.8/Single Board Computers/rock64.md
  website/content/docs/v0.8/Single Board Computers/rpi_4.md
  website/src/data/cloud-images.json
Labels: status/approved, status/lgtm

#2993 feat: support type filter in list API and CLI
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/list.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  pkg/archiver/archiver.go
  pkg/archiver/archiver_test.go
  pkg/archiver/tar_test.go
  pkg/archiver/walker.go
  pkg/archiver/walker_test.go
  pkg/machinery/api/machine/machine.pb.go
  website/content/docs/v0.8/Reference/api.md
  website/content/docs/v0.8/Reference/cli.md
Labels: status/approved, status/lgtm

#2999 refactor: define default kernel flags in machinery instead of procfs
  cmd/installer/pkg/install/install.go
  go.mod
  go.sum
  pkg/machinery/kernel/kernel.go
  pkg/provision/providers/firecracker/node.go
  pkg/provision/providers/qemu/node.go
Labels: status/approved, status/lgtm

#3001 chore: update upgrade test version used
  Makefile
  internal/integration/provision/upgrade.go
Labels: status/approved

#3004 feat: bump pkgs for kernel with CONFIG_IPV6_MULTIPLE_TABLES
  Makefile
Labels: status/approved, status/lgtm

#2987 fix: checkpoint controller-manager and scheduler
  go.mod
  go.sum
  hack/test/e2e-docker.sh
  internal/integration/api/recover.go
Labels: status/approved, status/lgtm

#3008 fix: bring up bonded interfaces correctly on packet
  internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go
  internal/app/networkd/pkg/networkd/networkd.go
Labels: status/approved, status/lgtm
