Repository siderolabs/talos, pull requests merged in 2020-09, with the labels that each got.

#2464 chore: drop vmlinux from assets
  .drone.jsonnet
  Dockerfile
  Makefile
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2437 feat: add grub bootloader
  .drone.jsonnet
  Dockerfile
  Makefile
  cmd/installer/pkg/install/install.go
  cmd/installer/pkg/install/manifest.go
  hack/test/run.sh
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/main.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/adv.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/adv_test.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/bootloader.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/constants.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/syslinux/syslinux.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/testdata/adv.sys
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/integration/provision/upgrade.go
  internal/pkg/mount/system.go
  pkg/blockdevice/probe/probe.go
  pkg/blockdevice/table/gpt/header/header.go
  pkg/blockdevice/table/gpt/partition/options.go
  pkg/blockdevice/table/gpt/partition/partition.go
  pkg/blockdevice/util/util.go
  pkg/endianness/endianness.go
  pkg/endianness/endianness_test.go
  pkg/machinery/constants/constants.go
Labels: status/approved, status/needs-docs

#2466 chore: upgrade Go to 1.14.8
  Dockerfile
  Makefile
Labels: status/approved, status/lgtm, status/needs-cherry-pick

#2467 chore: update k8s modules to 1.19 final version
  go.mod
  go.sum
Labels: status/approved, status/lgtm, status/needs-cherry-pick

#2470 chore: upgrade Go to 1.14.8
  Dockerfile
  Makefile
Labels: status/approved, status/lgtm

#2471 chore: update k8s modules to 1.19 final version
  go.mod
  go.sum
Labels: status/approved, status/lgtm

#2473 release(v0.7.0-alpha.1): prepare release
  CHANGELOG.md
Labels: status/approved, status/lgtm

#2465 docs: add Kubernetes upgrade guide
  docs/website/content/v0.6.en.json
  docs/website/content/v0.6/en/guides/upgrading/index.md
Labels: status/approved

#2474 release(v0.6.0): prepare release
  CHANGELOG.md
Labels: status/approved, status/lgtm

#2475 fix: add syslinux to create ISO
  Dockerfile
Labels: status/approved, status/lgtm

#2477 docs: graduate v0.6 docs
  docs/website/components/DocumentationDropdown.vue
  docs/website/components/Header.vue
Labels: status/approved, status/lgtm

#2472 refactor: extract packages loadbalancer and retry
  cmd/installer/pkg/install/manifest.go
  cmd/talosctl/cmd/mgmt/loadbalancer_launch.go
  go.mod
  go.sum
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/service_runner_test.go
  internal/app/machined/pkg/system/services/apid.go
  internal/app/machined/pkg/system/services/bootkube.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/networkd/pkg/nic/nic.go
  internal/app/timed/pkg/ntp/ntp.go
  internal/integration/api/reboot.go
  internal/integration/api/version.go
  internal/integration/base/api.go
  internal/integration/base/cli.go
  internal/integration/provision/upgrade.go
  internal/pkg/containers/image/image.go
  internal/pkg/loadbalancer/loadbalancer.go
  internal/pkg/loadbalancer/loadbalancer_test.go
  internal/pkg/loadbalancer/upstream/upstream.go
  internal/pkg/loadbalancer/upstream/upstream_test.go
  internal/pkg/mount/mount.go
  pkg/blockdevice/blkpg/blkpg_linux.go
  pkg/blockdevice/blockdevice_linux.go
  pkg/blockdevice/probe/probe.go
  pkg/cluster/bootstrap.go
  pkg/download/download.go
  pkg/kubernetes/kubernetes.go
  pkg/retry/constant.go
  pkg/retry/constant_test.go
  pkg/retry/exponential.go
  pkg/retry/exponential_test.go
  pkg/retry/linear.go
  pkg/retry/linear_test.go
  pkg/retry/options.go
  pkg/retry/options_test.go
  pkg/retry/retry.go
  pkg/retry/retry_test.go
Labels: status/approved, status/lgtm

#2478 fix: change apid container image name to expected value
  docs/website/content/v0.5/en/guides/getting-started/talosctl.md
  docs/website/content/v0.6/en/guides/getting-started/talosctl.md
  internal/app/machined/pkg/system/services/apid.go
Labels: status/approved, status/lgtm

#2480 refactor: move udevadm trigger/settle to udevd healthcheck
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/udevd.go
  internal/app/machined/pkg/system/services/udevd_test.go
  pkg/cmd/cmd.go
Labels: status/approved, status/lgtm

#2481 release(v0.7.0-alpha.1): prepare release
  CHANGELOG.md
Labels: status/approved

#2482 fix: allow static pod files
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/approved, status/lgtm

#2484 fix: update permissions for directories and files created via extraFiles
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/approved, status/lgtm

#2483 chore: remove extra COPY from rootfs
  Dockerfile
Labels: status/approved, status/lgtm

#2487 chore: upgrade Go to 1.15.1
  Dockerfile
  Makefile
Labels: status/approved, status/lgtm

#2488 fix: remove udevd debug flag
  internal/app/machined/pkg/system/services/udevd.go
Labels: status/approved

#2489 feat: remove ISO support
  .drone.jsonnet
  Dockerfile
  Makefile
  cmd/installer/cmd/iso.go
  cmd/installer/pkg/iso.go
Labels: status/approved, status/lgtm

#2490 feat: upgrade containerd to v1.4.0
  Dockerfile
  go.mod
  go.sum
  pkg/machinery/constants/constants.go
Labels: status/approved

#2494 docs: update 0.6 links
  docs/website/content/v0.6/en/guides/getting-started/intro.md
  docs/website/content/v0.6/en/guides/upgrading/index.md
Labels: status/approved, status/lgtm

#2493 feat: upgrade runc to v1.0.0-rc92
  Dockerfile
  go.mod
  go.sum
  internal/app/machined/internal/install/install.go
  internal/app/machined/pkg/system/services/kubelet.go
Labels: status/approved, status/lgtm

#2496 fix: default endpoint to 127.0.0.1 for Docker/OS X
  cmd/talosctl/cmd/mgmt/cluster/create.go
  pkg/provision/providers/docker/docker.go
  pkg/provision/providers/firecracker/firecracker.go
  pkg/provision/providers/qemu/qemu.go
Labels: status/approved, status/lgtm

#2497 feat: use latest packages
  Dockerfile
Labels: status/approved, status/lgtm

#2500 refactor: deduplicate packages version in Dockerfile
  Dockerfile
  Makefile
Labels: status/approved, status/lgtm

#2501 fix: don't abort reboot sequence on bootloader meta failure
  internal/app/machined/main.go
Labels: status/approved, status/lgtm

#2502 fix: update vmware image and platform
  cmd/installer/pkg/ova/ova.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
Labels: status/approved, status/lgtm

#2503 test: add e2e test to the provision (upgrade) tests
  .drone.jsonnet
  Makefile
  cmd/talosctl/cmd/talos/health.go
  docs/talosctl/talosctl_health.md
  go.mod
  go.sum
  hack/test/provision-tests.sh
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/integration/integration_test.go
  internal/integration/provision/provision.go
  internal/integration/provision/upgrade.go
  pkg/cluster/cluster.go
  pkg/cluster/kubernetes.go
  pkg/cluster/sonobuoy/sonobuoy.go
  pkg/kubernetes/kubernetes.go
Labels: status/approved, status/lgtm

#2505 feat: implement command `talosctl upgrade-k8s`
  cmd/talosctl/cmd/talos/upgrade-k8s.go
  docs/talosctl/talosctl.md
  docs/talosctl/talosctl_upgrade-k8s.md
  pkg/cluster/kubernetes/kubernetes.go
  pkg/cluster/kubernetes/upgrade.go
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2507 feat: upgrade kubernetes to 1.19.1
  Makefile
  docs/talosctl/talosctl_cluster_create.md
  docs/talosctl/talosctl_gen_config.md
  docs/talosctl/talosctl_upgrade-k8s.md
  go.mod
  go.sum
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2508 test: verify kubernetes control plane upgrade in provision tests
  .drone.jsonnet
  internal/integration/provision/upgrade.go
Labels: status/approved, status/lgtm

#2513 fix: tell grub to use console output
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
Labels: status/approved, status/lgtm

#2511 test: re-enable Cilium e2e upgrade test
  .drone.jsonnet
Labels: status/approved, status/lgtm

#2517 release(v0.6.1): prepare release
  CHANGELOG.md
Labels: status/approved, status/lgtm

#2519 feat: update Flannel to 0.12, support for arm64
  go.mod
  go.sum
  internal/app/bootkube/assets.go
Labels: status/approved, status/lgtm

#2523 fix: don't enforce k8s version in `talosctl cluster create` by default
  cmd/talosctl/cmd/mgmt/cluster/create.go
Labels: status/approved, status/lgtm

#2516 test: implement API for QEMU VM provisioner
  pkg/provision/internal/inmemhttp/inmemhttp.go
  pkg/provision/providers/firecracker/launch.go
  pkg/provision/providers/qemu/controller.go
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/qemu/node.go
  pkg/provision/providers/vm/controller.go
  pkg/provision/providers/vm/launch.go
  pkg/provision/result.go
Labels: status/approved, status/lgtm

#2525 feat: use architecture-specific image for core k8s components
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/mgmt/config.go
  cmd/talosctl/cmd/talos/upgrade-k8s.go
  docs/talosctl/talosctl_gen_config.md
  docs/talosctl/talosctl_upgrade-k8s.md
  internal/integration/provision/upgrade.go
  pkg/cluster/kubernetes/upgrade.go
  pkg/machinery/config/types/v1alpha1/generate/generate.go
  pkg/machinery/config/types/v1alpha1/generate/init.go
  pkg/machinery/config/types/v1alpha1/generate/options.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
Labels: status/approved, status/lgtm

#2524 refactor: garbage collect unused constants
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2526 docs: update upgrade guide with `talosctl upgrade-k8s`
  docs/website/content/v0.6/en/guides/upgrading/index.md
  pkg/cluster/kubernetes/upgrade.go
Labels: status/approved, status/lgtm

#2528 fix: set environment variable for etcd on arm64
  internal/app/machined/pkg/system/services/etcd.go
Labels: status/approved, status/lgtm

#2530 chore: update ntp time headers
  cmd/talosctl/cmd/talos/time.go
Labels: status/approved, status/lgtm

#2532 fix: gracefully handle invalid interfaces in bond
  internal/app/networkd/pkg/networkd/networkd.go
Labels: status/approved, status/lgtm

#2403 docs: add recommneded settings in overview
  docs/website/content/v0.6/en/configuration/overview.md
Labels: status/approved, status/lgtm

#2518 feat: allow for link local networking
  internal/app/networkd/pkg/address/static.go
  internal/app/networkd/pkg/networkd/netconf.go
  internal/app/networkd/pkg/nic/nic.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
Labels: status/approved, status/lgtm

#2534 fix: improve error message on empty config
  pkg/machinery/client/client.go
Labels: status/approved, status/lgtm

#2537 feat: ugrade Linux kernel to 5.8.10
  Makefile
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2538 feat: upgrade Linux kernel to 5.8.10
  Dockerfile
  pkg/constants/constants.go
Labels: status/approved, status/lgtm

#2540 release(v0.6.2): prepare release
  CHANGELOG.md
Labels: status/approved, status/lgtm

#2541 fix: validate cluster endpoint
  go.mod
  go.sum
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#2542 fix: address node package update
  docs/website/package-lock.json
Labels: status/approved

#2539 release(v0.7.0-alpha.2): prepare release
  CHANGELOG.md
Labels: status/approved, status/lgtm

#2543 feat: add images command
  cmd/talosctl/cmd/talos/images.go
  docs/talosctl/talosctl.md
  docs/talosctl/talosctl_images.md
  internal/app/bootkube/assets.go
  internal/app/bootkube/images/images.go
  internal/integration/cli/images.go
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2546 chore: push edge releases on successful nightly integration
  .drone.jsonnet
Labels: status/approved, status/lgtm

#2548 fix: retry image pulling, stop on 404, no duplicate pulls
  go.mod
  go.sum
  internal/app/machined/internal/install/install.go
  internal/pkg/containers/image/image.go
Labels: status/approved, status/lgtm

#2550 docs: add v0.7 docs
  Dockerfile
  docs/website/components/DocumentationDropdown.vue
  docs/website/content/v0.7.en.json
  docs/website/content/v0.7/en/components/apid.md
  docs/website/content/v0.7/en/components/containerd.md
  docs/website/content/v0.7/en/components/kernel.md
  docs/website/content/v0.7/en/components/machined.md
  docs/website/content/v0.7/en/components/networkd.md
  docs/website/content/v0.7/en/components/osctl.md
  docs/website/content/v0.7/en/components/overview.md
  docs/website/content/v0.7/en/components/timed.md
  docs/website/content/v0.7/en/components/trustd.md
  docs/website/content/v0.7/en/components/udevd.md
  docs/website/content/v0.7/en/configuration/overview.md
  docs/website/content/v0.7/en/configuration/v1alpha1.md
  docs/website/content/v0.7/en/customization/containerd.md
  docs/website/content/v0.7/en/customization/kernel.md
  docs/website/content/v0.7/en/customization/overview.md
  docs/website/content/v0.7/en/customization/proxy.md
  docs/website/content/v0.7/en/guides/cloud/aws.md
  docs/website/content/v0.7/en/guides/cloud/azure.md
  docs/website/content/v0.7/en/guides/cloud/digitalocean.md
  docs/website/content/v0.7/en/guides/cloud/gcp.md
  docs/website/content/v0.7/en/guides/cloud/vmware.md
  docs/website/content/v0.7/en/guides/getting-started/help.md
  docs/website/content/v0.7/en/guides/getting-started/intro.md
  docs/website/content/v0.7/en/guides/getting-started/talosctl.md
  docs/website/content/v0.7/en/guides/local/docker.md
  docs/website/content/v0.7/en/guides/local/firecracker.md
  docs/website/content/v0.7/en/guides/local/qemu.md
  docs/website/content/v0.7/en/guides/local/registry-cache.md
  docs/website/content/v0.7/en/guides/metal/arges.md
  docs/website/content/v0.7/en/guides/metal/digitalrebar.md
  docs/website/content/v0.7/en/guides/metal/matchbox.md
  docs/website/content/v0.7/en/guides/metal/overview.md
  docs/website/content/v0.7/en/guides/upgrading/index.md
  docs/website/content/v0.7/en/troubleshooting/machine-reset.md
  docs/website/content/v0.7/en/troubleshooting/overview.md
  docs/website/content/v0.7/en/troubleshooting/pki.md
Labels: status/approved

#2547 feat: add default install image
  Dockerfile
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
Labels: status/approved, status/lgtm

#2557 ghcr
  Dockerfile
  Makefile
  docs/talosctl/talosctl_cluster_create.md
  docs/talosctl/talosctl_gen_config.md
  docs/website/content/v0.7/en/configuration/v1alpha1.md
  docs/website/content/v0.7/en/customization/overview.md
  hack/test/e2e-firecracker.sh
  hack/test/e2e-qemu.sh
  hack/test/e2e.sh
  hack/test/libvirt/libvirt.sh
  pkg/machinery/config/types/v1alpha1/doc.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
Labels: status/approved, status/lgtm

#2558 chore: fix docker login
  Makefile
Labels: status/approved

#2562 feat: bump default resource limits for `talosctl cluster create`
  cmd/talosctl/cmd/mgmt/cluster/create.go
  docs/talosctl/talosctl_cluster_create.md
Labels: status/approved, status/lgtm

#2564 fix: enable --removable options for GRUB
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
Labels: status/approved, status/lgtm

#2565 fix: move installer image variables out of machinery
  Dockerfile
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/mgmt/config.go
  cmd/talosctl/cmd/talos/images.go
  pkg/images/images.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2563 docs: add ghcr.io to the registry cache docs
  docs/website/content/v0.7/en/guides/local/registry-cache.md
Labels: status/approved, status/lgtm

#2568 fix: use images package in integration tests
  internal/integration/provision/upgrade.go
Labels: status/approved, status/lgtm

#2569 fix: update the docs to fix the lint-markdown
  docs/website/content/v0.7/en/configuration/v1alpha1.md
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
Labels: status/approved, status/lgtm

#2570 fix: update one more places which had stale reference for constants
  internal/integration/provision/upgrade.go
Labels: status/approved, status/lgtm

#2566 release(v0.7.0-alpha.3): prepare release
  CHANGELOG.md
Labels: status/approved, status/lgtm

#2479 feat: build Talos images/artifacts for amd64/arm64
  .drone.jsonnet
  Dockerfile
  Makefile
  cmd/talosctl/cmd/mgmt/cluster/create.go
  docs/talosctl/talosctl_cluster_create.md
  hack/fix-artifacts.sh
  hack/test/e2e-qemu.sh
  hack/test/e2e.sh
  hack/test/provision-tests.sh
  internal/integration/provision/upgrade.go
  pkg/machinery/constants/constants.go
  pkg/provision/providers/firecracker/node.go
  pkg/provision/providers/qemu/node.go
Labels: status/approved, status/lgtm

#2574 chore: fix 'push' targets
  .drone.jsonnet
Labels: status/approved, status/lgtm

#2575 fix: retry container image import
  internal/app/machined/pkg/system/runner/containerd/containerd_test.go
  internal/app/machined/pkg/system/runner/containerd/import.go
  internal/app/machined/pkg/system/services/apid.go
  internal/app/machined/pkg/system/services/bootkube.go
  internal/app/machined/pkg/system/services/networkd.go
  internal/app/machined/pkg/system/services/routerd.go
  internal/app/machined/pkg/system/services/timed.go
  internal/app/machined/pkg/system/services/trustd.go
  internal/pkg/containers/image/image.go
Labels: status/approved, status/lgtm

#2579 docs: fix cluster name in docker docs
  docs/website/content/v0.6/en/guides/local/docker.md
  docs/website/content/v0.7/en/guides/local/docker.md
Labels: status/approved, status/lgtm

#2554 feat: validate cluster DNS name
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
Labels: status/approved

#2576 docs: remove second meeting from README
  README.md
Labels: status/approved

#2580 docs: add note on settings endpoints on MacOS
  docs/website/content/v0.6/en/guides/local/docker.md
Labels: status/approved, status/lgtm

#2581 fix: make Flannel CNI image follow `$PKGS` version
  Dockerfile
  internal/app/bootkube/images/images.go
  pkg/version/version.go
Labels: status/approved, status/lgtm

#2584 fix: provide unique username in generated kubeconfig
  internal/pkg/kubeconfig/admin.go
Labels: status/approved, status/lgtm

#2553 feat: add ApplyConfiguration API
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/apply-config.go
  docs/talosctl/talosctl.md
  docs/talosctl/talosctl_apply-config.md
  go.sum
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/integration/api/apply-config.go
  internal/pkg/mount/mount.go
  internal/pkg/mount/options.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/client/client.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#2585 docs: add guide on setting up air-gapped environment with `images`
  docs/website/content/v0.7.en.json
  docs/website/content/v0.7/en/guides/local/air-gapped.md
Labels: status/approved, status/lgtm

#2583 feat: add support for disabling time
  docs/website/content/v0.7/en/configuration/v1alpha1.md
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/apid.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/app/machined/pkg/system/services/trustd.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
Labels: status/approved, status/lgtm

#2586 chore: update qemu hack script to use ISO
  hack/test/qemu/qemu.sh
Labels: status/approved, status/lgtm

#2588 feat: support custom filename for talosctl kubeconfig
  cmd/talosctl/cmd/talos/kubeconfig.go
  docs/talosctl/talosctl_kubeconfig.md
  internal/integration/cli/kubeconfig.go
Labels: status/approved, status/lgtm

#2589 feat: show cluster state when `talosctl cluster create` finishes
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/mgmt/cluster/show.go
Labels: status/approved
