Repository siderolabs/talos, pull requests merged in 2020-07, with the labels that each got.

#2222 docs: digital rebar docs
  docs/website/content/v0.6.en.json
  docs/website/content/v0.6/en/guides/metal/digitalrebar.md
  hack/test/digitalrebar/bootenv.yaml
  hack/test/digitalrebar/params.yaml
  hack/test/digitalrebar/stages.yaml
  hack/test/digitalrebar/talos-controlplane-profile.yaml
  hack/test/digitalrebar/talos-init-profile.yaml
  hack/test/digitalrebar/talos-worker-profile.yaml
  hack/test/digitalrebar/workflow.yaml
Labels: status/approved, status/lgtm

#2253 feat: add /system directory
  Dockerfile
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/containerd.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/pkg/mount/mount.go
  internal/pkg/mount/overlay.go
  internal/pkg/mount/pseudo.go
  internal/pkg/provision/providers/docker/node.go
  pkg/constants/constants.go
Labels: status/approved, status/lgtm

#2252 feat: upgrade containerd to v1.3.6
  Dockerfile
Labels: status/approved

#2254 test: add short integration test with custom CNI
  .drone.yml
  Makefile
  cmd/talosctl/cmd/mgmt/cluster/create.go
  docs/talosctl/talosctl_cluster_create.md
  hack/drone.jsonnet
  hack/test/e2e-firecracker.sh
  hack/test/e2e.sh
  pkg/config/types/v1alpha1/generate/generate.go
  pkg/config/types/v1alpha1/generate/init.go
  pkg/config/types/v1alpha1/generate/join.go
  pkg/config/types/v1alpha1/generate/options.go
Labels: status/approved, status/lgtm

#2257 fix: report the correct containerd version
  Dockerfile
  pkg/constants/constants.go
Labels: status/approved, status/lgtm

#2255 test: run `e2e-firecracker-short` for default pipeline only
  .codecov.yml
  .drone.yml
  hack/drone.jsonnet
Labels: status/approved, status/lgtm

#2256 test: stabilize race unit-tests (circular, events)
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events_test.go
  internal/pkg/circular/circular_test.go
Labels: status/approved, status/lgtm

#2258 feat: upgrade Linux to v5.7.7
  Dockerfile
  pkg/constants/constants.go
Labels: status/approved, status/lgtm

#2259 test: run integration pipeline nightly
  .drone.yml
  hack/drone.jsonnet
Labels: status/approved, status/lgtm

#2262 test: resolve old TODO item
  internal/pkg/containers/containerd/containerd_test.go
Labels: status/approved, status/lgtm

#2260 feat: upgrade runc to v1.0.0-rc90
  Dockerfile
  Makefile
  api/common/common.pb.go
  api/health/health.pb.go
  api/machine/machine.pb.go
  api/network/network.pb.go
  api/os/os.pb.go
  api/security/security.pb.go
  api/time/time.pb.go
  cmd/talosctl/cmd/talos/list.go
  go.mod
  go.sum
  internal/app/apid/pkg/backend/apid.go
  internal/app/apid/pkg/backend/apid_test.go
  internal/app/machined/pkg/runtime/events.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events.go
  internal/app/networkd/pkg/nic/nic.go
  pkg/client/client.go
Labels: status/approved, status/lgtm

#2264 fix: provide default DNS domain to talosctl cluster create
  cmd/talosctl/cmd/mgmt/cluster/create.go
  docs/talosctl/talosctl_cluster_create.md
Labels: status/approved, status/lgtm

#2265 feat: implement service events
  api/machine/machine.pb.go
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/events.go
  go.mod
  internal/app/machined/pkg/system/events/events.go
  internal/app/machined/pkg/system/service_runner.go
  internal/integration/api/events.go
  internal/integration/cli/validate.go
  pkg/client/client.go
Labels: status/approved, status/lgtm

#2271 chore: cleanup sonobuoy after failed attempts
  hack/test/e2e.sh
Labels: status/approved, status/lgtm

#2279 chore: wait for resource deletion in sonobuoy
  hack/test/e2e.sh
Labels: status/approved, status/lgtm

#2282 fix: print correct sequence/task duration
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
Labels: status/approved, status/lgtm

#2284 fix: implement Unload() for services to make sure bootkube runs always
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/system.go
  internal/app/machined/pkg/system/system_test.go
Labels: status/approved, status/lgtm

#2283 fix: update the control plane cluster health check
  internal/pkg/cluster/check/kubernetes.go
Labels: kind/bug, status/approved

#2274 feat: implement API access to event history
  api/machine/machine.pb.go
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/events.go
  docs/talosctl/talosctl_events.md
  go.mod
  go.sum
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/main.go
  internal/app/machined/pkg/runtime/events.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events_test.go
  internal/app/machined/pkg/system/runner/goroutine/goroutine_test.go
  internal/integration/api/events.go
  pkg/client/client.go
  pkg/client/events.go
Labels: status/approved, status/lgtm

#2288 feat: add round-robin LB policy to Talos client by default
  cmd/talosctl/cmd/mgmt/cluster/create.go
  internal/integration/api/events.go
  internal/integration/api/logs.go
  internal/integration/provision/upgrade.go
  internal/pkg/cluster/check/default.go
  internal/pkg/cluster/check/reporter.go
  internal/pkg/cluster/check/service.go
  pkg/client/events.go
  pkg/client/resolver.go
Labels: status/approved, status/lgtm

#2290 test: fix sonobuoy delete
  hack/test/e2e.sh
Labels: status/approved

#2292 docs: update firecracker for new home of tc-redirect-tap plugin
  docs/website/content/v0.6/en/guides/local/firecracker.md
Labels: status/approved, status/lgtm

#2294 test: fix cli tests after load-balancing got enabled
  internal/app/osd/internal/reg/reg.go
  internal/integration/cli/logs.go
  internal/integration/cli/restart.go
Labels: status/approved, status/lgtm

#2291 feat: uncordon nodes automatically on boot
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/talos/health.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/integration/base/api.go
  internal/pkg/cluster/check/default.go
  internal/pkg/cluster/check/kubernetes.go
  pkg/kubernetes/kubernetes.go
Labels: status/approved, status/lgtm

#2296 fix: improve node uncordon tasks
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  pkg/kubernetes/kubernetes.go
Labels: status/approved, status/lgtm

#2287 test: update init node check in reset API tests
  internal/integration/api/reset.go
Labels: status/approved, status/lgtm

#2299 test: update tests for `pkg/follow` to be less time-dependent
  pkg/follow/follow_test.go
Labels: status/approved, status/lgtm

#2300 feat: print crash dump in `talosctl cluster create` on failure
  cmd/talosctl/cmd/mgmt/cluster/create.go
  docs/talosctl/talosctl_cluster_create.md
  hack/test/e2e-docker.sh
  hack/test/e2e-firecracker.sh
Labels: status/approved, status/lgtm

#2301 test: update events test with more flow control
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events_test.go
Labels: status/approved, status/lgtm

#2297 feat: merge mode in talosctl kubeconfig
  cmd/talosctl/cmd/talos/kubeconfig.go
  cmd/talosctl/pkg/talos/helpers/archive.go
  cmd/talosctl/pkg/talos/helpers/helpers_test.go
  cmd/talosctl/pkg/talos/helpers/testdata/archive.tar.gz
  docs/talosctl/talosctl_kubeconfig.md
  go.mod
  go.sum
  internal/integration/cli/kubeconfig.go
Labels: status/approved, status/lgtm

#2289 feat: add names to tasks and phases
  cmd/talosctl/cmd/talos/events.go
  internal/app/machined/pkg/runtime/controller.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller_test.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_test.go
Labels: status/approved, status/lgtm

#2302 test: workaround famous flaky Containerd.RunTwice test
  internal/app/machined/pkg/system/runner/containerd/containerd_test.go
Labels: status/approved, status/lgtm

#2303 refactor: merge osd into machined
  .conform.yaml
  Dockerfile
  api/machine/machine.pb.go
  api/machine/machine.proto
  api/os/os.pb.go
  api/os/os.proto
  cmd/talosctl/cmd/talos/containers.go
  cmd/talosctl/cmd/talos/memory.go
  cmd/talosctl/cmd/talos/processes.go
  cmd/talosctl/cmd/talos/stats.go
  docs/website/content/v0.6.en.json
  docs/website/content/v0.6/en/components/apid.md
  docs/website/content/v0.6/en/components/machined.md
  docs/website/content/v0.6/en/components/osctl.md
  docs/website/content/v0.6/en/components/osd.md
  docs/website/content/v0.6/en/components/overview.md
  docs/website/content/v0.6/en/configuration/overview.md
  docs/website/content/v0.6/en/guides/cloud/azure.md
  docs/website/content/v0.6/en/guides/getting-started/talosctl.md
  internal/app/apid/main.go
  internal/app/machined/internal/server/v1alpha1/osd_compat.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/runner/containerd/containerd_test.go
  internal/app/machined/pkg/system/services/osd.go
  internal/app/machined/pkg/system/services/osd_test.go
  internal/app/machined/pkg/system/system_test.go
  internal/app/osd/internal/reg/reg.go
  internal/app/osd/internal/reg/reg_test.go
  internal/app/osd/main.go
  internal/app/routerd/main.go
  internal/integration/api/logs.go
  internal/integration/cli/containers.go
  internal/integration/cli/services.go
  internal/integration/cli/stats.go
  pkg/client/client.go
  pkg/constants/constants.go
Labels: area/api, status/approved, status/lgtm

#2304 chore: update meeting links
  README.md
Labels: status/approved

#2305 release(v0.6.0-alpha.5): prepare release
  CHANGELOG.md
Labels: status/approved, status/lgtm

#2307 feat: upgrade Kubernetes to v1.19.0-rc.0
  Makefile
  docs/talosctl/talosctl_cluster_create.md
  docs/talosctl/talosctl_gen_config.md
  go.mod
  go.sum
  pkg/constants/constants.go
Labels: status/approved, status/lgtm

#2310 docs: update worker creation flags for azure docs
  docs/website/content/v0.4/en/guides/cloud/azure.md
  docs/website/content/v0.5/en/guides/cloud/azure.md
  docs/website/content/v0.6/en/guides/cloud/azure.md
Labels: status/approved, status/lgtm

#2306 feat: implement server-side API for cluster health checks
  Dockerfile
  api/cluster/cluster.pb.go
  api/cluster/cluster.proto
  cmd/talosctl/cmd/talos/crashdump.go
  cmd/talosctl/cmd/talos/health.go
  docs/talosctl/talosctl_health.md
  internal/app/apid/main.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_cluster.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/system/services/apid.go
  internal/app/routerd/main.go
  internal/integration/cli/health.go
  internal/pkg/cluster/kubelet.go
  internal/pkg/cluster/kubernetes.go
  internal/pkg/cluster/local.go
  pkg/client/client.go
  pkg/client/options.go
  pkg/constants/constants.go
  pkg/kubernetes/kubernetes.go
Labels: area/cli, status/approved, status/lgtm

#2312 chore: update clusterctl for CI testing
  Makefile
  hack/test/e2e-capi.sh
Labels: status/approved

#2314 chore: upgrade Go to 1.14.5
  Dockerfile
  Makefile
Labels: status/approved, status/lgtm

#2311 chore: update k8s v1.18 version
  Makefile
  docs/talosctl/talosctl_cluster_create.md
  docs/talosctl/talosctl_gen_config.md
  docs/website/content/v0.4/en/configuration/v1alpha1.md
  docs/website/content/v0.5/en/configuration/v1alpha1.md
  hack/test/libvirt/libvirt.sh
  pkg/config/types/v1alpha1/doc.go
  pkg/constants/constants.go
Labels: status/approved, status/lgtm

#2315 chore: update golangci-lint to 1.28.3
  Dockerfile
  Makefile
  cmd/installer/cmd/iso.go
  cmd/installer/pkg/install/install.go
  cmd/installer/pkg/ova/ova.go
  cmd/talosctl/cmd/docs.go
  cmd/talosctl/cmd/mgmt/config.go
  cmd/talosctl/cmd/mgmt/gen.go
  cmd/talosctl/cmd/talos/copy.go
  cmd/talosctl/cmd/talos/kubeconfig.go
  cmd/talosctl/pkg/talos/helpers/archive.go
  internal/app/bootkube/assets.go
  internal/app/machined/internal/install/install.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/logging/file.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/syslinux/syslinux.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/azure/register.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/digitalocean/digitalocean.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/runner/containerd/containerd_test.go
  internal/app/machined/pkg/system/service_runner.go
  internal/app/machined/pkg/system/services/apid.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/app/machined/pkg/system/services/networkd.go
  internal/app/machined/pkg/system/services/routerd.go
  internal/app/machined/pkg/system/services/timed.go
  internal/app/networkd/pkg/networkd/misc.go
  internal/app/networkd/pkg/networkd/networkd.go
  internal/pkg/containers/containerd/containerd_test.go
  internal/pkg/containers/cri/containerd/config.go
  internal/pkg/containers/cri/containerd/config_test.go
  internal/pkg/containers/cri/cri.go
  internal/pkg/containers/cri/cri_test.go
  internal/pkg/containers/image/resolver_test.go
  internal/pkg/cri/cri_test.go
  internal/pkg/kmsg/kmsg.go
  internal/pkg/mount/mount.go
  internal/pkg/provision/providers/firecracker/inmemhttp/inmemhttp_test.go
  internal/pkg/provision/providers/firecracker/loadbalancer.go
  internal/pkg/provision/providers/firecracker/node.go
  pkg/archiver/archiver_test.go
  pkg/archiver/walker_test.go
  pkg/blockdevice/blkpg/blkpg_linux.go
  pkg/blockdevice/blockdevice_linux.go
  pkg/blockdevice/lba/lba_darwin.go
  pkg/blockdevice/lba/lba_linux.go
  pkg/client/client.go
  pkg/client/config/config.go
  pkg/config/types/v1alpha1/generate/generate.go
  pkg/follow/follow.go
  pkg/grpc/factory/factory.go
  pkg/grpc/gen/remote.go
  pkg/sysctl/sysctl.go
Labels: status/approved, status/lgtm

#2317 chore: update module dependencies
  go.mod
  go.sum
  internal/integration/api/dmesg.go
  internal/integration/api/events.go
  internal/integration/api/logs.go
  internal/integration/api/reboot.go
  internal/integration/api/recover.go
  internal/integration/api/reset.go
  internal/integration/api/version.go
  internal/integration/cli/gen.go
  internal/integration/cli/validate.go
Labels: status/approved, status/lgtm

#2319 fix: update container name in docker crashdump
  internal/pkg/provision/providers/docker/crashdump.go
Labels: status/approved, status/lgtm

#2320 fix: wrap errors in upgrade API handler
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
Labels: status/approved, status/lgtm

#2309 feat: implement talosctl dashboard command
  api/machine/machine.pb.go
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/dashboard.go
  cmd/talosctl/cmd/talos/dashboard/components/components.go
  cmd/talosctl/cmd/talos/dashboard/components/gauges.go
  cmd/talosctl/cmd/talos/dashboard/components/graphs.go
  cmd/talosctl/cmd/talos/dashboard/components/info.go
  cmd/talosctl/cmd/talos/dashboard/components/nodetabs.go
  cmd/talosctl/cmd/talos/dashboard/components/sparklines.go
  cmd/talosctl/cmd/talos/dashboard/components/tables.go
  cmd/talosctl/cmd/talos/dashboard/components/topline.go
  cmd/talosctl/cmd/talos/dashboard/dashboard.go
  cmd/talosctl/cmd/talos/dashboard/data/data.go
  cmd/talosctl/cmd/talos/dashboard/data/diff.go
  cmd/talosctl/cmd/talos/dashboard/data/node.go
  cmd/talosctl/cmd/talos/dashboard/source.go
  cmd/talosctl/cmd/talos/dashboard/ui.go
  docs/talosctl/talosctl.md
  docs/talosctl/talosctl_dashboard.md
  internal/app/machined/internal/server/v1alpha1/v1alpha1_monitoring.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
Labels: area/api, area/cli, status/approved, status/lgtm

#2322 chore: move inmemhttp from firecracker provisioner to internal/pkg/
  internal/pkg/inmemhttp/inmemhttp.go
  internal/pkg/inmemhttp/inmemhttp_test.go
  internal/pkg/provision/providers/firecracker/launch.go
Labels: status/approved, status/lgtm

#2324 Update talosctl.md
  docs/website/content/v0.6/en/guides/getting-started/talosctl.md
Labels: status/approved, status/lgtm

#2323 chore: initial extraction of base vm provisioner
  internal/pkg/provision/providers/firecracker/crashdump.go
  internal/pkg/provision/providers/firecracker/create.go
  internal/pkg/provision/providers/firecracker/destroy.go
  internal/pkg/provision/providers/firecracker/firecracker.go
  internal/pkg/provision/providers/firecracker/loadbalancer.go
  internal/pkg/provision/providers/firecracker/network.go
  internal/pkg/provision/providers/firecracker/node.go
  internal/pkg/provision/providers/firecracker/state.go
  internal/pkg/provision/providers/vm/reflect.go
  internal/pkg/provision/providers/vm/state.go
  internal/pkg/provision/providers/vm/vm.go
Labels: status/approved, status/lgtm

#2321 test: provider correct installer kernel args for firecracker
  internal/pkg/provision/providers/firecracker/firecracker.go
  pkg/config/types/v1alpha1/generate/generate.go
  pkg/config/types/v1alpha1/generate/init.go
  pkg/config/types/v1alpha1/generate/join.go
  pkg/config/types/v1alpha1/generate/options.go
Labels: status/approved, status/lgtm

#2325 refactor: use `humanize.Bytes` everywhere
  cmd/talosctl/cmd/talos/processes.go
  go.mod
  go.sum
Labels: status/approved, status/lgtm

#2328 chore: extract loadbalancer, network, crashdup and process from firecracker
  internal/pkg/provision/providers/firecracker/create.go
  internal/pkg/provision/providers/firecracker/destroy.go
  internal/pkg/provision/providers/firecracker/node.go
  internal/pkg/provision/providers/vm/crashdump.go
  internal/pkg/provision/providers/vm/loadbalancer.go
  internal/pkg/provision/providers/vm/network.go
  internal/pkg/provision/providers/vm/process.go
Labels: status/approved, status/lgtm

#2329 chore: bump lodash from 4.17.15 to 4.17.19 in /docs/website
  docs/website/package-lock.json
Labels: status/approved, status/lgtm

#2332 fix: ignore sequence lock errors in machined
  api/common/common.pb.go
  api/common/common.proto
  internal/app/machined/main.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
Labels: status/approved, status/lgtm

#2333 fix: log messages properly when sequence/phase/task fails
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
Labels: status/approved, status/lgtm

#2331 feat: make partitions on additional disk without size occupy full disk
  cmd/installer/pkg/install/manifest.go
  docs/website/content/v0.6/en/configuration/v1alpha1.md
  pkg/blockdevice/table/gpt/gpt.go
  pkg/config/types/v1alpha1/v1alpha1_types.go
  pkg/config/types/v1alpha1/v1alpha1_validation.go
Labels: area/machineconfig, status/approved, status/lgtm

#2336 feat: upgrade etcd to 3.3.22 version
  docs/website/content/v0.6/en/guides/local/registry-cache.md
  go.mod
  go.sum
  internal/app/machined/pkg/system/services/etcd.go
  pkg/config/types/v1alpha1/v1alpha1_configurator.go
  pkg/constants/constants.go
Labels: status/approved, status/lgtm

#2327 feat: force nodes to be set in `talosctl` commands using the API
  cmd/talosctl/cmd/talos/crashdump.go
  cmd/talosctl/cmd/talos/health.go
  cmd/talosctl/cmd/talos/root.go
  hack/test/e2e-docker.sh
  hack/test/e2e-firecracker.sh
  hack/test/e2e.sh
  internal/integration/api/dmesg.go
  internal/integration/api/events.go
  internal/integration/api/logs.go
  internal/integration/api/reboot.go
  internal/integration/api/recover.go
  internal/integration/api/reset.go
  internal/integration/api/version.go
  internal/integration/base/api.go
  internal/integration/base/base.go
  internal/integration/base/cli.go
  internal/integration/base/discovery_k8s.go
  internal/integration/base/discovery_nok8s.go
  internal/integration/cli/containers.go
  internal/integration/cli/copy.go
  internal/integration/cli/dmesg.go
  internal/integration/cli/health.go
  internal/integration/cli/interfaces.go
  internal/integration/cli/kubeconfig.go
  internal/integration/cli/list.go
  internal/integration/cli/logs.go
  internal/integration/cli/memory.go
  internal/integration/cli/mounts.go
  internal/integration/cli/processes.go
  internal/integration/cli/read.go
  internal/integration/cli/restart.go
  internal/integration/cli/routes.go
  internal/integration/cli/services.go
  internal/integration/cli/stats.go
  internal/integration/cli/version.go
  pkg/client/client.go
Labels: status/approved, status/lgtm

#2347 chore: use Kubernetes pipelines
  .drone.jsonnet
  .drone.yml
  Dockerfile
  Makefile
  hack/test/e2e-docker.sh
  hack/test/e2e-firecracker.sh
  hack/test/e2e.sh
  hack/test/provision-tests.sh
  pkg/config/types/v1alpha1/generate/generate.go
  pkg/config/types/v1alpha1/v1alpha1_configurator.go
  pkg/constants/constants.go
Labels: status/lgtm

#2343 chore: upgrade pkgs and tools for Go 1.14.6
  Dockerfile
  Makefile
Labels: status/lgtm

#2355 fix: skip vmware platform for !amd64
  internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_other.go
Labels: status/lgtm

#2340 fix: skip removing CRI state when doing upgrade with preserve
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/approved, status/lgtm

#2357 chore: use outer docker as buildkit instance
  .drone.jsonnet
Labels: status/lgtm

#2358 chore: set default CIDRs
  pkg/constants/constants.go
Labels: status/approved

#2359 release(v0.6.0-alpha.6): prepare release
  CHANGELOG.md
Labels: status/approved, status/lgtm

#2338 release(v0.5.1): prepare release
  CHANGELOG.md
Labels: status/approved

#2361 fix: generate admin kubeconfig with default namespace
  internal/pkg/kubeconfig/admin.go
Labels: status/approved, status/lgtm

#2362 fix: bump timeouts
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/approved, status/lgtm

#2366 fix: fail ntpd service if initial time sync fails
  internal/app/timed/pkg/ntp/ntp.go
  internal/pkg/cluster/check/default.go
Labels: status/approved, status/lgtm

#2365 feat: pull in kernel with fuse support
  Dockerfile
Labels: status/approved, status/lgtm

#2354 test: remove apid load balancer for firecracker
  .drone.jsonnet
  Makefile
  cmd/talosctl/cmd/mgmt/loadbalancer_launch.go
  hack/test/provision-tests.sh
  internal/pkg/provision/providers/vm/loadbalancer.go
  internal/pkg/provision/request.go
Labels: status/approved

#2337 test: provide node discovery for cli tests via kubectl
  hack/test/e2e.sh
  internal/integration/base/base.go
  internal/integration/base/cli.go
  internal/integration/base/cluster.go
  internal/integration/base/discovery_k8s.go
  internal/integration/integration_test.go
Labels: status/approved, status/lgtm

#2339 test: upgrade versions the upgrade tests are operating on
  Makefile
  internal/integration/provision/upgrade.go
Labels: status/approved, status/lgtm

#2369 chore: add release notes
  .drone.jsonnet
  Makefile
  hack/release.sh
Labels: status/approved

#2374 fix: update status when adjusting the time
  internal/app/timed/pkg/ntp/ntp.go
  internal/app/timed/pkg/timex/timex.go
Labels: status/approved, status/lgtm

#2372 feat: upgrade Kubernetes to v1.19.0-rc.3
  Makefile
  docs/talosctl/talosctl_cluster_create.md
  docs/talosctl/talosctl_gen_config.md
  go.mod
  go.sum
  pkg/constants/constants.go
Labels: status/approved, status/lgtm

#2375 feat: taint master nodes with `NoSchedule` taint
  go.mod
  go.sum
  internal/integration/base/cli.go
  internal/pkg/cluster/check/kubernetes.go
  pkg/kubernetes/kubernetes.go
Labels: status/approved, status/lgtm

#2377 chore: mount `/tmp` in CI to the build steps
  .drone.jsonnet
Labels: status/approved

#2379 chore: really mount /tmp in CI as tmpfs
  .drone.jsonnet
Labels: status/approved

#2376 feat: add dynamic config decoder
  cmd/talosctl/cmd/mgmt/config.go
  cmd/talosctl/pkg/talos/helpers/helpers_test.go
  go.mod
  go.sum
  internal/pkg/provision/providers/vm/reflect.go
  internal/pkg/provision/providers/vm/state.go
  pkg/client/config/config.go
  pkg/config/configloader/configloader.go
  pkg/config/configloader/configloader_test.go
  pkg/config/decoder/decoder.go
  pkg/config/decoder/decoder_test.go
  pkg/config/registry.go
  pkg/config/types/v1alpha1/bundle/bundle.go
  pkg/config/types/v1alpha1/v1alpha1_loader.go
  pkg/config/types/v1alpha1/v1alpha1_provider.go
  pkg/config/types/v1alpha1/v1alpha1_types.go
Labels: status/approved, status/lgtm

#2380 fix: workaround edge case for etcd re-injection on bootstrap
  internal/app/machined/pkg/system/system.go
Labels: status/approved, status/lgtm

#2373 test: update qemu/firecracker provisioners
  Makefile
  cmd/talosctl/cmd/mgmt/cluster/create.go
  docs/talosctl/talosctl_cluster_create.md
  hack/test/e2e-firecracker.sh
  hack/test/e2e-qemu.sh
  hack/test/e2e.sh
  internal/integration/provision/upgrade.go
  internal/pkg/provision/options.go
  internal/pkg/provision/providers/firecracker/create.go
  internal/pkg/provision/providers/firecracker/kernel.go
  internal/pkg/provision/providers/firecracker/node.go
  internal/pkg/provision/providers/qemu/create.go
  internal/pkg/provision/providers/qemu/launch.go
  internal/pkg/provision/providers/qemu/node.go
  internal/pkg/provision/providers/qemu/qemu.go
  internal/pkg/provision/request.go
Labels: status/approved

#2381 chore: use qemu instead of firecracker in CI
  .drone.jsonnet
  internal/integration/provision/upgrade.go
Labels: kind/ci, status/approved

#2384 test: bump timeout for upgrade tests
  internal/integration/provision/upgrade.go
Labels: status/approved

#2383 chore: add aliases to some `talosctl` commands
  cmd/talosctl/cmd/talos/memory.go
  cmd/talosctl/cmd/talos/mounts.go
  cmd/talosctl/cmd/talos/processes.go
  cmd/talosctl/cmd/talos/routes.go
  cmd/talosctl/cmd/talos/stats.go
  docs/talosctl/talosctl.md
  docs/talosctl/talosctl_stats.md
Labels: status/approved, status/lgtm

#2386 test: destroy clusters in e2e tests (qemu/firecracker)
  hack/test/e2e-firecracker.sh
  hack/test/e2e-qemu.sh
Labels: status/approved

#2349 test: use registry mirrors in CI
  hack/test/e2e-docker.sh
  hack/test/e2e-firecracker.sh
  hack/test/e2e-qemu.sh
  hack/test/e2e.sh
Labels: status/approved

#2391 chore: bump elliptic from 6.5.2 to 6.5.3 in /docs/website
  docs/website/package-lock.json
Labels: status/approved, status/lgtm
