Repository siderolabs/talos, pull requests merged in 2020-10, with the labels that each got.

#2590 docs: small fixes for the config docs and air-gapped
  docs/website/content/v0.7/en/configuration/v1alpha1.md
  docs/website/content/v0.7/en/guides/local/air-gapped.md
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
Labels: status/approved, status/lgtm

#2591 fix: registry auth config building
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
Labels: status/approved, status/lgtm

#2596 chore: attempt to fix image pushing for GitHub
  .drone.jsonnet
Labels: status/approved, status/lgtm

#2594 feat: support --registry-insecure-skip-verify for `cluster create`
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/mgmt/validate.go
  docs/talosctl/talosctl_cluster_create.md
  docs/website/content/v0.7/en/configuration/v1alpha1.md
  pkg/machinery/config/types/v1alpha1/generate/generate.go
  pkg/machinery/config/types/v1alpha1/generate/init.go
  pkg/machinery/config/types/v1alpha1/generate/join.go
  pkg/machinery/config/types/v1alpha1/generate/options.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_marshal.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_marshal_test.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
Labels: status/approved, status/lgtm

#2598 fix: make CLI context exit immediately on second ^C
  pkg/cli/context.go
Labels: status/approved, status/lgtm

#2599 feat: use kubeconfig merge in `talosctl kubeconfig` by default
  cmd/talosctl/cmd/talos/kubeconfig.go
  docs/talosctl/talosctl_kubeconfig.md
  go.mod
  go.sum
  internal/integration/cli/kubeconfig.go
  internal/pkg/kubeconfig/kubeconfig.go
  internal/pkg/kubeconfig/merge.go
  internal/pkg/kubeconfig/merge_test.go
Labels: status/approved, status/lgtm

#2604 refactor: extract blockdevice library
  cmd/installer/pkg/install/install.go
  cmd/installer/pkg/install/manifest.go
  cmd/installer/pkg/install/verify.go
  go.mod
  go.sum
  internal/app/machined/pkg/runtime/state.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/adv.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_state.go
  internal/pkg/mount/mount.go
  internal/pkg/mount/system.go
  pkg/blockdevice/blkpg/blkpg_darwin.go
  pkg/blockdevice/blkpg/blkpg_linux.go
  pkg/blockdevice/blockdevice.go
  pkg/blockdevice/blockdevice_darwin.go
  pkg/blockdevice/blockdevice_linux.go
  pkg/blockdevice/blockdevice_test.go
  pkg/blockdevice/filesystem/fs.go
  pkg/blockdevice/filesystem/iso9660/iso9660.go
  pkg/blockdevice/filesystem/iso9660/options.go
  pkg/blockdevice/filesystem/iso9660/superblock.go
  pkg/blockdevice/filesystem/vfat/filesystem.go
  pkg/blockdevice/filesystem/vfat/options.go
  pkg/blockdevice/filesystem/vfat/superblock.go
  pkg/blockdevice/filesystem/xfs/options.go
  pkg/blockdevice/filesystem/xfs/superblock.go
  pkg/blockdevice/lba/lba_darwin.go
  pkg/blockdevice/lba/lba_linux.go
  pkg/blockdevice/lba/lba_test.go
  pkg/blockdevice/options.go
  pkg/blockdevice/probe/probe.go
  pkg/blockdevice/probe/probe_test.go
  pkg/blockdevice/table/gpt/gpt.go
  pkg/blockdevice/table/gpt/header/header.go
  pkg/blockdevice/table/gpt/header/options.go
  pkg/blockdevice/table/gpt/options.go
  pkg/blockdevice/table/gpt/partition/options.go
  pkg/blockdevice/table/gpt/partition/partition.go
  pkg/blockdevice/table/table.go
  pkg/blockdevice/util/util.go
  pkg/blockdevice/util/util_test.go
  pkg/makefs/makefs.go
  pkg/makefs/vfat.go
  pkg/makefs/xfs.go
  pkg/provision/providers/firecracker/bootloader.go
  pkg/provision/providers/qemu/launch.go
Labels: status/approved, status/lgtm

#2605 feat: pull kubeconfig from the cluster on successful `cluster create`
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/talos/kubeconfig.go
  docs/talosctl/talosctl_cluster.md
  docs/talosctl/talosctl_cluster_create.md
  internal/pkg/kubeconfig/kubeconfig.go
Labels: status/approved, status/lgtm

#2607 feat: allow disabling NoSchedule on master nodes
  docs/website/content/v0.7/en/configuration/v1alpha1.md
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  pkg/kubernetes/kubernetes.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
Labels: status/approved, status/lgtm

#2600 feat: add etcd API
  api/machine/machine.proto
  internal/app/bootkube/recover.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/integration/api/etcd.go
  internal/pkg/etcd/etcd.go
  pkg/machinery/api/machine/machine.pb.go
Labels: status/approved

#2611 release(v0.7.0-alpha.4): prepare release
  CHANGELOG.md
Labels: status/approved, status/lgtm

#2613 fix: nil pointer panic in talosctl dashboard
  cmd/talosctl/cmd/talos/dashboard/components/tables.go
Labels: status/approved, status/lgtm

#2615 chore: publish list of images to release notes
  Makefile
  hack/release.sh
Labels: status/approved, status/lgtm

#2616 fix: apply --removable option always to get standard UEFI filename
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
Labels: status/approved, status/lgtm

#2617 chore: bump pkgs version
  Makefile
Labels: status/approved, status/lgtm

#2614 chore: add Context as param to some methods of `Platform` interface
  internal/app/machined/pkg/runtime/platform.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/azure/register.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/container/container.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/digitalocean/digitalocean.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_other.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/networkd/pkg/networkd/networkd.go
  pkg/download/download.go
Labels: status/approved, status/lgtm

#2618 feat: implement talos.shutdown=[halt|poweroff] kernel argument
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  pkg/machinery/constants/constants.go
  pkg/provision/providers/qemu/node.go
  pkg/provision/providers/qemu/qemu.go
Labels: status/approved

#2619 fix: random failures in cluster health checks
  cmd/talosctl/cmd/talos/health.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_cluster.go
  internal/integration/base/cluster.go
Labels: status/approved, status/lgtm

#2620 feat: bring in install-cni & pod-checkpointer from extras packages
  Dockerfile
  Makefile
  cmd/talosctl/cmd/talos/images.go
  internal/app/bootkube/images/images.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/constants/constants.go
  pkg/version/version.go
Labels: status/approved, status/lgtm

#2621 release(v0.7.0-alpha.5): prepare release
  CHANGELOG.md
Labels: status/approved

#2622 test: potential fix for talosctl cluster destroy being stuck
  pkg/provision/internal/inmemhttp/inmemhttp.go
  pkg/provision/providers/qemu/launch.go
Labels: status/approved, status/lgtm

#2623 release(v0.7.0-alpha.6): prepare release
  CHANGELOG.md
Labels: status/approved, status/lgtm

#2634 fix: improve logging and errors for extra manifests by URL
  internal/app/bootkube/assets.go
Labels: status/approved, status/lgtm

#2633 docs: add link to latest docs
  README.md
  docs/website/components/DocumentationDropdown.vue
  docs/website/components/Header.vue
  docs/website/nuxt.config.js
Labels: status/approved, status/lgtm

#2636 feat: support disk usage command in talosctl
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/diskusage.go
  cmd/talosctl/cmd/talos/list.go
  docs/talosctl/talosctl.md
  internal/app/apid/main.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/integration/api/diskusage.go
  internal/integration/cli/diskusage.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/client/client.go
Labels: status/approved, status/lgtm

#2637 feat: handle unsupported commands being called for docker
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/mode.go
  pkg/machinery/client/client.go
Labels: status/approved, status/lgtm

#2639 feat: bump packages version for the kernel with BBR TCP congestion algo
  Makefile
Labels: status/approved, status/lgtm

#2643 chore: bump Go to 1.15.3
  Makefile
Labels: status/approved, status/lgtm

#2644 test: add unit-test for the installer manifest
  cmd/installer/pkg/install/manifest.go
  cmd/installer/pkg/install/manifest_test.go
  internal/pkg/loopback/loopback.go
Labels: status/approved, status/lgtm

#2645 feat: support metric values for DHCP
  docs/website/content/v0.7/en/configuration/v1alpha1.md
  internal/app/networkd/pkg/address/dhcp.go
  internal/app/networkd/pkg/networkd/netconf.go
  internal/app/networkd/pkg/nic/nic.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
Labels: status/approved, status/lgtm

#2647 feat: bump packages for Linux 5.8.15 and containerd 1.4.1
  Makefile
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2648 feat: support MTU and route changes for DHCP
  docs/website/content/v0.7/en/configuration/v1alpha1.md
  internal/app/networkd/pkg/address/dhcp.go
  internal/app/networkd/pkg/networkd/netconf.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
Labels: status/approved, status/lgtm

#2652 fix: address nil pointer panic
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
Labels: status/approved, status/lgtm

#2653 docs: link container images to our repository
  Dockerfile
Labels: status/approved, status/lgtm

#2651 test: clean up integration test code, fix flakes
  .golangci.yml
  internal/integration/api/apply-config.go
  internal/integration/api/diskusage.go
  internal/integration/api/dmesg.go
  internal/integration/api/etcd.go
  internal/integration/api/logs.go
  internal/integration/api/reboot.go
  internal/integration/api/recover.go
  internal/integration/api/reset.go
  internal/integration/api/version.go
  internal/integration/base/api.go
  internal/integration/base/base.go
  internal/integration/base/cli.go
  internal/integration/base/cluster.go
  internal/integration/base/discovery_k8s.go
  internal/integration/base/run.go
  internal/integration/cli/crashdump.go
  internal/integration/cli/diskusage.go
  internal/integration/cli/gen.go
  internal/integration/cli/health.go
  internal/integration/cli/restart.go
  internal/integration/cli/validate.go
  internal/integration/cli/version.go
  internal/integration/integration_test.go
  internal/integration/k8s/version.go
  internal/integration/provision/upgrade.go
Labels: status/approved, status/lgtm

#2654 refactor: bring more control to install.Manifest execution
  cmd/installer/pkg/install/install.go
  cmd/installer/pkg/install/manifest.go
  cmd/installer/pkg/install/manifest_test.go
  docs/website/content/v0.7/en/configuration/v1alpha1.md
  go.mod
  go.sum
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/bootloader.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/pkg/mount/iter.go
  internal/pkg/mount/mount.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
Labels: status/approved, status/lgtm

#2649 feat: upgrade Kubernetes to 1.19.3
  Makefile
  docs/talosctl/talosctl_cluster_create.md
  docs/talosctl/talosctl_gen_config.md
  docs/talosctl/talosctl_upgrade-k8s.md
  docs/talosctl/talosctl_usage.md
  go.mod
  go.sum
  internal/integration/base/api.go
  internal/integration/provision/upgrade.go
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2655 chore: bump module dependencies in go.mod
  docs/talosctl/talosctl.md
  docs/talosctl/talosctl_apply-config.md
  docs/talosctl/talosctl_bootstrap.md
  docs/talosctl/talosctl_cluster.md
  docs/talosctl/talosctl_cluster_create.md
  docs/talosctl/talosctl_cluster_destroy.md
  docs/talosctl/talosctl_cluster_show.md
  docs/talosctl/talosctl_config.md
  docs/talosctl/talosctl_config_add.md
  docs/talosctl/talosctl_config_context.md
  docs/talosctl/talosctl_config_endpoint.md
  docs/talosctl/talosctl_config_node.md
  docs/talosctl/talosctl_containers.md
  docs/talosctl/talosctl_crashdump.md
  docs/talosctl/talosctl_dmesg.md
  docs/talosctl/talosctl_events.md
  docs/talosctl/talosctl_gen.md
  docs/talosctl/talosctl_gen_ca.md
  docs/talosctl/talosctl_gen_crt.md
  docs/talosctl/talosctl_gen_csr.md
  docs/talosctl/talosctl_gen_key.md
  docs/talosctl/talosctl_gen_keypair.md
  docs/talosctl/talosctl_health.md
  docs/talosctl/talosctl_images.md
  docs/talosctl/talosctl_interfaces.md
  docs/talosctl/talosctl_list.md
  docs/talosctl/talosctl_logs.md
  docs/talosctl/talosctl_memory.md
  docs/talosctl/talosctl_mounts.md
  docs/talosctl/talosctl_processes.md
  docs/talosctl/talosctl_read.md
  docs/talosctl/talosctl_reboot.md
  docs/talosctl/talosctl_recover.md
  docs/talosctl/talosctl_reset.md
  docs/talosctl/talosctl_restart.md
  docs/talosctl/talosctl_rollback.md
  docs/talosctl/talosctl_routes.md
  docs/talosctl/talosctl_shutdown.md
  docs/talosctl/talosctl_stats.md
  docs/talosctl/talosctl_time.md
  docs/talosctl/talosctl_upgrade.md
  docs/talosctl/talosctl_usage.md
  docs/talosctl/talosctl_validate.md
  docs/talosctl/talosctl_version.md
  go.mod
  go.sum
  internal/app/networkd/pkg/address/dhcp.go
Labels: status/approved, status/lgtm

#2659 fix: update handling of ntp disable
  docs/website/content/v0.7/en/configuration/v1alpha1.md
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/apid.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/app/machined/pkg/system/services/trustd.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
Labels: status/approved, status/lgtm

#2656 release(v0.7.0-alpha.7): prepare release
  CHANGELOG.md
Labels: status/approved, status/lgtm

#2657 chore: fix the check-dirty command to abort on untracked files
  Makefile
Labels: status/approved, status/lgtm

#2660 fix: correctly calculate output width in colored health reporter
  pkg/cluster/check/reporter.go
Labels: status/approved, status/lgtm

#2662 chore: reduce numer of steps/parallelism of Drone build
  .drone.jsonnet
Labels: status/approved, status/lgtm

#2664 chore: move to newer release of rtnetlink with fn args
  go.mod
  go.sum
  internal/app/networkd/pkg/nic/nic.go
Labels: status/approved, status/lgtm

#2665 feat: wipe disks faster in the installer
  cmd/installer/pkg/install/manifest.go
  go.mod
  go.sum
Labels: status/approved, status/lgtm

#2666 chore: update CI scripts
  hack/test/capi/cluster-aws.yaml
  hack/test/capi/cluster-gcp.yaml
  hack/test/e2e-azure.sh
  hack/test/e2e-capi.sh
  hack/test/e2e-gcp.sh
Labels: status/approved, status/lgtm

#2663 fix: implement preserving contents of partition on install
  cmd/installer/cmd/root.go
  cmd/installer/pkg/install/install.go
  cmd/installer/pkg/install/manifest.go
  cmd/installer/pkg/install/manifest_test.go
  cmd/talosctl/cmd/talos/rollback.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/integration/base/api.go
  internal/pkg/mount/system.go
  pkg/archiver/archiver.go
  pkg/archiver/untar.go
Labels: status/approved, status/lgtm

#2671 fix: stop ignoring `EINVAL` on mount
  internal/pkg/mount/mount.go
Labels: status/approved, status/lgtm

#2672 fix: ignore transient errors in upgrade Kubernetes code
  pkg/cluster/kubernetes/upgrade.go
Labels: status/approved, status/lgtm

#2668 feat: extend etcd health check on upgrade
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/pkg/etcd/etcd.go
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2678 fix: stop etcd on any path on upgrade
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/system.go
Labels: status/approved, status/lgtm

#2661 feat: encode comments as part of talosctl generated configs
  Dockerfile
  Makefile
  cmd/talosctl/cmd/docs.go
  docs/website/content/v0.7/en/configuration/v1alpha1.md
  hack/docgen/go.mod
  hack/docgen/go.sum
  hack/docgen/main.go
  pkg/machinery/config/decoder/decoder_test.go
  pkg/machinery/config/encoder/documentation.go
  pkg/machinery/config/encoder/encoder.go
  pkg/machinery/config/encoder/encoder_test.go
  pkg/machinery/config/encoder/markdown.go
  pkg/machinery/config/types/v1alpha1/doc.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
Labels: status/approved, status/lgtm

#2679 fix: stop CRI pods on upgrade with preserve
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/pkg/cri/pods.go
Labels: status/approved, status/lgtm

#2682 fix: single-node upgrade: stopping etcd and CRI pods
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/system.go
  internal/pkg/cri/pods.go
Labels: status/approved, status/lgtm

#2681 docs: fix config reference types links
  pkg/machinery/config/encoder/markdown.go
  website/content/docs/v0.7/Reference/configuration.md
Labels: status/approved, status/lgtm

#2683 docs: add robots.txt and fix sitemap.xml
  website/gridsome.config.js
  website/static/robots.txt
Labels: status/approved

#2684 feat: bump CoreDNS to 1.7.0
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/constants/constants.go
Labels: status/lgtm

#2686 fix: revert "feat: bump CoreDNS to 1.7.0"
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2685 docs: address small nits
  website/package-lock.json
  website/package.json
  website/src/components/LayoutHeader.vue
  website/src/components/NextPrevLinks.vue
  website/src/components/Sidebar.vue
  website/src/components/SidebarSection.vue
  website/src/layouts/Default.vue
  website/src/main.js
Labels: status/approved, status/lgtm

#2673 fix: re-implement upgrade (install) with preserve
  Makefile
  cmd/installer/pkg/install/install.go
  cmd/installer/pkg/install/manifest.go
  cmd/installer/pkg/install/manifest_test.go
  go.mod
  go.sum
  internal/integration/integration_test.go
  internal/integration/provision/provision.go
  internal/integration/provision/upgrade.go
  internal/pkg/loopback/loopback.go
  internal/pkg/mount/mount.go
  pkg/archiver/archiver.go
  pkg/archiver/walker.go
  pkg/archiver/walker_test.go
  pkg/cluster/check/default.go
  pkg/cluster/check/kubernetes.go
  pkg/machinery/config/encoder/encoder.go
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2689 fix: retry connection refused errors while bootstrapping a cluster
  pkg/cluster/bootstrap.go
Labels: status/approved, status/lgtm

#2690 feat: bump Linux to 5.8.16, enable mpt3sas driver
  Makefile
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2688 feat: bump CoreDNS to 1.7.0
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2692 fix: remove default time server in time command
  cmd/talosctl/cmd/talos/time.go
  website/content/docs/v0.7/Reference/cli.md
Labels: status/approved, status/lgtm

#2693 release(v0.6.3): prepare release
  CHANGELOG.md
Labels: status/approved

#2694 chore: output more logs from the installer
  cmd/installer/cmd/install.go
  cmd/installer/pkg/install/manifest.go
Labels: status/approved

#2695 docs: improve search bar
  website/content/docs/v0.7/Introduction/quickstart.md
  website/src/components/LayoutHeader.vue
  website/src/components/Search.vue
  website/src/components/Sidebar.vue
  website/src/components/SidebarDropdown.vue
  website/src/layouts/Default.vue
  website/src/templates/MarkdownPage.vue
Labels: status/approved, status/lgtm

#2699 fix: properly initialize manifest in user disks creation
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/approved

#2700 fix: bump type for `DiskSize` to be 64-bit
  cmd/installer/pkg/install/manifest.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  website/content/docs/v0.7/Reference/configuration.md
Labels: status/approved

#2696 test: bump Talos version for upgrade tests, bump Cilium version
  .drone.jsonnet
  Makefile
  internal/integration/provision/upgrade.go
Labels: status/approved

#2701 docs: improve the config reference documentation
  go.sum
  hack/docgen/main.go
  pkg/machinery/config/encoder/documentation.go
  pkg/machinery/config/encoder/markdown.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  website/content/docs/v0.7/Reference/configuration.md
  website/src/assets/css/main.css
Labels: status/approved, status/lgtm

#2698 docs: use grid instead of flexbox
  website/src/components/OnThisPage.vue
  website/src/components/Sidebar.vue
  website/src/components/SidebarDropdown.vue
  website/src/components/SidebarSearch.vue
  website/src/components/SidebarSection.vue
  website/src/layouts/Default.vue
  website/src/templates/MarkdownPage.vue
Labels: status/approved, status/lgtm

#2703 release(v0.7.0-alpha.8): prepare release
  CHANGELOG.md
Labels: status/approved, status/lgtm

#2704 docs: fix small CSS issues
  pkg/machinery/config/encoder/markdown.go
  website/content/docs/v0.7/Reference/configuration.md
  website/src/assets/css/main.css
  website/src/components/OnThisPage.vue
  website/src/templates/MarkdownPage.vue
Labels: status/approved, status/lgtm

#2697 feat: allow specifying user-disks in talosctl cluster create
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/mgmt/cluster/show.go
  hack/test/e2e-qemu.sh
  internal/integration/cli/mounts.go
  internal/integration/integration_test.go
  internal/integration/provision/provision.go
  internal/integration/provision/upgrade.go
  pkg/machinery/config/types/v1alpha1/generate/generate.go
  pkg/machinery/config/types/v1alpha1/generate/init.go
  pkg/machinery/config/types/v1alpha1/generate/join.go
  pkg/machinery/config/types/v1alpha1/generate/options.go
  pkg/provision/providers/docker/docker.go
  pkg/provision/providers/firecracker/node.go
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/qemu/node.go
  pkg/provision/providers/vm/disk.go
  pkg/provision/provision.go
  pkg/provision/request.go
  pkg/provision/result.go
  website/content/docs/v0.7/Reference/cli.md
Labels: status/approved, status/lgtm

#2705 docs: add redirect for /docs/latest
  website/static/_redirects
Labels: status/approved, status/lgtm

#2707 fix: read/write human readable representations for bytes and octals
  cmd/talosctl/cmd/mgmt/cluster/create.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  website/content/docs/v0.7/Reference/configuration.md
Labels: status/approved, status/lgtm

#2708 docs: update config reference docs
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  website/content/docs/v0.7/Guides/configuring-pull-through-cache.md
  website/content/docs/v0.7/Reference/configuration.md
Labels: status/approved

#2709 feat: skip resizing ephemeral partition if not required
  go.mod
  go.sum
  internal/pkg/mount/mount.go
Labels: status/approved, status/lgtm

#2702 feat: build talosctl-cni-bundle, use it in talosctl for QEMU
  .drone.jsonnet
  Dockerfile
  Makefile
  cmd/talosctl/cmd/mgmt/cluster/cluster.go
  cmd/talosctl/cmd/mgmt/cluster/create.go
  go.mod
  go.sum
  hack/test/e2e-qemu.sh
  pkg/provision/providers/qemu/arch.go
  pkg/provision/providers/qemu/create.go
  pkg/provision/providers/qemu/node.go
  pkg/provision/providers/qemu/preflight.go
  pkg/provision/request.go
  website/content/docs/v0.7/Local Platforms/firecracker.md
  website/content/docs/v0.7/Local Platforms/qemu.md
  website/content/docs/v0.7/Reference/cli.md
Labels: status/approved, status/lgtm

#2706 docs: address small nits
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  website/content/docs/v0.7/Reference/configuration.md
  website/gridsome.config.js
  website/src/components/LayoutHeader.vue
  website/src/components/OnThisPage.vue
  website/src/layouts/Default.vue
  website/static/_redirects
Labels: status/approved, status/lgtm

#2597 feat: add webconfig service
  internal/app/machined/pkg/runtime/v1alpha1/platform/container/container.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/errors/errors.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/pkg/webconfig/webconfig.go
Labels: status/approved, status/lgtm
