Repository siderolabs/talos, pull requests merged in 2020-02, with the labels that each got.

#1856 chore: use common method to pull etcd image
  internal/app/machined/pkg/system/services/etcd.go
Labels: status/needs-cherry-pick

#1854 chore: support slash commands in drone
  .drone.yml
  .github/workflows/promote-e2e.yml
  hack/drone.jsonnet
Labels: needs-e2e, ok-to-test

#1861 chore: only run ok-to-test when PR
  .drone.yml
  hack/drone.jsonnet
Labels: needs-e2e, ok-to-test

#1863 chore: sign .drone.yml
  .drone.yml
Labels: ok-to-test

#1862 chore: prepare release v0.4.0-alpha.4
  CHANGELOG-0.4.md
Labels: ok-to-test

#1870 fix: do not add empty netconf
  internal/app/networkd/pkg/networkd/networkd.go
Labels: ok-to-test

#1868 fix: don't proxy gRPC unix connections
  internal/app/machined/pkg/system/services/networkd.go
  internal/app/machined/pkg/system/services/osd.go
  internal/app/networkd/pkg/reg/reg_test.go
  internal/app/ntpd/pkg/reg/reg_test.go
  internal/pkg/cri/client.go
  pkg/grpc/dialer/dialer.go
  pkg/grpc/dialer/dialer_test.go
Labels: ok-to-test, status/needs-cherry-pick

#1875 chore: implement loadbalancer for firecracker provisioner
  cmd/osctl/cmd/cluster.go
  cmd/osctl/cmd/firecracker_launch_linux.go
  cmd/osctl/cmd/loadbalancer_launch.go
  go.mod
  go.sum
  internal/integration/api/reboot.go
  internal/pkg/loadbalancer/loadbalancer.go
  internal/pkg/loadbalancer/loadbalancer_test.go
  internal/pkg/loadbalancer/upstream/upstream.go
  internal/pkg/loadbalancer/upstream/upstream_test.go
  internal/pkg/provision/check/service.go
  internal/pkg/provision/providers/docker/docker.go
  internal/pkg/provision/providers/firecracker/create.go
  internal/pkg/provision/providers/firecracker/destroy.go
  internal/pkg/provision/providers/firecracker/firecracker.go
  internal/pkg/provision/providers/firecracker/loadbalancer.go
  internal/pkg/provision/providers/firecracker/node.go
  internal/pkg/provision/providers/firecracker/process.go
  internal/pkg/provision/provision.go
Labels: ok-to-test

#1866 chore: support bootloader emulation in firecracker provisioner
  cmd/osctl/cmd/cluster.go
  docs/osctl/osctl_cluster_create.md
  go.mod
  go.sum
  internal/pkg/kernel/vmlinuz/vmlinuz.go
  internal/pkg/provision/options.go
  internal/pkg/provision/providers/firecracker/bootloader.go
  internal/pkg/provision/providers/firecracker/create.go
  internal/pkg/provision/providers/firecracker/launch.go
  internal/pkg/provision/providers/firecracker/node.go
  pkg/blockdevice/filesystem/vfat/filesystem.go
  pkg/blockdevice/filesystem/vfat/superblock.go
  pkg/blockdevice/lba/lba.go
Labels: ok-to-test

#1867 feat: implement registry mirror & config for image pull
  cmd/osctl/cmd/cluster.go
  cmd/osctl/cmd/config.go
  docs/osctl/osctl_cluster_create.md
  docs/osctl/osctl_config_generate.md
  docs/website/content/v0.3/en/configuration/v1alpha1.md
  go.mod
  internal/app/machined/internal/api/reg/reg.go
  internal/app/machined/internal/phase/config/extra_files.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/pkg/containers/cri/containerd/config.go
  internal/pkg/containers/cri/containerd/config_test.go
  internal/pkg/containers/cri/containerd/containerd.go
  internal/pkg/containers/image/image.go
  internal/pkg/containers/image/resolver.go
  internal/pkg/containers/image/resolver_test.go
  internal/pkg/install/install.go
  pkg/config/machine/machine.go
  pkg/config/types/v1alpha1/generate/controlplane.go
  pkg/config/types/v1alpha1/generate/generate.go
  pkg/config/types/v1alpha1/generate/init.go
  pkg/config/types/v1alpha1/generate/join.go
  pkg/config/types/v1alpha1/generate/options.go
  pkg/config/types/v1alpha1/v1alpha1_configurator.go
  pkg/config/types/v1alpha1/v1alpha1_types.go
Labels: ok-to-test

#1878 chore: update pkgs
  Dockerfile
Labels: ok-to-test

#1877 chore: build app container images skipping export to host
  .drone.yml
  Dockerfile
  Makefile
  hack/drone.jsonnet
Labels: ok-to-test

#1881 chore: prepare release v0.4.0-alpha.5
  CHANGELOG-0.4.md
Labels: ok-to-test

#1884 fix: PodCIDR, ServiceCIDR should be comma sets
  pkg/config/types/v1alpha1/v1alpha1_configurator.go
Labels: ok-to-test

#1882 fix: validate install disk
  pkg/config/types/v1alpha1/v1alpha1_validation.go
Labels: ok-to-test

#1886 chore: remove KubernetesVersion from provision request
  cmd/osctl/cmd/cluster.go
  internal/pkg/provision/request.go
Labels: ok-to-test

#1885 test: implement RebootAllNodes test
  internal/integration/api/reboot.go
Labels: ok-to-test

#1887 test: fix `RebootAllNodes` test to reboot all nodes in one call
  internal/integration/api/reboot.go
Labels: ok-to-test

#1889 fix: allow kublet to handle multiple service CIDRs
  internal/app/machined/pkg/system/services/kubelet.go
Labels: ok-to-test

#1890 chore: move golangci-lint.yaml to .golangci.yml
  .dockerignore
  .golangci.yml
  Dockerfile
Labels: ok-to-test

#1876 chore: push installer & talos images to the CI registry on every build
  .drone.yml
  Makefile
  hack/drone.jsonnet
  hack/test/e2e-firecracker.sh
Labels: ok-to-test

#1891 fix: fix reset command
  api/machine/machine.pb.go
  api/machine/machine.proto
  cmd/osctl/cmd/reset.go
  cmd/osctl/pkg/client/client.go
  docs/osctl/osctl_reset.md
  internal/app/machined/internal/api/reg/reg.go
  internal/app/machined/internal/phase/disk/reset_system_disk.go
  internal/app/machined/internal/sequencer/sequencer.go
  internal/app/machined/internal/sequencer/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/main.go
  internal/pkg/event/event.go
  internal/pkg/runtime/runtime.go
  pkg/blockdevice/blockdevice.go
Labels: ok-to-test

#1892 feat: add reboot flag to reset API
  api/machine/machine.pb.go
  api/machine/machine.proto
  cmd/osctl/cmd/reset.go
  cmd/osctl/pkg/client/client.go
  go.mod
  go.sum
  internal/app/machined/main.go
Labels: ok-to-test

#1896 fix: stop firecracker launcher on signal
  internal/pkg/provision/providers/firecracker/launch.go
Labels: ok-to-test

#1897 feat: support sending machine info
  go.mod
  go.sum
  internal/pkg/runtime/platform/metal/metal.go
Labels: ok-to-test

#1895 fix: add reboot flag to reset command
  cmd/osctl/cmd/reset.go
  docs/osctl/osctl_reset.md
Labels: ok-to-test

#1893 refactor: use go-procfs
  cmd/installer/pkg/install.go
  cmd/installer/pkg/installer.go
  go.mod
  go.sum
  internal/app/networkd/pkg/address/dhcp.go
  internal/app/networkd/pkg/networkd/netconf.go
  internal/app/networkd/pkg/networkd/networkd.go
  internal/app/networkd/pkg/nic/nic.go
  internal/pkg/install/install.go
  internal/pkg/kernel/kernel.go
  internal/pkg/kernel/kernel_test.go
  internal/pkg/kernel/kspp/kspp.go
  internal/pkg/provision/providers/firecracker/node.go
  internal/pkg/runtime/initializer/interactive/interactive.go
  internal/pkg/runtime/platform.go
  internal/pkg/runtime/platform/aws/aws.go
  internal/pkg/runtime/platform/azure/azure.go
  internal/pkg/runtime/platform/container/container.go
  internal/pkg/runtime/platform/digitalocean/digitalocean.go
  internal/pkg/runtime/platform/gcp/gcp.go
  internal/pkg/runtime/platform/iso/iso.go
  internal/pkg/runtime/platform/metal/metal.go
  internal/pkg/runtime/platform/packet/packet.go
  internal/pkg/runtime/platform/platform.go
  internal/pkg/runtime/platform/vmware/vmware.go
Labels: ok-to-test

#1899 fix: default reboot flag to false
  cmd/osctl/cmd/reset.go
  docs/osctl/osctl_reset.md
Labels: ok-to-test

#1900 feat: support proxy in docker buildx
  Makefile
Labels: ok-to-test

#1902 fix: refresh proxy settings from environment in image resolver
  internal/pkg/containers/image/resolver.go
Labels: ok-to-test

#1903 test: implement new class of tests: provision tests (upgrades)
  .drone.yml
  Dockerfile
  Makefile
  hack/drone.jsonnet
  hack/test/provision-tests.sh
  internal/integration/base/flags.go
  internal/integration/integration_test.go
  internal/integration/provision/provision.go
  internal/integration/provision/upgrade.go
  pkg/constants/constants.go
Labels: area/upgrades, kind/test, ok-to-test

#1904 fix: unmount bind mounts for system (fixes upgrade stuck on disk busy)
  internal/app/machined/internal/phase/disk/verify_availability.go
  internal/app/machined/internal/phase/rootfs/unmount_system_disk_bind_mounts.go
  internal/app/machined/internal/sequencer/v1alpha1/v1alpha1_sequencer.go
Labels: ok-to-test

#1905 test: enable upgrade tests 0.4.x -> latest
  go.mod
  go.sum
  hack/test/provision-tests.sh
  internal/integration/provision/upgrade.go
  internal/pkg/provision/providers/docker/crashdump.go
  internal/pkg/provision/providers/firecracker/crashdump.go
  internal/pkg/provision/provision.go
Labels: ok-to-test

#1908 fix: ensure proxy is used when fetching additional manifests for bootkube
  internal/app/machined/pkg/system/services/bootkube.go
Labels: ok-to-test

#1910 chore: fix small misprint
  internal/pkg/loadbalancer/loadbalancer.go
Labels: ok-to-test

#1909 chore: update pkgs & tools for Go 1.14
  Dockerfile
  Makefile
  pkg/config/machine/machine.go
  pkg/constants/constants.go
Labels: ok-to-test

#1912 chore: prepare release v0.4.0-alpha.6
  CHANGELOG-0.4.md
Labels: ok-to-test

#1913 feat: generate kubeconfig on the fly on request
  .gitignore
  cmd/installer/cmd/image.go
  cmd/osctl/cmd/loadbalancer_launch.go
  internal/app/machined/internal/api/reg/reg.go
  internal/app/machined/pkg/system/services/bootkube.go
  internal/integration/provision/upgrade.go
  internal/pkg/kubeconfig/admin.go
  internal/pkg/kubeconfig/admin_test.go
  internal/pkg/kubeconfig/kubeconfig.go
  internal/pkg/provision/providers/firecracker/loadbalancer.go
  internal/pkg/provision/request.go
  pkg/config/cluster/cluster.go
  pkg/constants/constants.go
  pkg/crypto/x509/x509.go
Labels: ok-to-test

#1915 feat: add function for mounting a specific system disk partition
  internal/pkg/mount/manager/owned/owned.go
Labels: ok-to-test
