Repository siderolabs/talos, pull requests merged in 2020-03, with the labels that each got.

#1916 feat: make admin kubeconfig cert lifetime configurable
  docs/website/content/v0.3/en/configuration/v1alpha1.md
  internal/pkg/kubeconfig/admin.go
  internal/pkg/kubeconfig/admin_test.go
  pkg/config/cluster/cluster.go
  pkg/config/types/v1alpha1/v1alpha1_configurator.go
  pkg/config/types/v1alpha1/v1alpha1_types.go
Labels: ok-to-test

#1918 fix: ensure CA cert generation respects the hour flag
  cmd/osctl/cmd/gen.go
  cmd/osctl/cmd/root.go
Labels: ok-to-test

#1924 chore: add service state to postfunc
  internal/app/machined/pkg/system/mocks_test.go
  internal/app/machined/pkg/system/service.go
  internal/app/machined/pkg/system/service_runner.go
  internal/app/machined/pkg/system/services/apid.go
  internal/app/machined/pkg/system/services/bootkube.go
  internal/app/machined/pkg/system/services/containerd.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/app/machined/pkg/system/services/machined_api.go
  internal/app/machined/pkg/system/services/networkd.go
  internal/app/machined/pkg/system/services/ntpd.go
  internal/app/machined/pkg/system/services/osd.go
  internal/app/machined/pkg/system/services/routerd.go
  internal/app/machined/pkg/system/services/system-containerd.go
  internal/app/machined/pkg/system/services/trustd.go
  internal/app/machined/pkg/system/services/udevd.go
  internal/app/machined/pkg/system/services/udevd_trigger.go
Labels: ok-to-test

#1923 chore: improve handling of etcd responses in bootkube pre-func
  go.mod
  hack/test/e2e.sh
  internal/app/machined/pkg/system/services/bootkube.go
  internal/integration/integration_test.go
Labels: ok-to-test

#1921 chore: cleanup assets dir after bootkube is done
  internal/app/machined/internal/bootkube/bootkube.go
  internal/app/machined/pkg/system/services/bootkube.go
  pkg/constants/constants.go
Labels: ok-to-test

#1922 test: add 'reset' integration test for Reset() API
  internal/integration/api/reboot.go
  internal/integration/api/reset.go
  internal/integration/base/api.go
  internal/pkg/provision/providers/firecracker/launch.go
Labels: ok-to-test

#1929 fix: ensure hostname is never empty
  internal/app/networkd/pkg/address/dhcp.go
  internal/app/networkd/pkg/networkd/networkd_test.go
Labels: ok-to-test

#1930 feat: respect panic kernel flag
  internal/app/init/main.go
  pkg/constants/constants.go
Labels: ok-to-test

#1931 test: add test for empty hostname option
  internal/app/networkd/pkg/networkd/networkd_test.go
Labels: ok-to-test

#1936 feat: add debug logs to networkd health check
  internal/app/machined/pkg/system/services/networkd.go
Labels: ok-to-test

#1894 fix: skip links without a carrier
  internal/app/networkd/pkg/networkd/misc.go
  internal/app/networkd/pkg/networkd/networkd.go
Labels: ok-to-test

#1938 fix: add debug option to v1alpha1 config
  docs/website/content/v0.3/en/configuration/v1alpha1.md
  pkg/config/types/v1alpha1/v1alpha1_configurator.go
  pkg/config/types/v1alpha1/v1alpha1_types.go
Labels: ok-to-test

#1941 fix: ensure printing of panic message
  internal/app/init/main.go
Labels: ok-to-test

#1942 chore: update Firecracker Go SDK to the official release
  go.mod
  go.sum
Labels: ok-to-test

#1940 feat: update talos base packages
  Dockerfile
  pkg/constants/constants.go
Labels: ok-to-test

#1950 chore: fix formatting of imports
  Dockerfile
  cmd/osctl/cmd/gen.go
  internal/app/apid/pkg/provider/tls.go
  internal/app/machined/internal/phase/phase.go
  internal/app/machined/pkg/system/runner/goroutine/goroutine.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/trustd/main.go
  pkg/config/machine/machine.go
  pkg/config/types/v1alpha1/generate/generate.go
  pkg/kubernetes/kubernetes.go
  pkg/startup/rand.go
Labels: ok-to-test

#1937 fix: respect dns domain from machine config
  cmd/osctl/cmd/config.go
  docs/osctl/osctl_config_generate.md
  go.mod
  go.sum
  internal/app/machined/pkg/system/services/bootkube.go
  internal/app/machined/pkg/system/services/kubelet.go
  pkg/config/cluster/cluster.go
  pkg/config/types/v1alpha1/generate/generate.go
  pkg/config/types/v1alpha1/generate/options.go
  pkg/config/types/v1alpha1/v1alpha1_configurator.go
  pkg/constants/constants.go
Labels: ok-to-test

#1952 feat: upgrade Go to version 1.14.1
  Dockerfile
  Makefile
Labels: ok-to-test

#1954 docs: update the website generator's npm packages
  docs/website/package-lock.json
  docs/website/package.json
  docs/website/pages/docs/_.vue
  docs/website/pages/roadmap/index.vue
Labels: ok-to-test

#1953 feat: add support for `--with-debug` to osctl cluster create
  cmd/osctl/cmd/mgmt/cluster/create.go
  docs/osctl/osctl_cluster_create.md
  pkg/config/types/v1alpha1/generate/controlplane.go
  pkg/config/types/v1alpha1/generate/generate.go
  pkg/config/types/v1alpha1/generate/init.go
  pkg/config/types/v1alpha1/generate/join.go
  pkg/config/types/v1alpha1/generate/options.go
Labels: ok-to-test

#1939 fix: refactor the upgrade process
  api/machine/machine.pb.go
  api/machine/machine.proto
  cmd/installer/cmd/install.go
  cmd/installer/cmd/root.go
  cmd/installer/pkg/bootloader/syslinux/adv.go
  cmd/installer/pkg/bootloader/syslinux/adv_test.go
  cmd/installer/pkg/bootloader/syslinux/syslinux.go
  cmd/installer/pkg/bootloader/syslinux/testdata/ldlinux.sys
  cmd/installer/pkg/install.go
  cmd/installer/pkg/installer.go
  cmd/installer/pkg/manifest/manifest.go
  cmd/osctl/cmd/talos/upgrade.go
  cmd/osctl/pkg/client/client.go
  docs/osctl/osctl_upgrade.md
  internal/app/machined/internal/api/reg/reg.go
  internal/app/machined/internal/phase/platform/platform.go
  internal/app/machined/internal/phase/rootfs/check_install.go
  internal/app/machined/internal/phase/rootfs/syslinux.go
  internal/app/machined/internal/phase/services/start_services.go
  internal/app/machined/internal/phase/services/stop_services.go
  internal/app/machined/internal/phase/upgrade/leave_etcd.go
  internal/app/machined/internal/phase/upgrade/upgrade.go
  internal/app/machined/internal/sequencer/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/main.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/integration/provision/upgrade.go
  internal/pkg/etcd/etcd.go
  internal/pkg/install/install.go
  internal/pkg/install/options.go
  internal/pkg/metadata/metadata.go
  internal/pkg/provision/providers/firecracker/bootloader.go
  internal/pkg/provision/providers/firecracker/crashdump.go
  internal/pkg/runtime/initializer/interactive/interactive.go
  pkg/blockdevice/filesystem/vfat/filesystem.go
  pkg/constants/constants.go
Labels: needs-e2e, ok-to-test

#1957 chore: prepare release v0.4.0-alpha.7
  CHANGELOG-0.4.md
Labels: ok-to-test

#1959 feat: build talosctl for ARM64
  .drone.yml
  Dockerfile
  hack/drone.jsonnet
Labels: ok-to-test

#1960 chore: run npm audit fix
  docs/website/package-lock.json
Labels: ok-to-test

#1961 feat: build talosctl for ARM v7
  .drone.yml
  Dockerfile
  hack/drone.jsonnet
Labels: ok-to-test

#1962 fix: update rtnetlink checks for bit masks
  internal/app/networkd/pkg/reg/reg.go
Labels: ok-to-test

#1945 feat: Add support for VLAN devices on Talos
  internal/app/networkd/pkg/address/static.go
  internal/app/networkd/pkg/networkd/netconf.go
  internal/app/networkd/pkg/networkd/networkd.go
  internal/app/networkd/pkg/nic/netlink.go
  internal/app/networkd/pkg/nic/nic.go
  internal/app/networkd/pkg/nic/nic_test.go
  internal/app/networkd/pkg/nic/options.go
  internal/app/networkd/pkg/nic/vars.go
  internal/app/networkd/pkg/nic/vlan_options.go
  pkg/config/machine/machine.go
  pkg/config/types/v1alpha1/v1alpha1_validation.go
Labels: area/networking, ok-to-test

#1965 fix: update k8s to 1.17.3
  Makefile
  docs/talosctl/talosctl_cluster_create.md
  docs/talosctl/talosctl_gen_config.md
  docs/website/content/v0.3/en/configuration/v1alpha1.md
  docs/website/content/v0.4/en/configuration/v1alpha1.md
  go.mod
  go.sum
  hack/test/capi/cluster-aws.yaml
  hack/test/capi/cluster-gcp.yaml
  hack/test/libvirt/libvirt.sh
  pkg/config/types/v1alpha1/doc.go
  pkg/constants/constants.go
Labels: ok-to-test, status/needs-cherry-pick

#1966 fix: update k8s to 1.17.3
  docs/osctl/osctl_config_generate.md
  docs/website/content/v0.3/en/configuration/v1alpha1.md
  go.mod
  go.sum
  hack/test/integration/libvirt.sh
  hack/test/manifests/aws-cluster.yaml
  hack/test/manifests/gcp-cluster.yaml
  pkg/config/types/v1alpha1/doc.go
  pkg/constants/constants.go
  pkg/startup/rand.go
Labels: ok-to-test

#1964 docs: add bare-metal install example yaml
  docs/website/content/v0.4/en/configuration/v1alpha1.md
  pkg/config/types/v1alpha1/v1alpha1_types.go
Labels: ok-to-test

#1970 feat: add usb storage support
  Dockerfile
  internal/pkg/kernel/vmlinuz/vmlinuz.go
Labels: ok-to-test

#1973 docs: run make docs
  docs/osctl/osctl_cluster_create.md
Labels: ok-to-test

#1974 chore: update upgrade tests for new version, split into two tracks
  .drone.yml
  Makefile
  hack/drone.jsonnet
  hack/test/e2e.sh
  hack/test/provision-tests.sh
  internal/app/init/main.go
  internal/integration/base/base.go
  internal/integration/base/cli.go
  internal/integration/integration_test.go
  internal/integration/provision/upgrade.go
  internal/pkg/provision/access/crashdump.go
  internal/pkg/provision/adapters.go
Labels: ok-to-test

#1972 feat: update bootkube
  go.mod
  go.sum
Labels: ok-to-test

#1975 chore: prepare release v0.4.0-alpha.8
  CHANGELOG-0.4.md
Labels: ok-to-test

#1968 docs: Add example of a VLAN configured device.
  docs/website/content/v0.4/en/components/networkd.md
Labels: ok-to-test

#1976 feat: make `--wait` default option to `talosctl cluster create`
  cmd/talosctl/cmd/mgmt/cluster/create.go
  docs/talosctl/talosctl_cluster_create.md
  hack/test/e2e-docker.sh
  hack/test/e2e-firecracker.sh
Labels: ok-to-test

#1963 feat: upgrade kubernetes to 1.18
  Makefile
  docs/talosctl/talosctl_cluster_create.md
  docs/talosctl/talosctl_gen_config.md
  docs/website/content/v0.3/en/configuration/v1alpha1.md
  docs/website/content/v0.4/en/configuration/v1alpha1.md
  go.mod
  go.sum
  hack/test/capi/cluster-aws.yaml
  hack/test/capi/cluster-gcp.yaml
  hack/test/libvirt/libvirt.sh
  internal/integration/base/discovery_k8s.go
  internal/integration/k8s/version.go
  internal/pkg/provision/check/kubernetes.go
  pkg/config/types/v1alpha1/doc.go
  pkg/constants/constants.go
  pkg/kubernetes/kubernetes.go
Labels: ok-to-test

#1978 fix: don't use ARP table for networkd health check
  internal/app/networkd/pkg/reg/reg.go
Labels: ok-to-test

#1977 fix: make upgrades work with UEFI
  cmd/installer/pkg/bootloader/syslinux/constants.go
  cmd/installer/pkg/bootloader/syslinux/syslinux.go
  cmd/installer/pkg/installer.go
  internal/app/machined/internal/phase/rootfs/syslinux.go
  internal/app/machined/main.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/pkg/provision/providers/firecracker/bootloader.go
  pkg/constants/constants.go
Labels: ok-to-test

#1981 test: mark long tests as !short
  internal/integration/api/reboot.go
  internal/integration/api/reset.go
  internal/integration/cli/restart.go
Labels: ok-to-test

#1980 feat: move bootkube out as full service
  Dockerfile
  internal/app/bootkube/assets.go
  internal/app/bootkube/main.go
  internal/app/machined/pkg/system/services/bootkube.go
  internal/app/machined/pkg/system/services/kubelet.go
Labels: ok-to-test

#1982 fix: ignore EINVAL on unmounting when mount point isn't mounted
  internal/pkg/mount/mount.go
Labels: ok-to-test

#1983 refactor: include partition label when unmount fails
  internal/app/machined/internal/phase/rootfs/unmount_system_disks.go
Labels: ok-to-test

#1986 fix: wait for USB storage
  internal/app/machined/internal/phase/rootfs/validate_config.go
Labels: ok-to-test

#1979 feat: allow for exposing ports on docker clusters
  cmd/talosctl/cmd/mgmt/cluster/cluster.go
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/mgmt/cluster/destroy.go
  cmd/talosctl/cmd/mgmt/cluster/show.go
  docs/talosctl/talosctl_cluster_create.md
  internal/pkg/provision/options.go
  internal/pkg/provision/providers/docker/create.go
  internal/pkg/provision/providers/docker/node.go
Labels: ok-to-test

#1987 fix: move empty label check
  cmd/installer/pkg/bootloader/syslinux/syslinux.go
  internal/app/machined/main.go
Labels: ok-to-test

#1988 fix: delete tag on revert with empty label
  internal/app/machined/main.go
Labels: ok-to-test
