Repository siderolabs/talos, pull requests merged in 2020-05, with the labels that each got.

#2074 chore: use clusterctl and v1alpha3 providers for tests
  Makefile
  hack/test/capi/cluster-aws.yaml
  hack/test/capi/cluster-gcp.yaml
  hack/test/capi/components-capa.yaml
  hack/test/capi/components-capg.yaml
  hack/test/capi/components-provider.yaml
  hack/test/e2e-capi.sh
Labels: status/approved

#2077 docs: clean up docs page scripts in preparation for 0.5 docs
  docs/website/components/Content.vue
  docs/website/components/DocumentationDropdown.vue
  docs/website/components/Sidebar.vue
  docs/website/pages/docs/_.vue
  docs/website/store/sidebar.js
Labels: status/approved, status/lgtm

#2080 docs: add 0.5 pre-release docs, add linkable anchors, other fixes
  docs/website/assets/css/main.css
  docs/website/assets/css/prism-ghcolors.css
  docs/website/components/Content.vue
  docs/website/components/DocumentationDropdown.vue
  docs/website/components/Sidebar.vue
  docs/website/content/v0.5.en.json
  docs/website/content/v0.5/en/components/apid.md
  docs/website/content/v0.5/en/components/containerd.md
  docs/website/content/v0.5/en/components/kernel.md
  docs/website/content/v0.5/en/components/machined.md
  docs/website/content/v0.5/en/components/networkd.md
  docs/website/content/v0.5/en/components/osctl.md
  docs/website/content/v0.5/en/components/osd.md
  docs/website/content/v0.5/en/components/overview.md
  docs/website/content/v0.5/en/components/timed.md
  docs/website/content/v0.5/en/components/trustd.md
  docs/website/content/v0.5/en/components/udevd.md
  docs/website/content/v0.5/en/configuration/overview.md
  docs/website/content/v0.5/en/configuration/v1alpha1.md
  docs/website/content/v0.5/en/customization/containerd.md
  docs/website/content/v0.5/en/customization/kernel.md
  docs/website/content/v0.5/en/customization/overview.md
  docs/website/content/v0.5/en/customization/proxy.md
  docs/website/content/v0.5/en/guides/cloud/aws.md
  docs/website/content/v0.5/en/guides/cloud/azure.md
  docs/website/content/v0.5/en/guides/cloud/digitalocean.md
  docs/website/content/v0.5/en/guides/cloud/gcp.md
  docs/website/content/v0.5/en/guides/cloud/vmware.md
  docs/website/content/v0.5/en/guides/getting-started/help.md
  docs/website/content/v0.5/en/guides/getting-started/intro.md
  docs/website/content/v0.5/en/guides/local/docker.md
  docs/website/content/v0.5/en/guides/local/firecracker.md
  docs/website/content/v0.5/en/guides/metal/matchbox.md
  docs/website/content/v0.5/en/guides/metal/overview.md
  docs/website/content/v0.5/en/troubleshooting/overview.md
  docs/website/content/v0.5/en/troubleshooting/pki.md
  docs/website/docgen.js
  docs/website/nuxt.config.js
  docs/website/package-lock.json
  docs/website/package.json
Labels: status/approved, status/lgtm

#2067 feat: add recovery API
  .codecov.yml
  api/machine/machine.pb.go
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/recover.go
  docs/talosctl/talosctl.md
  docs/talosctl/talosctl_recover.md
  go.mod
  go.sum
  internal/app/bootkube/main.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/sequencer.go
  internal/app/machined/pkg/runtime/sequencer_test.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/bootkube.go
  internal/app/machined/pkg/system/system.go
  internal/integration/api/recover.go
  internal/integration/api/reset.go
  internal/integration/base/api.go
  internal/pkg/cluster/check/default.go
  internal/pkg/cluster/check/kubernetes.go
  pkg/client/client.go
Labels: status/approved, status/lgtm

#2081 docs: fix netlify deep linking for 0.5 docs with fallback routes
  docs/website/nuxt.config.js
Labels: status/approved, status/lgtm

#2082 docs: backport intro text to 0.3 and 0.4 docs
  docs/website/content/v0.3/en/guides/index.md
  docs/website/content/v0.4/en/guides/index.md
Labels: status/approved

#2083 test: stabilize tests by bumping timeouts
  .drone.yml
  hack/drone.jsonnet
  internal/integration/api/reset.go
Labels: status/approved, status/lgtm

#2084 chore: pin markdown linting libraries
  Dockerfile
Labels: status/approved, status/lgtm

#2085 test: add node name to error messages in RebootAllNodes
  internal/integration/api/reboot.go
Labels: status/approved

#2088 fix: write machined RPC logs to file
  internal/app/machined/main.go
Labels: status/approved, status/lgtm

#2078 feat: add bootstrap API
  api/machine/machine.pb.go
  api/machine/machine.proto
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/talos/bootstrap.go
  docs/talosctl/talosctl.md
  docs/talosctl/talosctl_bootstrap.md
  docs/talosctl/talosctl_cluster_create.md
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/service_events.go
  internal/app/machined/pkg/system/service_runner.go
  internal/app/machined/pkg/system/services/bootkube.go
  internal/app/machined/pkg/system/services/etcd.go
  pkg/client/client.go
Labels: status/approved, status/lgtm

#2086 fix: update kernel package
  Dockerfile
Labels: status/approved, status/lgtm

#2098 docs: update copyright date
  docs/website/components/Footer.vue
Labels: status/approved, status/lgtm

#2092 feat: enable rpfilter
  Dockerfile
Labels: status/approved, status/lgtm

#2094 fix: refactor client creation API
  cmd/talosctl/cmd/talos/root.go
  internal/integration/base/api.go
  internal/pkg/cluster/config.go
  pkg/client/client.go
  pkg/client/options.go
  pkg/client/resolver.go
Labels: status/approved, status/lgtm

#2087 chore: serialize firecracker e2e tests
  .drone.yml
  hack/drone.jsonnet
Labels: status/approved, status/lgtm

#2103 feat: add support for file scheme
  cmd/installer/cmd/root.go
  cmd/installer/pkg/install/install.go
  pkg/download/download.go
Labels: status/approved, status/lgtm

#2090 feat: add events API
  api/common/common.pb.go
  api/common/common.proto
  api/machine/machine.pb.go
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/events.go
  docs/talosctl/talosctl.md
  docs/talosctl/talosctl_events.md
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/main.go
  internal/app/machined/pkg/runtime/events.go
  internal/app/machined/pkg/runtime/runtime.go
  internal/app/machined/pkg/runtime/sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events_test.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  pkg/client/client.go
Labels: status/approved, status/lgtm

#2102 docs: add a sitemap and Netlify redirects
  docs/website/.gitignore
  docs/website/docgen.config.js
  docs/website/docgen.js
  docs/website/nuxt.config.js
  docs/website/package-lock.json
  docs/website/package.json
Labels: status/approved

#2104 release(v0.5.0-beta.0): prepare release
  CHANGELOG.md
Labels: status/approved, status/lgtm

#2107 chore: fix nits in the events code
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events_test.go
Labels: status/approved, status/lgtm, status/needs-cherry-pick

#2105 fix: register event service with router
  api/machine/machine.pb.go
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/events.go
  internal/app/apid/main.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  pkg/client/client.go
Labels: status/approved, status/lgtm, status/needs-cherry-pick

#2111 fix: update Events API response type to match proxying conventions
  api/machine/machine.pb.go
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/events.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
Labels: status/approved, status/lgtm

#2112 fix: respect nameservers when using docker cluster
  cmd/talosctl/cmd/mgmt/cluster/create.go
  docs/talosctl/talosctl_cluster_create.md
  internal/pkg/provision/providers/docker/docker.go
Labels: status/approved, status/lgtm

#2106 fix: run machined API as a service
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/main.go
  internal/app/machined/pkg/system/runner/goroutine/goroutine.go
  internal/app/machined/pkg/system/runner/goroutine/goroutine_test.go
  internal/app/machined/pkg/system/services/machined.go
Labels: status/approved, status/needs-cherry-pick

#2114 release(v0.6.0-alpha.0): prepare release
  .conform.yaml
  CHANGELOG.md
Labels: status/approved

#2116 docs: overview of talos components
  docs/website/content/v0.5/en/components/overview.md
Labels: status/approved, status/lgtm

#2122 fix: wrap etcd address URLs with formatting
  internal/app/machined/pkg/system/services/etcd.go
  internal/pkg/etcd/etcd.go
  pkg/net/net.go
Labels: status/approved, status/lgtm, status/needs-cherry-pick

#2125 feat: upgrade Linux to v5.6.13
  Dockerfile
  pkg/constants/constants.go
Labels: status/approved, status/lgtm

#2127 fix: allow all seccomp profile names
  go.mod
  go.sum
Labels: status/approved

#2126 test: update Talos versions for upgrade tests
  Makefile
  internal/integration/provision/upgrade.go
Labels: status/approved, status/lgtm

#2132 fix: bump service wait to ten minutes
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/approved, status/lgtm

#2113 chore: replace underlying event implementation with single slice
  go.mod
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/main.go
  internal/app/machined/pkg/runtime/events.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events_test.go
Labels: status/approved, status/lgtm

#2136 test: improve reboot/reset test resiliency against request timeouts
  internal/integration/base/api.go
Labels: status/approved, status/lgtm

#2137 chore: upgrade Go to 1.14.3 and use toolchain for race detector
  .drone.yml
  Dockerfile
  Makefile
  hack/drone.jsonnet
  hack/golang/test.sh
Labels: status/approved, status/lgtm

#2140 Added image and overview
  docs/diagrams/Talos_metal-flow.xml
  docs/website/content/v0.4/en/guides/metal/overview.md
  docs/website/content/v0.5/en/guides/metal/overview.md
  docs/website/static/images/metal-overview.png
Labels: status/approved, status/lgtm

#2134 feat: implement simplified client method to consume events
  cmd/talosctl/cmd/talos/containers.go
  cmd/talosctl/cmd/talos/dmesg.go
  cmd/talosctl/cmd/talos/events.go
  cmd/talosctl/cmd/talos/interfaces.go
  cmd/talosctl/cmd/talos/list.go
  cmd/talosctl/cmd/talos/logs.go
  cmd/talosctl/cmd/talos/memory.go
  cmd/talosctl/cmd/talos/mounts.go
  cmd/talosctl/cmd/talos/processes.go
  cmd/talosctl/cmd/talos/routes.go
  cmd/talosctl/cmd/talos/service.go
  cmd/talosctl/cmd/talos/stats.go
  cmd/talosctl/cmd/talos/time.go
  cmd/talosctl/cmd/talos/upgrade.go
  cmd/talosctl/cmd/talos/version.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  pkg/client/client.go
  pkg/client/peer.go
Labels: status/approved

#2143 chore: fix markdown lint
  README.md
Labels: status/approved

#2144 fix: prevent panic on nil pointer in ServiceInfo method
  pkg/client/client.go
Labels: status/approved, status/lgtm

#2142 feat: add LVM2
  Dockerfile
Labels: status/approved, status/lgtm

#2147 release(v0.5.0): prepare release
  CHANGELOG.md
Labels: status/approved, status/lgtm

#2150 docs: make v0.5 docs the default
  docs/website/components/DocumentationDropdown.vue
  docs/website/components/Header.vue
  docs/website/pages/index.vue
Labels: status/approved

#2152 release(v0.6.0-alpha.1): prepare release
  CHANGELOG.md
Labels: status/approved, status/lgtm

#2149 docs: add talosctl docs document
  docs/website/content/v0.5.en.json
  docs/website/content/v0.5/en/guides/getting-started/talosctl.md
Labels: status/approved, status/lgtm

#2153 chore: update provision test versions
  Makefile
  internal/integration/provision/upgrade.go
Labels: status/approved, status/lgtm
