Repository siderolabs/talos, pull requests merged in 2020-04, with the labels that each got.

#1992 refactor: move Talos client package to `pkg/`
  cmd/talosctl/cmd/mgmt/cluster/cluster.go
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/root.go
  cmd/talosctl/cmd/talos/config.go
  cmd/talosctl/cmd/talos/containers.go
  cmd/talosctl/cmd/talos/copy.go
  cmd/talosctl/cmd/talos/dmesg.go
  cmd/talosctl/cmd/talos/interfaces.go
  cmd/talosctl/cmd/talos/kubeconfig.go
  cmd/talosctl/cmd/talos/list.go
  cmd/talosctl/cmd/talos/logs.go
  cmd/talosctl/cmd/talos/memory.go
  cmd/talosctl/cmd/talos/mounts.go
  cmd/talosctl/cmd/talos/processes.go
  cmd/talosctl/cmd/talos/read.go
  cmd/talosctl/cmd/talos/reboot.go
  cmd/talosctl/cmd/talos/reset.go
  cmd/talosctl/cmd/talos/restart.go
  cmd/talosctl/cmd/talos/root.go
  cmd/talosctl/cmd/talos/routes.go
  cmd/talosctl/cmd/talos/service.go
  cmd/talosctl/cmd/talos/shutdown.go
  cmd/talosctl/cmd/talos/stats.go
  cmd/talosctl/cmd/talos/time.go
  cmd/talosctl/cmd/talos/upgrade.go
  cmd/talosctl/cmd/talos/version.go
  internal/integration/api/dmesg.go
  internal/integration/api/logs.go
  internal/integration/api/reboot.go
  internal/integration/api/reset.go
  internal/integration/api/version.go
  internal/integration/base/api.go
  internal/integration/base/discovery_k8s.go
  internal/integration/base/discovery_nok8s.go
  internal/integration/integration_test.go
  internal/integration/provision/upgrade.go
  internal/pkg/provision/access/adapter.go
  internal/pkg/provision/access/crashdump.go
  internal/pkg/provision/adapters.go
  internal/pkg/provision/check/apid.go
  internal/pkg/provision/check/service.go
  internal/pkg/provision/options.go
  internal/pkg/runtime/configurator.go
  pkg/client/client.go
  pkg/client/config/config.go
  pkg/client/config/config_test.go
  pkg/client/config/path.go
  pkg/client/context.go
  pkg/client/reply.go
  pkg/client/reply_test.go
  pkg/config/config.go
  pkg/config/types/v1alpha1/generate/talosconfig.go
  pkg/config/types/v1alpha1/v1alpha1_configurator_bundle.go
Labels: ok-to-test

#1993 feat: introduce ability to specify extra hosts in /etc/hosts
  docs/website/content/v0.4/en/configuration/v1alpha1.md
  internal/app/networkd/pkg/networkd/misc.go
  internal/app/networkd/pkg/networkd/networkd.go
  pkg/config/machine/machine.go
  pkg/config/types/v1alpha1/v1alpha1_configurator.go
  pkg/config/types/v1alpha1/v1alpha1_types.go
Labels: ok-to-test

#1995 feat: add BNX drivers
  Dockerfile
Labels: ok-to-test

#1996 fix: make sure Close() is called on every path
  cmd/installer/pkg/installer.go
  internal/app/machined/internal/api/reg/reg.go
  internal/app/machined/internal/phase/security/ima.go
  internal/app/machined/pkg/system/runner/containerd/import.go
  internal/pkg/containers/container.go
Labels: ok-to-test, status/needs-cherry-pick

#1997 chore: update timeout values for e2e tests
  internal/integration/api/reboot.go
Labels: needs-e2e, ok-to-test, status/needs-cherry-pick

#1998 chore: update sonobuoy to v0.18.0
  Makefile
Labels: needs-e2e, ok-to-test

#2001 fix: mount TLS certs into bootkube container
  internal/app/machined/pkg/system/services/bootkube.go
Labels: ok-to-test, status/needs-cherry-pick

#2000 fix: wait for `system-containerd` to become healthy before proceeding
  internal/app/machined/internal/phase/services/start_system_containerd.go
Labels: ok-to-test, status/needs-cherry-pick

#2003 fix: add bnx2 and bnx2x firmware
  Dockerfile
Labels: ok-to-test, status/needs-cherry-pick

#2004 feat: upgrade Linux to v5.5.15
  Dockerfile
  pkg/constants/constants.go
Labels: ok-to-test, status/needs-cherry-pick

#2007 test: serialize `docs` step execution
  .drone.yml
  Makefile
  hack/drone.jsonnet
Labels: ok-to-test

#2006 test: update versions used for upgrade tests
  Makefile
  internal/integration/provision/upgrade.go
Labels: ok-to-test, status/needs-cherry-pick

#2009 chore: prepare release v0.5.0-alpha.0
  CHANGELOG-0.5.md
Labels: ok-to-test

#2011 fix: add hpsa drivers
  Dockerfile
Labels: ok-to-test, status/needs-cherry-pick

#2013 refactor: don't log installer verification
  internal/app/machined/internal/api/reg/reg.go
Labels: ok-to-test, status/needs-cherry-pick

#2014 feat: upgrade Go to 1.14.2
  Dockerfile
  Makefile
Labels: ok-to-test, status/needs-cherry-pick

#1999 docs: improve the docs sidebar styling
  docs/website/components/Content.vue
  docs/website/components/Sidebar.vue
  docs/website/content/v0.3.en.json
  docs/website/content/v0.3/en/components/overview.md
  docs/website/content/v0.3/en/configuration/overview.md
  docs/website/content/v0.3/en/customization/overview.md
  docs/website/content/v0.3/en/guides/cloud/overview.md
  docs/website/content/v0.3/en/guides/metal/overview.md
  docs/website/content/v0.3/en/troubleshooting/overview.md
  docs/website/content/v0.4.en.json
  docs/website/content/v0.4/en/components/overview.md
  docs/website/content/v0.4/en/configuration/overview.md
  docs/website/content/v0.4/en/customization/overview.md
  docs/website/content/v0.4/en/guides/cloud/index.md
  docs/website/content/v0.4/en/guides/metal/overview.md
  docs/website/content/v0.4/en/troubleshooting/overview.md
  docs/website/pages/docs/_.vue
Labels: [zube]: Accepted, ok-to-test

#2012 docs: add firecracker documentation
  docs/website/content/v0.4.en.json
  docs/website/content/v0.4/en/guides/getting-started/docker.md
  docs/website/content/v0.4/en/guides/getting-started/firecracker.md
Labels: ok-to-test

#2017 fix: resolve race condition in createNodes
  internal/pkg/provision/providers/docker/node.go
  internal/pkg/provision/providers/firecracker/node.go
Labels: ok-to-test, status/needs-cherry-pick

#2019 chore: address random CI nits
  .codecov.yml
  .conform.yaml
  .drone.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ok-to-test.yml
  .github/workflows/promote-e2e.yml
  Dockerfile
  Makefile
  hack/drone.jsonnet
  internal/app/machined/main.go
  internal/pkg/containers/image/resolver_test.go
  internal/pkg/kmsg/writer.go
  pkg/version/version.go
Labels: status/approved, status/lgtm, status/needs-cherry-pick

#2021 refactor: rename system-containerd and containerd services
  internal/app/machined/internal/phase/services/start_containerd.go
  internal/app/machined/internal/phase/services/start_services.go
  internal/app/machined/internal/sequencer/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/system/services/apid.go
  internal/app/machined/pkg/system/services/cri.go
  internal/app/machined/pkg/system/services/cri_test.go
  internal/app/machined/pkg/system/services/networkd.go
  internal/app/machined/pkg/system/services/ntpd.go
  internal/app/machined/pkg/system/services/osd.go
  internal/app/machined/pkg/system/services/routerd.go
  internal/app/machined/pkg/system/services/system-containerd.go
  internal/app/machined/pkg/system/services/system-containerd_test.go
Labels: status/approved, status/lgtm

#2020 refactor: rename ntpd to timed
  .conform.yaml
  Dockerfile
  docs/website/content/v0.4.en.json
  docs/website/content/v0.4/en/components/machined.md
  docs/website/content/v0.4/en/components/ntpd.md
  docs/website/content/v0.4/en/components/timed.md
  internal/app/machined/internal/phase/services/start_services.go
  internal/app/machined/pkg/system/services/timed.go
  internal/app/machined/pkg/system/services/timed_test.go
  internal/app/timed/main.go
  internal/app/timed/pkg/ntp/ntp.go
  internal/app/timed/pkg/ntp/ntp_test.go
  internal/app/timed/pkg/ntp/options.go
  internal/app/timed/pkg/reg/reg.go
  internal/app/timed/pkg/reg/reg_test.go
  pkg/constants/constants.go
Labels: status/approved, status/lgtm

#2022 chore: update pkgs tag to v0.2.0
  Dockerfile
Labels: status/approved, status/lgtm

#2026 chore: remove random.trust_cpu references
  cmd/installer/cmd/iso.go
  docs/website/content/v0.4/en/guides/metal/matchbox.md
  docs/website/content/v0.4/en/guides/metal/overview.md
  hack/test/libvirt/matchbox/profiles/controlplane.json
  hack/test/libvirt/matchbox/profiles/default.json
  hack/test/libvirt/matchbox/profiles/init.json
  hack/test/qemu/qemu.sh
Labels: status/approved, status/lgtm

#2010 feat: add extra headers to fetch of extraManifests
  docs/website/content/v0.4/en/configuration/v1alpha1.md
  internal/app/bootkube/assets.go
  pkg/config/cluster/cluster.go
  pkg/config/types/v1alpha1/v1alpha1_configurator.go
  pkg/config/types/v1alpha1/v1alpha1_types.go
Labels: status/approved, status/lgtm

#2024 feat: make machine config persist by default
  internal/pkg/provision/providers/docker/docker.go
  pkg/config/types/v1alpha1/generate/controlplane.go
  pkg/config/types/v1alpha1/generate/generate.go
  pkg/config/types/v1alpha1/generate/init.go
  pkg/config/types/v1alpha1/generate/join.go
  pkg/config/types/v1alpha1/generate/options.go
Labels: status/approved, status/lgtm

#2031 feat: disable kubelet ro port
  internal/app/machined/pkg/system/services/kubelet.go
Labels: status/approved, status/lgtm

#2033 feat: add extra headers to fetch of extraManifests
  docs/website/content/v0.4/en/configuration/v1alpha1.md
  internal/app/bootkube/assets.go
  pkg/config/cluster/cluster.go
  pkg/config/types/v1alpha1/v1alpha1_configurator.go
  pkg/config/types/v1alpha1/v1alpha1_types.go
Labels: status/approved, status/lgtm

#2034 feat: disable kubelet ro port
  internal/app/machined/pkg/system/services/kubelet.go
Labels: status/approved, status/lgtm

#2036 fix: ensure ordering of interfaces when deciding hostname
  internal/app/networkd/pkg/networkd/networkd.go
Labels: status/approved, status/lgtm

#2029 fix: set ephemeral partition to max size
  .drone.yml
  cmd/installer/cmd/image.go
  cmd/installer/pkg/installer.go
  cmd/installer/pkg/manifest/manifest.go
  hack/drone.jsonnet
  internal/pkg/mount/manager/manager.go
  pkg/blockdevice/table/gpt/gpt.go
  pkg/blockdevice/table/gpt/partition/options.go
Labels: status/approved, status/lgtm, status/needs-cherry-pick

#2027 chore: use a single CHANGELOG
  CHANGELOG-0.1.md
  CHANGELOG-0.2.md
  CHANGELOG-0.3.md
  CHANGELOG-0.4.md
  CHANGELOG-0.5.md
  CHANGELOG.md
  hack/chglog/CHANGELOG.tpl.md
  hack/chglog/config.yml
  hack/release.sh
Labels: status/approved

#2047 docs: default to v0.4
  README.md
  docs/website/components/DocumentationDropdown.vue
  docs/website/components/Header.vue
  docs/website/pages/index.vue
Labels: status/approved, status/lgtm

#2045 refactor: use upstream bootkube
  go.mod
  go.sum
  internal/app/bootkube/assets.go
  pkg/config/types/v1alpha1/v1alpha1_configurator.go
Labels: status/approved, status/lgtm

#2035 docs: improve CLI menu and metal docs
  cmd/talosctl/cmd/mgmt/config.go
  cmd/talosctl/cmd/talos/logs.go
  docs/talosctl/talosctl.md
  docs/talosctl/talosctl_gen_config.md
  docs/talosctl/talosctl_logs.md
  docs/website/content/v0.3/en/guides/cloud/aws.md
  docs/website/content/v0.3/en/guides/cloud/digitalocean.md
  docs/website/content/v0.3/en/guides/cloud/vmware.md
  docs/website/content/v0.3/en/guides/metal/matchbox.md
  docs/website/content/v0.4/en/guides/cloud/aws.md
  docs/website/content/v0.4/en/guides/cloud/digitalocean.md
  docs/website/content/v0.4/en/guides/cloud/vmware.md
  docs/website/content/v0.4/en/guides/metal/matchbox.md
Labels: status/approved

#2044 chore: add bug report issue template
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status/approved

#2051 fix: prevent formatting the ephemeral partition twice
  cmd/installer/pkg/installer.go
Labels: status/approved, status/lgtm, status/needs-cherry-pick

#2052 release(v0.5.0-alpha.1): prepare release
  .conform.yaml
  CHANGELOG.md
  hack/release.sh
Labels: status/approved, status/lgtm

#2053 fix: pass dev path to mkfs
  cmd/installer/pkg/installer.go
  cmd/installer/pkg/manifest/manifest.go
  go.sum
  internal/pkg/install/install.go
  pkg/blockdevice/filesystem/xfs/xfs.go
Labels: status/approved, status/lgtm, status/needs-cherry-pick

#2057 fix: ensure disk is not busy
  internal/app/machined/internal/phase/disk/verify_availability.go
  internal/app/machined/internal/sequencer/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/system/services/trustd.go
Labels: status/approved, status/lgtm, status/needs-cherry-pick

#2058 fix: ensure disk is not busy
  internal/app/machined/internal/phase/disk/verify_availability.go
  internal/app/machined/internal/sequencer/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/system/services/trustd.go
Labels: status/approved, status/lgtm

#2059 chore: prepare release v0.4.1
  CHANGELOG-0.4.md
Labels: status/approved, status/lgtm

#2063 chore: fix markdown linting issues
  .dockerignore
  .markdownlint.json
  CONTRIBUTING.md
  Dockerfile
  README.md
  docs/community/project-layout.md
  internal/app/networkd/README.md
  internal/pkg/provision/providers/firecracker/README.md
Labels: status/approved

#2064 docs: add install and troubleshooting section in firecracker getting started
  docs/website/content/v0.4/en/guides/getting-started/firecracker.md
Labels: status/approved, status/lgtm

#2018 feat: add commands talosctl health/crashdump
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/talos/crashdump.go
  cmd/talosctl/cmd/talos/health.go
  docs/talosctl/talosctl.md
  docs/talosctl/talosctl_crashdump.md
  docs/talosctl/talosctl_health.md
  internal/integration/base/api.go
  internal/integration/cli/crashdump.go
  internal/integration/cli/health.go
  internal/integration/integration_test.go
  internal/integration/provision/upgrade.go
  internal/pkg/cluster/check/apid.go
  internal/pkg/cluster/check/check.go
  internal/pkg/cluster/check/check_test.go
  internal/pkg/cluster/check/default.go
  internal/pkg/cluster/check/kubernetes.go
  internal/pkg/cluster/check/options.go
  internal/pkg/cluster/check/reporter.go
  internal/pkg/cluster/check/service.go
  internal/pkg/cluster/cluster.go
  internal/pkg/cluster/cluster_test.go
  internal/pkg/cluster/config.go
  internal/pkg/cluster/crashdump.go
  internal/pkg/cluster/kubernetes.go
  internal/pkg/provision/access/adapter.go
  internal/pkg/provision/adapters.go
Labels: status/approved

#2066 release(v0.5.0-alpha.2): prepare release
  CHANGELOG.md
  hack/release.sh
Labels: status/approved, status/lgtm

#2056 feat: allow dual-stack support with bootkube wrapper
  docs/website/content/v0.4/en/configuration/v1alpha1.md
  go.mod
  go.sum
  internal/app/bootkube/assets.go
  internal/app/machined/pkg/runtime/configurator.go
  pkg/config/types/v1alpha1/generate/init.go
  pkg/config/types/v1alpha1/v1alpha1_configurator.go
  pkg/config/types/v1alpha1/v1alpha1_types.go
Labels: status/approved, status/lgtm

#2072 refactor: remove warning about missing boot partition
  cmd/installer/pkg/install/install.go
Labels: status/approved, status/lgtm

#2069 chore: fix prototool lint
  Dockerfile
Labels: status/approved, status/lgtm

#2075 fix IPv6 static default gateway not set if gateway is a LL unicast address
  internal/app/networkd/pkg/nic/nic.go
Labels: status/approved, status/lgtm
