Repository siderolabs/talos, pull requests merged in 2020-01, with the labels that each got.

#1709 fix: set the correct kernel args for VMware
  cmd/installer/cmd/image.go
  cmd/installer/cmd/root.go
  internal/pkg/runtime/platform/vmware/vmware.go
Labels: status/needs-cherry-pick

#1711 chore: use the correct condition for latest and edge pushes
  .drone.yml
  hack/drone.jsonnet
Labels: status/needs-cherry-pick

#1712 chore: push latest tag on tag events
  .drone.yml
  Makefile
  hack/drone.jsonnet
Labels: status/needs-cherry-pick

#1713 chore: fix push events
  .drone.yml
  hack/drone.jsonnet
Labels: status/needs-cherry-pick

#1715 chore: fix release dependency
  .drone.yml
  hack/drone.jsonnet
Labels: status/needs-cherry-pick

#1723 chore: disable iso artifact creation
  .drone.yml
  hack/drone.jsonnet
Labels: status/needs-cherry-pick

#1727 feat: upgrade linux to v5.4.8
  Dockerfile
  pkg/constants/constants.go
Labels: status/needs-cherry-pick

#1726 fix: make the CNI URL error better
  pkg/config/types/v1alpha1/v1alpha1_validation.go
Labels: status/needs-cherry-pick

#1728 feat: Upgrade bootkube
  go.mod
  go.sum
  internal/pkg/provision/check/default.go
Labels: status/needs-cherry-pick

#1735 fix: raise default NOFILE limit
  internal/app/machined/internal/phase/limits/limits.go
  internal/app/machined/internal/phase/limits/limits_test.go
  internal/app/machined/internal/sequencer/v1alpha1/v1alpha1_sequencer.go
Labels: status/needs-cherry-pick

#1746 chore: publish boot.tar.gz
  .drone.yml
  Makefile
  hack/drone.jsonnet
Labels: status/needs-cherry-pick

#1747 fix: check for installer image before proceeding with upgrade
  internal/app/machined/internal/api/reg/reg.go
  internal/app/machined/internal/phase/upgrade/upgrade.go
  internal/pkg/install/install.go
  internal/pkg/install/options.go
Labels: status/needs-cherry-pick

#1749 fix: set kube-dns labels
  go.mod
  go.sum
  internal/pkg/provision/check/default.go
Labels: status/needs-cherry-pick

#1733 chore: fix E2E script
  hack/test/basic-integration.sh
  hack/test/e2e-runner.sh
Labels: status/needs-cherry-pick

#1750 fix: shutdown on button/power ACPI event
  internal/app/machined/internal/phase/acpi/acpi.go
  internal/app/machined/internal/phase/acpi/acpi_test.go
Labels: status/needs-cherry-pick

#1756 chore: log ignored ACPI events
  internal/app/machined/internal/phase/acpi/acpi.go
Labels: status/needs-cherry-pick

#1760 feat: upgrade Linux to v5.4.10
  Dockerfile
  pkg/constants/constants.go
Labels: status/needs-cherry-pick

#1764 feat: upgrade Linux to v5.4.11
  Dockerfile
Labels: status/needs-cherry-pick

#1765 fix: update kernel version constant
  pkg/constants/constants.go
Labels: status/needs-cherry-pick

#1773 chore: bump tools/pkgs for Go 1.13.6
  Dockerfile
  Makefile
Labels: status/needs-cherry-pick

#1772 fix: refuse to upgrade if single master
  internal/pkg/etcd/etcd.go
Labels: status/needs-cherry-pick

#1775 fix: add Close func in remote generator
  pkg/grpc/gen/remote.go
Labels: status/needs-cherry-pick

#1777 fix: Update bootkube to include node ready check
  go.mod
  go.sum
Labels: area/bootkube, status/needs-cherry-pick

#1780 fix(networkd): Set hostname properly for dhcp when no hostname option is returned
  internal/app/networkd/pkg/address/dhcp.go
  internal/app/networkd/pkg/networkd/networkd_test.go
Labels: status/needs-cherry-pick

#1782 chore: validate installer image before upgrade
  internal/app/machined/internal/api/reg/reg.go
Labels: status/needs-cherry-pick

#1755 fix(networkd): Fix incorrect resolver settings
  internal/app/machined/internal/phase/network/network.go
  internal/app/machined/pkg/system/services/networkd.go
  internal/app/networkd/pkg/networkd/networkd.go
Labels: area/networking, kind/bug, status/needs-cherry-pick

#1761 chore: run sonobuoy in quick mode
  .drone.yml
  hack/drone.jsonnet
  hack/test/basic-integration.sh
  hack/test/capi.sh
  hack/test/conformance.sh
  hack/test/e2e-integration.sh
  hack/test/e2e-runner.sh
Labels: status/needs-cherry-pick

#1786 feat: upgrade kubernetes version to 1.17.1
  docs/osctl/osctl_cluster_create.md
  docs/osctl/osctl_config_generate.md
  docs/website/content/v0.3/en/configuration/v1alpha1.md
  hack/test/e2e-runner.sh
  hack/test/integration/libvirt.sh
  hack/test/manifests/aws-cluster.yaml
  hack/test/manifests/gcp-cluster.yaml
  pkg/config/types/v1alpha1/doc.go
  pkg/constants/constants.go
Labels: status/needs-cherry-pick

#1787 fix: update newtorkd permissions
  internal/app/machined/pkg/system/services/networkd.go
Labels: status/needs-cherry-pick

#1790 fix: stop race condition between kubelet and networkd
  internal/app/machined/internal/api/reg/reg.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/pkg/containers/image/image.go
  internal/pkg/install/install.go
Labels: status/needs-cherry-pick

#1791 chore: use v0.1.0 tools and pkgs
  Dockerfile
  Makefile
Labels: status/needs-cherry-pick

#1788 fix: block when handling bus event
  internal/app/machined/main.go
  internal/pkg/event/event.go
  internal/pkg/event/event_test.go
Labels: status/needs-cherry-pick

#1800 fix: install sequence stuck on event bus
  internal/app/machined/internal/phase/phase.go
  internal/app/machined/main.go
  internal/pkg/runtime/errors.go
  internal/pkg/runtime/initializer/metal/metal.go
Labels: status/needs-cherry-pick

#1796 fix: leave etcd after draining node
  internal/app/machined/internal/sequencer/v1alpha1/v1alpha1_sequencer.go
Labels: status/needs-cherry-pick

#1804 docs: remove pre-release from v0.3 docs
  docs/website/components/DocumentationDropdown.vue
Labels: status/needs-cherry-pick

#1809 docs: update metal section
  docs/website/content/v0.3/en/guides/metal/index.md
Labels: status/needs-cherry-pick

#1812 fix: re-enable control plane flags
  go.mod
  go.sum
  internal/app/machined/pkg/system/services/bootkube.go
  pkg/config/cluster/cluster.go
  pkg/config/types/v1alpha1/generate/init.go
  pkg/config/types/v1alpha1/v1alpha1_configurator.go
  pkg/config/types/v1alpha1/v1alpha1_types.go
Labels: status/needs-cherry-pick

#1813 docs: fix machined component
  docs/website/content/v0.3.en.json
  docs/website/content/v0.3/en/components/init.md
  docs/website/content/v0.3/en/components/machined.md
Labels: status/needs-cherry-pick

#1811 fix: retry system disk busy check
  internal/app/machined/internal/phase/disk/verify_availability.go
  internal/app/machined/internal/phase/rootfs/unmount_system_disks.go
Labels: status/needs-cherry-pick

#1826 fix: parse correctly kernel command line missing DNS config
  internal/app/networkd/pkg/networkd/netconf.go
  internal/app/networkd/pkg/networkd/netconf_test.go
Labels: status/needs-cherry-pick

#1831 fix: implement kubelet extra mounts
  docs/website/content/v0.3/en/configuration/v1alpha1.md
  pkg/config/types/v1alpha1/v1alpha1_configurator.go
  pkg/config/types/v1alpha1/v1alpha1_types.go
Labels: status/needs-cherry-pick

#1832 docs: remove invalid field from docs
  docs/website/content/v0.3/en/configuration/v1alpha1.md
  pkg/config/types/v1alpha1/v1alpha1_types.go
Labels: status/needs-cherry-pick

#1833 fix: follow symlinks
  pkg/archiver/walker.go
  pkg/archiver/walker_test.go
Labels: status/needs-cherry-pick

#1845 chore: update bootkube fork
  go.mod
  go.sum
Labels: status/needs-cherry-pick

#1847 chore: update bootkube
  go.mod
  go.sum
Labels: status/needs-cherry-pick
