Repository siderolabs/talos, pull requests merged in 2020-08, with the labels that each got.

#2396 fix: update AMI link to latest
  docs/website/content/v0.6/en/guides/cloud/aws.md
Labels: status/approved, status/lgtm

#2397 fix: update qemu launcher on arm64 to boot Talos properly
  internal/pkg/provision/providers/qemu/arch.go
  internal/pkg/provision/providers/qemu/create.go
  internal/pkg/provision/providers/qemu/launch.go
  internal/pkg/provision/providers/qemu/node.go
  internal/pkg/provision/providers/qemu/pflash.go
  internal/pkg/provision/providers/qemu/qemu.go
  internal/pkg/provision/providers/vm/state.go
Labels: status/approved, status/lgtm

#2402 feat: add persist flag to gen config
  cmd/talosctl/cmd/mgmt/config.go
  docs/talosctl/talosctl_gen_config.md
Labels: status/approved, status/lgtm

#2392 refactor: remove structs from config provider
  docs/website/content/v0.6/en/configuration/v1alpha1.md
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/networkd/pkg/address/static.go
  internal/app/networkd/pkg/networkd/netconf.go
  internal/app/networkd/pkg/networkd/netconf_test.go
  internal/app/networkd/pkg/networkd/networkd_test.go
  internal/pkg/containers/cri/containerd/config.go
  internal/pkg/containers/cri/containerd/config_test.go
  internal/pkg/containers/cri/containerd/containerd.go
  internal/pkg/containers/image/resolver.go
  internal/pkg/containers/image/resolver_test.go
  internal/pkg/provision/providers/firecracker/firecracker.go
  pkg/config/provider.go
  pkg/config/types/v1alpha1/generate/generate.go
  pkg/config/types/v1alpha1/generate/options.go
  pkg/config/types/v1alpha1/v1alpha1_provider.go
  pkg/config/types/v1alpha1/v1alpha1_types.go
  pkg/config/types/v1alpha1/v1alpha1_validation.go
Labels: status/approved, status/lgtm

#2407 chore: update packages
  Dockerfile
  Makefile
  pkg/constants/constants.go
Labels: status/approved, status/lgtm, status/needs-cherry-pick

#2409 chore: update packages
  Dockerfile
  Makefile
  pkg/constants/constants.go
Labels: status/approved, status/lgtm

#2408 fix: allow static pod files
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/approved, status/lgtm

#2410 fix: retry non-HTTP errors from API server
  pkg/kubernetes/kubernetes.go
Labels: status/approved, status/lgtm, status/needs-cherry-pick

#2411 fix: retry non-HTTP errors from API server
  pkg/kubernetes/kubernetes.go
Labels: status/approved, status/lgtm

#2413 chore: update node dependencies
  docs/website/package-lock.json
  docs/website/package.json
Labels: status/approved, status/lgtm

#2412 release(v0.6.0-beta.1): prepare release
  CHANGELOG.md
Labels: status/approved

#2313 chore: update capi CI manifests to use control planes
  hack/test/capi/cluster-aws.yaml
  hack/test/capi/cluster-gcp.yaml
  hack/test/e2e-capi.sh
  hack/test/e2e.sh
Labels: status/approved

#2415 fix: update e2e scripts to work with python3
  hack/test/e2e.sh
Labels: status/approved, status/lgtm

#2091 chore: integrate importvet
  Dockerfile
  Makefile
  pkg/.importvet.yaml
  pkg/config/internal/cis/cis.go
  pkg/config/internal/cis/cis_test.go
  pkg/config/types/v1alpha1/generate/generate.go
Labels: status/approved, status/lgtm

#2419 feat: upgrade etcd to 3.4.10
  go.mod
  go.sum
  internal/app/machined/pkg/system/services/etcd.go
  internal/pkg/etcd/etcd.go
  pkg/constants/constants.go
Labels: status/approved, status/lgtm

#2420 fix: ignore eth0 interface in docker provisioner
  pkg/provision/providers/docker/docker.go
Labels: status/approved, status/lgtm

#2421 fix: run health check for etcd service with Get API
  internal/app/machined/pkg/system/services/etcd.go
Labels: status/approved, status/lgtm

#2423 chore: extract pkg/crypto as external module
  cmd/talosctl/cmd/mgmt/gen.go
  go.mod
  go.sum
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/trustd/internal/reg/reg.go
  internal/pkg/containers/cri/containerd/config_test.go
  internal/pkg/etcd/etcd.go
  internal/pkg/kubeconfig/admin.go
  internal/pkg/kubeconfig/admin_test.go
  pkg/config/provider.go
  pkg/config/types/v1alpha1/generate/generate.go
  pkg/config/types/v1alpha1/generate/join.go
  pkg/config/types/v1alpha1/v1alpha1_provider.go
  pkg/config/types/v1alpha1/v1alpha1_types.go
  pkg/constants/constants.go
  pkg/crypto/x509/x509.go
  pkg/crypto/x509/x509_test.go
  pkg/grpc/gen/local.go
  pkg/grpc/gen/remote.go
  pkg/grpc/tls/local.go
  pkg/grpc/tls/remote.go
  pkg/kubernetes/kubernetes.go
Labels: status/approved, status/lgtm

#2425 refactor: extract `pkg/net` as `github.com/talos-systems/net`
  cmd/talosctl/cmd/mgmt/cluster/create.go
  go.mod
  go.sum
  internal/app/apid/pkg/backend/apid.go
  internal/app/apid/pkg/provider/tls.go
  internal/app/bootkube/assets.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/app/networkd/pkg/networkd/misc.go
  internal/app/trustd/main.go
  internal/integration/provision/upgrade.go
  internal/pkg/etcd/etcd.go
  pkg/client/client.go
  pkg/client/resolver.go
  pkg/config/types/v1alpha1/generate/generate.go
  pkg/grpc/middleware/auth/basic/basic.go
  pkg/net/net.go
  pkg/net/net_test.go
  pkg/provision/providers/vm/network.go
Labels: status/approved, status/lgtm

#2426 docs: fix download link
  docs/website/content/v0.6/en/guides/getting-started/talosctl.md
Labels: status/approved

#2427 refactor: rework `pkg/grpc/tls` to break dependency on `pkg/grpc/gen`
  internal/app/apid/pkg/provider/tls.go
  internal/app/trustd/main.go
  pkg/grpc/tls/local.go
  pkg/grpc/tls/provider.go
  pkg/grpc/tls/remote.go
Labels: status/approved, status/lgtm

#2431 chore: re-import talos-systems/pkg/crypto/tls
  go.mod
  go.sum
  internal/app/apid/pkg/provider/tls.go
  internal/app/trustd/main.go
  pkg/client/client.go
  pkg/grpc/tls/provider.go
  pkg/grpc/tls/tls.go
  pkg/grpc/tls/tls_test.go
Labels: status/approved, status/lgtm

#2433 release(v0.7.0-alpha.0): prepare release
  .conform.yaml
  CHANGELOG.md
Labels: status/approved, status/lgtm

#2436 feat: upgrade Linux to v5.7.15
  Dockerfile
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm, status/needs-cherry-pick

#2430 chore: update node.js dependencies
  docs/website/package-lock.json
Labels: status/approved, status/lgtm

#2435 fix: handle bootkube recover correctly, support recovery from etcd
  go.mod
  go.sum
  internal/app/bootkube/assets.go
  internal/app/bootkube/main.go
  internal/app/bootkube/recover.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/bootkube.go
  internal/integration/api/recover.go
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2438 chore: update machinery version in go.mod
  go.mod
Labels: status/approved, status/lgtm

#2440 feat: make boostrap via API default choice in talosctl cluster create
  cmd/talosctl/cmd/mgmt/cluster/create.go
  docs/talosctl/talosctl_cluster_create.md
Labels: status/approved, status/lgtm

#2439 refactor: extract cluster bootstrapper via API as common component
  cmd/talosctl/cmd/mgmt/cluster/create.go
  pkg/cluster/bootstrap.go
  pkg/cluster/cluster.go
  pkg/provision/access/adapter.go
Labels: status/approved, status/lgtm

#2443 fix: pass config via stdin
  internal/app/apid/main.go
  internal/app/bootkube/main.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/system/runner/containerd/containerd.go
  internal/app/machined/pkg/system/runner/containerd/containerd_test.go
  internal/app/machined/pkg/system/runner/runner.go
  internal/app/machined/pkg/system/services/apid.go
  internal/app/machined/pkg/system/services/bootkube.go
  internal/app/machined/pkg/system/services/networkd.go
  internal/app/machined/pkg/system/services/timed.go
  internal/app/machined/pkg/system/services/trustd.go
  internal/app/networkd/main.go
  internal/app/timed/main.go
  internal/app/trustd/main.go
  internal/pkg/etcd/etcd.go
  pkg/machinery/config/configloader/configloader.go
Labels: status/approved, status/lgtm, status/needs-cherry-pick

#2447 release(v0.6.0-beta.2): prepare release
  CHANGELOG.md
Labels: status/approved, status/lgtm

#2448 chore: bump next version to v0.6.0-beta.2
  Makefile
  internal/integration/provision/upgrade.go
Labels: status/approved

#2449 chore: add a method to merge Talos client config
  cmd/talosctl/cmd/mgmt/cluster/create.go
  pkg/machinery/client/config/config.go
  pkg/machinery/config/types/v1alpha1/bundle/bundle.go
Labels: status/approved, status/lgtm

#2451 test: determine reboots using boot id
  internal/integration/api/reboot.go
  internal/integration/base/api.go
Labels: status/approved, status/lgtm

#2414 chore: re-enable azure e2e testing
  Makefile
  docs/talosctl/talosctl_cluster_create.md
  docs/talosctl/talosctl_gen_config.md
  pkg/machinery/constants/constants.go
Labels: status/approved

#2452 feat: update kubernetes to v1.19.0
  Makefile
  docs/talosctl/talosctl_cluster_create.md
  docs/talosctl/talosctl_gen_config.md
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm, status/needs-cherry-pick

#2453 feat: update kubernetes to v1.19.0
  Makefile
  docs/talosctl/talosctl_cluster_create.md
  docs/talosctl/talosctl_gen_config.md
  pkg/constants/constants.go
Labels: status/approved, status/lgtm

#2455 feat: update linux to 5.8.5
  Dockerfile
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm, status/needs-cherry-pick

#2456 feat: update linux to 5.8.5
  Dockerfile
  pkg/constants/constants.go
Labels: status/approved, status/lgtm

#2457 release(v0.6.0-beta.3): prepare release
  CHANGELOG.md
Labels: status/approved, status/lgtm

#2454 feat: provide option to run Talos under UEFI in QEMU
  .drone.jsonnet
  cmd/talosctl/cmd/mgmt/cluster/create.go
  docs/talosctl/talosctl_cluster_create.md
  hack/test/e2e-qemu.sh
  pkg/provision/options.go
  pkg/provision/providers/qemu/arch.go
  pkg/provision/providers/qemu/create.go
  pkg/provision/providers/qemu/node.go
  pkg/provision/providers/qemu/pflash.go
  pkg/provision/providers/vm/state.go
Labels: status/approved, status/lgtm

#2459 feat: upgrade etcd to 3.4.12
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#2463 docs: add reset doc
  docs/website/content/v0.4.en.json
  docs/website/content/v0.4/en/troubleshooting/machine-reset.md
  docs/website/content/v0.5.en.json
  docs/website/content/v0.5/en/troubleshooting/machine-reset.md
  docs/website/content/v0.6.en.json
  docs/website/content/v0.6/en/troubleshooting/machine-reset.md
Labels: status/approved, status/lgtm
