Repository siderolabs/talos, pull requests merged in 2021-09, with the labels that each got.

#4184 fix: correctly define example for `extraMounts`
  hack/release.toml
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
Labels: status/approved

#3929 feat: use dynamic NodeAddresses/HostnameStatus in Kubernetes certs
  cmd/talosctl/cmd/mgmt/cluster/create.go
  internal/app/machined/pkg/controllers/secrets/altnames.go
  internal/app/machined/pkg/controllers/secrets/api.go
  internal/app/machined/pkg/controllers/secrets/api_test.go
  internal/app/machined/pkg/controllers/secrets/kubernetes.go
  internal/app/machined/pkg/controllers/secrets/kubernetes_test.go
  internal/app/machined/pkg/controllers/secrets/utils.go
  internal/app/machined/pkg/controllers/secrets/utils_test.go
  pkg/kubernetes/kubernetes.go
  pkg/machinery/config/contract.go
  pkg/machinery/config/contract_test.go
  pkg/machinery/config/types/v1alpha1/generate/generate.go
Labels: status/approved

#4186 chore: update tools/pkgs/extras to the new version
  Makefile
Labels: status/approved

#4187 chore: enable GPG identity check for Talos
  .conform.yaml
  Makefile
Labels: status/approved

#4190 feat: implement Kubernetes cluster discovery registry
  internal/app/machined/pkg/controllers/cluster/affiliate_merge.go
  internal/app/machined/pkg/controllers/cluster/affiliate_merge_test.go
  internal/app/machined/pkg/controllers/cluster/config.go
  internal/app/machined/pkg/controllers/cluster/config_test.go
  internal/app/machined/pkg/controllers/cluster/kubernetes_pull.go
  internal/app/machined/pkg/controllers/cluster/kubernetes_push.go
  internal/app/machined/pkg/controllers/cluster/local_affiliate.go
  internal/app/machined/pkg/controllers/cluster/member.go
  internal/app/machined/pkg/controllers/cluster/member_test.go
  internal/app/machined/pkg/controllers/secrets/kubernetes.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/pkg/discovery/registry/kubernetes.go
  internal/pkg/discovery/registry/kubernetes_test.go
  internal/pkg/discovery/registry/registry.go
  pkg/machinery/constants/constants.go
  pkg/resources/cluster/affiliate.go
  pkg/resources/cluster/affiliate_test.go
  pkg/resources/cluster/cluster.go
  pkg/resources/cluster/cluster_test.go
  pkg/resources/cluster/config.go
  pkg/resources/cluster/member.go
Labels: status/approved, area/kubespan

#4182 docs: document required options for extraMounts
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  website/content/docs/v0.13/Reference/configuration.md
Labels: status/approved

#4195 backport: fix: correctly define example for `extraMounts`
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
Labels: status/approved

#4196 release(v0.12.1): prepare release
  CHANGELOG.md
  website/content/docs/v0.12/Reference/cli.md
Labels: status/approved

#4198 chore: bump tools to the latest version
  Makefile
Labels: status/approved

#4201 chore: use named constants
  pkg/cluster/kubernetes/talos_managed.go
Labels: status/approved

#4092 feat: add hetzner.com cloud support
  .drone.jsonnet
  Makefile
  cmd/installer/cmd/image.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/errors/errors.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/hcloud.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/hcloud_test.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
  website/content/docs/v0.13/Cloud Platforms/hetzner.md
Labels: status/approved

#4205 docs: promote 0.12 docs to be the latest
  website/static/_redirects
Labels: status/approved

#4197 feat: drop some capabilities to be never available
  go.mod
  go.sum
  internal/app/machined/internal/install/install.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/runner/containerd/containerd.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/pkg/capability/capability.go
Labels: status/approved

#4206 fix: correctly parse multiple pod/service CIDRs
  internal/app/machined/pkg/controllers/config/k8s_address_filter.go
  internal/app/machined/pkg/controllers/config/k8s_address_filter_test.go
  internal/app/machined/pkg/controllers/config/k8s_control_plane.go
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
  internal/app/machined/pkg/controllers/k8s/manifest.go
  internal/app/machined/pkg/controllers/k8s/manifest_test.go
  internal/app/machined/pkg/controllers/k8s/templates.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go
  pkg/resources/config/k8s_control_plane.go
Labels: status/approved

#4204 feat: implement KubeSpan peer generation controller
  internal/app/machined/pkg/controllers/kubespan/kubespan_test.go
  internal/app/machined/pkg/controllers/kubespan/peer_spec.go
  internal/app/machined/pkg/controllers/kubespan/peer_spec_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/resources/kubespan/kubespan_test.go
  pkg/resources/kubespan/peer_spec.go
Labels: status/approved

#4207 fix: suppress spurious Kubernetes API server cert updates
  internal/app/machined/pkg/controllers/secrets/altnames.go
  internal/app/machined/pkg/controllers/secrets/api.go
  internal/app/machined/pkg/controllers/secrets/api_cert_sans.go
  internal/app/machined/pkg/controllers/secrets/api_cert_sans_test.go
  internal/app/machined/pkg/controllers/secrets/api_test.go
  internal/app/machined/pkg/controllers/secrets/kubernetes.go
  internal/app/machined/pkg/controllers/secrets/kubernetes_cert_sans.go
  internal/app/machined/pkg/controllers/secrets/kubernetes_cert_sans_test.go
  internal/app/machined/pkg/controllers/secrets/kubernetes_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/resources/secrets/cert_sans.go
  pkg/resources/secrets/secrets_test.go
Labels: status/approved

#4146 feat: add upcloud.com cloud support
  .drone.jsonnet
  cmd/installer/cmd/image.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/upcloud/upcloud.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/upcloud/upcloud_test.go
  website/content/docs/v0.13/Cloud Platforms/upcloud.md
Labels: status/approved, area/platforms

#4106 feat: add scaleway.com cloud support
  .drone.jsonnet
  cmd/installer/cmd/image.go
  go.mod
  go.sum
  internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/scaleway.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/scaleway_test.go
  website/content/docs/v0.13/Cloud Platforms/scaleway.md
Labels: status/approved

#4209 fix: build platform images
  Makefile
Labels: status/approved

#4210 fix: multiple fixes for KubeSpan and Wireguard implementation
  internal/app/machined/pkg/controllers/cluster/kubernetes_pull.go
  internal/app/machined/pkg/controllers/cluster/local_affiliate.go
  internal/app/machined/pkg/controllers/cluster/local_affiliate_test.go
  internal/app/machined/pkg/controllers/kubespan/peer_spec.go
  internal/app/machined/pkg/controllers/kubespan/peer_spec_test.go
  pkg/resources/kubespan/peer_spec.go
  pkg/resources/network/link.go
  pkg/resources/network/link_spec.go
  pkg/resources/network/link_status.go
  pkg/resources/network/link_test.go
Labels: status/approved, area/kubespan

#4222 fix: print etcd member ID in hex
  internal/pkg/etcd/etcd.go
Labels: status/approved

#4223 chore: bump dependencies
  Dockerfile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  internal/app/machined/pkg/controllers/network/address_spec.go
  internal/app/machined/pkg/controllers/network/route_spec_test.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved

#4226 release(v0.13.0-alpha.0): prepare release
  CHANGELOG.md
  hack/release.toml
  website/content/docs/v0.13/Reference/cli.md
Labels: status/approved

#4230 fix: update the way results are retrieved for certified conformance
  pkg/cluster/sonobuoy/sonobuoy.go
Labels: status/approved

#4234 fix: write KubernetesCACert chmodded 0400 instead of 0500
  internal/app/machined/pkg/system/services/kubelet.go
Labels: status/approved

#4236 feat: add vultr.com cloud support
  .drone.jsonnet
  Makefile
  cmd/installer/cmd/image.go
  go.mod
  go.sum
  internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/vultr/vultr.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/vultr/vultr_test.go
  website/content/docs/v0.13/Cloud Platforms/vultr.md
Labels: status/approved

#4237 fix: completely prevent editing resources other than mc
  cmd/talosctl/cmd/talos/edit.go
Labels: status/approved

#4211 feat: implement KubeSpan manager for Wireguard peer state
  Dockerfile
  internal/app/machined/pkg/controllers/cluster/local_affiliate.go
  internal/app/machined/pkg/controllers/kubespan/config.go
  internal/app/machined/pkg/controllers/kubespan/config_test.go
  internal/app/machined/pkg/controllers/kubespan/identity_test.go
  internal/app/machined/pkg/controllers/kubespan/kubespan_test.go
  internal/app/machined/pkg/controllers/kubespan/manager.go
  internal/app/machined/pkg/controllers/kubespan/manager_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/machinery/constants/constants.go
  pkg/resources/kubespan/config.go
  pkg/resources/kubespan/kubespan_test.go
  pkg/resources/kubespan/peer_state.go
  pkg/resources/kubespan/peer_status.go
  pkg/resources/kubespan/peer_status_test.go
  pkg/resources/kubespan/peerstate_string.go
Labels: status/approved, area/kubespan

#4239 fix: tear down control plane static pods when etcd is stopped
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod_test.go
  internal/app/machined/pkg/controllers/k8s/kubelet_static_pod_controller.go
Labels: status/approved

#4213 openstack platform refactoring
  internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
Labels: status/approved

#4200 feat: reboot via kexec
  cmd/talosctl/cmd/mgmt/cluster/create.go
  hack/release.toml
  internal/app/machined/pkg/runtime/state.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_state.go
  pkg/machinery/config/types/v1alpha1/generate/generate.go
  pkg/machinery/config/types/v1alpha1/generate/init.go
  pkg/machinery/config/types/v1alpha1/generate/options.go
  pkg/machinery/config/types/v1alpha1/generate/worker.go
  website/content/docs/v0.13/Introduction/support-matrix.md
Labels: status/approved

#4242 feat: update Kubernetes to 1.22.2
  Makefile
  hack/test/e2e.sh
  internal/integration/provision/upgrade.go
  pkg/machinery/constants/constants.go
  website/content/docs/v0.13/Reference/cli.md
  website/content/docs/v0.13/Reference/configuration.md
Labels: status/approved

#4244 fix: patch multi nodes support
  cmd/talosctl/cmd/talos/edit.go
  cmd/talosctl/cmd/talos/patch.go
Labels: status/approved

#4241 feat: add routes, routing rules and nftables rules for KubeSpan
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/kubespan/manager.go
  internal/app/machined/pkg/controllers/kubespan/manager_test.go
  internal/app/machined/pkg/controllers/kubespan/nftables.go
  internal/app/machined/pkg/controllers/kubespan/nftables_test.go
  internal/app/machined/pkg/controllers/kubespan/routing_rules.go
  internal/app/machined/pkg/controllers/kubespan/routing_rules_test.go
  internal/app/machined/pkg/controllers/network/link_merge_test.go
  internal/app/machined/pkg/controllers/network/operator_spec.go
  pkg/resources/network/operator.go
  pkg/resources/network/operator_string.go
Labels: status/approved, area/kubespan

#4245 feat: add an option to continue booting on NTP timeout
  internal/app/machined/pkg/controllers/time/sync.go
  internal/app/machined/pkg/controllers/time/sync_test.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  website/content/docs/v0.13/Reference/configuration.md
Labels: status/approved

#4246 fix: add node address to the list of allowed IPs (kubespan)
  internal/app/machined/pkg/controllers/kubespan/peer_spec.go
  internal/app/machined/pkg/controllers/kubespan/peer_spec_test.go
Labels: status/approved, area/kubespan

#4247 chore: add a special condition to check for kubeconfig readiness
  internal/app/machined/pkg/controllers/cluster/kubernetes_pull.go
  internal/app/machined/pkg/controllers/cluster/kubernetes_push.go
  internal/app/machined/pkg/controllers/k8s/endpoint.go
  pkg/conditions/files.go
  pkg/conditions/kubeconfig.go
Labels: status/approved

#4249 feat: add operating system version field to discovery
  internal/app/machined/pkg/controllers/cluster/local_affiliate.go
  internal/app/machined/pkg/controllers/cluster/local_affiliate_test.go
  internal/app/machined/pkg/controllers/cluster/member.go
  internal/app/machined/pkg/controllers/cluster/member_test.go
  internal/pkg/discovery/registry/kubernetes.go
  internal/pkg/discovery/registry/kubernetes_test.go
  pkg/resources/cluster/affiliate.go
  pkg/resources/cluster/member.go
Labels: status/approved, area/kubespan

#4253 release(v0.12.2): prepare release
  CHANGELOG.md
  hack/release.toml
  website/content/docs/v0.12/Reference/cli.md
Labels: status/approved

#4267 chore: bump dependencies and drop firecracker support
  Dockerfile
  cmd/talosctl/cmd/mgmt/cluster/cluster.go
  cmd/talosctl/cmd/mgmt/firecracker_launch_linux.go
  cmd/talosctl/cmd/mgmt/loadbalancer_launch.go
  cmd/talosctl/cmd/mgmt/qemu_launch_linux.go
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/test/e2e-firecracker.sh
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/provision/internal/cniutils/cniutils.go
  pkg/provision/providers/factory.go
  pkg/provision/providers/firecracker/bootloader.go
  pkg/provision/providers/firecracker/create.go
  pkg/provision/providers/firecracker/destroy.go
  pkg/provision/providers/firecracker/firecracker.go
  pkg/provision/providers/firecracker/kernel.go
  pkg/provision/providers/firecracker/launch.go
  pkg/provision/providers/firecracker/node.go
  pkg/provision/providers/firecracker_linux.go
  pkg/provision/providers/firecracker_other.go
  pkg/provision/providers/qemu/destroy.go
  pkg/provision/providers/qemu/launch.go
  website/content/docs/v0.13/Local Platforms/firecracker.md
  website/content/docs/v0.13/Reference/cli.md
Labels: status/approved

#4268 release(v0.13.0-alpha.1): prepare release
  CHANGELOG.md
  hack/release.toml
  website/content/docs/v0.13/Reference/cli.md
Labels: status/approved

#4269 fix: don't marshal clock with SecretsBundle
  pkg/machinery/config/types/v1alpha1/generate/generate.go
Labels: status/approved

#4271 backport: fix: don't marshal clock with SecretsBundle
  pkg/machinery/config/types/v1alpha1/generate/generate.go
Labels: status/approved

#4273 fix: containerd log symlink
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/kubelet.go
Labels: status/approved

#4277 test: update CABPT provider to 0.3 release
  hack/test/e2e-capi.sh
Labels: status/approved

#4280 fix: use readonly mode when probing devices with `All` lookup
  cmd/installer/cmd/image.go
  go.mod
  go.sum
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/approved

#4284 fix: check for existence of dhcp6 FQDN first
  internal/app/machined/pkg/controllers/network/operator/dhcp6.go
Labels: status/approved

#4282 fix: find devices without partition table
  go.mod
  go.sum
Labels: status/approved

#4281 chore: deprecate Interfaces and Routes APIs
  api/network/network.proto
  cmd/talosctl/cmd/talos/interfaces.go
  cmd/talosctl/cmd/talos/routes.go
  internal/app/networkd/pkg/server/server.go
  internal/app/networkd/pkg/server/server_test.go
  internal/integration/api/network-interfaces.go
  internal/integration/cli/interfaces.go
  internal/integration/cli/routes.go
  internal/pkg/tui/installer/connection.go
  internal/pkg/tui/installer/state.go
  pkg/machinery/api/network/network.pb.go
  pkg/machinery/api/network/network_grpc.pb.go
  pkg/machinery/client/client.go
  pkg/machinery/nethelpers/hwaddr.go
  pkg/resources/network/address_spec.go
  pkg/resources/network/address_status.go
  pkg/resources/network/consts.go
  pkg/resources/network/link.go
  pkg/resources/network/link_spec.go
  pkg/resources/network/link_status.go
  pkg/resources/network/network.go
  pkg/resources/network/route_spec.go
  pkg/resources/network/route_status.go
  website/content/docs/v0.13/Reference/cli.md
Labels: status/approved

#4291 chore: bump dependencies
  Dockerfile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved

#4293 chore: remove deprecated "join" term
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/mgmt/config.go
  pkg/machinery/config/bundle.go
  pkg/machinery/config/types/v1alpha1/bundle/bundle.go
  pkg/machinery/config/types/v1alpha1/bundle/options.go
  pkg/machinery/config/types/v1alpha1/machine/machine.go
  pkg/machinery/config/types/v1alpha1/machine/machine_test.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_configurator_bundle.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
Labels: status/approved

#4160 test: add fuzz test for configloader
  pkg/machinery/config/configloader/configloader_fuzz_test.go
  pkg/machinery/config/configloader/configloader_test.go
  pkg/machinery/config/configloader/testdata/controlplane.test
  pkg/machinery/config/configloader/testdata/empty1.test
  pkg/machinery/config/configloader/testdata/empty2.test
  pkg/machinery/config/configloader/testdata/worker.test
  pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
Labels: status/approved

#4255 feat: implement Hetzner Cloud support for virtual (shared) IP
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/network/operator/vip.go
  internal/app/machined/pkg/controllers/network/operator/vip/hcloud.go
  internal/app/machined/pkg/controllers/network/operator_config.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
  pkg/resources/network/operator_spec.go
  website/content/docs/v0.13/Reference/configuration.md
Labels: status/approved

#4294 fix: check trustd API CA on worker nodes
  internal/app/machined/pkg/controllers/secrets/api.go
  pkg/grpc/gen/remote.go
  pkg/grpc/middleware/auth/basic/basic.go
  pkg/machinery/config/types/v1alpha1/generate/worker.go
Labels: status/approved

#4295 chore: update Linux to 5.10.69
  Makefile
  pkg/machinery/constants/constants.go
Labels: status/approved

#4208 feat: add nocloud platform support
  .drone.jsonnet
  Makefile
  cmd/installer/cmd/image.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud_test.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
  website/content/docs/v0.13/Cloud Platforms/nocloud.md
Labels: status/approved

#4297 release(v0.12.3): prepare release
  CHANGELOG.md
  go.mod
  hack/protoc-lint/go.mod
  hack/protoc-lint/go.sum
  website/content/docs/v0.12/Reference/cli.md
Labels: status/approved

#4283 feat: implement integration with Discovery Service
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/cluster/config.go
  internal/app/machined/pkg/controllers/cluster/config_test.go
  internal/app/machined/pkg/controllers/cluster/discovery_service.go
  internal/app/machined/pkg/controllers/cluster/discovery_service_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/proto/proto.go
  pkg/resources/cluster/config.go
Labels: status/approved, area/kubespan

#4298 release(v0.13.0-alpha.2): prepare release
  CHANGELOG.md
  hack/release.toml
  website/content/docs/v0.13/Reference/cli.md
Labels: status/approved

#4299 test: workaround race in the tests with zaptest package
  internal/app/machined/pkg/controllers/cluster/discovery_service_test.go
Labels: status/approved

#4292 feat: override static pods default args by extra Args
  internal/app/machined/pkg/controllers/config/k8s_control_plane.go
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod_test.go
  internal/app/machined/pkg/controllers/k8s/manifest_test.go
  internal/app/machined/pkg/controllers/k8s/templates.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/machined/pkg/system/services/kubelet.go
  pkg/argsbuilder/argsbuilder_args.go
  pkg/argsbuilder/argsbuilder_interface.go
  pkg/argsbuilder/argsbuilder_test.go
  pkg/resources/config/k8s_control_plane.go
Labels: status/approved

#4302 fix: reset inputs back to initial state in secrets.APIController
  internal/app/machined/pkg/controllers/secrets/api.go
Labels: status/approved

#4303 feat: publish node's ExternalIPs as node addresses
  internal/app/machined/pkg/controllers/network/address_status.go
  internal/app/machined/pkg/controllers/network/node_address.go
  internal/app/machined/pkg/controllers/network/node_address_test.go
  internal/app/machined/pkg/controllers/network/platform_config.go
  internal/app/machined/pkg/controllers/network/platform_config_test.go
Labels: status/approved, area/kubespan

#4301 feat: add an option to skip downed peers in KubeSpan
  cmd/talosctl/cmd/mgmt/config.go
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/kubespan/config.go
  internal/app/machined/pkg/controllers/kubespan/config_test.go
  internal/app/machined/pkg/controllers/kubespan/manager.go
  internal/app/machined/pkg/controllers/kubespan/manager_test.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/resources/kubespan/config.go
  website/content/docs/v0.13/Reference/cli.md
  website/content/docs/v0.13/Reference/configuration.md
Labels: status/approved, area/kubespan

#4304 feat: harvest discovered endpoints and push them via discovery svc
  internal/app/machined/pkg/controllers/cluster/discovery_service.go
  internal/app/machined/pkg/controllers/cluster/discovery_service_test.go
  internal/app/machined/pkg/controllers/kubespan/endpoint.go
  internal/app/machined/pkg/controllers/kubespan/endpoint_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/resources/kubespan/endpoint.go
  pkg/resources/kubespan/kubespan_test.go
Labels: status/approved, area/kubespan

#4306 release(v0.13.0-alpha.3): prepare release
  CHANGELOG.md
  website/content/docs/v0.13/Reference/cli.md
Labels: status/approved

#4308 feat: update containerd to 1.5.6
  Makefile
  pkg/machinery/constants/constants.go
Labels: status/approved

#4310 fix: ignore 404 for AWS external IPs
  internal/app/machined/pkg/controllers/network/platform_config.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/scaleway.go
Labels: status/approved
