Repository siderolabs/talos, pull requests merged in 2021-04, with the labels that each got.

#3407 feat: bring in Linux 5.10.27, support for 32-bit time syscalls
  Makefile
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#3406 release(v0.9.1): prepare release
  CHANGELOG.md
  website/content/docs/v0.9/Reference/cli.md
Labels: status/approved, status/lgtm

#3417 docs(upgrading-talos): fix typo for stage flag
  website/content/docs/v0.10/Guides/upgrading-talos.md
  website/content/docs/v0.9/Guides/upgrading-talos.md
Labels: status/approved, status/lgtm

#3418 fix: ignore EOF errors from Kubernetes API when converting control plane
  pkg/cluster/kubernetes/kubernetes.go
Labels: status/approved, status/lgtm

#3423 fix: print task failure error immediately
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
Labels: status/approved, status/lgtm

#3422 fix: retry Kubernetes API errors on cordon/uncordon/etc.
  pkg/cluster/kubernetes/convert.go
  pkg/cluster/kubernetes/kubernetes.go
  pkg/cluster/kubernetes/self_hosted.go
  pkg/cluster/kubernetes/talos_managed.go
  pkg/kubernetes/errors.go
  pkg/kubernetes/kubernetes.go
Labels: status/approved, status/lgtm

#3424 test: update 0.9.x version in upgrade tests to 0.9.1
  Makefile
  internal/integration/provision/upgrade.go
Labels: status/approved, status/lgtm

#3426 fix: create rootfs for system services via /system tmpfs
  Dockerfile
  internal/app/machined/pkg/system/services/apid.go
  internal/app/machined/pkg/system/services/trustd.go
  internal/app/machined/pkg/system/services/utils.go
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#3398 feat: add API and command to save etcd snapshot (backup)
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/etcd.go
  internal/app/apid/main.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/integration/cli/etcd.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/machine/machine_grpc.pb.go
  pkg/machinery/client/client.go
  website/content/docs/v0.10/Reference/api.md
  website/content/docs/v0.10/Reference/cli.md
Labels: status/approved, status/lgtm

#3428 feat: add --config-patch parameter to talosctl gen config
  cmd/talosctl/cmd/mgmt/config.go
  internal/integration/cli/gen.go
  website/content/docs/v0.10/Bare Metal Platforms/digital-rebar.md
  website/content/docs/v0.10/Bare Metal Platforms/equinix-metal.md
  website/content/docs/v0.10/Bare Metal Platforms/matchbox.md
  website/content/docs/v0.10/Cloud Platforms/aws.md
  website/content/docs/v0.10/Cloud Platforms/digitalocean.md
  website/content/docs/v0.10/Cloud Platforms/gcp.md
  website/content/docs/v0.10/Cloud Platforms/openstack.md
  website/content/docs/v0.10/Reference/cli.md
  website/content/docs/v0.10/Virtualized Platforms/vmware.md
Labels: status/approved, status/lgtm

#3429 fix: publish rockpi4 image to release artifacts
  .drone.jsonnet
Labels: status/approved, status/lgtm

#3435 chore: bump dependencies via dependabot
  Dockerfile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#3436 refactor: download modules before `go generate`
  Dockerfile
Labels: status/approved, status/lgtm

#3425 fix: add a check for overlay mounts in installer pre-flight checks
  cmd/installer/pkg/install/manifest.go
  cmd/installer/pkg/install/manifest_test.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/approved, status/lgtm

#3430 fix: make both HDMI ports work on RPi 4
  internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/config.txt
  internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/rpi_4.go
Labels: status/approved

#3437 fix: require leader on etcd member operations
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/etcd.go
Labels: status/approved, status/lgtm

#3440 chore: update blockdevice library for PMBR bootable fix
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#3444 chore: update Go to 1.16.3
  Makefile
Labels: status/approved, status/lgtm

#3415 feat: allow external cloud provides configration
  Dockerfile
  Makefile
  hack/cleanup.sh
  hack/test/e2e-aws.sh
  internal/app/machined/pkg/controllers/config/k8s_control_plane.go
  internal/app/machined/pkg/controllers/config/k8s_control_plane_test.go
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/pkg/kubeconfig/admin_test.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_externalcloudproviderconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider_test.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
  website/content/docs/v0.10/Reference/configuration.md
Labels: status/approved, status/lgtm

#3405 refactor: pull new version of os-runtime, update code
  api/inspect/inspect.proto
  api/resource/resource.proto
  cmd/talosctl/cmd/talos/inspect.go
  go.mod
  go.sum
  internal/app/machined/internal/server/v1alpha1/v1alpha1_inspect.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_resource.go
  internal/app/machined/pkg/controllers/config/k8s_control_plane.go
  internal/app/machined/pkg/controllers/config/k8s_control_plane_test.go
  internal/app/machined/pkg/controllers/config/machine_type.go
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
  internal/app/machined/pkg/controllers/k8s/extra_manifest.go
  internal/app/machined/pkg/controllers/k8s/kubelet_static_pod_controller.go
  internal/app/machined/pkg/controllers/k8s/manifest.go
  internal/app/machined/pkg/controllers/k8s/manifest_apply.go
  internal/app/machined/pkg/controllers/k8s/render_secrets_static_pod.go
  internal/app/machined/pkg/controllers/secrets/etcd.go
  internal/app/machined/pkg/controllers/secrets/kubernetes.go
  internal/app/machined/pkg/controllers/secrets/root.go
  internal/app/machined/pkg/controllers/time/sync.go
  internal/app/machined/pkg/controllers/v1alpha1/boostrap_status.go
  internal/app/machined/pkg/controllers/v1alpha1/service.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/machinery/api/inspect/inspect.pb.go
  pkg/machinery/api/resource/resource.pb.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/resources/k8s/k8s.go
  website/content/docs/v0.10/Guides/converting-control-plane.md
  website/content/docs/v0.10/Guides/troubleshooting-control-plane.md
  website/content/docs/v0.10/Learn More/controllers-resources.md
  website/content/docs/v0.10/Reference/api.md
  website/static/images/controller-dependencies-v2.png
  website/static/images/controller-dependencies-with-resources-v2.png
Labels: status/approved, status/lgtm

#3446 fix: revert mark PMBR EFI partition as bootable
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#3445 docs: fix "DigitalOcean" spelling
  Makefile
  website/content/docs/v0.10/Cloud Platforms/digitalocean.md
  website/content/docs/v0.6/Cloud Platforms/digitalocean.md
  website/content/docs/v0.7/Cloud Platforms/digitalocean.md
  website/content/docs/v0.8/Cloud Platforms/digitalocean.md
  website/content/docs/v0.9/Cloud Platforms/digitalocean.md
Labels: status/approved, status/lgtm

#3448 fix: trim endpoints/nodes from arguments in talosctl config
  cmd/talosctl/cmd/talos/config.go
Labels: status/approved, status/lgtm

#3447 test: update CAPA to 0.6.4
  hack/test/e2e-capi.sh
Labels: status/approved

#3442 docs: describe steps to install and boot Talos from the SSD on rockpi4
  website/content/docs/v0.10/Single Board Computers/rockpi_4.md
Labels: status/approved, status/lgtm

#3449 test: update CAPA to 0.6.4
  hack/test/e2e-capi.sh
Labels: status/approved, status/lgtm

#3443 feat: support etcd recovery from snapshot on bootstrap
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/bootstrap.go
  cmd/talosctl/cmd/talos/etcd.go
  go.mod
  go.sum
  hack/release.toml
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/integration/api/etcd-recover.go
  internal/integration/api/reset.go
  internal/integration/base/api.go
  pkg/cluster/bootstrap.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/machine/machine_grpc.pb.go
  pkg/machinery/client/client.go
  pkg/machinery/constants/constants.go
  website/content/docs/v0.10/Reference/api.md
  website/content/docs/v0.10/Reference/cli.md
Labels: status/approved, status/lgtm

#3453 release(v0.10.0-alpha.2): prepare release
  CHANGELOG.md
  website/content/docs/v0.10/Reference/cli.md
Labels: status/approved, status/lgtm

#3450 feat: add config validation warnings
  api/machine/machine.proto
  cmd/talosctl/cmd/mgmt/validate.go
  cmd/talosctl/cmd/talos/apply-config.go
  cmd/talosctl/cmd/talos/edit.go
  cmd/talosctl/cmd/talos/patch.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/maintenance/server/server.go
  internal/integration/cli/validate.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
  pkg/machinery/config/validation.go
  website/content/docs/v0.10/Reference/api.md
  website/content/docs/v0.10/Reference/cli.md
Labels: status/approved, status/lgtm

#3441 fix: document HDMI problem on RPi 4
  internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/config.txt
  website/content/docs/v0.10/Single Board Computers/bananapi_m64.md
  website/content/docs/v0.10/Single Board Computers/libretech_all_h3_cc_h5.md
  website/content/docs/v0.10/Single Board Computers/rock64.md
  website/content/docs/v0.10/Single Board Computers/rockpi_4.md
  website/content/docs/v0.10/Single Board Computers/rpi_4.md
Labels: status/approved, status/lgtm

#3455 feat: update Kubernetes to 1.21.0 release
  Makefile
  go.mod
  go.sum
  hack/test/e2e.sh
  internal/integration/provision/upgrade.go
  pkg/machinery/constants/constants.go
  website/content/docs/v0.10/Reference/cli.md
  website/content/docs/v0.10/Reference/configuration.md
Labels: status/approved

#3459 feat: add support for "none" CNI type
  .gitignore
  cmd/talosctl/cmd/mgmt/cluster/create.go
  internal/app/machined/pkg/controllers/config/k8s_control_plane.go
  internal/integration/api/generate-config.go
  internal/integration/provision/upgrade.go
  internal/pkg/tui/installer/state.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_cniconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
  pkg/machinery/constants/constants.go
  website/content/docs/v0.10/Reference/configuration.md
Labels: status/approved, status/lgtm

#3458 test: update upgrade tests to 0.10 release
  Makefile
  internal/integration/provision/upgrade.go
Labels: status/approved, status/lgtm

#3461 chore: update Linux to 5.10.28, u-boot to final 2021.04 release
  Makefile
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#3463 docs: fixup typo in encryption guide command
  website/content/docs/v0.10/Guides/disk-encryption.md
  website/content/docs/v0.9/Guides/disk-encryption.md
Labels: status/approved, status/lgtm

#3470 chore: bump dependencies via dependabot
  Dockerfile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#3460 feat: validate the machine configuration in the installer container
  cmd/installer/cmd/install.go
  internal/app/machined/internal/install/install.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/runner/containerd/containerd.go
  internal/app/machined/pkg/system/runner/containerd/stdin.go
  pkg/machinery/config/configloader/configloader.go
Labels: status/approved, status/lgtm

#3469 chore: use Go 1.16 global install command
  Dockerfile
  Makefile
  pkg/machinery/api/cluster/cluster_grpc.pb.go
  pkg/machinery/api/health/health_grpc.pb.go
  pkg/machinery/api/inspect/inspect_grpc.pb.go
  pkg/machinery/api/machine/machine_grpc.pb.go
  pkg/machinery/api/network/network_grpc.pb.go
  pkg/machinery/api/resource/resource_grpc.pb.go
  pkg/machinery/api/security/security_grpc.pb.go
  pkg/machinery/api/storage/storage_grpc.pb.go
  pkg/machinery/api/time/time_grpc.pb.go
Labels: status/approved, status/lgtm

#3471 chore: re-import talos-systems/os-runtime as cosi-project/runtime
  cmd/talosctl/cmd/talos/inspect.go
  cmd/talosctl/cmd/talos/output/json.go
  cmd/talosctl/cmd/talos/output/output.go
  cmd/talosctl/cmd/talos/output/table.go
  cmd/talosctl/cmd/talos/output/yaml.go
  go.mod
  go.sum
  internal/app/machined/internal/server/v1alpha1/v1alpha1_inspect.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_resource.go
  internal/app/machined/pkg/controllers/config/k8s_control_plane.go
  internal/app/machined/pkg/controllers/config/k8s_control_plane_test.go
  internal/app/machined/pkg/controllers/config/machine_type.go
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod_test.go
  internal/app/machined/pkg/controllers/k8s/extra_manifest.go
  internal/app/machined/pkg/controllers/k8s/kubelet_static_pod_controller.go
  internal/app/machined/pkg/controllers/k8s/manifest.go
  internal/app/machined/pkg/controllers/k8s/manifest_apply.go
  internal/app/machined/pkg/controllers/k8s/manifest_test.go
  internal/app/machined/pkg/controllers/k8s/render_secrets_static_pod.go
  internal/app/machined/pkg/controllers/secrets/etcd.go
  internal/app/machined/pkg/controllers/secrets/kubernetes.go
  internal/app/machined/pkg/controllers/secrets/root.go
  internal/app/machined/pkg/controllers/time/sync.go
  internal/app/machined/pkg/controllers/time/sync_test.go
  internal/app/machined/pkg/controllers/v1alpha1/boostrap_status.go
  internal/app/machined/pkg/controllers/v1alpha1/service.go
  internal/app/machined/pkg/runtime/controller.go
  internal/app/machined/pkg/runtime/state.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/cluster/kubernetes/convert.go
  pkg/cluster/kubernetes/talos_managed.go
  pkg/machinery/client/resources.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/resources/config/config.go
  pkg/resources/config/config_test.go
  pkg/resources/config/k8s_control_plane.go
  pkg/resources/config/machine_config.go
  pkg/resources/config/machine_type.go
  pkg/resources/k8s/k8s.go
  pkg/resources/k8s/k8s_test.go
  pkg/resources/k8s/manifest.go
  pkg/resources/k8s/manifest_status.go
  pkg/resources/k8s/secrets_status.go
  pkg/resources/k8s/static_pod.go
  pkg/resources/k8s/static_pod_status.go
  pkg/resources/secrets/etcd.go
  pkg/resources/secrets/kubernetes.go
  pkg/resources/secrets/root.go
  pkg/resources/secrets/secrets.go
  pkg/resources/secrets/secrets_test.go
  pkg/resources/time/condition.go
  pkg/resources/time/status.go
  pkg/resources/time/time_test.go
  pkg/resources/v1alpha1/bootstrap_status.go
  pkg/resources/v1alpha1/service.go
  pkg/resources/v1alpha1/v1alpha1.go
  pkg/resources/v1alpha1/v1alpha1_test.go
Labels: status/approved, status/lgtm

#3467 test: extend unit-tests for config contract parsing
  pkg/machinery/config/contract_test.go
Labels: status/approved, status/lgtm

#3472 chore: use tagged version of cluster-api-templates
  hack/test/e2e-aws.sh
Labels: status/approved, status/lgtm

#3372 chore: apply coverage analysis to all packages
  .codecov.yml
  Dockerfile
Labels: status/approved, status/lgtm

#3462 fix: check retryable network errors by interface
  pkg/kubernetes/errors.go
Labels: status/approved, status/lgtm

#3456 feat: implement inline manifests in the machine configuration
  hack/release.toml
  internal/app/machined/pkg/controllers/config/k8s_control_plane.go
  internal/app/machined/pkg/controllers/config/k8s_control_plane_test.go
  internal/app/machined/pkg/controllers/k8s/extra_manifest.go
  internal/app/machined/pkg/controllers/k8s/extra_manifest_test.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/generate/init.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_inlinemanifest.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
  pkg/resources/config/k8s_control_plane.go
  website/content/docs/v0.10/Reference/configuration.md
Labels: status/approved, status/lgtm

#3473 chore: fix import path mismerge
  internal/app/machined/pkg/controllers/k8s/extra_manifest_test.go
Labels: status/approved, status/lgtm

#3474 feat: Linux 5.10.29 kernel
  Makefile
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#3451 Read VMWare OVF Environment
  cmd/installer/pkg/ova/ova.go
  go.mod
  go.sum
  internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
  pkg/machinery/constants/constants.go
Labels: status/approved

#3477 fix: zero out manifest contents before setting new value
  pkg/resources/k8s/manifest.go
Labels: status/approved, status/lgtm

#3475 feat: provide Talos machine config with field placeholders and docs
  cmd/talosctl/cmd/talos/images.go
  pkg/machinery/config/encoder/documentation.go
  pkg/machinery/config/encoder/encoder.go
  pkg/machinery/config/encoder/encoder_test.go
  pkg/machinery/config/types/v1alpha1/generate/init.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  website/content/docs/v0.10/Reference/configuration.md
Labels: status/approved, status/lgtm

#3478 chore: bump website node.js dependencies
  website/package-lock.json
Labels: status/lgtm

#3480 release(v0.10.0-beta.0): prepare release
  .conform.yaml
  CHANGELOG.md
  website/content/docs/v0.10/Reference/cli.md
Labels: status/approved, status/lgtm

#3481 chore: fix conform with scopes
  .conform.yaml
  Makefile
Labels: status/approved, status/lgtm

#3483 feat: provide an option to recover etcd from data directory copy
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/bootstrap.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/etcd.go
  pkg/machinery/api/machine/machine.pb.go
  website/content/docs/v0.10/Reference/api.md
  website/content/docs/v0.10/Reference/cli.md
Labels: status/approved, status/lgtm

#3484 fix: update etcd client errors, print etcd join failures
  internal/app/machined/pkg/system/services/etcd.go
  internal/pkg/etcd/etcd.go
Labels: status/approved, status/lgtm

#3490 feat: bump k8s version to 1.20.6
  Makefile
  hack/test/e2e.sh
  internal/integration/provision/upgrade.go
  pkg/machinery/constants/constants.go
  website/content/docs/v0.9/Reference/cli.md
  website/content/docs/v0.9/Reference/configuration.md
Labels: status/approved, status/lgtm

#3493 release(v0.9.2): prepare release
  CHANGELOG.md
  website/content/docs/v0.9/Reference/cli.md
Labels: status/approved, status/lgtm

#3485 test: implement `talosctl conformance` command to run e2e tests
  .drone.jsonnet
  cmd/talosctl/cmd/talos/conformance.go
  hack/test/e2e-qemu.sh
  hack/test/e2e.sh
  pkg/cluster/sonobuoy/product.go
  pkg/cluster/sonobuoy/sonobuoy.go
  website/content/docs/v0.10/Reference/cli.md
Labels: status/approved, status/lgtm

#3494 feat: update pkgs version
  Makefile
Labels: status/approved, status/lgtm

#3497 feat: update pkgs version
  Makefile
Labels: status/approved

#3488 feat: print complete member info in etcd members
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/etcd.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  pkg/machinery/api/machine/machine.pb.go
  website/content/docs/v0.10/Reference/api.md
Labels: status/approved, status/lgtm

#3507 chore: bump dependencies via dependabot
  Dockerfile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#3496 chore: use REGISTRY_MIRROR_FLAGS if defined
  hack/test/e2e.sh
Labels: status/approved, status/lgtm

#3509 release(v0.10.0-beta.1): prepare release
  CHANGELOG.md
  website/content/docs/v0.10/Reference/cli.md
Labels: status/approved

#3491 chore: use codecov from the build container
  .drone.jsonnet
Labels: status/approved, status/lgtm

#3514 fix: check if OVF env is empty
  internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
Labels: status/approved, status/lgtm

#3512 chore: list specifically for enabled regions
  hack/cloud-image-uploader/aws.go
  hack/cloud-image-uploader/main.go
Labels: status/approved, status/lgtm

#3492 chore: refactor Dockerfile for cross-compilation
  .drone.jsonnet
  Dockerfile
  Makefile
  cmd/installer/cmd/image.go
  cmd/installer/cmd/iso.go
  cmd/installer/cmd/root.go
  cmd/installer/pkg/install/install.go
  cmd/installer/pkg/install/manifest.go
  cmd/installer/pkg/ova/ova.go
  internal/app/machined/pkg/runtime/v1alpha1/board/bananapi_m64/bananapi_m64.go
  internal/app/machined/pkg/runtime/v1alpha1/board/libretech_all_h3_cc_h5/libretech_all_h3_cc_h5.go
  internal/app/machined/pkg/runtime/v1alpha1/board/rock64/rock64.go
  internal/app/machined/pkg/runtime/v1alpha1/board/rockpi4/rockpi4.go
  internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/rpi_4.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
  pkg/machinery/constants/constants.go
  pkg/provision/providers/qemu/preflight.go
Labels: status/approved, status/lgtm

#3501 docs: add etcd backup and restore guide
  website/content/docs/v0.10/Guides/disaster-recovery.md
Labels: status/approved, status/lgtm

#3516 fix: update osType in OVA other3xLinux64Guest"
  cmd/installer/pkg/ova/ova.go
Labels: status/approved, status/lgtm

#3506 add WithRegistryCaCert
  pkg/machinery/config/types/v1alpha1/generate/options.go
Labels: status/approved, status/lgtm

#3518 docs: update AWS instructions
  website/content/docs/v0.10/Cloud Platforms/aws.md
  website/content/docs/v0.8/Cloud Platforms/aws.md
  website/content/docs/v0.9/Cloud Platforms/aws.md
Labels: status/approved, status/lgtm

#3520 docs: add survey
  website/content/docs/v0.10/index.md
  website/content/docs/v0.9/index.md
Labels: status/approved, status/lgtm

#3525 release(v0.9.3): prepare release
  CHANGELOG.md
  website/content/docs/v0.9/Reference/cli.md
Labels: status/approved, status/lgtm

#3527 docs: add what's new for Talos 0.10
  website/content/docs/v0.10/Introduction/what-is-new.md
Labels: status/approved, status/lgtm

#3529 docs: update cloud images for Talos v0.9.3
  website/src/data/cloud-images.json
Labels: status/approved, status/lgtm

#3531 release(v0.10.0): prepare release
  CHANGELOG.md
  hack/release.toml
  website/content/docs/v0.10/Reference/cli.md
Labels: status/approved, status/lgtm

#3536 fix: use both self-signed and Kubernetes CA to verify Kubelet cert
  pkg/kubernetes/kubelet/kubelet.go
Labels: status/approved, status/lgtm

#3542 chore: update wgctrl dependecy
  go.mod
  go.sum
Labels: status/approved, status/lgtm

#3540 chore: remove security API ReadFile/WriteFile
  api/security/security.proto
  internal/app/trustd/internal/reg/reg.go
  pkg/machinery/api/security/security.pb.go
  pkg/machinery/api/security/security_grpc.pb.go
  website/content/docs/v0.11/Reference/api.md
Labels: status/approved, status/lgtm

#3553 fix: bump crypto library for the CSR verification fix
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#3554 chore: bump dependencies via dependabot
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
Labels: status/approved, status/lgtm

#3539 feat: add `--config-patch` flag by node type
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/mgmt/config.go
  internal/integration/cli/gen.go
  pkg/machinery/config/types/v1alpha1/bundle/bundle.go
  pkg/machinery/config/types/v1alpha1/bundle/options.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_configurator_bundle.go
  website/content/docs/v0.11/Reference/cli.md
Labels: status/approved, status/lgtm

#3557 chore: remove temporary fork
  go.mod
  go.sum
Labels: status/approved, status/lgtm

#3558 feat: pull kernel with VMware balloon module enabled
  Makefile
Labels: status/approved, status/lgtm

#3559 WIP: add Pine64 SBC support
  Makefile
  internal/app/machined/pkg/runtime/v1alpha1/board/board.go
  internal/app/machined/pkg/runtime/v1alpha1/board/pine64/pine64.go
  pkg/machinery/constants/constants.go
  website/content/docs/v0.11/Single Board Computers/pine64.md
Labels: status/lgtm

#3555 docs: update redirects to Talos 0.10
  website/static/_redirects
Labels: status/approved

#3521 docs: add survey to README
  README.md
  website/content/docs/v0.10/index.md
  website/content/docs/v0.11/index.md
  website/content/docs/v0.6/index.md
  website/content/docs/v0.7/index.md
  website/content/docs/v0.8/index.md
  website/content/docs/v0.9/index.md
Labels: status/approved

#3561 feat: add USB serial drivers
  Makefile
Labels: status/approved

#3560 feat: deterministic builds
  Dockerfile
Labels: status/approved
