Repository siderolabs/talos, pull requests merged in 2021-08, with the labels that each got.

#3987 chore: fix typos
  CHANGELOG.md
  website/content/docs/v0.10/Introduction/what-is-new.md
  website/content/docs/v0.12/Introduction/what-is-new.md
Labels: status/approved, status/lgtm

#3998 feat: remove remnants of bootkube support
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/convert-k8s.go
  cmd/talosctl/cmd/talos/upgrade-k8s.go
  hack/release.toml
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod_test.go
  internal/app/machined/pkg/controllers/k8s/kubelet_static_pod_controller.go
  internal/app/machined/pkg/controllers/k8s/manifest_apply.go
  internal/app/machined/pkg/controllers/v1alpha1/boostrap_status.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/app/machined/pkg/system/services/machined.go
  pkg/cluster/kubernetes/convert.go
  pkg/cluster/kubernetes/daemonset.go
  pkg/cluster/kubernetes/patch.go
  pkg/cluster/kubernetes/self_hosted.go
  pkg/cluster/kubernetes/talos_managed.go
  pkg/cluster/kubernetes/upgrade.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/machine/machine_grpc.pb.go
  pkg/machinery/constants/constants.go
  pkg/resources/v1alpha1/bootstrap_status.go
  pkg/resources/v1alpha1/v1alpha1_test.go
  website/content/docs/v0.12/Guides/converting-control-plane.md
  website/content/docs/v0.12/Reference/api.md
  website/content/docs/v0.12/Reference/cli.md
Labels: status/approved, status/lgtm

#4003 chore: bump dependencies via dependabot
  Dockerfile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  pkg/cluster/sonobuoy/sonobuoy.go
Labels: status/approved, status/lgtm

#4004 feat: update containerd to 1.5.5
  Makefile
  go.mod
  go.sum
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#4006 docs: add disk encryptions examples
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  website/content/docs/v0.12/Reference/configuration.md
Labels: status/approved, status/lgtm

#4007 fix: resolve several issues with Wireguard link specs
  internal/app/machined/pkg/controllers/network/link_merge_test.go
  internal/app/machined/pkg/controllers/network/link_spec.go
  pkg/resources/network/link.go
  pkg/resources/network/link_spec.go
  pkg/resources/network/link_test.go
Labels: status/approved, status/lgtm

#4010 feat: update GRUB to 2.06
  Makefile
Labels: status/approved, status/lgtm

#4013 fix: align partitions with minimal I/O size
  cmd/installer/pkg/install/manifest.go
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#4015 fix: preserve PMBR bootable flag correctly
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#4014 fix: remove admission plugins enabled by default from the list
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
Labels: status/approved, status/lgtm

#4016 fix: preserve PMBR bootable, align partitions with minimal I/O size
  cmd/installer/pkg/install/manifest.go
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#4017 feat: update containerd to 1.5.5, runc to 1.0.1
  Makefile
  go.mod
  go.sum
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#4020 release(v0.11.4): prepare release
  CHANGELOG.md
  hack/release.toml
  website/content/docs/v0.11/Reference/cli.md
Labels: status/approved, status/lgtm

#4021 feat: allow both DHCP and static addressing for the interface
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  website/content/docs/v0.12/Reference/configuration.md
Labels: status/approved, status/lgtm

#4019 feat: add an option to disable PSP
  internal/app/machined/pkg/controllers/config/k8s_control_plane.go
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
  internal/app/machined/pkg/controllers/k8s/manifest.go
  internal/app/machined/pkg/controllers/k8s/manifest_test.go
  internal/app/machined/pkg/controllers/k8s/templates.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_apiserverconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/resources/config/k8s_control_plane.go
  website/content/docs/v0.12/Reference/configuration.md
Labels: status/approved, status/lgtm

#3935 feat: update Kubernetes to v1.22.0
  Makefile
  go.mod
  go.sum
  hack/protoc-lint/go.sum
  hack/test/e2e.sh
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/integration/provision/upgrade.go
  pkg/cluster/kubernetes/talos_managed.go
  pkg/machinery/constants/constants.go
  website/content/docs/v0.12/Reference/cli.md
  website/content/docs/v0.12/Reference/configuration.md
Labels: status/approved, status/lgtm

#4025 chore: workaround GitHub new release notes limit
  .drone.jsonnet
  hack/release.sh
Labels: status/approved, status/lgtm

#4024 chore: use parallel xz with higher compression level
  cmd/installer/cmd/image.go
Labels: status/approved, status/lgtm

#4030 fix: update go-blockdevice
  go.mod
  go.sum
Labels: status/approved, status/lgtm

#4032 fix: update go-blockdevice
  go.mod
  go.sum
Labels: status/approved, status/lgtm

#4042 chore: update PKGS version (512 cpus, new ca-certficates)
  Makefile
Labels: status/approved, status/lgtm

#4023 chore: improve artifacts generation reproducibility
  Dockerfile
  cmd/installer/cmd/image.go
  cmd/installer/pkg/raw.go
Labels: status/approved, status/lgtm

#4045 chore: bump dependencies via dependabot
  Dockerfile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#4027 chore: use vtprotobuf compiled marshaling in Talos API
  .golangci.yml
  Dockerfile
  Makefile
  internal/app/apid/pkg/backend/apid.go
  internal/app/apid/pkg/backend/apid_test.go
  internal/app/machined/pkg/runtime/events.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events.go
  pkg/grpc/factory/factory.go
  pkg/machinery/api/cluster/cluster_vtproto.pb.go
  pkg/machinery/api/common/common_vtproto.pb.go
  pkg/machinery/api/inspect/inspect_vtproto.pb.go
  pkg/machinery/api/machine/machine_vtproto.pb.go
  pkg/machinery/api/network/network_vtproto.pb.go
  pkg/machinery/api/resource/resource_vtproto.pb.go
  pkg/machinery/api/resource/secrets/secrets_vtproto.pb.go
  pkg/machinery/api/security/security_vtproto.pb.go
  pkg/machinery/api/storage/storage_vtproto.pb.go
  pkg/machinery/api/time/time_vtproto.pb.go
  pkg/machinery/client/events.go
  pkg/machinery/proto/codec.go
  pkg/machinery/proto/proto.go
  pkg/resources/secrets/api.go
Labels: status/approved, status/lgtm

#4043 chore: workaround GitHub new release notes limit
  .drone.jsonnet
  hack/release.sh
  hack/release.toml
Labels: status/approved, status/lgtm

#4048 feat: update grub to 2.06, bump max CPUs to 512
  Makefile
Labels: status/approved, status/lgtm

#4044 chore: use etcd client TryLock function on upgrade
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
Labels: status/approved, status/lgtm

#4049 fix: maintenance mode reason message
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/approved, status/lgtm

#4028 feat: bootstrap token limit
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
  internal/app/machined/pkg/controllers/k8s/templates.go
Labels: status/approved, status/lgtm

#4050 release(v0.11.5): prepare release
  CHANGELOG.md
  hack/release.toml
  website/content/docs/v0.11/Reference/cli.md
Labels: status/approved, status/lgtm

#4053 docs: add AMIs for v0.11.5
  website/src/data/cloud-images.json
Labels: status/approved, status/lgtm

#4055 fix: correctly handle nodoc for struct fields
  hack/docgen/main.go
  pkg/machinery/config/encoder/markdown.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  website/content/docs/v0.12/Reference/configuration.md
Labels: status/approved, status/lgtm

#4051 fix: make route resources ID match closer routing table primary key
  internal/app/machined/pkg/controllers/network/address_config.go
  internal/app/machined/pkg/controllers/network/address_merge.go
  internal/app/machined/pkg/controllers/network/operator_spec.go
  internal/app/machined/pkg/controllers/network/route_config.go
  internal/app/machined/pkg/controllers/network/route_config_test.go
  internal/app/machined/pkg/controllers/network/route_merge.go
  internal/app/machined/pkg/controllers/network/route_merge_test.go
  internal/app/machined/pkg/controllers/network/route_status.go
  internal/app/machined/pkg/controllers/network/route_status_test.go
  pkg/resources/network/network.go
Labels: status/approved, status/lgtm

#4058 chore: revert "improve artifacts generation reproducibility"
  Dockerfile
  cmd/installer/cmd/image.go
  cmd/installer/pkg/raw.go
Labels: status/approved, status/lgtm

#3999 feat: implement sysctl controllers
  hack/release.toml
  internal/app/machined/pkg/controllers/runtime/common_test.go
  internal/app/machined/pkg/controllers/runtime/kernel_param_config.go
  internal/app/machined/pkg/controllers/runtime/kernel_param_config_test.go
  internal/app/machined/pkg/controllers/runtime/kernel_param_defaults.go
  internal/app/machined/pkg/controllers/runtime/kernel_param_defaults_test.go
  internal/app/machined/pkg/controllers/runtime/kernel_param_spec.go
  internal/app/machined/pkg/controllers/runtime/kernel_param_spec_test.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/kernel/kernel.go
  pkg/kernel/kspp/kspp.go
  pkg/resources/runtime/condition.go
  pkg/resources/runtime/condition_test.go
  pkg/resources/runtime/kernel_params_spec.go
  pkg/resources/runtime/kernel_params_status.go
  pkg/resources/runtime/kernel_params_test.go
Labels: status/approved, status/lgtm

#4047 chore: use k8s 1.21.3 in CAPI tests for now
  .drone.jsonnet
  hack/test/e2e-capi.sh
  hack/test/e2e-docker.sh
  hack/test/e2e-firecracker.sh
  hack/test/e2e-iso.sh
  hack/test/e2e-qemu.sh
  hack/test/e2e.sh
Labels: status/approved, status/lgtm

#4054 feat: allow multiple addresses per interface
  cmd/talosctl/pkg/mgmt/helpers/wireguard.go
  internal/app/machined/pkg/controllers/network/address_config.go
  internal/app/machined/pkg/controllers/network/address_config_test.go
  internal/app/machined/pkg/controllers/network/link_config_test.go
  internal/app/machined/pkg/controllers/network/route_config_test.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_network_options.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
  pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
  website/content/docs/v0.12/Guides/advanced-networking.md
  website/content/docs/v0.12/Guides/configuring-wireguard-network.md
  website/content/docs/v0.12/Reference/configuration.md
Labels: status/approved, status/lgtm

#4056 fix: match correctly routes on the address family
  internal/app/machined/pkg/controllers/network/route_spec.go
Labels: status/approved, status/lgtm

#4060 fix: move etcd PKI under /system/secrets
  internal/app/machined/pkg/system/services/etcd.go
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#4061 release(v0.12.0-alpha.0): prepare release
  CHANGELOG.md
  hack/release.toml
  website/content/docs/v0.12/Reference/cli.md
Labels: status/approved, status/lgtm

#4059 feat: make ISO builds reproducible
  Dockerfile
  Makefile
  cmd/installer/cmd/iso.go
  cmd/installer/pkg/epoch.go
  cmd/installer/pkg/iso.go
  cmd/installer/pkg/touch.go
Labels: status/approved, status/lgtm

#4064 chore: require GPG signatures
  .conform.yaml
Labels: status/approved

#4062 feat: add new etcd members in learner mode
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/etcd.go
  hack/release.toml
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/system/services/etcd.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/machine/machine_vtproto.pb.go
  website/content/docs/v0.12/Reference/api.md
Labels: status/approved, status/lgtm

#4067 chore: update Go to 1.16.7, Linux to 5.10.57
  Makefile
  hack/release.toml
  pkg/machinery/api/cluster/cluster.pb.go
  pkg/machinery/api/common/common.pb.go
  pkg/machinery/api/inspect/inspect.pb.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/network/network.pb.go
  pkg/machinery/api/resource/resource.pb.go
  pkg/machinery/api/resource/secrets/secrets.pb.go
  pkg/machinery/api/security/security.pb.go
  pkg/machinery/api/storage/storage.pb.go
  pkg/machinery/api/time/time.pb.go
  pkg/machinery/constants/constants.go
Labels: status/approved

#4063 feat: validate if extra fields present in the decoder
  hack/release.toml
  pkg/machinery/config/decoder/decoder.go
  pkg/machinery/config/decoder/decoder_test.go
Labels: status/approved

#4068 fix: enable seccomp default profile by default
  hack/release.toml
  internal/app/machined/pkg/system/runner/containerd/containerd.go
Labels: status/approved

#4069 feat: print uid/gid for the files in `ls -l`
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/list.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/integration/cli/diskusage.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/machine/machine_vtproto.pb.go
  website/content/docs/v0.12/Reference/api.md
Labels: status/approved

#4005 chore: run apid and trustd services as non-root user
  hack/release.toml
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/apid.go
  internal/app/machined/pkg/system/services/machined.go
  internal/app/machined/pkg/system/services/trustd.go
  internal/app/machined/pkg/system/services/utils.go
  internal/pkg/mount/pseudo.go
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#4072 chore: drop deprecated `--no-reboot` param and KernelCurrentRoot const
  cmd/talosctl/cmd/talos/apply-config.go
  pkg/machinery/constants/constants.go
Labels: status/approved

#4073 chore: run etcd as non-root user
  hack/release.toml
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/machined/pkg/system/services/utils.go
  pkg/machinery/constants/constants.go
Labels: status/approved

#4071 feat: add ClusterID and ClusterSecret
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/generate/generate.go
  pkg/machinery/config/types/v1alpha1/generate/generate_test.go
  pkg/machinery/config/types/v1alpha1/generate/init.go
  pkg/machinery/config/types/v1alpha1/generate/options.go
  pkg/machinery/config/types/v1alpha1/generate/worker.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider_test.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/constants/constants.go
  website/content/docs/v0.12/Reference/configuration.md
Labels: status/approved, status/lgtm

#4074 release(v0.12.0-alpha.1): prepare release
  CHANGELOG.md
  website/content/docs/v0.12/Reference/cli.md
Labels: status/approved

#4076 feat: update Linux to 5.10.58 and many pkgs updates
  Makefile
  pkg/machinery/constants/constants.go
Labels: status/approved

#4086 chore: bump dependencies via dependabot
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved

#4075 feat: support for route source addresses in the configuration
  internal/app/machined/pkg/controllers/network/operator/dhcp4.go
  internal/app/machined/pkg/controllers/network/route_config.go
  internal/app/machined/pkg/controllers/network/route_config_test.go
  internal/app/machined/pkg/controllers/network/route_spec.go
  internal/app/machined/pkg/controllers/network/route_spec_test.go
  internal/app/machined/pkg/controllers/network/route_status.go
  internal/app/machined/pkg/controllers/network/route_status_test.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
  pkg/resources/network/route_spec.go
  pkg/resources/network/route_status.go
  website/content/docs/v0.12/Reference/configuration.md
Labels: status/approved

#4087 chore: run e2e-qemu test against Talos with race-detector enabled
  .drone.jsonnet
  Makefile
Labels: status/approved

#4090 chore: update versions to final release tags
  Makefile
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved

#4091 release(v0.12.0-beta.0): prepare release
  CHANGELOG.md
  hack/release.toml
  website/content/docs/v0.12/Reference/cli.md
Labels: status/approved

#4093 docs: ensure azure VMs are 0 indexed
  website/content/docs/v0.11/Cloud Platforms/azure.md
  website/content/docs/v0.12/Cloud Platforms/azure.md
Labels: status/approved

#4095 chore: do not check that go mod tidy gives empty output
  Dockerfile
Labels: status/approved

#4096 fix: make sure file mode is same (reproducibility issue)
  Dockerfile
Labels: status/approved

#4097 fix: don't panic if the machine config doesn't have network (EM)
  internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go
Labels: status/approved

#4089 feat: check if cluster has deprecated resources versions
  cmd/talosctl/cmd/talos/upgrade-k8s.go
  hack/release.toml
  pkg/cluster/kubernetes/daemonset.go
  pkg/cluster/kubernetes/talos_managed.go
  pkg/cluster/kubernetes/upgrade.go
  website/content/docs/v0.12/Guides/upgrading-kubernetes.md
  website/content/docs/v0.12/Reference/cli.md
Labels: status/approved

#4099 fix: extramount should have `yaml:",inline"` tag
  pkg/machinery/config/decoder/decoder_test.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
Labels: status/approved

#4100 test: adapt tests to the cgroupsv2
  internal/app/machined/pkg/system/runner/containerd/containerd.go
  internal/app/machined/pkg/system/runner/containerd/containerd_test.go
  internal/app/machined/pkg/system/runner/process/process.go
  internal/app/machined/pkg/system/runner/process/process_test.go
  internal/app/machined/pkg/system/runner/runner.go
  internal/app/machined/pkg/system/services/containerd.go
  internal/app/machined/pkg/system/services/cri.go
  internal/app/machined/pkg/system/services/udevd.go
  internal/pkg/containers/containerd/containerd_test.go
  internal/pkg/containers/cri/cri_test.go
  internal/pkg/cri/cri_test.go
Labels: status/approved

#4103 fix: don't support cgroups nesting in process runner
  internal/app/machined/pkg/system/runner/process/process.go
Labels: status/approved

#4102 fix: do not set KSPP kernel params in container mode
  internal/app/machined/pkg/controllers/runtime/kernel_param_defaults.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/approved

#4124 chore: bump dependencies
  Dockerfile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/protoc-lint/go.mod
  hack/protoc-lint/go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved

#4104 feat: update Kubernetes to 1.22.1
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/docs/v0.12/Reference/cli.md
  website/content/docs/v0.12/Reference/configuration.md
Labels: status/approved

#4101 docs: add release notes for 0.12, support matrix
  website/content/docs/v0.12/Cloud Platforms/aws.md
  website/content/docs/v0.12/Introduction/support-matrix.md
  website/content/docs/v0.12/Introduction/what-is-new.md
Labels: status/approved

#4110 fix: cgroup delegate
  internal/pkg/mount/cgroups.go
Labels: status/approved

#4128 release(v0.12.0-beta.1): prepare release
  CHANGELOG.md
  website/content/docs/v0.12/Reference/cli.md
Labels: status/approved

#4136 fix: don't allow bootstrap if etcd data directory is not empty
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/etcd.go
Labels: status/approved

#4141 chore: fix arm64 reproducibility issues
  Dockerfile
  Makefile
Labels: status/approved

#4144 fix: properly case the VMware name
  internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
  website/content/docs/v0.12/Introduction/support-matrix.md
Labels: status/approved

#4142 feat: provide first NIC hardware addr as a resource
  Dockerfile
  internal/app/machined/pkg/controllers/network/hardware_addr.go
  internal/app/machined/pkg/controllers/network/hardware_addr_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/resources/network/hardrware_addr.go
  pkg/resources/network/network_test.go
Labels: status/approved, area/kubespan

#4168 feat: add node address filters, filter out k8s addresses for Talos API
  internal/app/machined/pkg/controllers/config/k8s_address_filter.go
  internal/app/machined/pkg/controllers/config/k8s_address_filter_test.go
  internal/app/machined/pkg/controllers/config/k8s_control_plane_test.go
  internal/app/machined/pkg/controllers/network/node_address.go
  internal/app/machined/pkg/controllers/network/node_address_test.go
  internal/app/machined/pkg/controllers/secrets/api.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/resources/k8s/k8s.go
  pkg/resources/network/network_test.go
  pkg/resources/network/node_address.go
  pkg/resources/network/node_address_filter.go
Labels: status/approved, area/kubespan

#4175 fix: ignore error on duplicate for `MountStatus`
  internal/pkg/mount/system.go
Labels: status/approved

#4176 chore: bump dependencies via dependabot
  Dockerfile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
Labels: status/approved

#4165 feat: add subnet filter for etcd address
  internal/app/machined/pkg/system/services/etcd.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_etcdconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
  website/content/docs/v0.13/Reference/configuration.md
Labels: status/approved

#4181 release(v0.12.0): prepare release
  CHANGELOG.md
  hack/release.toml
  website/content/docs/v0.12/Reference/cli.md
Labels: status/approved

#4177 docs: update docs for Talos 0.12 release
  website/content/docs/v0.12/Guides/upgrading-talos.md
  website/content/docs/v0.12/Introduction/support-matrix.md
  website/content/docs/v0.12/Introduction/what-is-new.md
  website/content/docs/v0.13/Introduction/support-matrix.md
  website/gridsome.config.js
Labels: status/approved
