Repository siderolabs/talos, pull requests merged in 2021-06, with the labels that each got.

#3689 ISO installer static ip
  website/content/docs/v0.11/Virtualized Platforms/proxmox.md
  website/static/images/proxmox-guide/maintenance-mode-grub-menu-ip.png
  website/static/images/proxmox-guide/maintenance-mode-grub-menu.png
Labels: status/approved, status/lgtm

#3708 refactor: rename *.Status() to *.TypedSpec() in the resources
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
  internal/app/machined/pkg/controllers/k8s/kubelet_static_pod_controller.go
  internal/app/machined/pkg/controllers/k8s/manifest_apply.go
  internal/app/machined/pkg/controllers/k8s/render_secrets_static_pod.go
  internal/app/machined/pkg/controllers/network/address_config.go
  internal/app/machined/pkg/controllers/network/address_config_test.go
  internal/app/machined/pkg/controllers/network/address_merge.go
  internal/app/machined/pkg/controllers/network/address_merge_test.go
  internal/app/machined/pkg/controllers/network/address_spec.go
  internal/app/machined/pkg/controllers/network/address_spec_test.go
  internal/app/machined/pkg/controllers/network/address_status.go
  internal/app/machined/pkg/controllers/network/link_config.go
  internal/app/machined/pkg/controllers/network/link_config_test.go
  internal/app/machined/pkg/controllers/network/link_merge.go
  internal/app/machined/pkg/controllers/network/link_merge_test.go
  internal/app/machined/pkg/controllers/network/link_spec.go
  internal/app/machined/pkg/controllers/network/link_spec_test.go
  internal/app/machined/pkg/controllers/network/link_status.go
  internal/app/machined/pkg/controllers/network/link_status_test.go
  internal/app/machined/pkg/controllers/network/route_config.go
  internal/app/machined/pkg/controllers/network/route_config_test.go
  internal/app/machined/pkg/controllers/network/route_merge.go
  internal/app/machined/pkg/controllers/network/route_merge_test.go
  internal/app/machined/pkg/controllers/network/route_spec.go
  internal/app/machined/pkg/controllers/network/route_spec_test.go
  internal/app/machined/pkg/controllers/network/route_status.go
  internal/app/machined/pkg/controllers/network/route_status_test.go
  internal/app/machined/pkg/controllers/v1alpha1/boostrap_status.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  pkg/resources/k8s/manifest_status.go
  pkg/resources/k8s/secrets_status.go
  pkg/resources/network/address_spec.go
  pkg/resources/network/address_status.go
  pkg/resources/network/link_spec.go
  pkg/resources/network/link_status.go
  pkg/resources/network/route_spec.go
  pkg/resources/network/route_status.go
  pkg/resources/v1alpha1/bootstrap_status.go
Labels: status/approved, status/lgtm

#3707 fix: use COSI runtime DestroyReady input type
  api/inspect/inspect.proto
  cmd/talosctl/cmd/talos/inspect.go
  go.mod
  go.sum
  internal/app/machined/internal/server/v1alpha1/v1alpha1_inspect.go
  internal/app/machined/pkg/controllers/network/address_merge.go
  internal/app/machined/pkg/controllers/network/link_merge.go
  internal/app/machined/pkg/controllers/network/route_merge.go
  pkg/machinery/api/inspect/inspect.pb.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  website/content/docs/v0.11/Reference/api.md
Labels: status/approved, status/lgtm

#3709 feat: implement NodeAddress controller
  internal/app/machined/pkg/controllers/network/node_address.go
  internal/app/machined/pkg/controllers/network/node_address_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/resources/network/address_status.go
  pkg/resources/network/link_status.go
  pkg/resources/network/network_test.go
  pkg/resources/network/node_address.go
Labels: status/approved, status/lgtm

#3711 feat: parse Talos-specific cmdline params
  internal/app/machined/pkg/controllers/network/cmdline.go
  internal/app/machined/pkg/controllers/network/cmdline_test.go
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#3706 feat: implement CPU and Memory stats controller
  internal/app/machined/pkg/controllers/perf/perf.go
  internal/app/machined/pkg/controllers/perf/perf_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/resources/perf/cpu.go
  pkg/resources/perf/mem.go
  pkg/resources/perf/perf.go
  pkg/resources/perf/perf_test.go
  pkg/resources/secrets/etcd.go
Labels: status/approved, status/lgtm

#3713 feat: default to bootstrap workflow
  cmd/talosctl/cmd/mgmt/config.go
  hack/release.toml
  internal/integration/cli/gen.go
  internal/integration/cli/validate.go
  website/content/docs/v0.11/Bare Metal Platforms/digital-rebar.md
  website/content/docs/v0.11/Bare Metal Platforms/equinix-metal.md
  website/content/docs/v0.11/Bare Metal Platforms/matchbox.md
  website/content/docs/v0.11/Cloud Platforms/aws.md
  website/content/docs/v0.11/Cloud Platforms/azure.md
  website/content/docs/v0.11/Cloud Platforms/digitalocean.md
  website/content/docs/v0.11/Cloud Platforms/gcp.md
  website/content/docs/v0.11/Cloud Platforms/openstack.md
  website/content/docs/v0.11/Guides/configuring-the-cluster-endpoint.md
  website/content/docs/v0.11/Introduction/getting-started.md
  website/content/docs/v0.11/Local Platforms/virtualbox.md
  website/content/docs/v0.11/Virtualized Platforms/proxmox.md
  website/content/docs/v0.11/Virtualized Platforms/vmware.md
Labels: status/approved, status/lgtm

#3716 feat: update COSI runtime and add support for tail in the Talos gRPC
  api/resource/resource.proto
  go.mod
  go.sum
  internal/app/machined/internal/server/v1alpha1/v1alpha1_resource.go
  pkg/machinery/api/resource/resource.pb.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  website/content/docs/v0.11/Reference/api.md
Labels: status/approved, status/lgtm

#3717 fix: drop into maintenance mode if config URL is `none` (metal)
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
Labels: status/approved, status/lgtm

#3715 fix: remove conflicting etcd member on rejoin with empty data directory
  internal/app/machined/pkg/system/services/etcd.go
  internal/integration/api/reset.go
Labels: status/approved, status/lgtm

#3710 docs: update Rpi4 firmware guide
  website/content/docs/v0.11/Single Board Computers/rpi_4.md
Labels: status/lgtm

#3718 feat: implement new controllers for hostname, resolvers and time servers
  internal/app/machined/pkg/controllers/network/hostname_config.go
  internal/app/machined/pkg/controllers/network/hostname_config_test.go
  internal/app/machined/pkg/controllers/network/hostname_merge.go
  internal/app/machined/pkg/controllers/network/hostname_merge_test.go
  internal/app/machined/pkg/controllers/network/hostname_spec.go
  internal/app/machined/pkg/controllers/network/hostname_spec_test.go
  internal/app/machined/pkg/controllers/network/resolver_config.go
  internal/app/machined/pkg/controllers/network/resolver_config_test.go
  internal/app/machined/pkg/controllers/network/resolver_merge.go
  internal/app/machined/pkg/controllers/network/resolver_merge_test.go
  internal/app/machined/pkg/controllers/network/resolver_spec.go
  internal/app/machined/pkg/controllers/network/resolver_spec_test.go
  internal/app/machined/pkg/controllers/network/timeserver_config.go
  internal/app/machined/pkg/controllers/network/timeserver_config_test.go
  internal/app/machined/pkg/controllers/network/timeserver_merge.go
  internal/app/machined/pkg/controllers/network/timeserver_merge_test.go
  internal/app/machined/pkg/controllers/network/timeserver_spec.go
  internal/app/machined/pkg/controllers/network/timeserver_spec_test.go
  internal/app/machined/pkg/controllers/time/sync.go
  internal/app/machined/pkg/controllers/time/sync_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/constants/constants.go
  pkg/resources/network/address_spec.go
  pkg/resources/network/address_status.go
  pkg/resources/network/hostname_spec.go
  pkg/resources/network/hostname_status.go
  pkg/resources/network/link_refresh.go
  pkg/resources/network/link_spec.go
  pkg/resources/network/link_status.go
  pkg/resources/network/network_test.go
  pkg/resources/network/node_address.go
  pkg/resources/network/resolver_spec.go
  pkg/resources/network/resolver_status.go
  pkg/resources/network/route_spec.go
  pkg/resources/network/route_status.go
  pkg/resources/network/timeserver_spec.go
  pkg/resources/network/timeserver_status.go
Labels: status/approved, status/lgtm

#3731 chore: bump dependencies via dependabot
  Dockerfile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
Labels: status/approved, status/lgtm

#3732 chore: use Go 1.16.5
  Makefile
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#3712 feat: implement basic RBAC interceptors
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/mgmt/config.go
  cmd/talosctl/cmd/mgmt/gen/csr.go
  go.mod
  go.sum
  internal/app/apid/main.go
  internal/app/apid/pkg/backend/apid.go
  internal/app/apid/pkg/backend/apid_test.go
  internal/app/apid/pkg/provider/tls.go
  internal/app/machined/pkg/controllers/k8s/templates.go
  internal/app/machined/pkg/system/services/machined.go
  internal/app/maintenance/main.go
  internal/app/trustd/main.go
  pkg/grpc/factory/factory.go
  pkg/grpc/middleware/auth/basic/token.go
  pkg/grpc/middleware/authz/authorizer.go
  pkg/grpc/middleware/authz/authorizer_test.go
  pkg/grpc/middleware/authz/context.go
  pkg/grpc/middleware/authz/injector.go
  pkg/grpc/middleware/authz/metadata.go
  pkg/grpc/proxy/backend/local.go
  pkg/grpc/proxy/backend/local_test.go
  pkg/machinery/config/types/v1alpha1/generate/generate.go
  pkg/machinery/config/types/v1alpha1/generate/generate_test.go
  pkg/machinery/constants/constants.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/machinery/role/role.go
  pkg/machinery/role/role_test.go
  website/content/docs/v0.11/Reference/cli.md
Labels: status/approved, status/lgtm

#3733 Prefer extraConfig over OVF env, skip empty config
  internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
Labels: status/approved, status/lgtm

#3734 feat: implement EtcFileController to render files in `/etc`
  internal/app/machined/pkg/controllers/files/etcfile.go
  internal/app/machined/pkg/controllers/files/etcfile_test.go
  internal/app/machined/pkg/controllers/files/files.go
  internal/app/machined/pkg/controllers/network/etcfile.go
  internal/app/machined/pkg/controllers/network/etcfile_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/resources/files/etcfile_spec.go
  pkg/resources/files/etcfile_status.go
  pkg/resources/files/files.go
  pkg/resources/files/files_test.go
Labels: status/approved, status/lgtm

#3735 feat: add configuration for enabling RBAC
  .gitignore
  Dockerfile
  hack/docgen/go.mod
  hack/docgen/go.sum
  hack/docgen/main.go
  internal/app/machined/pkg/system/services/machined.go
  pkg/grpc/middleware/authz/authorizer.go
  pkg/machinery/config/encoder/documentation.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/registry.go
  pkg/machinery/config/types/v1alpha1/generate/generate_test.go
  pkg/machinery/config/types/v1alpha1/generate/init.go
  pkg/machinery/config/types/v1alpha1/generate/join.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_features.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider_test.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  website/content/docs/v0.11/Reference/configuration.md
Labels: status/approved, status/lgtm

#3738 feat: enable RBAC by default
  internal/app/apid/pkg/backend/apid.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_cluster.go
  pkg/grpc/middleware/authz/context.go
  pkg/grpc/middleware/authz/metadata.go
  pkg/grpc/proxy/backend/local.go
  pkg/machinery/client/context.go
  pkg/machinery/config/types/v1alpha1/generate/generate_test.go
  pkg/machinery/config/types/v1alpha1/generate/init.go
  pkg/machinery/config/types/v1alpha1/generate/join.go
Labels: status/approved, status/lgtm

#3737 feat: implement network.Status resource and controller
  internal/app/machined/pkg/controllers/network/status.go
  internal/app/machined/pkg/controllers/network/status_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/resources/network/condition.go
  pkg/resources/network/condition_test.go
  pkg/resources/network/network_test.go
  pkg/resources/network/status.go
Labels: status/approved, status/lgtm

#3736 feat: bring unconfigured links with link carrier up by default
  internal/app/machined/pkg/controllers/network/link_config.go
  internal/app/machined/pkg/controllers/network/link_config_test.go
Labels: status/approved, status/lgtm

#3739 feat: implement operator framework with DHCP4 as the first example
  internal/app/machined/pkg/controllers/network/address_merge_test.go
  internal/app/machined/pkg/controllers/network/hostname_merge_test.go
  internal/app/machined/pkg/controllers/network/link_merge_test.go
  internal/app/machined/pkg/controllers/network/operator/dhcp4.go
  internal/app/machined/pkg/controllers/network/operator/operator.go
  internal/app/machined/pkg/controllers/network/resolver_merge_test.go
  internal/app/machined/pkg/controllers/network/route_merge_test.go
  internal/app/machined/pkg/controllers/network/timeserver_merge_test.go
  pkg/resources/network/configlayer.go
  pkg/resources/network/configlayer_string.go
Labels: status/approved, status/lgtm

#3740 feat: implement operator configuration controller
  internal/app/machined/pkg/controllers/network/operator_config.go
  internal/app/machined/pkg/controllers/network/operator_config_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/resources/network/network.go
  pkg/resources/network/network_test.go
  pkg/resources/network/operator.go
  pkg/resources/network/operator_spec.go
  pkg/resources/network/operator_string.go
Labels: status/approved, status/lgtm

#3744 chore: expose WatchRequest in the resources client
  pkg/machinery/client/resources.go
Labels: status/approved, status/lgtm

#3742 feat: implement virtual IP (shared IP) network operator
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/network/address_spec.go
  internal/app/machined/pkg/controllers/network/operator/vip.go
  pkg/resources/network/address_spec.go
Labels: status/approved, status/lgtm

#3746 fix: overwrite nodes in the gRPC metadata
  pkg/machinery/client/context.go
Labels: status/approved, status/lgtm

#3748 feat: implement controller which runs network operators
  internal/app/machined/pkg/controllers/network/operator_spec.go
  internal/app/machined/pkg/controllers/network/operator_spec_test.go
Labels: status/approved, status/lgtm

#3749 feat: implement platform config controller (hostnames)
  internal/app/machined/pkg/controllers/network/platform_config.go
Labels: status/approved, status/lgtm

#3758 docs: update community meeting time
  website/content/docs/v0.10/index.md
  website/content/docs/v0.11/index.md
Labels: status/approved, status/lgtm

#3747 fix: do not complain about empty roles
  pkg/machinery/role/role.go
  pkg/machinery/role/role_test.go
Labels: status/approved, status/lgtm

#3763 fix: don't treat ethtool errors as fatal
  internal/app/machined/pkg/controllers/network/link_status.go
Labels: status/approved

#3764 chore: bump dependencies via dependabot
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
Labels: status/approved, status/lgtm

#3766 feat: support NFS 4.1
  Makefile
Labels: status/approved, status/lgtm

#3767 feat: update controller-runtime logs to console level on config.debug
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/system/services/kubelet.go
  pkg/logging/zap.go
Labels: status/approved, status/lgtm

#3768 fix: wait for the network to be ready in mainteancne mode
  internal/app/maintenance/main.go
  pkg/resources/network/hostname_status.go
Labels: status/approved, status/lgtm

#3770 fix: update retry package with a fix for errors.Is
  go.mod
  go.sum
Labels: status/approved, status/lgtm

#3762 fix: separate healthy and unknown flags in the service resource
  internal/app/machined/pkg/controllers/v1alpha1/service.go
  pkg/resources/v1alpha1/service.go
Labels: status/approved, status/lgtm

#3771 fix: update networking stack after Equinix Metal testing
  internal/app/machined/pkg/controllers/network/link_config.go
  internal/app/machined/pkg/controllers/network/link_config_test.go
  internal/app/machined/pkg/controllers/network/link_merge.go
  internal/app/machined/pkg/controllers/network/link_spec.go
  internal/app/machined/pkg/controllers/network/link_spec_test.go
  internal/app/machined/pkg/controllers/network/operator_config.go
  internal/app/machined/pkg/controllers/network/resolver_merge.go
  internal/app/machined/pkg/controllers/network/resolver_spec.go
  internal/app/machined/pkg/controllers/network/route_spec.go
  internal/app/machined/pkg/controllers/network/timeserver_merge.go
  pkg/machinery/nethelpers/routeflag_string_linux.go
  pkg/machinery/nethelpers/routeflags_linux.go
  pkg/resources/network/link_spec.go
Labels: status/approved, status/lgtm

#3769 fix: do not format state partition in the initialize sequence
  .drone.jsonnet
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/pkg/mount/mount.go
  internal/pkg/mount/options.go
  internal/pkg/mount/system.go
Labels: status/approved, status/lgtm

#3772 fix: don't enable RBAC feature in the config for Talos < 0.11
  pkg/machinery/config/contract.go
  pkg/machinery/config/contract_test.go
  pkg/machinery/config/types/v1alpha1/generate/generate.go
  pkg/machinery/config/types/v1alpha1/generate/generate_test.go
  pkg/machinery/config/types/v1alpha1/generate/init.go
  pkg/machinery/config/types/v1alpha1/generate/join.go
Labels: status/approved, status/lgtm

#3774 fix: stop etcd client logs from going to the server console
  internal/pkg/etcd/etcd.go
Labels: status/approved, status/lgtm

#3775 chore: remove bootkube check from cluster health check
  pkg/cluster/check/default.go
Labels: status/approved, status/lgtm

#3779 chore: update RBAC rules, remove old APIs
  Dockerfile
  api/health/health.proto
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/recover.go
  hack/protoc-lint/go.mod
  hack/protoc-lint/go.sum
  hack/protoc-lint/lint.go
  hack/protoc-lint/lint_test.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/system/services/machined.go
  internal/app/machined/pkg/system/services/machined_test.go
  pkg/cluster/kubernetes/convert.go
  pkg/grpc/factory/factory.go
  pkg/grpc/middleware/authz/authorizer.go
  pkg/grpc/middleware/authz/authorizer_test.go
  pkg/machinery/api/health/health.pb.go
  pkg/machinery/api/health/health_grpc.pb.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/machine/machine_grpc.pb.go
  pkg/machinery/client/client.go
  pkg/machinery/role/role.go
  website/content/docs/v0.11/Reference/api.md
  website/content/docs/v0.11/Reference/cli.md
Labels: status/approved, status/lgtm

#3776 feat: provide Kubernetes nodename as a COSI resource
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod_test.go
  internal/app/machined/pkg/controllers/k8s/extra_manifest_test.go
  internal/app/machined/pkg/controllers/k8s/kubelet_static_pod_controller.go
  internal/app/machined/pkg/controllers/k8s/manifest_test.go
  internal/app/machined/pkg/controllers/k8s/nodename.go
  internal/app/machined/pkg/controllers/k8s/nodename_test.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/app/machined/pkg/system/services/kubelet.go
  pkg/kubernetes/kubelet/kubelet.go
  pkg/resources/k8s/condition.go
  pkg/resources/k8s/condition_test.go
  pkg/resources/k8s/k8s_test.go
  pkg/resources/k8s/nodename.go
Labels: status/approved, status/lgtm

#3778 feat: improve security of Kubernetes control plane components
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
  internal/app/machined/pkg/controllers/k8s/render_secrets_static_pod.go
  internal/app/machined/pkg/controllers/secrets/kubernetes.go
  internal/pkg/kubeconfig/admin.go
  internal/pkg/kubeconfig/generate.go
  internal/pkg/kubeconfig/generate_test.go
  pkg/machinery/constants/constants.go
  pkg/resources/secrets/kubernetes.go
Labels: status/approved, status/lgtm

#3780 fix: use localhost API server endpoint for internal communication
  internal/app/machined/pkg/controllers/secrets/kubernetes.go
Labels: status/approved, status/lgtm

#3781 release(v0.11.0-alpha.1): prepare release
  CHANGELOG.md
  hack/release.toml
  website/content/docs/v0.11/Reference/cli.md
Labels: status/approved, status/lgtm

#3750 docs: provide more storage details
  website/content/docs/v0.11/Guides/storage.md
Labels: kind/documentation, size/S, status/approved, status/lgtm

#3785 feat: improve security of Kubernetes control plane components
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
Labels: status/approved, status/lgtm

#3782 chore: bump etcd client libraries to final 3.5.0 release
  go.mod
  go.sum
Labels: status/approved, status/lgtm

#3799 chore: bump dependencies
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/docgen/go.mod
  hack/docgen/go.sum
  hack/test/e2e.sh
  internal/integration/provision/upgrade.go
  pkg/machinery/constants/constants.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  website/content/docs/v0.11/Reference/cli.md
  website/content/docs/v0.11/Reference/configuration.md
Labels: status/approved, status/lgtm

#3800 fix: mark kube-proxy as system critical priority
  internal/app/machined/pkg/controllers/k8s/templates.go
Labels: status/approved, status/lgtm

#3786 fix: build with custom kernel/rootfs
  Dockerfile
  website/content/docs/v0.11/Guides/customizing-the-kernel.md
Labels: status/approved, status/lgtm

#3804 feat: improve security of Kubernetes control plane components
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
Labels: status/approved, status/lgtm

#3802 feat: use COSI RD's sensitivity for RBAC
  go.mod
  go.sum
  internal/app/machined/internal/server/v1alpha1/v1alpha1_resource.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/resources/config/machine_config.go
  pkg/resources/secrets/etcd.go
  pkg/resources/secrets/kubernetes.go
  pkg/resources/secrets/root.go
Labels: status/approved, status/lgtm

#3806 feat: skip overlay mount checks with docker
  cmd/installer/pkg/install/manifest.go
Labels: status/approved, status/lgtm

#3801 feat: update Linux kernel to 5.10.45
  Makefile
  hack/release.toml
  pkg/machinery/constants/constants.go
  website/content/docs/v0.11/Reference/configuration.md
Labels: status/approved, status/lgtm

#3809 release(v0.10.4): prepare release
  CHANGELOG.md
  website/content/docs/v0.10/Reference/cli.md
Labels: status/approved, status/lgtm

#3808 fix: assign source address to the DHCP default gateway routes
  internal/app/machined/pkg/controllers/network/operator/dhcp4.go
Labels: status/approved, status/lgtm

#3813 docs: add AMI IDs for Talos 0.10.4
  website/src/data/cloud-images.json
Labels: status/approved, status/lgtm

#3812 chore: update e2e tests to use latest capi releases
  Makefile
  hack/test/e2e-capi.sh
  hack/test/e2e.sh
Labels: status/approved, status/lgtm

#3815 feat: enable MACVTAP support
  Makefile
Labels: status/approved, status/lgtm

#3810 chore: refactor CLI tests
  internal/integration/base/cli.go
  internal/integration/base/run.go
  internal/integration/cli/config.go
  internal/integration/cli/copy.go
  internal/integration/cli/etcd.go
  internal/integration/cli/gen.go
  internal/integration/cli/kubeconfig.go
  internal/integration/cli/validate.go
Labels: status/approved, status/lgtm

#3814 feat: reimplement apid certificate generation on top of COSI
  Dockerfile
  api/resource/secrets/secrets.proto
  go.mod
  go.sum
  internal/app/apid/main.go
  internal/app/apid/pkg/provider/endpoints.go
  internal/app/apid/pkg/provider/provider.go
  internal/app/apid/pkg/provider/tls.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/controllers/k8s/endpoint.go
  internal/app/machined/pkg/controllers/secrets/api.go
  internal/app/machined/pkg/controllers/secrets/root.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/app/machined/pkg/system/services/apid.go
  pkg/cluster/bootstrap.go
  pkg/grpc/gen/remote.go
  pkg/machinery/api/resource/secrets/secrets.pb.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/constants/constants.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/resources/k8s/endpoint.go
  pkg/resources/k8s/k8s_test.go
  pkg/resources/secrets/api.go
  pkg/resources/secrets/api_test.go
  pkg/resources/secrets/condition.go
  pkg/resources/secrets/root.go
  pkg/resources/secrets/secrets_test.go
Labels: status/approved, status/lgtm

#3819 chore: add an option to launch cluster with bad RTC state
  cmd/talosctl/cmd/mgmt/cluster/create.go
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/qemu/node.go
  pkg/provision/request.go
  website/content/docs/v0.11/Reference/cli.md
Labels: status/approved, status/lgtm

#3777 Separate etcd certificates
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/k8s/render_secrets_static_pod.go
  internal/app/machined/pkg/controllers/secrets/etcd.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/pkg/etcd/certs.go
  internal/pkg/etcd/etcd.go
  pkg/machinery/constants/constants.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/resources/secrets/etcd.go
Labels: status/approved, status/lgtm

#3820 feat: add cloud images to releases
  .drone.jsonnet
  hack/cloud-image-uploader/main.go
Labels: status/approved

#3821 feat: add created and updated timestamps to the resource metadata
  api/resource/resource.proto
  go.mod
  go.sum
  internal/app/machined/internal/server/v1alpha1/v1alpha1_resource.go
  pkg/machinery/api/resource/resource.pb.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  website/content/docs/v0.11/Reference/api.md
Labels: status/approved, status/lgtm

#3824 fix: replace tabs with spaces in console output
  go.mod
  go.sum
Labels: status/approved, status/lgtm

#3823 fix: revert back resource.proto order
  api/resource/resource.proto
  pkg/machinery/api/resource/resource.pb.go
Labels: status/approved, status/lgtm

#3822 release(v0.11.0-alpha.2): prepare release
  CHANGELOG.md
  website/content/docs/v0.11/Reference/cli.md
Labels: status/approved, status/lgtm

#3826 feat: remove go-runner in staticpods
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
Labels: status/approved, status/lgtm

#3829 chore: use tagged versions of bldr dependencies for 0.11
  Makefile
Labels: status/approved, status/lgtm

#3833 chore: bump Talos Go modules to release versions
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#3830 chore: update coredns to 1.8.4
  internal/app/machined/pkg/controllers/k8s/templates.go
  pkg/machinery/constants/constants.go
  website/content/docs/v0.11/Reference/configuration.md
Labels: status/approved, status/lgtm

#3832 chore: bump go.mod dependencies, fix netaddr API changes
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/network/address_config.go
  internal/app/machined/pkg/controllers/network/address_spec.go
  internal/app/machined/pkg/controllers/network/address_spec_test.go
  internal/app/machined/pkg/controllers/network/address_status.go
  internal/app/machined/pkg/controllers/network/cmdline.go
  internal/app/machined/pkg/controllers/network/node_address.go
  internal/app/machined/pkg/controllers/network/operator/vip.go
  internal/app/machined/pkg/controllers/network/route_config.go
  internal/app/machined/pkg/controllers/network/route_spec.go
  internal/app/machined/pkg/controllers/network/route_spec_test.go
  internal/app/machined/pkg/controllers/network/route_status.go
  internal/app/machined/pkg/controllers/network/route_status_test.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/resources/network/link.go
  pkg/resources/network/route_spec.go
Labels: status/approved, status/lgtm

#3834 feat: add a method to get gRPC connection from the client
  pkg/machinery/client/client.go
Labels: status/approved, status/lgtm

#3839 fix: ignore EINVAL on `unmount` operations
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/approved, status/lgtm

#3838 fix: limit apid access to COSI runtime resources
  go.mod
  go.sum
  internal/app/machined/pkg/system/services/apid.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#3827 chore: small RBAC improvements
  Makefile
  cmd/talosctl/cmd/talos/config.go
  internal/app/apid/pkg/backend/apid.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_cluster.go
  internal/app/machined/pkg/system/services/machined.go
  internal/app/machined/pkg/system/services/machined_test.go
  internal/integration/base/cli.go
  internal/integration/base/run.go
  internal/integration/cli/config.go
  internal/integration/cli/copy.go
  internal/integration/cli/diskusage.go
  internal/integration/cli/gen.go
  internal/integration/cli/health.go
  internal/integration/cli/kubeconfig.go
  internal/integration/cli/patch.go
  internal/integration/cli/read.go
  pkg/grpc/middleware/authz/authorizer.go
  pkg/grpc/middleware/authz/authorizer_test.go
  pkg/grpc/middleware/authz/metadata.go
  pkg/grpc/proxy/backend/local.go
  pkg/machinery/client/client.go
Labels: status/approved, status/lgtm

#3842 chore: add CAPI version to CI setup
  hack/test/e2e-capi.sh
Labels: status/approved, status/lgtm

#3853 chore: bump go.mod dependencies
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#3845 fix: documentation typos
  docs/proposals/20190704-AutomatedUpgrades.md
  website/content/docs/v0.10/Learn More/architecture.md
  website/content/docs/v0.11/Learn More/architecture.md
  website/content/docs/v0.8/Learn More/architecture.md
  website/content/docs/v0.9/Learn More/architecture.md
Labels: status/approved, status/lgtm

#3854 feat: add RBAC to `talosctl version` output
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/version.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/integration/cli/config.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/version/version.go
  website/content/docs/v0.11/Reference/api.md
Labels: status/approved, status/lgtm

#3857 fix: don't set bond delay options if miimon is not enabled
  internal/app/machined/pkg/controllers/network/link_spec_test.go
  pkg/resources/network/link.go
Labels: status/approved, status/lgtm

#3858 release(v0.11.0-beta.0): prepare release
  CHANGELOG.md
  hack/release.toml
  website/content/docs/v0.11/Reference/cli.md
Labels: status/approved, status/lgtm

#3855 chore: fix tests for disabled RBAC
  cmd/talosctl/cmd/talos/version.go
  internal/integration/cli/config.go
Labels: status/approved, status/lgtm

#3862 fix: issue worker apid certs properly on renewal
  internal/app/machined/pkg/controllers/secrets/api.go
  pkg/grpc/gen/remote.go
Labels: status/approved, status/lgtm

#3864 release(v0.11.0-beta.1): prepare release
  CHANGELOG.md
  website/content/docs/v0.11/Reference/cli.md
Labels: status/approved, status/lgtm

#3867 fix: don't print git sha of the release twice in the dashboard
  cmd/talosctl/cmd/talos/dashboard/components/topline.go
Labels: status/approved, status/lgtm

#3865 fix: ignore deadline exceeded errors on bootstrap
  pkg/cluster/bootstrap.go
Labels: status/approved, status/lgtm

#3868 fix: restart the merge controllers on conflict
  internal/app/machined/pkg/controllers/network/address_merge.go
  internal/app/machined/pkg/controllers/network/link_merge.go
  internal/app/machined/pkg/controllers/network/route_merge.go
Labels: status/approved, status/lgtm
