Repository siderolabs/talos, pull requests merged in 2021-03, with the labels that each got.

#3230 feat: update etcd to 3.4.15
  pkg/machinery/constants/constants.go
  website/content/docs/v0.9/Reference/configuration.md
Labels: status/approved, status/lgtm

#3231 chore: bump dependencies via dependabot
  Dockerfile
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#3220 feat: implement etcd remove-member cli command
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/etcd.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/pkg/etcd/etcd.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/client/client.go
  website/content/docs/v0.9/Reference/api.md
  website/content/docs/v0.9/Reference/cli.md
Labels: status/approved, status/lgtm

#3232 fix: add ApplyDynamicConfig call in the apply-config --immediate mode
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  pkg/machinery/config/types/v1alpha1/bundle/bundle.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider_test.go
Labels: status/approved, status/lgtm

#3233 fix: update in-cluster kubeconfig validity to match other certs
  internal/app/machined/pkg/controllers/secrets/kubernetes.go
  internal/integration/api/events.go
  pkg/resources/secrets/etcd.go
  pkg/resources/secrets/kubernetes.go
  pkg/resources/secrets/root.go
Labels: status/approved, status/lgtm

#3235 release(v0.9.0-alpha.3): prepare release
  CHANGELOG.md
  website/content/docs/v0.9/Reference/cli.md
Labels: status/approved, status/lgtm

#3182 docs: add disk encryption guide
  website/content/docs/v0.9/Guides/disk-encryption.md
Labels: status/approved, status/lgtm

#3239 docs: bump v0.8 release version in the SBCs guides
  website/content/docs/v0.8/Single Board Computers/bananapi_m64.md
  website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
  website/content/docs/v0.8/Single Board Computers/rock64.md
  website/content/docs/v0.8/Single Board Computers/rpi_4.md
Labels: status/approved, status/lgtm

#3236 chore: update provision/upgrade tests to 0.9.0-alpha.3
  Makefile
  internal/integration/provision/upgrade.go
  pkg/provision/providers/qemu/node.go
Labels: status/approved, status/lgtm

#3237 fix: move etcd to `cri` containerd runner
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/pkg/containers/image/image.go
Labels: status/approved, status/lgtm

#3241 feat: update linux kernel to 5.10.19
  Makefile
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#3242 fix: ignore 'ENOENT' (no such file directory) on mount
  internal/pkg/mount/mount.go
Labels: status/approved, status/lgtm

#3244 release(v0.9.0-alpha.4): prepare release
  CHANGELOG.md
  website/content/docs/v0.9/Reference/cli.md
Labels: status/approved, status/lgtm

#3240 feat: rename namespaces, resources, types etc.
  cmd/talosctl/cmd/talos/apply-config.go
  cmd/talosctl/cmd/talos/edit.go
  cmd/talosctl/cmd/talos/output/table.go
  cmd/talosctl/cmd/talos/patch.go
  go.mod
  go.sum
  internal/app/machined/internal/server/v1alpha1/v1alpha1_resource.go
  internal/app/machined/pkg/controllers/config/k8s_control_plane.go
  internal/app/machined/pkg/controllers/config/k8s_control_plane_test.go
  internal/app/machined/pkg/controllers/config/machine_type.go
  internal/app/machined/pkg/controllers/secrets/etcd.go
  internal/app/machined/pkg/controllers/secrets/kubernetes.go
  internal/app/machined/pkg/controllers/secrets/root.go
  internal/app/machined/pkg/controllers/v1alpha1/time_sync.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/integration/cli/patch.go
  pkg/cluster/kubernetes/convert.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/resources/config/config.go
  pkg/resources/config/config_test.go
  pkg/resources/config/k8s_control_plane.go
  pkg/resources/config/machine_config.go
  pkg/resources/config/machine_type.go
  pkg/resources/k8s/k8s.go
  pkg/resources/k8s/k8s_test.go
  pkg/resources/k8s/manifest.go
  pkg/resources/k8s/manifest_status.go
  pkg/resources/k8s/secrets_status.go
  pkg/resources/k8s/static_pod.go
  pkg/resources/k8s/static_pod_status.go
  pkg/resources/secrets/etcd.go
  pkg/resources/secrets/kubernetes.go
  pkg/resources/secrets/root.go
  pkg/resources/secrets/secrets_test.go
  pkg/resources/v1alpha1/bootstrap_status.go
  pkg/resources/v1alpha1/service.go
  pkg/resources/v1alpha1/time_status.go
  pkg/resources/v1alpha1/time_sync.go
  pkg/resources/v1alpha1/v1alpha1.go
  pkg/resources/v1alpha1/v1alpha1_test.go
  website/content/docs/v0.9/Reference/cli.md
Labels: status/approved, status/lgtm

#3243 chore: properly propagate context object in the controller
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/main.go
  internal/app/machined/pkg/runtime/controller.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller_test.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  pkg/kubernetes/kubernetes.go
Labels: status/approved

#3246 feat: support JSON output in `talosctl get`, event types
  cmd/talosctl/cmd/talos/output/json.go
  cmd/talosctl/cmd/talos/output/output.go
  cmd/talosctl/cmd/talos/output/yaml.go
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#3245 chore: bump Go module dependencies
  go.mod
  go.sum
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/provision/providers/docker/docker.go
  pkg/provision/providers/docker/node.go
Labels: status/approved, status/lgtm

#3248 feat: add `--on-reboot` flag to talosctl edit/patch machineConfig
  cmd/talosctl/cmd/talos/edit.go
  cmd/talosctl/cmd/talos/patch.go
  website/content/docs/v0.9/Reference/cli.md
Labels: status/approved, status/lgtm

#3247 feat: bypass lock if ACPI reboot/shutdown issued
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/main.go
  internal/app/machined/pkg/runtime/controller.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
Labels: status/approved

#3250 release(v0.9.0-alpha.5): prepare release
  CHANGELOG.md
  website/content/docs/v0.9/Reference/cli.md
Labels: status/approved, status/lgtm

#3252 fix: chmod etcd PKI path to fix virtual IP for upgrades with persistence
  internal/app/machined/pkg/system/services/networkd.go
Labels: status/approved, status/lgtm

#3251 chore: fix upgrade tests by bumping 0.9 to alpha.5
  Makefile
  internal/integration/provision/upgrade.go
Labels: status/approved, status/lgtm

#3253 chore: expire objects in CI S3 bucket
  .drone.jsonnet
Labels: status/approved, status/lgtm

#3259 fix: align partition start to the physical sector size
  go.mod
  go.sum
Labels: status/approved, status/lgtm

#3258 fix: ignore connection refused errors when updating/converting cp
  pkg/cluster/kubernetes/convert.go
  pkg/cluster/kubernetes/kubernetes.go
  pkg/cluster/kubernetes/self_hosted.go
  pkg/cluster/kubernetes/talos_managed.go
Labels: status/approved, status/lgtm

#3260 chore: update tools/pkgs/extras tags
  Makefile
Labels: status/approved, status/lgtm

#3262 feat: update containerd to version 1.4.4
  Makefile
  go.mod
  go.sum
  pkg/machinery/constants/constants.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#3263 fix: properly propagate nameservers to provisioned docker clusters
  pkg/provision/providers/docker/docker.go
Labels: status/approved, status/lgtm

#3261 fix: mkdir source of the extra mounts for the kubelet
  cmd/talosctl/cmd/mgmt/cluster/create.go
  internal/app/machined/pkg/system/services/kubelet.go
  pkg/machinery/config/types/v1alpha1/bundle/bundle.go
  pkg/machinery/config/types/v1alpha1/bundle/options.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_configurator_bundle.go
  website/content/docs/v0.9/Reference/cli.md
Labels: status/approved, status/lgtm

#3273 chore: bump dependencies via dependabot
  Dockerfile
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
Labels: status/approved, status/lgtm

#3249 docs: document controller runtime, resources and talosctl get
  website/content/docs/v0.9/Learn More/controllers-resources.md
  website/static/images/controller-dependencies-with-resources.png
  website/static/images/controller-dependencies.png
Labels: status/approved, status/lgtm

#3277 docs: update Kubernetes upgrade guide
  website/content/docs/v0.9/Guides/upgrading-kubernetes.md
Labels: status/approved, status/lgtm

#3275 docs: add troubleshooting control plane documentation
  website/content/docs/v0.9/Guides/troubleshooting-control-plane.md
Labels: status/approved, status/lgtm

#3278 docs: add control plane conversion guide and 0.9 upgrade notes
  website/content/docs/v0.9/Guides/converting-control-plane.md
  website/content/docs/v0.9/Guides/upgrading-talos.md
  website/content/docs/v0.9/Learn More/upgrades.md
Labels: status/approved, status/lgtm

#3279 docs: add highlights for 0.9 release
  website/content/docs/v0.9/Introduction/what-is-new.md
Labels: status/approved, status/lgtm

#3276 release(v0.9.0-beta.0): prepare release
  CHANGELOG.md
  website/content/docs/v0.9/Reference/cli.md
Labels: status/approved, status/lgtm

#3281 chore: update website npm dependencies
  website/package-lock.json
Labels: status/approved, status/lgtm

#3280 docs: add guide on editing machine configuration
  website/content/docs/v0.9/Guides/editing-machine-configuration.md
Labels: status/approved, status/lgtm

#3282 docs: add video for raspberry pi install
  website/content/docs/v0.9/Single Board Computers/rpi_4.md
Labels: status/approved

#3286 docs: fix links in the documentation
  website/content/docs/v0.9/Bare Metal Platforms/digital-rebar.md
  website/content/docs/v0.9/Guides/air-gapped.md
  website/content/docs/v0.9/Guides/configuring-pull-through-cache.md
  website/content/docs/v0.9/Guides/configuring-the-cluster-endpoint.md
  website/content/docs/v0.9/Guides/configuring-wireguard-network.md
  website/content/docs/v0.9/Guides/editing-machine-configuration.md
  website/content/docs/v0.9/Introduction/what-is-new.md
  website/content/docs/v0.9/Learn More/components.md
Labels: status/approved, status/lgtm

#3285 chore: bump Go to 1.16.1
  Makefile
Labels: status/approved, status/lgtm

#3290 docs: add guide for VIP
  website/content/docs/v0.9/Guides/vip.md
  website/content/docs/v0.9/Introduction/what-is-new.md
Labels: status/lgtm

#3287 fix: update output of `convert-k8s` command
  cmd/talosctl/cmd/talos/convert-k8s.go
  pkg/cluster/kubernetes/convert.go
  website/content/docs/v0.9/Guides/converting-control-plane.md
Labels: status/approved, status/lgtm

#3283 fix: move containerd CRI config files under `/var/`
  internal/pkg/containers/cri/containerd/config_test.go
  internal/pkg/containers/cri/containerd/containerd.go
Labels: status/approved, status/lgtm

#3284 chore: update Go to 1.15.9
  Makefile
Labels: status/approved, status/lgtm

#3225 docs: rewrite getting-started for ISO
  pkg/machinery/constants/constants.go
  website/content/docs/v0.9/Introduction/getting-started.md
  website/content/docs/v0.9/Reference/kernel.md
Labels: status/approved, status/lgtm

#3257 feat: add Rock pi 4 support
  Makefile
  internal/app/machined/pkg/runtime/v1alpha1/board/board.go
  internal/app/machined/pkg/runtime/v1alpha1/board/rockpi4/rockpi4.go
  pkg/machinery/constants/constants.go
  website/content/docs/v0.9/Single Board Computers/rockpi_4.md
Labels: status/approved, status/lgtm

#3292 refactor: provide explicit logger for networkd
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/networkd/main.go
  internal/app/networkd/pkg/address/address.go
  internal/app/networkd/pkg/address/dhcp4.go
  internal/app/networkd/pkg/address/dhcp6.go
  internal/app/networkd/pkg/address/static.go
  internal/app/networkd/pkg/networkd/misc.go
  internal/app/networkd/pkg/networkd/netconf.go
  internal/app/networkd/pkg/networkd/netconf_test.go
  internal/app/networkd/pkg/networkd/networkd.go
  internal/app/networkd/pkg/networkd/networkd_test.go
  internal/app/networkd/pkg/nic/nic.go
  internal/app/networkd/pkg/reg/reg.go
  internal/app/networkd/pkg/reg/reg_test.go
  internal/app/networkd/pkg/vip/vip.go
Labels: status/approved, status/lgtm

#3293 chore: fix provision tests after changes to build-container
  Makefile
  hack/test/provision-tests.sh
  internal/integration/integration_test.go
  internal/integration/provision/provision.go
  internal/integration/provision/upgrade.go
Labels: status/approved, status/lgtm

#3294 docs: minor fixes to getting started
  website/content/docs/v0.9/Introduction/getting-started.md
Labels: status/lgtm

#3303 chore: update dependencies via dependabot
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#3304 chore: update Linux to 5.10.23
  Makefile
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#3307 chore: update Linux to 5.10.23
  Makefile
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#3305 fix: don't touch any partitions on upgrade with --preserve
  cmd/installer/pkg/install/manifest.go
  cmd/installer/pkg/install/manifest_test.go
  cmd/installer/pkg/install/target.go
  pkg/machinery/constants/constants.go
Labels: status/approved, status/lgtm

#3308 release(v0.8.5): prepare release
  CHANGELOG.md
  website/content/docs/v0.8/Reference/cli.md
Labels: status/approved

#3309 test: update aws cloud provider version
  hack/test/e2e-aws.sh
Labels: status/approved, status/lgtm

#3310 fix: properly format spec comments in the resources
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#3256 chore: update tools, use new generators
  Dockerfile
  Makefile
  internal/app/machined/internal/server/v1alpha1/v1alpha1_inspect.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_resource.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/maintenance/server/server.go
  internal/app/networkd/pkg/reg/reg.go
  internal/app/storaged/server.go
  internal/app/timed/pkg/reg/reg.go
  internal/app/trustd/internal/reg/reg.go
  pkg/machinery/api/cluster/cluster.pb.go
  pkg/machinery/api/cluster/cluster_grpc.pb.go
  pkg/machinery/api/common/common.pb.go
  pkg/machinery/api/health/health.pb.go
  pkg/machinery/api/health/health_grpc.pb.go
  pkg/machinery/api/inspect/inspect.pb.go
  pkg/machinery/api/inspect/inspect_grpc.pb.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/machine/machine_grpc.pb.go
  pkg/machinery/api/network/network.pb.go
  pkg/machinery/api/network/network_grpc.pb.go
  pkg/machinery/api/resource/resource.pb.go
  pkg/machinery/api/resource/resource_grpc.pb.go
  pkg/machinery/api/security/security.pb.go
  pkg/machinery/api/security/security_grpc.pb.go
  pkg/machinery/api/storage/storage.pb.go
  pkg/machinery/api/storage/storage_grpc.pb.go
  pkg/machinery/api/time/time.pb.go
  pkg/machinery/api/time/time_grpc.pb.go
  prototool.yaml
Labels: status/approved, status/lgtm

#3315 fix: talosctl health should not check kube-proxy when it is disabled
  pkg/cluster/check/default.go
  pkg/cluster/check/kubernetes.go
  pkg/cluster/check/reporter.go
  pkg/conditions/conditions.go
  pkg/conditions/poll.go
  pkg/conditions/poll_test.go
Labels: status/approved, status/lgtm

#3291 chore: use Go 1.16 language version
  Dockerfile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  pkg/machinery/go.mod
Labels: status/approved, status/lgtm

#3316 backport: fix: talosctl health should not check kube-proxy when it is disabled
  pkg/cluster/check/default.go
  pkg/cluster/check/kubernetes.go
  pkg/cluster/check/reporter.go
  pkg/conditions/conditions.go
  pkg/conditions/poll.go
  pkg/conditions/poll_test.go
Labels: status/approved, status/lgtm

#3313 chore: use new release tool for changelogs and release notes
  hack/release.sh
  hack/release.toml
Labels: status/approved, status/lgtm

#3317 release(v0.10.0-alpha.0): prepare release
  CHANGELOG.md
  hack/release.sh
  website/content/docs/v0.9/Reference/cli.md
Labels: status/approved, status/lgtm

#3295 docs: add control plane in-depth guide
  website/content/docs/v0.9/Guides/converting-control-plane.md
  website/content/docs/v0.9/Guides/upgrading-kubernetes.md
  website/content/docs/v0.9/Guides/vip.md
  website/content/docs/v0.9/Learn More/control-plane.md
  website/content/docs/v0.9/Learn More/controllers-resources.md
  website/content/docs/v0.9/Learn More/faqs.md
Labels: status/approved, status/lgtm

#3320 release(v0.9.0-beta.1): prepare release
  CHANGELOG.md
  hack/release.sh
  hack/release.toml
  website/content/docs/v0.9/Reference/cli.md
Labels: status/approved, status/lgtm

#3322 chore: remove unused code
  pkg/endianness/endianness.go
  pkg/endianness/endianness_test.go
  pkg/serde/serde.go
  pkg/serde/serde_test.go
Labels: status/approved, status/lgtm

#3325 feat: publish talosctl container image
  Dockerfile
  Makefile
Labels: status/approved, status/lgtm

#3326 feat: update Kubernetes to 1.20.5
  Makefile
  go.mod
  go.sum
  hack/test/e2e.sh
  internal/integration/provision/upgrade.go
  pkg/machinery/constants/constants.go
  website/content/docs/v0.9/Guides/editing-machine-configuration.md
  website/content/docs/v0.9/Introduction/what-is-new.md
  website/content/docs/v0.9/Reference/cli.md
  website/content/docs/v0.9/Reference/configuration.md
Labels: status/approved, status/lgtm

#3330 chore: fix `make help` output
  Makefile
Labels: status/approved, status/lgtm

#3331 chore: remove old `osctl` reference
  cmd/talosctl/cmd/completion.go
  website/content/docs/v0.9/Reference/cli.md
Labels: status/approved, status/lgtm

#3066 chore: add script for starting registry proxies
  hack/start-registry-proxies.sh
Labels: status/approved, status/lgtm

#3334 fix: upgrade-k8s bug with empty config values and provision script
  internal/integration/provision/upgrade.go
  pkg/cluster/kubernetes/talos_managed.go
Labels: status/approved, status/lgtm

#3332 backport: chore: remove old `osctl` reference
  cmd/talosctl/cmd/completion.go
  website/content/docs/v0.9/Reference/cli.md
Labels: status/approved, status/lgtm

#3333 fix: build rockpi4 metal image as part of CI build
  Makefile
Labels: status/approved, status/lgtm

#3321 fix: repair zsh completion
  cmd/talosctl/cmd/completion.go
Labels: status/approved, status/lgtm

#3341 fix: `etcd remove-member` removes etcd data directory
  internal/pkg/etcd/etcd.go
Labels: status/approved, status/lgtm

#3344 backport: fix: command `etcd remove-member` shouldn't remove etcd data directory
  internal/pkg/etcd/etcd.go
Labels: status/approved, status/lgtm

#3346 release(v0.9.0): prepare release
  CHANGELOG.md
  hack/release.toml
  website/content/docs/v0.9/Reference/cli.md
Labels: status/approved, status/lgtm

#3348 docs: make v0.9 the default docs
  website/gridsome.config.js
  website/static/_redirects
Labels: status/approved, status/lgtm

#3349 docs: add AMIs for Talos 0.9.0
  website/src/data/cloud-images.json
Labels: status/approved, status/lgtm

#3342 chore: bump dependencies via dependabot
  Dockerfile
  Makefile
  cmd/talosctl/cmd/talos/service.go
  cmd/talosctl/cmd/talos/time.go
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  internal/app/machined/pkg/system/events/events.go
  internal/app/machined/pkg/system/health/status.go
  internal/app/timed/pkg/reg/reg.go
  pkg/machinery/api/cluster/cluster.pb.go
  pkg/machinery/api/common/common.pb.go
  pkg/machinery/api/health/health.pb.go
  pkg/machinery/api/inspect/inspect.pb.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/network/network.pb.go
  pkg/machinery/api/resource/resource.pb.go
  pkg/machinery/api/security/security.pb.go
  pkg/machinery/api/storage/storage.pb.go
  pkg/machinery/api/time/time.pb.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#3353 chore: update sonobuoy
  Makefile
Labels: status/approved, status/lgtm

#3350 refactor: run networkd as a goroutine in machined
  Dockerfile
  internal/app/machined/pkg/system/services/networkd.go
  internal/app/networkd/main.go
Labels: status/approved, status/lgtm

#3351 refactor: move apid, routerd, timed and trustd to single executable
  Dockerfile
  hack/release.toml
  internal/app/apid/main.go
  internal/app/machined/main.go
  internal/app/machined/pkg/system/runner/containerd/containerd.go
  internal/app/machined/pkg/system/runner/containerd/containerd_test.go
  internal/app/machined/pkg/system/services/apid.go
  internal/app/machined/pkg/system/services/routerd.go
  internal/app/machined/pkg/system/services/timed.go
  internal/app/machined/pkg/system/services/trustd.go
  internal/app/routerd/main.go
  internal/app/timed/main.go
  internal/app/trustd/main.go
  internal/integration/cli/containers.go
  internal/pkg/containers/containerd/containerd.go
Labels: status/approved, status/lgtm

#3335 feat: add ability to find disk by disk properties
  api/storage/storage.proto
  cmd/talosctl/cmd/mgmt/validate.go
  cmd/talosctl/cmd/talos/disks.go
  go.mod
  go.sum
  hack/docgen/main.go
  hack/release.toml
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/maintenance/server/server.go
  internal/app/routerd/main.go
  internal/app/storaged/server.go
  internal/integration/api/generate-config.go
  internal/integration/cli/disk.go
  pkg/machinery/api/storage/storage.pb.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/config/validation.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  website/content/docs/v0.10/Reference/api.md
  website/content/docs/v0.10/Reference/cli.md
  website/content/docs/v0.10/Reference/configuration.md
Labels: status/approved, status/lgtm

#3355 refactor: move networkd, timed APIs to machined, remove routerd
  .conform.yaml
  Dockerfile
  internal/app/apid/main.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_time.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_time_test.go
  internal/app/machined/main.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/apid.go
  internal/app/machined/pkg/system/services/routerd.go
  internal/app/machined/pkg/system/services/routerd_test.go
  internal/app/maintenance/server/server.go
  internal/app/networkd/main.go
  internal/app/networkd/pkg/networkd/devices.go
  internal/app/networkd/pkg/reg/reg.go
  internal/app/networkd/pkg/reg/reg_test.go
  internal/app/networkd/pkg/server/server.go
  internal/app/networkd/pkg/server/server_test.go
  internal/app/routerd/main.go
  internal/app/routerd/pkg/director/director.go
  internal/app/routerd/pkg/director/director_test.go
  internal/app/routerd/pkg/director/mocks_test.go
  internal/app/timed/main.go
  internal/app/timed/pkg/reg/reg.go
  internal/integration/cli/services.go
  internal/integration/cli/stats.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/constants/constants.go
  website/content/docs/v0.10/Learn More/components.md
Labels: status/approved, status/lgtm

#3358 docs: update path for kernel downloads in qemu docs
  website/content/docs/v0.10/Local Platforms/qemu.md
  website/content/docs/v0.7/Local Platforms/qemu.md
  website/content/docs/v0.8/Local Platforms/qemu.md
  website/content/docs/v0.9/Local Platforms/qemu.md
Labels: status/approved, status/lgtm

#3359 fix: allow empty list for CNI URLs
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
Labels: status/approved, status/lgtm, status/needs-cherry-pick

#3362 fix: CNI config validation should apply to cp nodes, encryption config
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
Labels: status/approved, status/lgtm

#3364 fix: resolve the issue with DHCP lease not being renewed
  internal/app/networkd/pkg/address/dhcp4.go
Labels: status/approved, status/lgtm

#3363 chore: cache go modules in the build
  Dockerfile
  hack/golang/test.sh
Labels: status/approved, status/lgtm

#3365 feat: show short options in talosctl kubeconfig
  cmd/talosctl/cmd/talos/kubeconfig.go
Labels: status/approved

#3368 chore: remove unused module replace directives
  go.mod
  go.sum
Labels: status/approved, status/lgtm

#3367 fix: resolve the issue with DHCP lease not being renewed
  internal/app/networkd/pkg/address/dhcp4.go
Labels: status/approved, status/lgtm

#3370 chore: remove old file
  hack/test/run.sh
Labels: status/approved, status/lgtm

#3369 docs: update AWS docs to ensure instances are tagged
  website/content/docs/v0.10/Cloud Platforms/aws.md
  website/content/docs/v0.6/Cloud Platforms/aws.md
  website/content/docs/v0.7/Cloud Platforms/aws.md
  website/content/docs/v0.8/Cloud Platforms/aws.md
  website/content/docs/v0.9/Cloud Platforms/aws.md
Labels: status/approved

#3366 fix: resolve the issue with DHCP lease not being renewed
  internal/app/networkd/pkg/address/dhcp.go
Labels: status/approved, status/lgtm

#3371 fix: resolve the issue with Kubernetes upgrade
  go.mod
  pkg/cluster/kubernetes/self_hosted.go
  pkg/cluster/kubernetes/talos_managed.go
  pkg/cluster/kubernetes/upgrade.go
  pkg/cluster/kubernetes/upgrade_test.go
Labels: status/approved, status/lgtm

#3373 chore: tweak nolintlint settings
  .golangci.yml
  cmd/talosctl/cmd/talos/convert-k8s.go
  internal/app/networkd/pkg/server/server.go
  pkg/cluster/kubernetes/talos_managed.go
Labels: status/approved, status/lgtm

#3374 fix: allow `convert-k8s --remove-initialized-keys` with K8s cp is down
  cmd/talosctl/cmd/talos/convert-k8s.go
  pkg/cluster/kubernetes/convert.go
Labels: status/approved, status/lgtm

#3375 chore: fix typo
  Dockerfile
Labels: status/approved, status/lgtm

#3379 chore: build integration tests with -race
  Dockerfile
  internal/integration/api/logs.go
Labels: status/approved, status/lgtm

#3383 fix: prevent panic in validate config if `machine.install` is missing
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
Labels: status/approved, status/lgtm

#3381 fix: get rid of data race in encoder and fix concurrent map access
  internal/pkg/mount/system.go
  pkg/machinery/config/encoder/documentation.go
  pkg/machinery/config/encoder/encoder_test.go
  pkg/machinery/config/encoder/markdown.go
Labels: status/approved, status/lgtm

#3390 chore: refactor: extract ClusterConfig
  .golangci.yml
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_apiserverconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_controllermanagerconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_etcdconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider_test.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_proxyconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_schedulerconfig.go
Labels: status/approved, status/lgtm

#3391 chore: bump dependencies via dependabot
  Dockerfile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/approved, status/lgtm

#3392 test: add unit-test for machine config validation
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
Labels: status/approved, status/lgtm

#3395 fix: workaround race in containerd runner with stdin pipe
  internal/app/machined/pkg/system/runner/containerd/containerd.go
Labels: status/approved, status/lgtm

#3389 fix: get rid of data race in encoder and fix concurrent map access
  internal/pkg/mount/system.go
  pkg/machinery/config/encoder/documentation.go
  pkg/machinery/config/encoder/encoder_test.go
  pkg/machinery/config/encoder/markdown.go
Labels: status/approved, status/lgtm

#3385 feat: add ability to disable comments in talosctl gen config
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/mgmt/config.go
  pkg/machinery/config/encoder/documentation.go
  pkg/machinery/config/encoder/encoder.go
  pkg/machinery/config/encoder/encoder_test.go
  pkg/machinery/config/encoder/markdown.go
  pkg/machinery/config/encoder/options.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_configurator_bundle.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  website/content/docs/v0.10/Cloud Platforms/aws.md
  website/content/docs/v0.10/Reference/cli.md
Labels: status/approved, status/lgtm

#3357 feat: update Kubernetes to 1.21.0-rc.0
  Makefile
  go.mod
  go.sum
  hack/test/e2e.sh
  internal/integration/provision/upgrade.go
  pkg/machinery/constants/constants.go
  website/content/docs/v0.10/Reference/cli.md
  website/content/docs/v0.10/Reference/configuration.md
Labels: status/approved, status/lgtm

#3393 fix: don't write to config object on access
  pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_etcdconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_network_options.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
Labels: status/approved, status/lgtm

#3399 fix: address several issues in TUI installer
  internal/pkg/tui/components/form.go
  internal/pkg/tui/installer/state.go
Labels: status/approved, status/lgtm

#3400 test: fix apply-config integration test, bump clusterctl version
  Makefile
  internal/integration/api/apply-config.go
Labels: status/approved, status/lgtm

#3401 test: fix data race in apply config tests
  internal/integration/api/apply-config.go
Labels: status/approved, status/lgtm

#3394 chore: build components with race detector enabled in dev mode
  Dockerfile
  Makefile
Labels: status/approved, status/lgtm

#3402 release(v0.10.0-alpha.1): prepare release
  CHANGELOG.md
  website/content/docs/v0.10/Reference/cli.md
Labels: status/approved
