Repository siderolabs/talos, pull requests merged in 2021-12, with the labels that each got.

#4624 docs: fix GCP docs
  website/content/docs/v0.14/Cloud Platforms/gcp.md
  website/content/docs/v0.14/Cloud Platforms/gcp/config.yaml
Labels: status/approved

#4622 docs: expand logging documentation
  website/content/docs/v0.14/Guides/logging.md
Labels: status/approved

#4625 feat: support MTU for VLAN's
  internal/app/machined/pkg/controllers/network/link_config.go
  internal/app/machined/pkg/controllers/network/link_config_test.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  website/content/docs/v0.14/Reference/configuration.md
Labels: status/approved

#4635 docs: fix typos
  website/content/docs/v0.13/Virtualized Platforms/proxmox.md
  website/content/docs/v0.14/Virtualized Platforms/proxmox.md
Labels: status/approved

#4630 feat: update Flannel to 0.15.1
  Makefile
  hack/release.toml
  pkg/images/list.go
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/vm/network.go
Labels: status/approved

#4633 feat: VIP for VLANs
  hack/release.toml
  internal/app/machined/pkg/controllers/network/operator_config.go
  internal/app/machined/pkg/controllers/network/operator_config_test.go
  internal/app/machined/pkg/system/services/kubelet.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider_test.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
  website/content/docs/v0.14/Reference/configuration.md
Labels: status/approved

#4627 feat: add powercycle mode in reboot
  api/api.descriptors
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/reboot.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/integration/api/etcd.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/machine/machine_grpc.pb.go
  pkg/machinery/api/machine/machine_vtproto.pb.go
  pkg/machinery/client/client.go
  website/content/docs/v0.14/Reference/api.md
  website/content/docs/v0.14/Reference/cli.md
Labels: status/approved

#4553 feat: can disable controller-manager and scheduler
  internal/app/machined/pkg/controllers/config/k8s_control_plane.go
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod_test.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
  pkg/machinery/resources/config/k8s_control_plane.go
  website/content/docs/v0.14/Reference/configuration.md
Labels: status/approved

#4639 feat: update Linux to 5.15.6
  Makefile
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test

#4641 feat: split installer and imager images
  .drone.jsonnet
  Dockerfile
  Makefile
  hack/release.toml
Labels: status/ok-to-test

#4631 test: uplift capi versions and templates
  hack/test/e2e-capi.sh
  hack/test/e2e-gcp.sh
Labels: status/approved

#4636 feat: allow overriding KSPP kernel parameters
  internal/app/machined/pkg/controllers/runtime/kernel_param_defaults.go
  internal/app/machined/pkg/controllers/runtime/kernel_param_defaults_test.go
  internal/app/machined/pkg/controllers/runtime/kernel_param_spec.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/integration/cli/support.go
  pkg/machinery/resources/runtime/kernel_params_spec.go
Labels: status/ok-to-test

#4643 chore: update Go to 1.17.4
  Makefile
  hack/release.sh
  hack/release.toml
Labels: status/ok-to-test

#4649 chore: drop unused package
  go.mod
  go.sum
  pkg/provision/internal/vmlinuz/vmlinuz.go
Labels: status/ok-to-test

#4651 test: bump Talos versions in upgrade tests
  Makefile
  internal/integration/provision/upgrade.go
Labels: status/ok-to-test

#4652 feat: update deps and Kubernetes to 1.23.0-rc.1
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  website/content/docs/v0.14/Guides/logging.md
  website/content/docs/v0.14/Reference/cli.md
  website/content/docs/v0.14/Reference/configuration.md
Labels: status/ok-to-test

#4644 docs: improve clarity for users
  cmd/talosctl/cmd/talos/get.go
  website/content/docs/v0.14/Introduction/getting-started.md
  website/content/docs/v0.14/Reference/cli.md
Labels: kind/documentation, size/S, status/ok-to-test

#4653 fix: drop unpacked layers from containerd image store
  hack/cri-containerd.toml
  internal/pkg/containers/image/image.go
  pkg/cli/formatters.go
Labels: status/ok-to-test

#4645 fix: tmpfs default permissions
  internal/pkg/mount/pseudo.go
Labels: status/ok-to-test

#4659 chore: bump tools/pkgs/extra to final released versions
  Makefile
Labels: status/ok-to-test

#4632 feat: autocomplete nodes, context and resource definitions
  cmd/talosctl/cmd/root.go
  cmd/talosctl/cmd/talos/config.go
  cmd/talosctl/cmd/talos/get.go
  cmd/talosctl/cmd/talos/output/output.go
  cmd/talosctl/cmd/talos/support.go
  website/content/docs/v0.14/Reference/cli.md
Labels: status/approved

#4658 fix: increase boot and etcd join timeouts
  internal/app/machined/pkg/system/services/etcd.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test

#4661 docs: vlan VIP
  website/content/docs/v0.14/Guides/vip.md
Labels: status/ok-to-test

#4657 fix: relax validation for wireguard endpoints
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
Labels: status/ok-to-test

#4660 chore: remove boot-{arch}.tar.gz artifact
  .drone.jsonnet
  Makefile
  website/content/docs/v0.14/Introduction/getting-started.md
Labels: status/ok-to-test

#4642 fix: make `apply-config` work reliably in any Talos state
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
Labels: status/ok-to-test

#4663 release(v0.14.0-beta.0): prepare release
  .conform.yaml
  CHANGELOG.md
  go.mod
  hack/release.toml
  website/content/docs/v0.14/Reference/cli.md
Labels: status/ok-to-test

#4667 feat: update Kubernetes to 1.23.0
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/docs/v0.14/Reference/cli.md
  website/content/docs/v0.14/Reference/configuration.md
Labels: status/ok-to-test

#4668 docs: document `ip=` kernel argument
  website/content/docs/v0.14/Reference/kernel.md
Labels: status/ok-to-test

#4673 chore: update Go to 1.17.5
  Makefile
  hack/release.toml
Labels: status/ok-to-test

#4671 fix: cleanup affiliates
  internal/app/machined/pkg/controllers/cluster/cluster.go
  internal/app/machined/pkg/controllers/cluster/discovery_service.go
  internal/app/machined/pkg/controllers/cluster/discovery_service_test.go
  internal/app/machined/pkg/controllers/cluster/kubernetes_pull.go
Labels: status/ok-to-test

#4674 fix: use default time servers in time API if none are configured
  internal/app/machined/internal/server/v1alpha1/v1alpha1_time.go
  internal/integration/cli/time.go
Labels: status/ok-to-test

#4675 fix: allow kubelet to be started via the API
  internal/app/machined/pkg/system/services/kubelet.go
  pkg/machinery/resources/k8s/condition.go
  pkg/machinery/resources/k8s/condition_test.go
Labels: status/ok-to-test

#4681 release(v0.14.0-beta.1): prepare release
  CHANGELOG.md
  go.mod
  website/content/docs/v0.14/Reference/cli.md
Labels: status/ok-to-test

#4683 fix: update DHCP library with the panic fix
  go.mod
  go.sum
Labels: status/ok-to-test

#4676 test: update capi templates to v1beta1
  Makefile
  hack/test/e2e-aws.sh
  hack/test/e2e-capi.sh
  hack/test/e2e-gcp.sh
Labels: status/ok-to-test

#4689 chore: remove govalidator library
  go.mod
  go.sum
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test

#4691 refactor: use updated go-blockdevice library with allocation fixes
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test

#4695 refactor: rewrite the check for unknown keys in the machine configuration
  pkg/machinery/config/decoder/decoder.go
  pkg/machinery/config/decoder/decoder_test.go
  pkg/machinery/config/decoder/testdata/controlplane.yaml
  pkg/machinery/config/decoder/testdata/worker.yaml
  pkg/machinery/config/decoder/unknown_keys.go
Labels: status/ok-to-test

#4698 docs: add cilium guide
  internal/integration/api/generate-config.go
  internal/pkg/tui/installer/state.go
  pkg/machinery/config/configloader/testdata/controlplane.test
  pkg/machinery/config/configloader/testdata/worker.test
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  website/content/docs/v0.14/Guides/deploying-cilium.md
  website/content/docs/v0.14/Reference/configuration.md
Labels: status/ok-to-test

#4699 feat: update Kubernetes to 1.23.1
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/docs/v0.14/Reference/cli.md
  website/content/docs/v0.14/Reference/configuration.md
Labels: status/ok-to-test

#4697 refactor: rewrite the implementation of Processes API
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/pkg/miniprocfs/miniprocfs.go
  internal/pkg/miniprocfs/processes.go
  internal/pkg/miniprocfs/processes_test.go
  internal/pkg/miniprocfs/testdata/1920080/cmdline
  internal/pkg/miniprocfs/testdata/1920080/comm
  internal/pkg/miniprocfs/testdata/1920080/exe
  internal/pkg/miniprocfs/testdata/1920080/stat
  internal/pkg/miniprocfs/testdata/3731034/cmdline
  internal/pkg/miniprocfs/testdata/3731034/comm
  internal/pkg/miniprocfs/testdata/3731034/exe
  internal/pkg/miniprocfs/testdata/3731034/stat
  internal/pkg/miniprocfs/testdata/keys
  internal/pkg/miniprocfs/testdata/kmsg
Labels: status/ok-to-test

#4701 feat: show human-readable aliases in `talosctl get rd`
  cmd/talosctl/cmd/talos/get.go
  cmd/talosctl/cmd/talos/output/table.go
  go.mod
  go.sum
  internal/app/resources/server.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/machinery/resources/runtime/kernel_params_status.go
  pkg/machinery/resources/runtime/mount_status.go
  website/content/docs/v0.14/Reference/cli.md
Labels: status/ok-to-test

#4702 test: retry `talosctl time` call in the tests
  internal/integration/base/run.go
  internal/integration/cli/time.go
  internal/pkg/miniprocfs/testdata/1920080/exe
  internal/pkg/miniprocfs/testdata/3731034/exe
Labels: status/ok-to-test

#4706 fix: config apply immediate
  go.mod
  go.sum
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test

#4711 chore: bump Go dependencies
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  internal/app/apid/main.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_time_test.go
  internal/app/machined/pkg/controllers/runtime/events_sink.go
  internal/app/machined/pkg/controllers/siderolink/manager.go
  internal/pkg/cri/client.go
  pkg/cluster/local.go
  pkg/grpc/proxy/backend/local.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test

#4713 release(v0.14.0): prepare release
  CHANGELOG.md
  go.mod
  hack/release.toml
  website/content/docs/v0.14/Reference/cli.md
Labels: status/ok-to-test

#4715 docs: update documentation for 0.14.0 release
  website/content/docs/v0.14/Introduction/support-matrix.md
  website/content/docs/v0.14/Introduction/what-is-new.md
  website/gridsome.config.js
  website/static/_redirects
Labels: status/ok-to-test

#4717 fix: pass path to conformance retrieve results
  pkg/cluster/sonobuoy/product.go
  pkg/cluster/sonobuoy/sonobuoy.go
Labels: status/ok-to-test

#4705 Add arm64 option to talosctl download docs
  website/content/docs/v0.13/Introduction/getting-started.md
  website/content/docs/v0.13/Introduction/quickstart.md
  website/content/docs/v0.14/Introduction/getting-started.md
  website/content/docs/v0.14/Introduction/quickstart.md
  website/content/docs/v0.15/Introduction/getting-started.md
  website/content/docs/v0.15/Introduction/quickstart.md
Labels: status/ok-to-test

#4718 test: attempt number on two on proper retries in CLI time tests
  internal/integration/base/cli.go
  internal/integration/base/run.go
Labels: status/ok-to-test, status/ok-to-merge

#4730 feat: output IPs when etcd needs to be bootstrapped
  internal/app/machined/pkg/system/services/etcd.go
Labels: status/ok-to-test, status/ok-to-merge

#4728 feat: shell completion for `list`, `read`
  cmd/talosctl/cmd/talos/list.go
  cmd/talosctl/cmd/talos/read.go
  cmd/talosctl/cmd/talos/root.go
Labels: status/ok-to-test, status/ok-to-merge

#4731 docs: update Mayastor deployment process
  website/content/docs/v0.14/Guides/storage.md
  website/content/docs/v0.15/Guides/storage.md
Labels: status/ok-to-test, status/ok-to-merge

#4733 feat: remove `ApplyDynamicConfig`
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider_test.go
Labels: status/ok-to-test, status/ok-to-merge

#4735 feat: update Linux to 5.15.11
  Makefile
  hack/release.toml
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#4738 docs: fix troubleshooting guide
  website/content/docs/v0.12/Guides/troubleshooting-control-plane.md
  website/content/docs/v0.13/Guides/troubleshooting-control-plane.md
  website/content/docs/v0.14/Guides/troubleshooting-control-plane.md
  website/content/docs/v0.15/Guides/troubleshooting-control-plane.md
Labels: status/ok-to-test, status/ok-to-merge

#4737 test: don't build all images in the default CI pipeline
  .drone.jsonnet
  Makefile
Labels: status/ok-to-test, status/ok-to-merge

#4739 fix: multiple usability fixes
  cmd/talosctl/cmd/talos/read.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/controllers/runtime/kernel_module_spec.go
Labels: status/ok-to-test, status/ok-to-merge

#4742 fix: kexec on RPI4
  Makefile
  internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/config.txt
  internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/rpi_4.go
Labels: status/ok-to-test, status/ok-to-merge

#4743 chore: remove unused methods in AWS platform
  go.mod
  go.sum
  internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
Labels: status/ok-to-test, status/ok-to-merge

#4746 test: retry in discovery tests
  internal/app/machined/pkg/controllers/runtime/kernel_module_spec.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/integration/api/discovery.go
Labels: status/ok-to-test, status/ok-to-merge

#4744 feat: use official Go SDK to fetch GCP instance metadata
  go.mod
  internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp_test.go
Labels: status/ok-to-test, status/ok-to-merge

#4736 feat: make machine configuration read-only in Talos (almost)
  cmd/talosctl/cmd/talos/edit.go
  cmd/talosctl/pkg/mgmt/helpers/wireguard.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/hcloud.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/upcloud/upcloud.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
  internal/integration/api/apply-config.go
  pkg/cluster/kubernetes/detect.go
  pkg/cluster/kubernetes/kubelet.go
  pkg/cluster/kubernetes/patch.go
  pkg/machinery/config/configloader/configloader.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_configurator_bundle.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_readonly_provider.go
  pkg/machinery/resources/config/machine_config.go
  pkg/machinery/resources/config/machine_config_test.go
  pkg/provision/providers/docker/node.go
  pkg/provision/providers/qemu/node.go
Labels: status/ok-to-test, status/ok-to-merge

#4747 refactor: use AWS SDK to access AWS metadata service
  go.mod
  go.sum
  internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
Labels: status/ok-to-test, status/ok-to-merge

#4734 feat: introduce `talos.experimental.wipe` kernel param to wipe system disk
  hack/release.toml
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  pkg/machinery/constants/constants.go
  website/content/docs/v0.15/Guides/resetting-a-machine.md
  website/content/docs/v0.15/Reference/kernel.md
Labels: status/ok-to-test, status/ok-to-merge

#4749 release(v0.15.0-alpha.0): prepare release
  .conform.yaml
  CHANGELOG.md
  api/api.descriptors
  api/machine/machine.proto
  go.mod
  hack/release.toml
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/config/types/v1alpha1/machine/machine_test.go
  website/content/docs/v0.15/Reference/api.md
  website/content/docs/v0.15/Reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#4751 chore: fix release pipeline
  .drone.jsonnet
Labels: status/ok-to-test, status/ok-to-merge

#4750 chore: bump dependencies
  Dockerfile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  internal/app/machined/pkg/controllers/kubespan/routing_rules.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#4752 fix: ignore missing init.yaml for cluster create
  pkg/machinery/config/types/v1alpha1/bundle/bundle.go
Labels: status/ok-to-test, status/ok-to-merge
