Repository siderolabs/talos, pull requests merged in 2024-07, with the labels that each got.

#8950 feat: add support for configuring vlan filtering on the bridge
  api/resource/definitions/network/network.proto
  hack/release.toml
  internal/app/machined/pkg/adapters/network/bridge_master_spec.go
  internal/app/machined/pkg/adapters/network/bridge_master_spec_test.go
  internal/app/machined/pkg/controllers/network/link_config_test.go
  internal/app/machined/pkg/controllers/network/link_spec_test.go
  internal/app/machined/pkg/controllers/network/network.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/network/network_vtproto.pb.go
  pkg/machinery/config/config/machine.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/resources/network/link.go
  website/content/v1.8/reference/api.md
  website/content/v1.8/reference/configuration/v1alpha1/config.md
  website/content/v1.8/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge

#8956 chore: bump dependencies
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/docgen/go.mod
  hack/docgen/go.sum
  hack/gotagsrewrite/go.mod
  hack/gotagsrewrite/go.sum
  hack/structprotogen/go.mod
  hack/structprotogen/go.sum
  internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/metadata.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/provision/providers/docker/network.go
Labels: status/ok-to-test, status/ok-to-merge

#8902 docs: clarify direct access needed to nodes in insecure mode
  website/content/_index.html
  website/content/v1.8/introduction/getting-started.md
Labels: status/ok-to-test, status/ok-to-merge

#8957 feat: update Kubernetes to v1.30.2
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/v1.8/reference/cli.md
  website/content/v1.8/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#8948 Update deploying cilium docs for v1.7 and v1.8
  website/content/v1.7/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.8/kubernetes-guides/network/deploying-cilium.md
Labels: status/ok-to-merge

#8960 feat: update Linux to 6.6.36
  Makefile
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#8953 docs: update opengraph image for main landing pages
  website/config.toml
  website/content/_index.html
  website/content/v1.7/_index.md
  website/content/v1.8/_index.md
  website/static/images/talos-dev-banner.png
Labels: status/ok-to-test, status/ok-to-merge

#8964 chore: update pkgs/tools/extras
  .github/workflows/lock.yaml
  .github/workflows/stale.yaml
  Makefile
  api/api.descriptors
  cmd/installer/pkg/install/errata.go
  cmd/installer/pkg/install/manifest.go
  hack/release.toml
  internal/app/machined/pkg/controllers/block/disks.go
  pkg/machinery/api/cluster/cluster.pb.go
  pkg/machinery/api/cluster/cluster_grpc.pb.go
  pkg/machinery/api/common/common.pb.go
  pkg/machinery/api/inspect/inspect.pb.go
  pkg/machinery/api/inspect/inspect_grpc.pb.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/machine/machine_grpc.pb.go
  pkg/machinery/api/resource/config/config.pb.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/cluster/cluster.pb.go
  pkg/machinery/api/resource/definitions/cri/cri.pb.go
  pkg/machinery/api/resource/definitions/enums/enums.pb.go
  pkg/machinery/api/resource/definitions/etcd/etcd.pb.go
  pkg/machinery/api/resource/definitions/extensions/extensions.pb.go
  pkg/machinery/api/resource/definitions/files/files.pb.go
  pkg/machinery/api/resource/definitions/hardware/hardware.pb.go
  pkg/machinery/api/resource/definitions/k8s/k8s.pb.go
  pkg/machinery/api/resource/definitions/kubeaccess/kubeaccess.pb.go
  pkg/machinery/api/resource/definitions/kubespan/kubespan.pb.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/perf/perf.pb.go
  pkg/machinery/api/resource/definitions/proto/proto.pb.go
  pkg/machinery/api/resource/definitions/runtime/runtime.pb.go
  pkg/machinery/api/resource/definitions/secrets/secrets.pb.go
  pkg/machinery/api/resource/definitions/siderolink/siderolink.pb.go
  pkg/machinery/api/resource/definitions/time/time.pb.go
  pkg/machinery/api/resource/definitions/v1alpha1/v1alpha1.pb.go
  pkg/machinery/api/resource/network/device_config.pb.go
  pkg/machinery/api/security/security.pb.go
  pkg/machinery/api/security/security_grpc.pb.go
  pkg/machinery/api/storage/storage.pb.go
  pkg/machinery/api/storage/storage_grpc.pb.go
  pkg/machinery/api/time/time.pb.go
  pkg/machinery/api/time/time_grpc.pb.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/extras
  pkg/machinery/gendata/data/pkgs
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/amd64/snp.efi
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/arm64/snp.efi
Labels: status/ok-to-test, status/ok-to-merge

#8966 chore(ci): fix parallel runs of tf pipelines
  hack/test/e2e-cloud-tf.sh
Labels: status/ok-to-test, status/ok-to-merge, integration/aws, integration/aws-nvidia-oss

#8962 chore: support version with and without `v` prefix
  pkg/machinery/config/contract.go
  pkg/machinery/config/contract_test.go
Labels: status/ok-to-test, status/ok-to-merge

#8974 chore: update hydrophone library
  go.mod
  go.sum
  pkg/cluster/hydrophone/hydrophone.go
Labels: status/ok-to-test, status/ok-to-merge

#8967 feat: suppress controller runtime first N failures on the console
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/pkg/ntp/ntp.go
  pkg/logging/error_suppress.go
  pkg/logging/error_suppress_test.go
  pkg/logging/zap.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#8976 chore: improve link spec controller code
  go.mod
  go.sum
  hack/docgen/go.sum
  internal/app/machined/pkg/controllers/network/link_spec.go
  internal/app/machined/pkg/controllers/network/link_spec_test.go
  internal/app/machined/pkg/controllers/network/nftables_chain.go
  internal/app/storaged/server.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#8979 test: fix the integrtion tests for apply-config
  Dockerfile
  go.mod
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
  internal/integration/api/apply-config.go
  pkg/machinery/config/configdiff/configdiff.go
  pkg/machinery/config/configdiff/configdiff_test.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#8975 release(v1.8.0-alpha.1): prepare release
  .conform.yaml
  .github/workflows/ci.yaml
  .kres.yaml
  CHANGELOG.md
  Makefile
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.8/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#8980 fix: properly output multi-doc machine config in `get mc`
  cmd/talosctl/cmd/talos/edit.go
  cmd/talosctl/cmd/talos/output/json.go
  cmd/talosctl/cmd/talos/output/table.go
  cmd/talosctl/cmd/talos/output/yaml.go
Labels: status/ok-to-test, status/ok-to-merge

#8981 chore: redo EncodeString and EncodeBytes using buffer interface
  pkg/machinery/config/container/container.go
Labels: status/ok-to-test, status/ok-to-merge

#8990 docs: add not about mayastor nvme_tcp init container check
  website/content/v1.8/kubernetes-guides/configuration/storage.md
Labels: status/ok-to-merge

#8994 feat: update Kubernetes to 1.31.0-alpha.3
  Makefile
  go.mod
  go.sum
  go.work
  hack/release.toml
  hack/test/e2e.sh
  internal/app/machined/pkg/controllers/k8s/control_plane.go
  internal/app/machined/pkg/controllers/k8s/control_plane_test.go
  internal/app/machined/pkg/controllers/kubeaccess/serviceaccount/crd_controller.go
  pkg/kubernetes/version.go
  pkg/kubernetes/version_test.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_proxyconfig.go
  pkg/machinery/constants/constants.go
  pkg/machinery/go.mod
  website/content/v1.8/_index.md
  website/content/v1.8/reference/cli.md
  website/content/v1.8/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge, integration/provision

#8999 chore: bump deps
  go.mod
  go.sum
  internal/app/apid/main.go
  internal/app/apid/pkg/backend/apid.go
  pkg/grpc/proxy/backend/local.go
  pkg/machinery/client/connection.go
Labels: status/ok-to-test, status/ok-to-merge

#8998 chore: redo FilterMessages as generic function
  pkg/machinery/client/client.go
  pkg/machinery/client/inspect.go
  pkg/machinery/client/reply.go
  pkg/machinery/client/reply_test.go
Labels: status/ok-to-test, status/ok-to-merge, integration/misc, integration/qemu, integration/cilium, integration/aws

#9001 fix: remove host bind mount for `/tmp` for trustd
  internal/app/machined/pkg/system/services/trustd.go
Labels: status/ok-to-test, status/ok-to-merge

#8997 doc: add missing backslashes
  website/content/v1.7/talos-guides/install/cloud-platforms/gcp.md
  website/content/v1.8/talos-guides/install/cloud-platforms/gcp.md
Labels: status/ok-to-test, status/ok-to-merge

#9006 fix: change the UEFI firmware search path order
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/integration/base/api.go
  pkg/provision/providers/qemu/arch.go
Labels: status/ok-to-test, status/ok-to-merge

#9005 feat: provide an option to enforce SecureBoot for TPM enrollment
  cmd/talosctl/cmd/mgmt/cluster/create.go
  internal/pkg/encryption/keys/keys.go
  internal/pkg/encryption/keys/tpm2.go
  pkg/machinery/config/config/machine.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  website/content/v1.8/reference/configuration/v1alpha1/config.md
  website/content/v1.8/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge, integration/trusted-boot

#9010 fix: sort ports and merge adjacent ones in the nft rule
  internal/app/machined/pkg/adapters/network/nftables_rule.go
  internal/app/machined/pkg/adapters/network/nftables_rule_test.go
  internal/app/machined/pkg/controllers/network/nftables_chain_test.go
Labels: status/ok-to-test, status/ok-to-merge, integration/cilium, integration/misc-0

#9002 feat: provide machine config document to update trusted CA roots
  Dockerfile
  Makefile
  cmd/talosctl/cmd/docs.go
  hack/release.toml
  internal/app/machined/pkg/controllers/secrets/data/ca-certificates
  internal/app/machined/pkg/controllers/secrets/trusted_roots.go
  internal/app/machined/pkg/controllers/secrets/trusted_roots_test.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/integration/api/trusted-roots.go
  internal/integration/integration_test.go
  pkg/machinery/config/config/config.go
  pkg/machinery/config/config/security.go
  pkg/machinery/config/container/container.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/security/deep_copy.generated.go
  pkg/machinery/config/types/security/security.go
  pkg/machinery/config/types/security/security_doc.go
  pkg/machinery/config/types/security/testdata/trustedrootsconfig.yaml
  pkg/machinery/config/types/security/trusted_roots.go
  pkg/machinery/config/types/security/trusted_roots_test.go
  pkg/machinery/config/types/types.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
  website/content/v1.8/reference/configuration/security/_index.md
  website/content/v1.8/reference/configuration/security/trustedrootsconfig.md
  website/content/v1.8/schemas/config.schema.json
  website/content/v1.8/talos-guides/configuration/certificate-authorities.md
Labels: status/ok-to-test, status/ok-to-merge

#9015 docs: fix talosctl spelling
  website/content/v1.7/talos-guides/configuration/editing-machine-configuration.md
  website/content/v1.8/talos-guides/configuration/editing-machine-configuration.md
Labels: status/ok-to-merge

#9016 feat: add label 'exclude-from-external-load-balancers' for cp nodes
  hack/release.toml
  pkg/machinery/config/contract.go
  pkg/machinery/config/contract_test.go
  pkg/machinery/config/generate/init.go
  pkg/machinery/config/types/v1alpha1/testdata/stability/v1.8/base-controlplane.yaml
  pkg/machinery/config/types/v1alpha1/testdata/stability/v1.8/overrides-controlplane.yaml
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#9018 fix: fix log format in cluster provisioning
  pkg/provision/providers/qemu/preflight.go
Labels: status/ok-to-test, status/ok-to-merge

#9020 chore: reduce memory requirement for contrplane nodes
  pkg/minimal/limits.go
Labels: status/ok-to-test, status/ok-to-merge

#9024 fix: panic on shutdown
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
Labels: status/ok-to-test, status/ok-to-merge

#9019 fix: be more smart when merging DNS resolver config
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/network/link_spec.go
  internal/app/machined/pkg/controllers/network/resolver_merge.go
  internal/app/machined/pkg/controllers/network/resolver_merge_test.go
  internal/app/machined/pkg/controllers/network/timeserver_merge.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#9021 chore: ensure tls required on s3 buckets
  hack/cloud-image-uploader/aws.go
Labels: status/ok-to-test, status/ok-to-merge, integration/cloud-images

#9028 fix: enforce secureboot enroll option only for supported releases
  cmd/talosctl/cmd/mgmt/cluster/create.go
  pkg/machinery/config/contract.go
  pkg/machinery/config/contract_test.go
Labels: status/ok-to-test, status/ok-to-merge

#9025 feat: update Kubernetes to 1.31.0-beta.0
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/v1.8/_index.md
  website/content/v1.8/reference/cli.md
  website/content/v1.8/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#9032 feat: provide POD_IP env var to scheduler and controller-manager
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
Labels: status/ok-to-test, status/ok-to-merge

#9052 chore(ci): remove artifacts directory prefix for checksums
  .github/workflows/ci.yaml
Labels: status/ok-to-test, status/ok-to-merge

#8992 docs: update openebs-jiva helm repo
  website/content/v1.7/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva.md
  website/content/v1.8/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva.md
Labels: status/ok-to-test, status/ok-to-merge

#9050 feat: use ethtool ioctl to get link status when netlink api not avail…
  internal/app/machined/pkg/controllers/network/link_status.go
Labels: status/ok-to-merge

#9053 feat: update etcd to 3.5.15, Flannel to 0.25.5
  go.mod
  go.sum
  hack/release.toml
  pkg/flannel/template.go
  pkg/machinery/constants/constants.go
  website/content/v1.8/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#9057 release(v1.6.8): prepare release
  CHANGELOG.md
  go.mod
  hack/release.toml
  pkg/machinery/gendata/data/tag
  website/content/v1.6/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9059 feat: update Linux, enable Broadcom MPI3 driver
  Makefile
  hack/modules-amd64.txt
  hack/modules-arm64.txt
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#9064 chore: add test for gvisor extension with platform kvm
  internal/integration/api/extensions_qemu.go
Labels: status/ok-to-test, status/ok-to-merge

#9065 Update vmware.sh
  website/content/v1.7/talos-guides/install/virtualized-platforms/vmware/vmware.sh
  website/content/v1.8/talos-guides/install/virtualized-platforms/vmware/vmware.sh
Labels: status/ok-to-merge

#9069 feat: runc memfd-bind service
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/cri/runc_memfd_bind.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/pkg/secureboot/database/certs/db/microsoft option rom uefi ca 2023.der
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu

#9077 chore: lock microsoft secureboot certs
  Dockerfile
  Makefile
Labels: status/ok-to-test, status/ok-to-merge

#9080 feat: update Linux to 6.6.43
  Makefile
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#9081 fix: generate kubeconfig using proper types
  .golangci.yml
  go.mod
  go.sum
  pkg/kubeconfig/generate.go
  pkg/kubeconfig/generate_test.go
Labels: status/ok-to-test, status/ok-to-merge

#9082 docs: extend multus configuration for Cilium
  website/content/v1.8/kubernetes-guides/network/multus.md
Labels: status/ok-to-merge

#9085 chore: add test for apparmor
  .github/workflows/ci.yaml
  .github/workflows/integration-misc-1-cron.yaml
  .github/workflows/integration-misc-4-cron.yaml
  .kres.yaml
  hack/test/e2e-qemu.sh
  internal/integration/base/k8s.go
  internal/integration/k8s/apparmor.go
  internal/integration/k8s/testdata/apparmor.yaml
Labels: status/ok-to-test, status/ok-to-merge, integration/misc-4

#9087 feat: update CoreDNS to 1.11.3
  hack/release.toml
  pkg/machinery/constants/constants.go
  website/content/v1.8/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#9036 Docs: Update Equinix Guide
  website/content/v1.8/talos-guides/install/bare-metal-platforms/equinix-metal.md
Labels: status/ok-to-merge

#9071 docs: fix docker getting started typo
  website/content/v1.7/talos-guides/install/local-platforms/docker.md
  website/content/v1.8/talos-guides/install/local-platforms/docker.md
Labels: status/ok-to-test, status/ok-to-merge

#9079 Update replicated local storage to use OpenEBS instead of OpenEBS Jiva which is now deprecated
  website/content/v1.8/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva.md
  website/content/v1.8/kubernetes-guides/configuration/replicated-local-storage-with-openebs.md
  website/content/v1.8/kubernetes-guides/configuration/storage.md
Labels: status/ok-to-merge

#9078 fix: update containerd configuration and settings
  hack/containerd.toml
  hack/cri-containerd.toml
  hack/cri-plugin.part
  internal/app/machined/pkg/system/services/containerd.go
  internal/app/machined/pkg/system/services/cri.go
  internal/app/machined/pkg/system/services/udevd.go
  internal/pkg/containers/cri/containerd/config.go
  internal/pkg/containers/cri/containerd/testdata/cri.toml
  website/content/v1.8/talos-guides/configuration/containerd.md
  website/content/v1.8/talos-guides/configuration/nvidia-gpu-proprietary.md
  website/content/v1.8/talos-guides/configuration/nvidia-gpu.md
Labels: status/ok-to-test, status/ok-to-merge, integration/extensions, integration/aws-nvidia-oss
