Repository siderolabs/talos, pull requests merged in 2024-09, with the labels that each got.

#9258 release(v1.8.0-alpha.2): prepare release
  CHANGELOG.md
  pkg/machinery/gendata/data/tag
  website/content/v1.8/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9266 test: update Talos versions in Image Factory tests
  .github/workflows/ci.yaml
  .github/workflows/integration-image-factory-cron.yaml
  .kres.yaml
Labels: status/ok-to-test, status/ok-to-merge, integration/image-factory

#9267 chore: remove matrix links from docs
  website/content/v0.10/_index.md
  website/content/v0.11/_index.md
  website/content/v0.12/_index.md
  website/content/v0.13/_index.md
  website/content/v0.14/_index.md
  website/content/v0.6/_index.md
  website/content/v0.7/_index.md
  website/content/v0.8/_index.md
  website/content/v0.9/_index.md
  website/content/v1.0/_index.md
  website/content/v1.1/_index.md
  website/content/v1.2/_index.md
  website/content/v1.3/_index.md
  website/content/v1.4/_index.md
  website/content/v1.5/_index.md
  website/content/v1.6/_index.md
  website/content/v1.7/_index.md
  website/content/v1.8/_index.md
Labels: status/ok-to-test, status/ok-to-merge

#9270 chore: support gcp in cloud-image-uploader
  .secrets.yaml
  hack/cloud-image-uploader/README.md
  hack/cloud-image-uploader/gcp.go
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/cloud-image-uploader/main.go
  hack/cloud-image-uploader/options.go
Labels: status/ok-to-test, status/ok-to-merge

#9272 feat: update Linux 6.6.49
  Makefile
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/amd64/snp.efi
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/arm64/snp.efi
Labels: status/ok-to-test, status/ok-to-merge

#9273 fix: report internally service as unhealthy if not running
  internal/app/machined/pkg/system/service_runner.go
Labels: status/ok-to-test, status/ok-to-merge

#9280 fix: never unarchive initramfs when loading boot assets in talosctl
  cmd/talosctl/cmd/mgmt/cluster/create.go
Labels: status/ok-to-test, status/ok-to-merge

#9265 feat: add configuration for EPHEMERAL volume
  .github/workflows/ci.yaml
  .github/workflows/integration-qemu-cron.yaml
  .github/workflows/integration-qemu-encrypted-vip-cron.yaml
  .kres.yaml
  api/resource/definitions/block/block.proto
  cmd/talosctl/cmd/docs.go
  hack/release.toml
  hack/test/e2e-qemu.sh
  hack/test/patches/ephemeral-nvme.yaml
  internal/app/machined/pkg/controllers/block/discovery.go
  internal/app/machined/pkg/controllers/block/disks.go
  internal/app/machined/pkg/controllers/block/internal/volumes/grow.go
  internal/app/machined/pkg/controllers/block/internal/volumes/locate.go
  internal/app/machined/pkg/controllers/block/volume_config.go
  internal/app/machined/pkg/controllers/block/volume_config_test.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/integration/api/reset.go
  internal/integration/api/volumes.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/block/block_vtproto.pb.go
  pkg/machinery/cel/cel.go
  pkg/machinery/cel/cel_test.go
  pkg/machinery/cel/celenv/celenv.go
  pkg/machinery/cel/celenv/celenv_test.go
  pkg/machinery/config/config/config.go
  pkg/machinery/config/config/volume.go
  pkg/machinery/config/container/container.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/block/block.go
  pkg/machinery/config/types/block/block_doc.go
  pkg/machinery/config/types/block/byte_size.go
  pkg/machinery/config/types/block/bytes_size_test.go
  pkg/machinery/config/types/block/deep_copy.generated.go
  pkg/machinery/config/types/block/testdata/volumeconfig_diskselector.yaml
  pkg/machinery/config/types/block/testdata/volumeconfig_empty.yaml
  pkg/machinery/config/types/block/testdata/volumeconfig_maxsize.yaml
  pkg/machinery/config/types/block/volume_config.go
  pkg/machinery/config/types/block/volume_config_test.go
  pkg/machinery/config/types/types.go
  pkg/machinery/resources/block/discovered_volume.go
  pkg/machinery/resources/block/disk.go
  pkg/machinery/resources/block/volume_status.go
  website/content/v1.8/reference/api.md
  website/content/v1.8/reference/configuration/block/_index.md
  website/content/v1.8/reference/configuration/block/volumeconfig.md
  website/content/v1.8/schemas/config.schema.json
  website/content/v1.8/talos-guides/configuration/disk-management.md
Labels: status/ok-to-test, status/ok-to-merge

#9277 feat: add KubeSpan extra endpoint configuration
  api/resource/definitions/kubespan/kubespan.proto
  hack/release.toml
  internal/app/machined/pkg/controllers/cluster/local_affiliate.go
  internal/app/machined/pkg/controllers/cluster/local_affiliate_test.go
  internal/app/machined/pkg/controllers/kubespan/config.go
  internal/app/machined/pkg/controllers/kubespan/config_test.go
  internal/integration/api/discovery.go
  pkg/machinery/api/resource/definitions/kubespan/kubespan.pb.go
  pkg/machinery/api/resource/definitions/kubespan/kubespan_vtproto.pb.go
  pkg/machinery/config/config/config.go
  pkg/machinery/config/config/kubespan.go
  pkg/machinery/config/container/container.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/network/deep_copy.generated.go
  pkg/machinery/config/types/network/default_action_config.go
  pkg/machinery/config/types/network/kubespan_endpoints.go
  pkg/machinery/config/types/network/kubespan_endpoints_test.go
  pkg/machinery/config/types/network/network.go
  pkg/machinery/config/types/network/network_doc.go
  pkg/machinery/config/types/network/testdata/kubespanendpointsconfig.yaml
  pkg/machinery/resources/kubespan/config.go
  pkg/machinery/resources/kubespan/deep_copy.generated.go
  website/content/v1.8/reference/api.md
  website/content/v1.8/reference/configuration/network/kubespanendpoints.md
  website/content/v1.8/schemas/config.schema.json
  website/content/v1.8/talos-guides/network/kubespan.md
Labels: status/ok-to-test, status/ok-to-merge, integration/misc-1

#9282 feat: update dependencies
  Makefile
  go.mod
  go.sum
  go.work
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/docgen/go.mod
  hack/docgen/go.sum
  hack/gotagsrewrite/go.mod
  hack/release.toml
  hack/structprotogen/go.mod
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/extras
  pkg/machinery/gendata/data/pkgs
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge, integration/extensions

#9284 chore: disallow duplicate documents on decoder level
  cmd/talosctl/cmd/mgmt/cluster/internal/firewallpatch/firewallpatch.go
  pkg/machinery/config/configloader/internal/decoder/decoder.go
  pkg/machinery/config/configloader/internal/decoder/decoder_test.go
  pkg/machinery/config/configloader/internal/decoder/testdata/double/v1alpha1.yaml
  pkg/machinery/config/configpatcher/load.go
  pkg/machinery/config/configpatcher/load_test.go
  pkg/machinery/config/configpatcher/strategic.go
  pkg/machinery/config/container/container.go
Labels: status/ok-to-test, status/ok-to-merge

#9285 chore: version specific kube-scheduler health checks
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
Labels: status/ok-to-test, status/ok-to-merge, integration/provision-2

#9287 feat: acquire machine config inline from kernel cmdline
  hack/release.toml
  internal/app/machined/pkg/controllers/config/acquire.go
  internal/app/machined/pkg/controllers/config/acquire_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  pkg/machinery/constants/constants.go
  website/content/v1.8/reference/kernel.md
Labels: status/ok-to-test, status/ok-to-merge

#9275 feat: implement "$patch: delete" logic
  hack/release.toml
  pkg/machinery/config/configloader/configloader.go
  pkg/machinery/config/configloader/internal/decoder/decoder.go
  pkg/machinery/config/configloader/internal/decoder/decoder_test.go
  pkg/machinery/config/configloader/internal/decoder/delete.go
  pkg/machinery/config/configloader/internal/decoder/delete_test.go
  pkg/machinery/config/configloader/internal/decoder/selector.go
  pkg/machinery/config/configloader/internal/decoder/testdata/delete/delete.yaml
  pkg/machinery/config/configloader/internal/decoder/testdata/delete/delete_expected.yaml
  pkg/machinery/config/configpatcher/apply_test.go
  pkg/machinery/config/configpatcher/load.go
  pkg/machinery/config/configpatcher/strategic.go
  pkg/machinery/config/configpatcher/testdata/patchdelete/config.yaml
  pkg/machinery/config/configpatcher/testdata/patchdelete/controlplane_expected.yaml
  pkg/machinery/config/configpatcher/testdata/patchdelete/controlplane_orig.yaml
  pkg/machinery/config/configpatcher/testdata/patchdelete/expected.yaml
  pkg/machinery/config/configpatcher/testdata/patchdelete/strategic1.yaml
  pkg/machinery/config/configpatcher/testdata/patchdelete/strategic2.yaml
  pkg/machinery/config/configpatcher/testdata/patchdelete/strategic3.yaml
  pkg/machinery/config/configpatcher/testdata/patchdelete/strategic4.yaml
  pkg/machinery/config/container/container.go
  website/content/v1.8/talos-guides/configuration/patching.md
Labels: status/ok-to-test, status/ok-to-merge

#9293 release(v1.8.0-beta.0): prepare release
  .github/workflows/ci.yaml
  .github/workflows/integration-aws-cron.yaml
  .github/workflows/integration-aws-nvidia-nonfree-cron.yaml
  .github/workflows/integration-aws-nvidia-oss-cron.yaml
  .github/workflows/integration-azure-cron.yaml
  .github/workflows/integration-cilium-cron.yaml
  .github/workflows/integration-cloud-images-cron.yaml
  .github/workflows/integration-conformance-cron.yaml
  .github/workflows/integration-equinix-metal-cron.yaml
  .github/workflows/integration-extensions-cron.yaml
  .github/workflows/integration-gcp-cron.yaml
  .github/workflows/integration-image-factory-cron.yaml
  .github/workflows/integration-images-cron.yaml
  .github/workflows/integration-misc-0-cron.yaml
  .github/workflows/integration-misc-1-cron.yaml
  .github/workflows/integration-misc-2-cron.yaml
  .github/workflows/integration-misc-3-cron.yaml
  .github/workflows/integration-misc-4-cron.yaml
  .github/workflows/integration-provision-0-cron.yaml
  .github/workflows/integration-provision-1-cron.yaml
  .github/workflows/integration-provision-2-cron.yaml
  .github/workflows/integration-qemu-cron.yaml
  .github/workflows/integration-qemu-csi-longhorn-cron.yaml
  .github/workflows/integration-qemu-csi-rook-ceph-cron.yaml
  .github/workflows/integration-qemu-encrypted-vip-cron.yaml
  .github/workflows/integration-qemu-race-cron.yaml
  .github/workflows/integration-reproducibility-test-cron.yaml
  .github/workflows/integration-trusted-boot-cron.yaml
  .kres.yaml
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.8/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge, integration/extensions, integration/gcp

#9297 docs: add what's new for Talos 1.8
  .github/workflows/ci.yaml
  .github/workflows/integration-aws-cron.yaml
  .github/workflows/integration-aws-nvidia-nonfree-cron.yaml
  .github/workflows/integration-aws-nvidia-oss-cron.yaml
  .github/workflows/integration-azure-cron.yaml
  .github/workflows/integration-cilium-cron.yaml
  .github/workflows/integration-cloud-images-cron.yaml
  .github/workflows/integration-conformance-cron.yaml
  .github/workflows/integration-equinix-metal-cron.yaml
  .github/workflows/integration-extensions-cron.yaml
  .github/workflows/integration-gcp-cron.yaml
  .github/workflows/integration-image-factory-cron.yaml
  .github/workflows/integration-images-cron.yaml
  .github/workflows/integration-misc-0-cron.yaml
  .github/workflows/integration-misc-1-cron.yaml
  .github/workflows/integration-misc-2-cron.yaml
  .github/workflows/integration-misc-3-cron.yaml
  .github/workflows/integration-misc-4-cron.yaml
  .github/workflows/integration-provision-0-cron.yaml
  .github/workflows/integration-provision-1-cron.yaml
  .github/workflows/integration-provision-2-cron.yaml
  .github/workflows/integration-qemu-cron.yaml
  .github/workflows/integration-qemu-csi-longhorn-cron.yaml
  .github/workflows/integration-qemu-csi-rook-ceph-cron.yaml
  .github/workflows/integration-qemu-encrypted-vip-cron.yaml
  .github/workflows/integration-qemu-race-cron.yaml
  .github/workflows/integration-reproducibility-test-cron.yaml
  .github/workflows/integration-trusted-boot-cron.yaml
  .kres.yaml
  website/content/v1.8/_index.md
  website/content/v1.8/introduction/support-matrix.md
  website/content/v1.8/introduction/what-is-new/index.md
  website/content/v1.8/talos-guides/configuration/nvidia-fabricmanager.md
  website/content/v1.8/talos-guides/upgrading-talos.md
Labels: status/ok-to-test, status/ok-to-merge

#9301 feat: update etcd to 3.5.16
  go.mod
  go.sum
  hack/release.toml
  pkg/machinery/constants/constants.go
  website/content/v1.8/introduction/what-is-new/index.md
  website/content/v1.8/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#9302 fix: remove extra logging on ethtool ioctl failures
  internal/app/machined/pkg/controllers/network/link_status.go
Labels: status/ok-to-test, status/ok-to-merge

#9304 fix: parse SideroLink API endpoint correctly
  internal/app/machined/pkg/controllers/siderolink/config_test.go
  internal/app/machined/pkg/controllers/siderolink/status.go
  internal/app/machined/pkg/controllers/siderolink/status_test.go
Labels: status/ok-to-test, status/ok-to-merge

#9310 chore: account for resource sorting in dns upstream resource
  internal/app/machined/pkg/controllers/network/dns_resolve_cache.go
  internal/app/machined/pkg/controllers/network/dns_resolve_cache_test.go
  internal/app/machined/pkg/controllers/network/dns_upstream.go
  internal/app/machined/pkg/controllers/network/resolver_merge.go
  pkg/machinery/resources/network/dns_upstream.go
Labels: status/ok-to-test, status/ok-to-merge

#9312 fix: update CoreDNS health check
  pkg/cluster/check/default.go
  pkg/cluster/check/kubernetes.go
Labels: status/ok-to-test, status/ok-to-merge

#9314 feat: update default Kubernetes version to 1.31.1
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/v1.8/_index.md
  website/content/v1.8/introduction/what-is-new/index.md
  website/content/v1.8/reference/cli.md
  website/content/v1.8/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#9313 fix: ignore invalid NTP responses
  internal/pkg/ntp/ntp.go
  internal/pkg/ntp/ntp_test.go
Labels: status/ok-to-test, status/ok-to-merge

#9315 test: add a test for inline machine config trusted roots
  .github/workflows/ci.yaml
  .github/workflows/integration-misc-4-cron.yaml
  .kres.yaml
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/mgmt/siderolink_launch_linux.go
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/siderolink/manager.go
  internal/pkg/encryption/keys/kms.go
  pkg/provision/providers/vm/siderolink-agent.go
  pkg/provision/request.go
Labels: status/ok-to-test, status/ok-to-merge, integration/misc-4

#9327 release(v1.8.0-beta.1): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.8/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9329 fix: strategic merge patch delete for map keys
  pkg/machinery/config/configloader/internal/decoder/selector.go
  pkg/machinery/config/configpatcher/testdata/patchdelete/controlplane_expected.yaml
  pkg/machinery/config/configpatcher/testdata/patchdelete/strategic2.yaml
Labels: status/ok-to-test, status/ok-to-merge

#9330 docs: document `/dev/net/tun` compatibility
  hack/release.toml
  website/content/v1.8/introduction/what-is-new/index.md
  website/content/v1.8/kubernetes-guides/configuration/device-plugins.md
Labels: status/ok-to-test, status/ok-to-merge

#9334 docs: add SECURITY.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
Labels: status/ok-to-test, status/ok-to-merge

#9340 fix: filter out non-printable characters in process line
  cmd/talosctl/cmd/talos/processes.go
  internal/pkg/dashboard/components/tables.go
Labels: status/ok-to-test, status/ok-to-merge

#9333 feat: support lvm auto activation
  .github/workflows/ci.yaml
  .github/workflows/integration-extensions-cron.yaml
  .github/workflows/integration-qemu-cron.yaml
  .kres.yaml
  internal/app/machined/pkg/controllers/block/lvm.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/integration/api/extensions_qemu.go
  internal/integration/api/volumes.go
  internal/integration/base/api.go
  internal/integration/base/k8s.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu, integration/extensions

#9343 chore: refactor tests
  internal/integration/api/common.go
  internal/integration/api/extensions_qemu.go
  internal/integration/api/volumes.go
  internal/integration/base/k8s.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu, integration/extensions

#9339 Allow /sbin/ldconfig (support for glibc extension for nvidia gpu-operator)
  pkg/machinery/extensions/extensions.go
Labels: status/ok-to-merge

#9345 chore: bump lvm2
  Makefile
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#9341 fix: audit and fix cgroup reservations
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/k8s/kubelet_spec.go
  internal/app/machined/pkg/controllers/k8s/kubelet_spec_test.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/runner/containerd/opts.go
  internal/app/machined/pkg/system/runner/runner.go
  internal/app/machined/pkg/system/services/apid.go
  internal/app/machined/pkg/system/services/dashboard.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/machined/pkg/system/services/trustd.go
  internal/pkg/cgroup/cpu.go
  internal/pkg/cgroup/cpu_test.go
  internal/pkg/mount/cgroups.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge, integration/misc, integration/qemu

#9349 docs: fix kubespan name inconsistency
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/network/kubespan_endpoints.go
  pkg/machinery/config/types/network/network_doc.go
  pkg/machinery/config/types/network/testdata/kubespanendpointsconfig.yaml
  website/content/v1.8/reference/configuration/network/kubespanendpointsconfig.md
  website/content/v1.8/schemas/config.schema.json
  website/content/v1.8/talos-guides/network/kubespan.md
  website/content/v1.8/talos-guides/upgrading-talos.md
Labels: status/ok-to-test, status/ok-to-merge

#9355 fix: update blockdevice library to v2.0.2
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#9356 release(v1.8.0): prepare release
  CHANGELOG.md
  go.mod
  hack/release.toml
  pkg/machinery/gendata/data/tag
  website/content/v1.8/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9360 docs: make Talos 1.8 current release
  website/config.toml
  website/content/v1.7/_index.md
  website/content/v1.7/introduction/support-matrix.md
  website/content/v1.8/_index.md
  website/content/v1.8/introduction/support-matrix.md
Labels: status/ok-to-test, status/ok-to-merge

#9362 docs: Fix Kernel Self Protection Project (KSPP) references
  website/content/v1.8/learn-more/components.md
  website/content/v1.8/reference/kernel.md
Labels: status/ok-to-merge

#9374 Update hetzner.md
  website/content/v1.8/talos-guides/install/cloud-platforms/hetzner.md
Labels: status/ok-to-merge

#9375 docs: enabled 'edit on GitHub' link
  website/config.toml
  website/themes/docsy/layouts/partials/page-meta-links.html
Labels: status/ok-to-test, status/ok-to-merge

#9382 fix: build talosctl without `tcell_minimal`
  Dockerfile
  Makefile
Labels: status/ok-to-test, status/ok-to-merge

#9386 release(v1.7.7): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.7/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9378 Update storage.md
  website/content/v1.8/kubernetes-guides/configuration/storage.md
Labels: status/ok-to-merge

#9399 chore: ignore more plugins for system containerd
  hack/containerd.toml
Labels: status/ok-to-test, status/ok-to-merge

#9402 chore: disable cloud-images cron workflow
  .github/workflows/integration-cloud-images-cron.yaml
  .github/workflows/slack-notify.yaml
  .kres.yaml
Labels: status/ok-to-test, status/ok-to-merge

#9352 feat: add support for CI Network config in nocloud
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud_test.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/metadata-v2-cloud-init.yaml
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/metadata-v2-nocloud.yaml
Labels: status/ok-to-merge
