Repository siderolabs/talos, pull requests merged in 2024-05, with the labels that each got.

#8678 chore: update minimum hardware requirement for vmware ova
  pkg/imager/ova/ova.go
Labels: status/ok-to-test, status/ok-to-merge

#8680 feat: update Linux to 6.6.29
  Makefile
  go.mod
  go.sum
  hack/cloud-image-uploader/aws.go
  hack/cloud-image-uploader/azure.go
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/cloud-image-uploader/options.go
  hack/release.toml
  hack/test/e2e-qemu.sh
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#8684 release(v1.7.1): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.7/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#8683 fix: use a fresh context for etcd unlock
  internal/pkg/etcd/lock.go
Labels: status/ok-to-test, status/ok-to-merge

#8686 release(v1.8.0-alpha.0): prepare release
  .conform.yaml
  .drone.jsonnet
  CHANGELOG.md
  go.mod
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/v1alpha1/testdata/stability/v1.8/base-controlplane.yaml
  pkg/machinery/config/types/v1alpha1/testdata/stability/v1.8/base-worker.yaml
  pkg/machinery/config/types/v1alpha1/testdata/stability/v1.8/overrides-controlplane.yaml
  pkg/machinery/config/types/v1alpha1/testdata/stability/v1.8/overrides-worker.yaml
  pkg/machinery/config/types/v1alpha1/v1alpha1_stability_test.go
  pkg/machinery/gendata/data/tag
  website/content/v1.8/reference/cli.md
  website/content/v1.8/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge

#8704 docs: add logs example for the certificate errors troubleshooting
  website/content/v1.7/introduction/troubleshooting.md
  website/content/v1.8/introduction/troubleshooting.md
Labels: status/ok-to-test, status/ok-to-merge

#8697 docs: fix grpc_tunnel value to true
  website/content/v1.7/talos-guides/network/siderolink.md
  website/content/v1.8/talos-guides/network/siderolink.md
Labels: status/ok-to-test, status/ok-to-merge

#8708 fix: do not fail cli action tracker when boot id cannot be read
  cmd/talosctl/pkg/talos/action/tracker.go
Labels: status/ok-to-test, status/ok-to-merge

#8701 Typo
  website/content/v1.7/advanced/building-images.md
  website/content/v1.8/advanced/building-images.md
Labels: status/ok-to-test, status/ok-to-merge

#8696 docs: remove mention of enabling KubePrism after v1.6
  website/content/v1.6/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.7/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.8/kubernetes-guides/network/deploying-cilium.md
Labels: status/ok-to-test, status/ok-to-merge

#8641 feat: mount /sys/kernel/security into kubelet
  internal/app/machined/pkg/system/services/kubelet.go
Labels: status/ok-to-test, status/ok-to-merge

#8712 fix: put cluster name to the worker machine config
  internal/integration/cli/gen.go
  pkg/machinery/config/contract.go
  pkg/machinery/config/contract_test.go
  pkg/machinery/config/generate/worker.go
  pkg/machinery/config/types/v1alpha1/testdata/stability/v1.8/base-worker.yaml
  pkg/machinery/config/types/v1alpha1/testdata/stability/v1.8/overrides-worker.yaml
Labels: status/ok-to-test, status/ok-to-merge

#8693 docs: add resource information, some grammar fixes
  website/content/v1.7/talos-guides/network/ingress-firewall.md
  website/content/v1.8/talos-guides/network/ingress-firewall.md
Labels: status/ok-to-test, status/ok-to-merge

#8700 feat: gather plaform dns names
  api/resource/definitions/runtime/runtime.proto
  internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/aws/metadata.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/azure/metadata.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/azure/testdata/compute.json
  internal/app/machined/pkg/runtime/v1alpha1/platform/azure/testdata/expected.yaml
  internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/metadata.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud_test.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/expected-v1.yaml
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/expected-v2.yaml
  pkg/machinery/api/resource/definitions/runtime/runtime.pb.go
  pkg/machinery/api/resource/definitions/runtime/runtime_vtproto.pb.go
  pkg/machinery/resources/runtime/platform_metadata.go
  website/content/v1.8/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge

#8722 fix: check for `nil` machine config during installation
  cmd/installer/cmd/installer/install.go
Labels: status/ok-to-test, status/ok-to-merge

#8668 Proxmox install update to add QEMU guest agent guidance
  website/content/v1.7/talos-guides/install/virtualized-platforms/proxmox.md
Labels: status/ok-to-test, status/ok-to-merge

#8728 feat: update Linux 6.6.30
  Makefile
  hack/release.toml
  internal/integration/api/extensions_qemu.go
  pkg/machinery/api/cluster/cluster.pb.go
  pkg/machinery/api/cluster/cluster_grpc.pb.go
  pkg/machinery/api/common/common.pb.go
  pkg/machinery/api/inspect/inspect.pb.go
  pkg/machinery/api/inspect/inspect_grpc.pb.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/machine/machine_grpc.pb.go
  pkg/machinery/api/resource/config/config.pb.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/cluster/cluster.pb.go
  pkg/machinery/api/resource/definitions/cri/cri.pb.go
  pkg/machinery/api/resource/definitions/enums/enums.pb.go
  pkg/machinery/api/resource/definitions/etcd/etcd.pb.go
  pkg/machinery/api/resource/definitions/extensions/extensions.pb.go
  pkg/machinery/api/resource/definitions/files/files.pb.go
  pkg/machinery/api/resource/definitions/hardware/hardware.pb.go
  pkg/machinery/api/resource/definitions/k8s/k8s.pb.go
  pkg/machinery/api/resource/definitions/kubeaccess/kubeaccess.pb.go
  pkg/machinery/api/resource/definitions/kubespan/kubespan.pb.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/perf/perf.pb.go
  pkg/machinery/api/resource/definitions/proto/proto.pb.go
  pkg/machinery/api/resource/definitions/runtime/runtime.pb.go
  pkg/machinery/api/resource/definitions/secrets/secrets.pb.go
  pkg/machinery/api/resource/definitions/siderolink/siderolink.pb.go
  pkg/machinery/api/resource/definitions/time/time.pb.go
  pkg/machinery/api/resource/definitions/v1alpha1/v1alpha1.pb.go
  pkg/machinery/api/resource/network/device_config.pb.go
  pkg/machinery/api/security/security.pb.go
  pkg/machinery/api/security/security_grpc.pb.go
  pkg/machinery/api/storage/storage.pb.go
  pkg/machinery/api/storage/storage_grpc.pb.go
  pkg/machinery/api/time/time.pb.go
  pkg/machinery/api/time/time_grpc.pb.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/amd64/snp.efi
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/arm64/snp.efi
Labels: status/ok-to-test, status/ok-to-merge

#8733 chore: handle I/O error for xfs_repair
  internal/pkg/mount/mount.go
Labels: status/ok-to-test, status/ok-to-merge

#8734 chore: remove docs prior to 1.0 from website navigation
  website/config.toml
Labels: status/ok-to-test, status/ok-to-merge

#8735 chore: update office hours in talos repo
  README.md
  website/content/v1.0/_index.md
  website/content/v1.1/_index.md
  website/content/v1.2/_index.md
  website/content/v1.3/_index.md
  website/content/v1.4/_index.md
  website/content/v1.5/_index.md
  website/content/v1.6/_index.md
  website/content/v1.7/_index.md
  website/content/v1.8/_index.md
Labels: status/ok-to-test, status/ok-to-merge

#8736 chore: update project in GCP testing
  hack/test/e2e-gcp.sh
Labels: status/ok-to-test, status/ok-to-merge

#8739 docs: fixing typos, docker socket info
  website/content/v1.8/introduction/quickstart.md
  website/content/v1.8/talos-guides/install/local-platforms/docker.md
Labels: status/ok-to-test, status/ok-to-merge

#8742 fix: update github.com/siderolabs/siderolink to v0.3.7
  go.mod
  go.sum
  hack/cloud-image-uploader/go.sum
  hack/structprotogen/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#8737 fix: increase host dns packet ttl for pods
  internal/app/machined/pkg/controllers/network/dns_resolve_cache.go
  internal/pkg/dns/dns.go
  internal/pkg/dns/dns_test.go
Labels: status/ok-to-test, status/ok-to-merge

#8745 feat: update Kubernetes to 1.30.1
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/v1.8/reference/cli.md
  website/content/v1.8/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#8744 feat: include EDAC drivers
  Makefile
  hack/modules-amd64.txt
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#8757 release(v1.7.2): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.7/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#8754 feat: use new circular buffer compressed chunks feature
  go.mod
  go.sum
  internal/app/machined/pkg/runtime/logging/circular.go
Labels: status/ok-to-test, status/ok-to-merge

#8752 Added documentation on using Multus with Talos
  website/content/v1.7/kubernetes-guides/network/multus.md
  website/content/v1.8/kubernetes-guides/network/multus.md
Labels: status/ok-to-test, status/ok-to-merge

#8767 fix: update go-tail library to fix 'short read' error
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#8773 chore: stop using containerd package for cri namespace
  cmd/talosctl/cmd/talos/containers.go
  cmd/talosctl/cmd/talos/logs.go
  cmd/talosctl/cmd/talos/netstat.go
  cmd/talosctl/cmd/talos/restart.go
  cmd/talosctl/cmd/talos/root.go
  cmd/talosctl/cmd/talos/stats.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_images.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#8775 refactor: make some of the extensions package public
  internal/pkg/extensions/compress.go
  internal/pkg/extensions/extensions.go
  internal/pkg/extensions/extensions_test.go
  internal/pkg/extensions/kernel_modules.go
  internal/pkg/extensions/list.go
  pkg/machinery/extensions/extensions.go
  pkg/machinery/extensions/extensions_test.go
  pkg/machinery/extensions/load.go
  pkg/machinery/extensions/testdata/bad/badpaths/manifest.yaml
  pkg/machinery/extensions/testdata/bad/badpaths/rootfs/boot/vmlinuz
  pkg/machinery/extensions/testdata/bad/emptymanifest/manifest.yaml
  pkg/machinery/extensions/testdata/bad/norootfs/manifest.yaml
  pkg/machinery/extensions/testdata/bad/wrongfiles/a
  pkg/machinery/extensions/testdata/good/extension1/manifest.yaml
  pkg/machinery/extensions/testdata/good/extension1/rootfs/lib/firmware/amd/cpu
  pkg/machinery/extensions/testdata/good/extension1/rootfs/lib64/ld-linux-x86-64.so.2
  pkg/machinery/extensions/testdata/good/extension1/rootfs/usr/local/lib/a.so
  pkg/machinery/extensions/testdata/good/extension1/rootfs/usr/local/lib/a.so.1
  pkg/machinery/extensions/validate.go
Labels: status/ok-to-test, status/ok-to-merge

#8774 fix: decrease maximum negative ttl for dns responses
  go.mod
  go.sum
  internal/pkg/dns/dns.go
Labels: status/ok-to-test, status/ok-to-merge, integration/misc

#8778 chore(ci): fix github action crons
  .github/workflows/ci.yaml
  .github/workflows/integration-aws-cron.yaml
  .github/workflows/integration-aws-nvidia-nonfree-cron.yaml
  .github/workflows/integration-aws-nvidia-oss-cron.yaml
  .github/workflows/integration-azure-cron.yaml
  .github/workflows/integration-cilium-cron.yaml
  .github/workflows/integration-cloud-images-cron.yaml
  .github/workflows/integration-equinix-metal-cron.yaml
  .github/workflows/integration-extensions-cron.yaml
  .github/workflows/integration-image-factory-cron.yaml
  .github/workflows/integration-images-cron.yaml
  .github/workflows/integration-misc-cron.yaml
  .github/workflows/integration-provision-0-cron.yaml
  .github/workflows/integration-provision-1-cron.yaml
  .github/workflows/integration-provision-2-cron.yaml
  .github/workflows/integration-qemu-cron.yaml
  .github/workflows/integration-qemu-csi-cron.yaml
  .github/workflows/integration-qemu-encrypted-vip-cron.yaml
  .github/workflows/integration-qemu-race-cron.yaml
  .github/workflows/integration-reproducibility-test-cron.yaml
  .github/workflows/integration-trusted-boot-cron.yaml
  .kres.yaml
Labels: status/ok-to-test, status/ok-to-merge

#8777 feat: update containerd to 2.0.0-rc.2, runc to 1.2.0-rc.1
  Makefile
  hack/release.toml
  pkg/machinery/api/cluster/cluster_grpc.pb.go
  pkg/machinery/api/inspect/inspect_grpc.pb.go
  pkg/machinery/api/machine/machine_grpc.pb.go
  pkg/machinery/api/security/security_grpc.pb.go
  pkg/machinery/api/storage/storage_grpc.pb.go
  pkg/machinery/api/time/time_grpc.pb.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#8783 fix(ci): fix crons fby rekres
  .github/workflows/ci.yaml
  .github/workflows/integration-aws-cron.yaml
  .github/workflows/integration-aws-nvidia-nonfree-cron.yaml
  .github/workflows/integration-aws-nvidia-oss-cron.yaml
  .github/workflows/integration-azure-cron.yaml
  .github/workflows/integration-cilium-cron.yaml
  .github/workflows/integration-cloud-images-cron.yaml
  .github/workflows/integration-equinix-metal-cron.yaml
  .github/workflows/integration-extensions-cron.yaml
  .github/workflows/integration-image-factory-cron.yaml
  .github/workflows/integration-images-cron.yaml
  .github/workflows/integration-misc-cron.yaml
  .github/workflows/integration-provision-0-cron.yaml
  .github/workflows/integration-provision-1-cron.yaml
  .github/workflows/integration-provision-2-cron.yaml
  .github/workflows/integration-qemu-cron.yaml
  .github/workflows/integration-qemu-csi-cron.yaml
  .github/workflows/integration-qemu-encrypted-vip-cron.yaml
  .github/workflows/integration-qemu-race-cron.yaml
  .github/workflows/integration-reproducibility-test-cron.yaml
  .github/workflows/integration-trusted-boot-cron.yaml
Labels: status/ok-to-test, status/ok-to-merge

#8784 fix: require accepted CAs on worker nodes
  internal/app/machined/pkg/controllers/secrets/api.go
  internal/integration/api/apply-config.go
  pkg/grpc/gen/remote.go
  pkg/grpc/middleware/auth/basic/basic.go
  pkg/machinery/config/container/container_test.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
Labels: status/ok-to-test, status/ok-to-merge

#8786 docs: default to brew docs for talosctl
  website/content/v1.7/introduction/getting-started.md
  website/content/v1.7/talos-guides/install/local-platforms/qemu.md
  website/content/v1.7/talos-guides/install/local-platforms/virtualbox.md
  website/content/v1.7/talos-guides/install/talosctl.md
  website/content/v1.7/talos-guides/install/virtualized-platforms/proxmox.md
Labels: status/ok-to-test, status/ok-to-merge

#8788 fix(ci): fix crons by setting up buildx always
  .github/workflows/ci.yaml
  .github/workflows/integration-aws-cron.yaml
  .github/workflows/integration-aws-nvidia-nonfree-cron.yaml
  .github/workflows/integration-aws-nvidia-oss-cron.yaml
  .github/workflows/integration-azure-cron.yaml
  .github/workflows/integration-cilium-cron.yaml
  .github/workflows/integration-cloud-images-cron.yaml
  .github/workflows/integration-equinix-metal-cron.yaml
  .github/workflows/integration-extensions-cron.yaml
  .github/workflows/integration-image-factory-cron.yaml
  .github/workflows/integration-images-cron.yaml
  .github/workflows/integration-misc-cron.yaml
  .github/workflows/integration-provision-0-cron.yaml
  .github/workflows/integration-provision-1-cron.yaml
  .github/workflows/integration-provision-2-cron.yaml
  .github/workflows/integration-qemu-cron.yaml
  .github/workflows/integration-qemu-csi-cron.yaml
  .github/workflows/integration-qemu-encrypted-vip-cron.yaml
  .github/workflows/integration-qemu-race-cron.yaml
  .github/workflows/integration-reproducibility-test-cron.yaml
  .github/workflows/integration-trusted-boot-cron.yaml
  .kres.yaml
Labels: status/ok-to-test, status/ok-to-merge

#8789 fix: time sync over NTP from future era
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#8791 test: add Equnix Metal sample metadata with two bonds
  internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/equinix_test.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/testdata/expected-2bonds.yaml
  internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/testdata/metadata-2bonds.json
Labels: status/ok-to-test, status/ok-to-merge

#8794 fix: produce stable order of bonds with equinix
  internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/equinix.go
Labels: status/ok-to-test, status/ok-to-merge

#8792 chore: require enabled bootloader for docker provisioner
  cmd/talosctl/cmd/mgmt/cluster/cluster.go
  cmd/talosctl/cmd/mgmt/cluster/create.go
Labels: status/ok-to-test, status/ok-to-merge

#8799 fix(ci): cron jobs
  .github/workflows/ci.yaml
  .github/workflows/integration-aws-cron.yaml
  .github/workflows/integration-aws-nvidia-nonfree-cron.yaml
  .github/workflows/integration-aws-nvidia-oss-cron.yaml
  .github/workflows/integration-equinix-metal-cron.yaml
  .github/workflows/integration-extensions-cron.yaml
  .github/workflows/integration-images-cron.yaml
  .github/workflows/integration-trusted-boot-cron.yaml
  .kres.yaml
Labels: status/ok-to-test, status/ok-to-merge

#8807 chore(ci): fix integration extensions
  .github/workflows/ci.yaml
  .github/workflows/integration-extensions-cron.yaml
  .kres.yaml
  Makefile
Labels: status/ok-to-test, status/ok-to-merge, integration/extensions

#8815 fix: mount `tracefs` filesystem
  internal/pkg/mount/pseudo.go
Labels: status/ok-to-test, status/ok-to-merge, integration/cilium

#8632 test: add a test for watchdog timers
  internal/integration/api/watchdog.go
  internal/integration/base/api.go
Labels: status/ok-to-test, status/ok-to-merge

#8821 release(v1.7.3): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.7/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#8822 feat: add multidoc check to the Talos quirks module
  pkg/machinery/imager/quirks/quirks.go
Labels: status/ok-to-test, status/ok-to-merge

#8825 chore: unify toml packages being used
  go.mod
  go.sum
  internal/pkg/containers/cri/containerd/containerd.go
  internal/pkg/containers/cri/containerd/hosts.go
  internal/pkg/containers/cri/containerd/hosts_test.go
  internal/pkg/containers/cri/containerd/testdata/cri.toml
  internal/pkg/toml/merge.go
  internal/pkg/toml/testdata/expected.toml
Labels: status/ok-to-test, status/ok-to-merge

#8816 fix: replace `nslookup` with `dig` in integration tests
  internal/integration/api/common.go
Labels: status/ok-to-test, status/ok-to-merge, integration/aws, integration/azure

#8830 fix: correct time adjustment in `time.SyncController`
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge, integration/aws

#8831 feat: update etcd to 3.5.14
  hack/release.toml
  pkg/machinery/constants/constants.go
  website/content/v1.8/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#8833 backport: fix: correct time adjustment in `time.SyncController`
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#8834 release(v1.7.4): prepare release
  CHANGELOG.md
  go.mod
  hack/release.toml
  pkg/machinery/gendata/data/tag
  website/content/v1.7/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#8839 chore: fix go.work resolution
  .golangci.yml
  go.mod
Labels: status/ok-to-test, status/ok-to-merge

#8838 fix: disable kexec on GCP/Azure
  internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
Labels: status/ok-to-test, status/ok-to-merge

#8832 feat: implement PCI device bus enumeration
  api/resource/definitions/hardware/hardware.proto
  go.mod
  go.sum
  hack/release.toml
  internal/app/machined/pkg/controllers/hardware/pcidevices.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/integration/api/hardware.go
  pkg/machinery/api/resource/definitions/hardware/hardware.pb.go
  pkg/machinery/api/resource/definitions/hardware/hardware_vtproto.pb.go
  pkg/machinery/resources/hardware/deep_copy.generated.go
  pkg/machinery/resources/hardware/hardware.go
  pkg/machinery/resources/hardware/hardware_test.go
  pkg/machinery/resources/hardware/pcidevice.go
  website/content/v1.8/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge
