Repository siderolabs/talos, pull requests merged in 2024-12, with the labels that each got.

#9851 docs: fix typo in virtualbox docs
  website/content/v1.7/talos-guides/install/local-platforms/virtualbox.md
  website/content/v1.8/talos-guides/install/local-platforms/virtualbox.md
  website/content/v1.9/talos-guides/install/local-platforms/virtualbox.md
Labels: status/ok-to-merge

#9845 feat: support image cache copying
  api/resource/definitions/cri/cri.proto
  api/resource/definitions/enums/enums.proto
  hack/release.toml
  internal/app/machined/pkg/controllers/cri/image_cache_config.go
  internal/app/machined/pkg/controllers/cri/image_cache_config_test.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  pkg/machinery/api/resource/definitions/cri/cri.pb.go
  pkg/machinery/api/resource/definitions/cri/cri_vtproto.pb.go
  pkg/machinery/api/resource/definitions/enums/enums.pb.go
  pkg/machinery/resources/cri/cri.go
  pkg/machinery/resources/cri/image_cache_config.go
  pkg/machinery/resources/cri/imagecachecopystatus_enumer.go
  pkg/machinery/resources/cri/imagecachestatus.go
  website/content/v1.9/reference/api.md
  website/content/v1.9/talos-guides/configuration/disk-management.md
  website/content/v1.9/talos-guides/configuration/image-cache.md
  website/content/v1.9/talos-guides/install/boot-assets.md
Labels: status/ok-to-test, status/ok-to-merge

#9854 Docs: fix KubeVirt links
  website/content/v1.8/advanced/install-kubevirt.md
  website/content/v1.9/advanced/install-kubevirt.md
Labels: status/ok-to-merge

#9836 Update the Cilium CNI Deployment Docu and Method 5: Using a Job
  website/content/v1.8/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.9/kubernetes-guides/network/deploying-cilium.md
Labels: status/ok-to-merge

#9863 release(v1.9.0-beta.0): prepare release
  CHANGELOG.md
  Makefile
  go.mod
  pkg/machinery/gendata/data/pkgs
  pkg/machinery/gendata/data/tag
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9864 doc: add Turing RK1 docs to Single Board Computer section
  website/content/v1.9/introduction/support-matrix.md
  website/content/v1.9/talos-guides/install/single-board-computers/turing_rk1.md
Labels: status/ok-to-merge

#9873 chore: refactor mergeDNSServers func
  internal/app/machined/pkg/controllers/network/resolver_merge.go
Labels: status/ok-to-test, status/ok-to-merge

#9875 feat: update Kubernetes to 1.32.0-rc.1
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/v1.9/reference/cli.md
  website/content/v1.9/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#9876 test: use two workers in qemu tests by default
  .github/workflows/ci.yaml
  .github/workflows/integration-cilium-cron.yaml
  .github/workflows/integration-conformance-cron.yaml
  .github/workflows/integration-extensions-cron.yaml
  .kres.yaml
  hack/test/e2e-qemu.sh
Labels: status/ok-to-test, status/ok-to-merge, integration/trusted-boot, integration/qemu-encrypted-vip, integration/extensions

#9862 feat: add more scheduling options for process runner
  internal/app/machined/pkg/system/runner/process/process.go
  internal/app/machined/pkg/system/runner/process/process_test.go
  internal/app/machined/pkg/system/runner/runner.go
  internal/app/machined/pkg/system/services/dashboard.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#9847 feat: implement new address sorting algorithm
  .github/workflows/ci.yaml
  .github/workflows/integration-misc-2-cron.yaml
  .kres.yaml
  api/resource/definitions/enums/enums.proto
  api/resource/definitions/network/network.proto
  hack/release.toml
  hack/test/patches/node-address-v2.yaml
  internal/app/machined/pkg/controllers/k8s/nodeip_test.go
  internal/app/machined/pkg/controllers/network/internal/addressutil/addressutil.go
  internal/app/machined/pkg/controllers/network/internal/addressutil/addressutil_test.go
  internal/app/machined/pkg/controllers/network/internal/addressutil/compare.go
  internal/app/machined/pkg/controllers/network/internal/addressutil/compare_test.go
  internal/app/machined/pkg/controllers/network/node_address.go
  internal/app/machined/pkg/controllers/network/node_address_sort_algorithm.go
  internal/app/machined/pkg/controllers/network/node_address_test.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/machinery/api/resource/definitions/enums/enums.pb.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/network/network_vtproto.pb.go
  pkg/machinery/config/config/machine.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/v1alpha1/v1alpha1_features.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
  pkg/machinery/nethelpers/addresssortalgorithm.go
  pkg/machinery/nethelpers/arpalltargets_enumer.go
  pkg/machinery/nethelpers/nethelpers.go
  pkg/machinery/resources/network/address_spec.go
  pkg/machinery/resources/network/deep_copy.generated.go
  pkg/machinery/resources/network/network_test.go
  pkg/machinery/resources/network/node_address.go
  pkg/machinery/resources/network/node_address_sort_algorithm.go
  website/content/v1.9/reference/api.md
  website/content/v1.9/reference/configuration/v1alpha1/config.md
  website/content/v1.9/schemas/config.schema.json
  website/content/v1.9/talos-guides/configuration/editing-machine-configuration.md
Labels: status/ok-to-test, status/ok-to-merge

#9878 fix: lock provisioning order of user disk partitions
  cmd/talosctl/cmd/mgmt/cluster/create.go
  internal/app/machined/pkg/controllers/block/user_disk_config.go
  internal/app/machined/pkg/controllers/block/user_disk_config_test.go
  pkg/machinery/resources/block/volume_config.go
  pkg/provision/providers/vm/disk.go
Labels: status/ok-to-test, status/ok-to-merge

#9888 fix: install iptables-nft to the host
  Dockerfile
  Makefile
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge, integration/cilium

#9872 chore: add integration tests for image-cache
  .github/workflows/ci.yaml
  .kres.yaml
  Makefile
  hack/test/e2e-qemu.sh
  hack/test/e2e.sh
  hack/test/patches/image-cache.yaml
  internal/integration/cli/image.go
  internal/integration/cli/list.go
  pkg/imager/cache/cache.go
Labels: status/ok-to-test, status/ok-to-merge, integration/image-cache

#9896 docs: fix a few mistakes in release notes
  hack/release.toml
Labels: status/ok-to-test, status/ok-to-merge

#9891 feat: update Linux to 6.12.3
  Makefile
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#9909 docs: build what's new for 1.9
  hack/release.toml
  pkg/machinery/config/types/v1alpha1/v1alpha1_examples.go
  website/content/v1.9/_index.md
  website/content/v1.9/introduction/support-matrix.md
  website/content/v1.9/introduction/what-is-new/index.md
  website/content/v1.9/reference/configuration/v1alpha1/config.md
  website/content/v1.9/talos-guides/install/bare-metal-platforms/network-config.md
  website/content/v1.9/talos-guides/install/cloud-platforms/azure.md
  website/content/v1.9/talos-guides/install/cloud-platforms/gcp.md
  website/content/v1.9/talos-guides/install/cloud-platforms/nocloud.md
  website/content/v1.9/talos-guides/install/cloud-platforms/openstack.md
  website/content/v1.9/talos-guides/install/cloud-platforms/upcloud.md
  website/content/v1.9/talos-guides/network/device-selector.md
  website/content/v1.9/talos-guides/upgrading-talos.md
Labels: status/ok-to-test, status/ok-to-merge

#9910 release(v1.9.0-beta.1): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9918 fix: power on the machine on reboot request in qemu power api
  pkg/provision/providers/qemu/controller.go
Labels: status/ok-to-test, status/ok-to-merge

#9919 fix: avoid nil-pointer-panic in `RegistriesConfigController`
  internal/app/machined/pkg/controllers/cri/registries_config.go
  internal/app/machined/pkg/controllers/cri/registries_config_test.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
Labels: status/ok-to-test, status/ok-to-merge

#9923 feat: update runc to 1.2.3
  Makefile
  hack/release.toml
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#9920 fix: Use mtu network option for podman
  pkg/provision/providers/docker/reflect.go
Labels: status/ok-to-merge

#9905 chore: enable proper parallel usage of TestDepth
  internal/integration/base/cli.go
  internal/integration/base/run.go
  internal/integration/cli/list.go
Labels: status/ok-to-test, status/ok-to-merge

#9930 docs: replace deprecated Hetzner server plans
  website/content/v1.8/talos-guides/install/cloud-platforms/hetzner.md
  website/content/v1.9/talos-guides/install/cloud-platforms/hetzner.md
Labels: status/ok-to-merge

#9938 fix: authorization config gen
  internal/app/machined/pkg/controllers/k8s/control_plane.go
  internal/app/machined/pkg/controllers/k8s/control_plane_test.go
Labels: status/ok-to-test, status/ok-to-merge

#9933 Multus (docs): fix typo
  website/content/v1.8/kubernetes-guides/network/multus.md
  website/content/v1.9/kubernetes-guides/network/multus.md
Labels: status/ok-to-merge

#9937 test: add an option to boot from a USB stick
  cmd/talosctl/cmd/mgmt/cluster/create.go
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/qemu/node.go
  pkg/provision/request.go
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9939 chore: drop semicolon for supporting vfat filesystems
  internal/app/machined/pkg/system/services/registry/registry.go
  internal/app/machined/pkg/system/services/registry/store.go
  internal/integration/cli/image.go
  pkg/imager/cache/cache.go
Labels: status/ok-to-test, status/ok-to-merge, integration/image-cache

#9940 feat: update Kubernetes to 1.32.0
  .github/workflows/ci.yaml
  .kres.yaml
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  website/content/v1.9/_index.md
  website/content/v1.9/introduction/what-is-new/index.md
  website/content/v1.9/reference/cli.md
  website/content/v1.9/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#9943 release(v1.8.4): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.8/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9950 test: fix flaky test NodeAddressSort
  internal/app/machined/pkg/controllers/network/node_address.go
  internal/app/machined/pkg/controllers/network/node_address_test.go
Labels: status/ok-to-test, status/ok-to-merge

#9941 fix: support image cache on VFAT USB stick
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/block/internal/volumes/format.go
  internal/app/machined/pkg/controllers/cri/image_cache_config.go
  internal/app/machined/pkg/controllers/cri/image_cache_config_test.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/provision/providers/qemu/launch.go
Labels: status/ok-to-test, status/ok-to-merge, integration/image-cache

#9954 fix: generating and serving registries with port
  internal/app/machined/pkg/system/services/registry/registry.go
  internal/app/machined/pkg/system/services/registry/registry_test.go
  pkg/imager/cache/cache.go
Labels: status/ok-to-test, status/ok-to-merge, integration/image-cache

#9929 docs: update image-cache doc for iso
  website/content/v1.9/talos-guides/configuration/image-cache.md
Labels: status/ok-to-test, status/ok-to-merge

#9961 feat: update containerd to v2.0.1
  Makefile
  go.mod
  go.sum
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
  website/content/v1.9/introduction/what-is-new/index.md
Labels: status/ok-to-test, status/ok-to-merge

#9953 fix: node identity flip
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/pkg/mount/system.go
Labels: status/ok-to-test, status/ok-to-merge

#9962 test: cleanup failed Kubernetes pods
  internal/integration/api/apply-config.go
  internal/integration/api/common.go
  internal/integration/api/etcd.go
  internal/integration/api/extensions_qemu.go
  internal/integration/api/reboot.go
  internal/integration/api/update-hostname.go
  internal/integration/api/volumes.go
  internal/integration/base/api.go
  internal/integration/base/k8s.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu, integration/trusted-boot, integration/qemu-encrypted-vip

#9964 docs: mention different paths for OpenEBS
  website/content/v1.8/kubernetes-guides/configuration/replicated-local-storage-with-openebs.md
  website/content/v1.9/kubernetes-guides/configuration/replicated-local-storage-with-openebs.md
Labels: status/ok-to-test, status/ok-to-merge

#9966 chore: add more debugging logs for META and volumes
  internal/app/machined/pkg/controllers/block/volume_manager.go
  internal/pkg/meta/internal/adv/syslinux/syslinux.go
  internal/pkg/meta/internal/adv/talos/talos.go
  internal/pkg/meta/meta.go
Labels: status/ok-to-test, status/ok-to-merge

#9967 chore: rekres for renovate changes
  .github/renovate.json
  .kres.yaml
Labels: status/ok-to-test, status/ok-to-merge

#9969 fix: match MAC addresses case-insensitive (nocloud)
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/metadata-v2-serverscom.yaml
Labels: status/ok-to-test, status/ok-to-merge

#9972 fix: renovate typo
  .github/renovate.json
  .kres.yaml
Labels: status/ok-to-test, status/ok-to-merge

#9926 Add --talosconfig option with generated talosconfig file when using talosctl
  website/content/v1.8/talos-guides/install/cloud-platforms/aws.md
  website/content/v1.9/talos-guides/install/cloud-platforms/aws.md
Labels: status/ok-to-merge

#9934 Fix 'containter' typo
  cmd/talosctl/cmd/talos/image.go
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-merge

#9968 feat: support link altnames/aliases
  api/resource/definitions/network/network.proto
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/network/address_spec.go
  internal/app/machined/pkg/controllers/network/address_spec_test.go
  internal/app/machined/pkg/controllers/network/link_config.go
  internal/app/machined/pkg/controllers/network/link_config_test.go
  internal/app/machined/pkg/controllers/network/link_spec.go
  internal/app/machined/pkg/controllers/network/link_spec_test.go
  internal/app/machined/pkg/controllers/network/link_status.go
  internal/app/machined/pkg/controllers/network/operator_config.go
  internal/app/machined/pkg/controllers/network/route_spec_test.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/network/network_vtproto.pb.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/machinery/resources/network/deep_copy.generated.go
  pkg/machinery/resources/network/link_status.go
  website/content/v1.9/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge

#9973 Update deploying-cilium.md - note about coredns and cilium
  website/content/v1.8/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.9/kubernetes-guides/network/deploying-cilium.md
Labels: status/ok-to-merge

#9975 release(v1.9.0): prepare release
  CHANGELOG.md
  go.mod
  hack/release.toml
  pkg/machinery/gendata/data/tag
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9976 docs: activate 1.9 docs as default
  website/config.toml
  website/content/v1.8/_index.md
  website/content/v1.9/_index.md
Labels: status/ok-to-test, status/ok-to-merge

#9987 fix: restore previous disk serial fetching
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/network/cmdline_test.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#9988 feat: remove cgroupsv1 in non-container mode
  .github/workflows/ci.yaml
  .github/workflows/integration-misc-2-cron.yaml
  .kres.yaml
  Makefile
  hack/release.toml
  hack/test/patches/cgroupsv1.yaml
  internal/app/machined/pkg/startup/cgroups.go
  internal/app/machined/pkg/startup/tasks.go
  internal/integration/api/cgroups.go
  internal/integration/api/process.go
  internal/pkg/mount/v2/cgroups.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
  website/content/v1.10/reference/kernel.md
Labels: status/ok-to-merge, integration/misc-2

#9956 Add lost steps in bootstrap. Add variant to upload image.
  website/content/v1.10/talos-guides/install/cloud-platforms/hetzner.md
  website/content/v1.8/talos-guides/install/cloud-platforms/hetzner.md
  website/content/v1.9/talos-guides/install/cloud-platforms/hetzner.md
Labels: status/ok-to-merge

#9992 chore: support gcr.io auth for cache and image gen
  pkg/imager/cache/cache.go
  pkg/imager/profile/input.go
Labels: status/ok-to-test, status/ok-to-merge

#9990 fix: make talosctl time work with PTP time sync
  internal/app/machined/internal/server/v1alpha1/v1alpha1_time.go
  internal/pkg/ntp/ntp.go
Labels: status/ok-to-test, status/ok-to-merge

#9997 chore: reduce memory usage for secureboot functions
  go.mod
  go.sum
  internal/pkg/secureboot/measure/internal/pcr/bank_data.go
  internal/pkg/secureboot/measure/internal/pcr/extend.go
  internal/pkg/secureboot/pesign/pesign.go
Labels: status/ok-to-test, status/ok-to-merge, integration/trusted-boot

#10004 fix: dashboard crash on CPU data
  internal/pkg/dashboard/components/header.go
Labels: status/ok-to-test, status/ok-to-merge

#10003 docs: fix several typos
  cmd/talosctl/cmd/talos/bootstrap.go
  website/content/v1.10/introduction/getting-started.md
  website/content/v1.10/reference/cli.md
  website/content/v1.10/talos-guides/install/virtualized-platforms/proxmox.md
  website/content/v1.9/introduction/getting-started.md
  website/content/v1.9/talos-guides/install/virtualized-platforms/proxmox.md
Labels: status/ok-to-test, status/ok-to-merge

#10010 fix: fix `Failed to initialize SELinux labeling handle` udev error
  Dockerfile
  hack/udevd/90-selinux.rules
Labels: status/ok-to-test, status/ok-to-merge

#10015 release(v1.10.0-alpha.0): prepare release
  .conform.yaml
  .github/renovate.json
  .kres.yaml
  CHANGELOG.md
  go.mod
  internal/app/machined/pkg/system/runner/process/process_test.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/gendata/data/tag
  pkg/makefs/ext4_test.go
  website/content/v1.10/reference/cli.md
  website/content/v1.10/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge, integration/provision, integration/misc, integration/qemu, integration/trusted-boot, integration/cilium, integration/extensions, integration/aws, integration/image-cache

#10016 refactor: use quirks in kernel args
  cmd/installer/pkg/install/install.go
  cmd/talosctl/cmd/mgmt/cluster/create.go
  internal/app/machined/pkg/controllers/network/platform_config_test.go
  internal/app/machined/pkg/runtime/platform.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/akamai/akamai.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/cloudstack/cloudstack.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/container/container.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/digitalocean/digitalocean.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/equinix.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/exoscale/exoscale.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/hcloud.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/opennebula/opennebula.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/oracle/oracle.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/scaleway.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/upcloud/upcloud.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/vultr/vultr.go
  internal/pkg/install/install.go
  pkg/imager/imager.go
  pkg/imager/imager_test.go
  pkg/machinery/imager/quirks/quirks.go
  pkg/machinery/kernel/kernel.go
  pkg/machinery/kernel/kernel_test.go
  pkg/provision/providers/qemu/node.go
  pkg/provision/request.go
Labels: status/ok-to-test, status/ok-to-merge

#10023 test: add a xfs makefs test
  pkg/makefs/xfs_test.go
Labels: status/ok-to-test, status/ok-to-merge

#10022 docs: fix two typos
  website/content/v1.10/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.10/talos-guides/install/boot-assets.md
  website/content/v1.9/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.9/talos-guides/install/boot-assets.md
Labels: status/ok-to-test, status/ok-to-merge

#10026 fix: get next rule number for IPv6 in the appropriate chain
  internal/app/machined/pkg/controllers/kubespan/routing_rules.go
Labels: status/ok-to-test, status/ok-to-merge

#10029 fix: reduce installer image
  .github/workflows/ci.yaml
  .github/workflows/integration-misc-1-cron.yaml
  .kres.yaml
  Dockerfile
  Makefile
  hack/test/e2e-qemu.sh
Labels: status/ok-to-test, status/ok-to-merge, integration/images, integration/misc-1

#10030 test: fix apparmor tests
  hack/test/e2e-qemu.sh
Labels: status/ok-to-test, status/ok-to-merge

#10028 fix: pull in containerd CNI deadlock fix
  Makefile
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge, integration/misc, integration/cilium

#10033 fix: pci driver rebind config validation
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/hardware/hardware_doc.go
  pkg/machinery/config/types/hardware/pci_driver_rebind_config.go
  pkg/machinery/config/types/hardware/testdata/pcidriverrebindconfig.yaml
  website/content/v1.10/reference/configuration/hardware/pcidriverrebindconfig.md
  website/content/v1.10/schemas/config.schema.json
  website/content/v1.9/reference/configuration/hardware/_index.md
  website/content/v1.9/reference/configuration/hardware/pcidriverrebindconfig.md
Labels: status/ok-to-test, status/ok-to-merge

#10031 fix: use correct default search domain
  internal/app/machined/pkg/controllers/network/resolver_config.go
  internal/app/machined/pkg/controllers/network/resolver_config_test.go
Labels: status/ok-to-test, status/ok-to-merge

#10041 fix: update go-blockdevice to v2.0.9
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#10043 test: use node informer instead of raw watch
  internal/integration/api/node-annotations.go
  internal/integration/api/node-labels.go
  internal/integration/api/node-taints.go
  internal/integration/base/k8s.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu

#10042 fix: talosctl support and race tests
  .github/workflows/ci.yaml
  .github/workflows/integration-qemu-race-cron.yaml
  .kres.yaml
  cmd/talosctl/cmd/talos/support.go
  go.mod
  go.sum
  internal/app/machined/pkg/startup/cgroups.go
  pkg/cluster/crashdump.go
Labels: status/ok-to-test, status/ok-to-merge

#10044 fix: ignore member not found error on leave cluster
  internal/pkg/etcd/etcd.go
Labels: status/ok-to-test, status/ok-to-merge

#10047 chore: update dependencies
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/docgen/go.mod
  hack/docgen/go.sum
  hack/structprotogen/go.mod
  hack/structprotogen/go.sum
  internal/app/apid/pkg/backend/apid_factory.go
  internal/app/machined/pkg/controllers/secrets/data/ca-certificates
  internal/integration/k8s/constants.go
  internal/pkg/rng/tpm.go
  internal/pkg/secureboot/tpm2/pcr.go
  internal/pkg/secureboot/tpm2/seal.go
  internal/pkg/secureboot/tpm2/unseal.go
  internal/pkg/tpm/tpm.go
  pkg/machinery/api/cluster/cluster.pb.go
  pkg/machinery/api/cluster/cluster_grpc.pb.go
  pkg/machinery/api/common/common.pb.go
  pkg/machinery/api/inspect/inspect.pb.go
  pkg/machinery/api/inspect/inspect_grpc.pb.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/machine/machine_grpc.pb.go
  pkg/machinery/api/resource/config/config.pb.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/cluster/cluster.pb.go
  pkg/machinery/api/resource/definitions/cri/cri.pb.go
  pkg/machinery/api/resource/definitions/enums/enums.pb.go
  pkg/machinery/api/resource/definitions/etcd/etcd.pb.go
  pkg/machinery/api/resource/definitions/extensions/extensions.pb.go
  pkg/machinery/api/resource/definitions/files/files.pb.go
  pkg/machinery/api/resource/definitions/hardware/hardware.pb.go
  pkg/machinery/api/resource/definitions/k8s/k8s.pb.go
  pkg/machinery/api/resource/definitions/kubeaccess/kubeaccess.pb.go
  pkg/machinery/api/resource/definitions/kubespan/kubespan.pb.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/perf/perf.pb.go
  pkg/machinery/api/resource/definitions/proto/proto.pb.go
  pkg/machinery/api/resource/definitions/runtime/runtime.pb.go
  pkg/machinery/api/resource/definitions/secrets/secrets.pb.go
  pkg/machinery/api/resource/definitions/siderolink/siderolink.pb.go
  pkg/machinery/api/resource/definitions/time/time.pb.go
  pkg/machinery/api/resource/definitions/v1alpha1/v1alpha1.pb.go
  pkg/machinery/api/resource/network/device_config.pb.go
  pkg/machinery/api/security/security.pb.go
  pkg/machinery/api/security/security_grpc.pb.go
  pkg/machinery/api/storage/storage.pb.go
  pkg/machinery/api/storage/storage_grpc.pb.go
  pkg/machinery/api/time/time.pb.go
  pkg/machinery/api/time/time_grpc.pb.go
  pkg/machinery/gendata/data/pkgs
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/amd64/snp.efi
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/arm64/snp.efi
Labels: status/ok-to-test, status/ok-to-merge, integration/extensions

#10052 fix: build of talosctl on non-Linux platforms
  internal/pkg/tpm/tpm_linux.go
  internal/pkg/tpm/tpm_other.go
Labels: status/ok-to-test, status/ok-to-merge

#10053 release(v1.9.1): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#10054 chore(ci): drop equinix metal e2e-test
  .github/workflows/ci.yaml
  .github/workflows/integration-equinix-metal-cron.yaml
  .github/workflows/slack-notify.yaml
  .kres.yaml
  .secrets.yaml
  .sops.yaml
  hack/test/e2e-equinix-metal-prepare.sh
  hack/test/e2e-equinix-metal.sh
  hack/test/tfvars/equinix-arm64.yaml
  hack/test/tfvars/equinix-metal.jq
Labels: status/ok-to-test, status/ok-to-merge

#10057 refactor: generate /etc/os-release file static way
  Dockerfile
  Makefile
  internal/app/machined/pkg/startup/os_release.go
  internal/app/machined/pkg/startup/startup.go
  pkg/machinery/version/gen.go
  pkg/machinery/version/os-release
  pkg/machinery/version/osrelease.go
Labels: status/ok-to-test, status/ok-to-merge

#10059 fix: exclude disks with empty transport for disk selector
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider_test.go
Labels: status/ok-to-test, status/ok-to-merge

#10060 fix: update field name for bus path disk selector
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider_test.go
Labels: status/ok-to-test, status/ok-to-merge

#10063 refactor: rewrite cloud uploader to use AWS SDK Go v2
  hack/cloud-image-uploader/aws.go
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/cloud-image-uploader/main.go
Labels: status/ok-to-test, status/ok-to-merge, integration/cloud-images
