Repository siderolabs/talos, pull requests merged in 2024-10, with the labels that each got.

#9337 feat: support cgroup deep analysis in `talosctl`
  Dockerfile
  api/machine/machine.proto
  cmd/talosctl/cmd/talos/cgroups.go
  cmd/talosctl/cmd/talos/cgroupsprinter/presets.go
  cmd/talosctl/cmd/talos/cgroupsprinter/presets/cpu.yaml
  cmd/talosctl/cmd/talos/cgroupsprinter/presets/cpuset.yaml
  cmd/talosctl/cmd/talos/cgroupsprinter/presets/io.yaml
  cmd/talosctl/cmd/talos/cgroupsprinter/presets/memory.yaml
  cmd/talosctl/cmd/talos/cgroupsprinter/presets/process.yaml
  cmd/talosctl/cmd/talos/cgroupsprinter/presets/swap.yaml
  cmd/talosctl/cmd/talos/cgroupsprinter/presets_test.go
  cmd/talosctl/cmd/talos/cgroupsprinter/schema.go
  cmd/talosctl/cmd/talos/cgroupsprinter/tree.go
  hack/release.toml
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/integration/cli/cgroups.go
  internal/pkg/cgroups/cgroups.go
  internal/pkg/cgroups/raw.go
  internal/pkg/cgroups/tar.go
  internal/pkg/cgroups/tar_test.go
  internal/pkg/cgroups/testdata/cgroup.tar.gz
  internal/pkg/cgroups/value.go
  internal/pkg/cgroups/value_test.go
  internal/pkg/containers/container.go
  internal/pkg/containers/cri/cri.go
  internal/pkg/zboot/zboot.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/machine/machine_vtproto.pb.go
  website/content/v1.9/advanced/cgroups-analysis.md
  website/content/v1.9/reference/api.md
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9346 chore: better lvm2 tests
  .github/workflows/ci.yaml
  .github/workflows/integration-extensions-cron.yaml
  .github/workflows/integration-qemu-cron.yaml
  .github/workflows/integration-qemu-csi-rook-ceph-cron.yaml
  .github/workflows/integration-qemu-encrypted-vip-cron.yaml
  .github/workflows/integration-qemu-race-cron.yaml
  .kres.yaml
  hack/test/patches/dm-raid-module.yaml
  internal/integration/api/common.go
  internal/integration/api/volumes.go
  internal/integration/api/watchdog.go
  internal/integration/base/base.go
  internal/integration/k8s/apparmor.go
Labels: status/ok-to-test, status/ok-to-merge

#9413 fix: prevent file descriptors leaks to child processes
  .golangci.yml
  go.mod
  go.sum
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/pkg/logind/logind.go
  internal/pkg/mount/switchroot/switchroot.go
Labels: status/ok-to-test, status/ok-to-merge

#9409 docs: Fix typo in extraMounts directory definition for openebs/mayastor documentation
  website/content/v1.8/kubernetes-guides/configuration/replicated-local-storage-with-openebs.md
  website/content/v1.9/kubernetes-guides/configuration/replicated-local-storage-with-openebs.md
Labels: status/ok-to-merge

#9420 docs: fix nvidia CRI config example
  website/content/v1.8/talos-guides/configuration/nvidia-gpu.md
  website/content/v1.9/talos-guides/configuration/nvidia-gpu.md
Labels: status/ok-to-test, status/ok-to-merge

#9396 feat: replace eudev with systemd-udevd
  Dockerfile
  Makefile
  internal/app/machined/pkg/system/services/udevd.go
  internal/integration/api/extensions_qemu.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu-csi, integration/extensions

#9422 fix: multiple fixes for LVM activation
  Makefile
  internal/app/machined/pkg/controllers/block/lvm.go
  internal/integration/api/volumes.go
  internal/integration/base/k8s.go
  internal/integration/k8s/testdata/rook-ceph-cluster-values.yaml
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu, integration/qemu-csi, integration/extensions

#9433 fix: make /var/run empty on reboots
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu, integration/extensions

#9436 feat: enable QEDF driver
  Makefile
  go.mod
  go.work
  hack/cloud-image-uploader/go.mod
  hack/docgen/go.mod
  hack/gotagsrewrite/go.mod
  hack/module-sig-verify/go.mod
  hack/modules-amd64.txt
  hack/modules-arm64.txt
  hack/release.toml
  hack/structprotogen/go.mod
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
  pkg/machinery/go.mod
Labels: status/ok-to-test, status/ok-to-merge

#9443 feat: bring in lpfc kernel module driver
  Makefile
  hack/modules-amd64.txt
  hack/modules-arm64.txt
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#9447 fix: fix mdadm system extension
  Makefile
  internal/integration/api/extensions_qemu.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu-csi, integration/extensions

#9455 fix: improve container detection
  Dockerfile
  internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
Labels: status/ok-to-test, status/ok-to-merge

#9462 feat: update Flannel to v0.25.7
  hack/release.toml
  pkg/flannel/template.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#9453 fix: do not stop udevd before unmounting volumes
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/ok-to-test, status/ok-to-merge

#9464 fix: update grpc-go the latest patch release
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#9465 fix: wipe system partitions correctly via kernel args
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/pkg/partition/wipe.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu

#9476 release(v1.8.1): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.8/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9477 test: skip lvm test if not enough user disks available
  internal/integration/api/volumes.go
Labels: status/ok-to-test, status/ok-to-merge, integration/trusted-boot

#9475 docs: add egress documentation
  website/content/v1.6/advanced/egress-domains.md
  website/content/v1.7/advanced/egress-domains.md
  website/content/v1.8/advanced/egress-domains.md
  website/content/v1.9/advanced/egress-domains.md
Labels: status/ok-to-test, status/ok-to-merge

#9488 Fix typo in documentation
  website/content/v1.8/kubernetes-guides/configuration/device-plugins.md
Labels: status/ok-to-test, status/ok-to-merge

#9497 fix: do not use pflag csv comma reader for config-patch
  cmd/talosctl/cmd/talos/apply-config.go
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9478 test: skip no error test in Cilium
  hack/test/e2e.sh
Labels: status/ok-to-test, status/ok-to-merge, integration/cilium

#9507 fix: skip ram disks
  internal/app/machined/pkg/controllers/block/discovery.go
  internal/app/machined/pkg/controllers/block/disks.go
Labels: status/ok-to-test, status/ok-to-merge

#9508 test: update provision upgrade tests for Talos 1.9
  Makefile
  internal/integration/provision/upgrade.go
Labels: status/ok-to-test, status/ok-to-merge

#9506 chore(ci): add config for lldpd extension
  hack/test/extensions/extension-patch-filter.jq
  hack/test/patches/extensions.yaml
Labels: status/ok-to-test, status/ok-to-merge

#9509 chore: use virtio driver for disks in arm64
  cmd/talosctl/cmd/mgmt/cluster/create.go
Labels: status/ok-to-test, status/ok-to-merge

#9510 fix: json logging panic
  go.mod
  go.sum
  internal/app/machined/pkg/runtime/logging/circular.go
Labels: status/ok-to-test, status/ok-to-merge

#9512 chore: add arm64 target for integration-test
  Dockerfile
  Makefile
Labels: status/ok-to-test, status/ok-to-merge

#9513 fix: support `extra-disks` when using iso
  pkg/provision/providers/qemu/launch.go
Labels: status/ok-to-test, status/ok-to-merge

#9484 feat: add recommended app.kubernetes.io labels to control-plane Pods
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
Labels: status/ok-to-merge

#9467 feat: optionally decode hcloud userdata as base64 when fetching machine configuration
  internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/export_test.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/hcloud.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/hcloud_test.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/testdata/userdata-base64.txt
  internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/testdata/userdata-plain.yaml
Labels: status/ok-to-merge

#9504 chore: update siderolabs/crypto module and return proper ALPN
  cmd/talosctl/acompat/acompat.go
  cmd/talosctl/main.go
  go.mod
  go.sum
  internal/app/machined/pkg/system/services/apid.go
  internal/pkg/mount/switchroot/switchroot.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge, integration/provision

#9424 chore: add proto-codec/codec
  Makefile
  cmd/talosctl/cmd/talos/root.go
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/docgen/go.mod
  hack/docgen/go.sum
  internal/app/apid/main.go
  internal/app/apid/pkg/backend/apid.go
  internal/app/apid/pkg/provider/provider.go
  pkg/grpc/codec/codec.go
  pkg/grpc/factory/factory.go
  pkg/grpc/proxy/backend/local.go
  pkg/machinery/client/client.go
  pkg/machinery/client/secure_credentials.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge, integration/misc, integration/qemu

#9430 doc: Update Nvidia docs with Proprietary/OSS hardware reqs
  website/content/v1.8/talos-guides/configuration/nvidia-gpu-proprietary.md
  website/content/v1.8/talos-guides/configuration/nvidia-gpu.md
  website/content/v1.9/talos-guides/configuration/nvidia-gpu-proprietary.md
  website/content/v1.9/talos-guides/configuration/nvidia-gpu.md
Labels: status/ok-to-merge

#9511 test: add json logs test environment
  .github/workflows/ci.yaml
  .github/workflows/integration-qemu-cron.yaml
  .kres.yaml
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/mgmt/json_logs_launch.go
  cmd/talosctl/cmd/mgmt/kms_launch.go
  hack/test/e2e-qemu.sh
  pkg/provision/options.go
  pkg/provision/providers/qemu/create.go
  pkg/provision/providers/qemu/destroy.go
  pkg/provision/providers/vm/json-logs.go
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9517 feat: add Talos 1.9 compatiblity guarantees
  pkg/machinery/compatibility/kubernetes_version.go
  pkg/machinery/compatibility/kubernetes_version_test.go
  pkg/machinery/compatibility/talos19/talos19.go
  pkg/machinery/compatibility/talos_version.go
  pkg/machinery/compatibility/talos_version_test.go
Labels: status/ok-to-test, status/ok-to-merge

#9525 release(v1.9.0-alpha.0): prepare release
  .conform.yaml
  CHANGELOG.md
  go.mod
  hack/release.toml
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/gendata/data/tag
  website/content/v1.9/reference/cli.md
  website/content/v1.9/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge

#9523 fix: update incorrect alias for PCIDevice resource
  pkg/machinery/resources/hardware/pcidevice.go
Labels: status/ok-to-test, status/ok-to-merge

#9514 feat: update Kubernetes to v1.32.0-alpha.1
  .github/workflows/ci.yaml
  .github/workflows/integration-provision-0-cron.yaml
  .github/workflows/integration-provision-1-cron.yaml
  .github/workflows/integration-provision-2-cron.yaml
  .kres.yaml
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/v1.9/_index.md
  website/content/v1.9/reference/cli.md
  website/content/v1.9/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge, integration/provision

#9201 chore: support debug shell for advanced development
  Dockerfile
  Makefile
  cmd/talosctl/cmd/mgmt/cluster/create.go
  internal/pkg/mount/switchroot/switchroot.go
  pkg/provision/options.go
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/qemu/node.go
  website/content/v1.9/advanced/developing-talos.md
Labels: status/ok-to-test, status/ok-to-merge

#9528 Fix typo in prodnotes.md
  website/content/v1.8/introduction/prodnotes.md
  website/content/v1.9/introduction/prodnotes.md
Labels: status/ok-to-merge

#9535 fix: correct error message for invalid ip=
  internal/app/machined/pkg/controllers/network/cmdline.go
Labels: status/ok-to-merge

#9540 feat: update Kubernetes to 1.32.0-alpha.2
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/v1.9/_index.md
  website/content/v1.9/reference/cli.md
  website/content/v1.9/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#9541 docs: fix image factory links
  website/content/v1.7/talos-guides/install/single-board-computers/bananapi_m64.md
  website/content/v1.7/talos-guides/install/single-board-computers/jetson_nano.md
  website/content/v1.7/talos-guides/install/single-board-computers/libretech_all_h3_cc_h5.md
  website/content/v1.7/talos-guides/install/single-board-computers/nanopi_r4s.md
  website/content/v1.7/talos-guides/install/single-board-computers/orangepi_r1_plus_lts.md
  website/content/v1.7/talos-guides/install/single-board-computers/pine64.md
  website/content/v1.7/talos-guides/install/single-board-computers/rock4cplus.md
  website/content/v1.7/talos-guides/install/single-board-computers/rock64.md
  website/content/v1.7/talos-guides/install/single-board-computers/rockpi_4.md
  website/content/v1.7/talos-guides/install/single-board-computers/rockpi_4c.md
  website/content/v1.7/talos-guides/install/single-board-computers/rpi_generic.md
  website/content/v1.8/talos-guides/install/single-board-computers/bananapi_m64.md
  website/content/v1.8/talos-guides/install/single-board-computers/jetson_nano.md
  website/content/v1.8/talos-guides/install/single-board-computers/libretech_all_h3_cc_h5.md
  website/content/v1.8/talos-guides/install/single-board-computers/nanopi_r4s.md
  website/content/v1.8/talos-guides/install/single-board-computers/orangepi_r1_plus_lts.md
  website/content/v1.8/talos-guides/install/single-board-computers/pine64.md
  website/content/v1.8/talos-guides/install/single-board-computers/rock4cplus.md
  website/content/v1.8/talos-guides/install/single-board-computers/rock64.md
  website/content/v1.8/talos-guides/install/single-board-computers/rockpi_4.md
  website/content/v1.8/talos-guides/install/single-board-computers/rockpi_4c.md
  website/content/v1.8/talos-guides/install/single-board-computers/rpi_generic.md
  website/content/v1.9/talos-guides/install/single-board-computers/bananapi_m64.md
  website/content/v1.9/talos-guides/install/single-board-computers/jetson_nano.md
  website/content/v1.9/talos-guides/install/single-board-computers/libretech_all_h3_cc_h5.md
  website/content/v1.9/talos-guides/install/single-board-computers/nanopi_r4s.md
  website/content/v1.9/talos-guides/install/single-board-computers/orangepi_r1_plus_lts.md
  website/content/v1.9/talos-guides/install/single-board-computers/pine64.md
  website/content/v1.9/talos-guides/install/single-board-computers/rock4cplus.md
  website/content/v1.9/talos-guides/install/single-board-computers/rock64.md
  website/content/v1.9/talos-guides/install/single-board-computers/rockpi_4.md
  website/content/v1.9/talos-guides/install/single-board-computers/rockpi_4c.md
  website/content/v1.9/talos-guides/install/single-board-computers/rpi_generic.md
Labels: status/ok-to-test, status/ok-to-merge

#9546 feat: update runc to 1.2.0 final
  Makefile
  hack/release.toml
  internal/integration/api/cgroups.go
  internal/integration/api/process.go
  internal/integration/base/api.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge, integration/misc

#9547 docs: add documentation on performance tuning
  website/content/v1.8/talos-guides/configuration/performance-tuning.md
  website/content/v1.9/talos-guides/configuration/performance-tuning.md
Labels: status/ok-to-test, status/ok-to-merge

#9553 feat: update Flannel to v0.26.0
  hack/release.toml
  pkg/flannel/template.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#9542 chore: move system extensions' udev rules
  Dockerfile
  Makefile
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/extensions/extensions.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#9555 fix: rework the 'metal-iso' config acquisition
  .github/workflows/ci.yaml
  .github/workflows/integration-misc-3-cron.yaml
  .kres.yaml
  api/resource/definitions/enums/enums.proto
  cmd/talosctl/cmd/mgmt/cluster/create.go
  hack/test/e2e-qemu.sh
  internal/app/machined/pkg/controllers/block/discovery.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
  pkg/machinery/api/resource/definitions/enums/enums.pb.go
  pkg/machinery/cel/cel.go
  pkg/machinery/resources/block/block.go
  pkg/machinery/resources/block/filesystemtype.go
  pkg/machinery/resources/block/volumetype_enumer.go
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/qemu/node.go
  pkg/provision/request.go
  website/content/v1.9/reference/api.md
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge, integration/misc-3

#9562 feat: update containerd to v2.0.0-rc.6
  Makefile
  go.mod
  go.sum
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#9564 fix: talosctl process null character
  internal/pkg/miniprocfs/processes.go
Labels: status/ok-to-test, status/ok-to-merge

#9559 chore: simplify `DNSUpstreamController` and `DNSUpstream` resource
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/docgen/go.mod
  hack/docgen/go.sum
  internal/app/machined/pkg/controllers/network/dns_resolve_cache.go
  internal/app/machined/pkg/controllers/network/dns_resolve_cache_test.go
  internal/app/machined/pkg/controllers/network/dns_upstream.go
  internal/pkg/dns/dns.go
  internal/pkg/dns/dns_test.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/machinery/resources/network/dns_upstream.go
Labels: status/ok-to-test, status/ok-to-merge, integration/misc, integration/aws

#9567 Add Mynewsdesk to ADOPTERS.md
  ADOPTERS.md
Labels: status/ok-to-merge

#9561 Improve field description for BridgeSTP, BridgeVLAN
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  website/content/v1.9/reference/configuration/v1alpha1/config.md
  website/content/v1.9/schemas/config.schema.json
Labels: status/ok-to-merge

#9576 feat: allow extensions to log to console
  internal/app/machined/pkg/system/runner/containerd/containerd.go
  internal/app/machined/pkg/system/services/extension.go
  pkg/machinery/extensions/services/services.go
  website/content/v1.8/advanced/extension-services.md
  website/content/v1.9/advanced/extension-services.md
Labels: status/ok-to-test, status/ok-to-merge

#9584 fix: include iptables/netfilter ipv6 fix
  Makefile
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge, integration/misc

#9585 fix: update the CRI sandbox image reference
  internal/integration/api/containers.go
  pkg/images/list.go
Labels: status/ok-to-test, status/ok-to-merge

#9586 release(v1.8.2): prepare release
  CHANGELOG.md
  go.mod
  hack/release.toml
  pkg/machinery/gendata/data/tag
  website/content/v1.8/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9580 fix: generation of SecureBoot iso
  pkg/imager/iso/uefi.go
Labels: status/ok-to-test, status/ok-to-merge, integration/trusted-boot

#9583 feat: add parsing of vlanNNNN:ethX style VLAN cmdline args
  internal/app/machined/pkg/controllers/network/cmdline.go
  internal/app/machined/pkg/controllers/network/cmdline_test.go
Labels: status/ok-to-merge

#9566 refactor: remove unmaintained github.com/vishvananda/netlink
  .golangci.yml
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/kubespan/manager.go
  internal/app/machined/pkg/controllers/kubespan/manager_test.go
  internal/app/machined/pkg/controllers/kubespan/routing_rules.go
  pkg/provision/providers/vm/network.go
Labels: status/ok-to-test, status/ok-to-merge

#9588 fix: prevent panic in nocloud platform code
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud.go
Labels: status/ok-to-test, status/ok-to-merge

#9489 feat: remove wrapperd and launch processes directly
  Dockerfile
  go.mod
  go.sum
  internal/app/machined/main.go
  internal/app/machined/pkg/system/runner/process/process.go
  internal/app/machined/pkg/system/runner/process/process_test.go
  internal/app/machined/pkg/system/services/dashboard.go
  internal/app/wrapperd/main.go
Labels: status/ok-to-test, status/ok-to-merge

#9590 chore: small refactoring
  internal/app/machined/pkg/system/runner/process/process.go
Labels: status/ok-to-test, status/ok-to-merge

#9501 feat: introduce metal agent mode
  internal/app/machined/pkg/controllers/block/volume_config.go
  internal/app/machined/pkg/controllers/runtime/maintenance_service.go
  internal/app/machined/pkg/runtime/mode.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/maintenance/server.go
  pkg/machinery/cel/celenv/celenv.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#9591 fix: do not trim 0 from process SELinux label
  internal/pkg/miniprocfs/processes.go
Labels: status/ok-to-test, status/ok-to-merge

#9595 Fixing documentation typo
  website/content/v1.8/talos-guides/install/bare-metal-platforms/network-config.md
Labels: status/ok-to-merge

#9598 docs: update network-config.md (cont)
  website/content/v1.9/talos-guides/install/bare-metal-platforms/network-config.md
Labels: status/ok-to-test, status/ok-to-merge

#9473 refactor: replace the old v1 mount package with new one
  internal/app/init/main.go
  internal/app/machined/main.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/extension.go
  internal/pkg/mount/bpffs.go
  internal/pkg/mount/cgroups.go
  internal/pkg/mount/iter.go
  internal/pkg/mount/mount.go
  internal/pkg/mount/mount_test.go
  internal/pkg/mount/options.go
  internal/pkg/mount/pseudo.go
  internal/pkg/mount/squashfs.go
  internal/pkg/mount/switchroot/switchroot.go
  internal/pkg/mount/unmount.go
  internal/pkg/mount/v2/all.go
  internal/pkg/mount/v2/cgroups.go
  internal/pkg/mount/v2/mount.go
  internal/pkg/mount/v2/overlay.go
  internal/pkg/mount/v2/points.go
  internal/pkg/mount/v2/pseudo.go
  internal/pkg/mount/v2/repair_test.go
  internal/pkg/mount/v2/squashfs.go
Labels: status/ok-to-test, status/ok-to-merge

#9599 fix: use more correct condition to skip generating hosts files
  internal/pkg/containers/cri/containerd/hosts.go
  internal/pkg/containers/cri/containerd/hosts_test.go
Labels: status/ok-to-test, status/ok-to-merge

#9601 feat: update Kubernetes to v1.32.0-alpha.3
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/v1.9/_index.md
  website/content/v1.9/reference/cli.md
  website/content/v1.9/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#9597 docs: Added warning about NVMe bus path bug
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  website/content/v1.9/reference/configuration/v1alpha1/config.md
  website/content/v1.9/schemas/config.schema.json
Labels: status/ok-to-merge

#9606 chore: disable coredns cache for cluster domain
  internal/app/machined/pkg/controllers/k8s/templates/core-dns-template.yaml
Labels: status/ok-to-test, status/ok-to-merge

#9618 fix: mount pseudo sub-mountpoints in init
  internal/app/init/main.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/ok-to-test, status/ok-to-merge
