Repository siderolabs/talos, pull requests merged in 2024-08, with the labels that each got.

#9098 chore: add test for crun extension
  Makefile
  internal/integration/api/extensions_qemu.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge, integration/extensions

#9107 feat: update Kubernetes to 1.31.0-rc.0
  Makefile
  go.mod
  go.sum
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
  website/content/v1.8/_index.md
  website/content/v1.8/reference/cli.md
  website/content/v1.8/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#9101 docs: better for-loop in shell
  website/content/v1.8/talos-guides/install/cloud-platforms/aws.md
Labels: status/ok-to-merge

#9104 docs: replace removed Cilium/kubeProxyReplacement value
  website/content/v1.8/kubernetes-guides/network/deploying-cilium.md
Labels: status/ok-to-merge

#9120 feat: update Kubernetes to 1.31.0-rc.1
  Makefile
  go.mod
  go.sum
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/v1.8/_index.md
  website/content/v1.8/reference/cli.md
  website/content/v1.8/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#9119 Remove arch-specific etcd image tag
  pkg/machinery/config/types/v1alpha1/v1alpha1_etcdconfig.go
Labels: status/ok-to-merge

#9122 chore: generate deepcopy for SecureBootAssets type
  pkg/imager/profile/deep_copy.generated.go
  pkg/imager/profile/profile.go
Labels: status/ok-to-test, status/ok-to-merge

#9099 fix: fix graph diffs in dashboard when node aliases are used
  internal/pkg/dashboard/apidata/source.go
  internal/pkg/dashboard/dashboard.go
  internal/pkg/dashboard/logdata/logdata.go
  internal/pkg/dashboard/resolver/resolver.go
Labels: status/ok-to-test, status/ok-to-merge

#9129 chore: support `unsupported` flag for mkfs
  Makefile
  hack/release.toml
  hack/test/e2e-qemu.sh
  internal/pkg/partition/format.go
  pkg/machinery/api/cluster/cluster.pb.go
  pkg/machinery/api/cluster/cluster_grpc.pb.go
  pkg/machinery/api/common/common.pb.go
  pkg/machinery/api/inspect/inspect.pb.go
  pkg/machinery/api/inspect/inspect_grpc.pb.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/machine/machine_grpc.pb.go
  pkg/machinery/api/resource/config/config.pb.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/cluster/cluster.pb.go
  pkg/machinery/api/resource/definitions/cri/cri.pb.go
  pkg/machinery/api/resource/definitions/enums/enums.pb.go
  pkg/machinery/api/resource/definitions/etcd/etcd.pb.go
  pkg/machinery/api/resource/definitions/extensions/extensions.pb.go
  pkg/machinery/api/resource/definitions/files/files.pb.go
  pkg/machinery/api/resource/definitions/hardware/hardware.pb.go
  pkg/machinery/api/resource/definitions/k8s/k8s.pb.go
  pkg/machinery/api/resource/definitions/kubeaccess/kubeaccess.pb.go
  pkg/machinery/api/resource/definitions/kubespan/kubespan.pb.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/perf/perf.pb.go
  pkg/machinery/api/resource/definitions/proto/proto.pb.go
  pkg/machinery/api/resource/definitions/runtime/runtime.pb.go
  pkg/machinery/api/resource/definitions/secrets/secrets.pb.go
  pkg/machinery/api/resource/definitions/siderolink/siderolink.pb.go
  pkg/machinery/api/resource/definitions/time/time.pb.go
  pkg/machinery/api/resource/definitions/v1alpha1/v1alpha1.pb.go
  pkg/machinery/api/resource/network/device_config.pb.go
  pkg/machinery/api/security/security.pb.go
  pkg/machinery/api/security/security_grpc.pb.go
  pkg/machinery/api/storage/storage.pb.go
  pkg/machinery/api/storage/storage_grpc.pb.go
  pkg/machinery/api/time/time.pb.go
  pkg/machinery/api/time/time_grpc.pb.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/extras
  pkg/machinery/gendata/data/pkgs
  pkg/makefs/makefs.go
  pkg/makefs/xfs.go
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/amd64/snp.efi
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/arm64/snp.efi
Labels: status/ok-to-test, status/ok-to-merge

#9137 chore: fix k8s tests
  internal/integration/base/k8s.go
Labels: status/ok-to-test, status/ok-to-merge

#9126 chore: bump deps
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/docgen/go.mod
  hack/docgen/go.sum
  hack/structprotogen/go.mod
  hack/structprotogen/go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu, integration/qemu-race

#9139 chore: document slim kubelet image
  hack/release.toml
Labels: status/ok-to-test, status/ok-to-merge

#9138 chore(ci): update nvidia integration tests
  .github/workflows/ci.yaml
  .github/workflows/integration-aws-nvidia-nonfree-cron.yaml
  .github/workflows/integration-aws-nvidia-oss-cron.yaml
  .kres.yaml
  hack/test/e2e-aws-prepare.sh
Labels: status/ok-to-test, status/ok-to-merge

#9095 docs: AWS getting started re-write
  website/content/v1.7/talos-guides/install/cloud-platforms/aws.md
  website/content/v1.8/talos-guides/install/cloud-platforms/aws.md
Labels: status/ok-to-test, status/ok-to-merge

#9151 chore: bump github.com/docker/docker to v27.1.1+incompatible
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#9152 chore(ci): fix cilium ci tests
  hack/test/e2e.sh
Labels: status/ok-to-test, status/ok-to-merge, integration/cilium

#9154 docs: fix typo in doc
  website/content/v0.10/guides/configuring-network-connectivity.md
  website/content/v0.11/guides/configuring-network-connectivity.md
  website/content/v0.12/guides/configuring-network-connectivity.md
  website/content/v0.13/guides/configuring-network-connectivity.md
  website/content/v0.14/guides/configuring-network-connectivity.md
  website/content/v0.8/guides/configuring-network-connectivity.md
  website/content/v0.9/guides/configuring-network-connectivity.md
  website/content/v1.0/learn-more/talos-network-connectivity.md
  website/content/v1.1/learn-more/talos-network-connectivity.md
  website/content/v1.2/learn-more/talos-network-connectivity.md
  website/content/v1.3/learn-more/talos-network-connectivity.md
  website/content/v1.4/learn-more/talos-network-connectivity.md
  website/content/v1.5/learn-more/talos-network-connectivity.md
  website/content/v1.6/learn-more/talos-network-connectivity.md
  website/content/v1.7/learn-more/talos-network-connectivity.md
  website/content/v1.8/learn-more/talos-network-connectivity.md
Labels: status/ok-to-merge

#9155 Fix default openEBS StorageClass base path in docs to match the default in openEBS docs
  website/content/v1.8/kubernetes-guides/configuration/replicated-local-storage-with-openebs.md
Labels: status/ok-to-merge

#9160 fix: add dns-resolve-cache to the support bundle
  go.mod
  go.sum
  go.work
  pkg/machinery/go.mod
Labels: status/ok-to-test, status/ok-to-merge

#9159 feat: scaleway routed ip
  internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/scaleway.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/scaleway_test.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/testdata/expected-v1.yaml
  internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/testdata/expected-v2.yaml
  internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/testdata/metadata-v1.json
  internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/testdata/metadata-v2.json
Labels: status/ok-to-merge

#9131 fix talos version in vmware.sh for 1.7.6
  website/content/v1.7/_index.md
  website/content/v1.7/talos-guides/install/virtualized-platforms/vmware.md
  website/content/v1.7/talos-guides/install/virtualized-platforms/vmware/cp.patch.yaml
  website/content/v1.7/talos-guides/install/virtualized-platforms/vmware/vmware.sh
  website/content/v1.8/_index.md
  website/content/v1.8/talos-guides/install/virtualized-platforms/vmware.md
  website/content/v1.8/talos-guides/install/virtualized-platforms/vmware/cp.patch.yaml
  website/content/v1.8/talos-guides/install/virtualized-platforms/vmware/vmware.sh
Labels: status/ok-to-merge

#9163 docs: fix the VMWare docs
  website/content/v1.7/talos-guides/install/virtualized-platforms/vmware.md
  website/content/v1.8/talos-guides/install/virtualized-platforms/vmware.md
Labels: status/ok-to-test, status/ok-to-merge

#9146 feat: ISO VolumeID named with ReleaseID
  Makefile
  pkg/imager/iso/grub.go
  pkg/imager/iso/iso.go
  pkg/imager/iso/iso_test.go
  pkg/imager/iso/uefi.go
  pkg/machinery/imager/quirks/quirks.go
Labels: status/ok-to-merge, integration/images

#9165 chore: fix release notes
  hack/release.toml
Labels: status/ok-to-test, status/ok-to-merge

#9162 chore: support arm64 kexec from zboot kernel images
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/zboot/zboot.go
Labels: status/ok-to-test, status/ok-to-merge

#9158 feat: bundle (some) CNI plugins with Talos core
  Dockerfile
  Makefile
  api/api.descriptors
  api/resource/definitions/k8s/k8s.proto
  cmd/talosctl/cmd/talos/image.go
  hack/release.toml
  internal/app/machined/pkg/controllers/k8s/control_plane.go
  internal/app/machined/pkg/controllers/k8s/manifest_test.go
  pkg/flannel/gen.go
  pkg/flannel/template.go
  pkg/images/list.go
  pkg/machinery/api/resource/definitions/k8s/k8s.pb.go
  pkg/machinery/api/resource/definitions/k8s/k8s_vtproto.pb.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
  pkg/machinery/resources/k8s/manifests_config.go
  website/content/v1.8/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge, integration/cilium

#9176 feat: provide device extra settle timeout
  hack/release.toml
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/udevd.go
  pkg/machinery/constants/constants.go
  website/content/v1.8/reference/kernel.md
Labels: status/ok-to-test, status/ok-to-merge

#9177 chore: drop image assets from release
  .github/workflows/ci.yaml
  .kres.yaml
  hack/release.toml
  website/content/v1.8/advanced/talos-api-access-from-k8s.md
  website/content/v1.8/talos-guides/install/bare-metal-platforms/digital-rebar.md
  website/content/v1.8/talos-guides/install/bare-metal-platforms/pxe.md
  website/content/v1.8/talos-guides/install/boot-assets.md
  website/content/v1.8/talos-guides/install/cloud-platforms/akamai.md
  website/content/v1.8/talos-guides/install/cloud-platforms/aws.md
  website/content/v1.8/talos-guides/install/cloud-platforms/digitalocean.md
  website/content/v1.8/talos-guides/install/cloud-platforms/gcp/talos-ha.jinja
  website/content/v1.8/talos-guides/install/cloud-platforms/hetzner.md
  website/content/v1.8/talos-guides/install/cloud-platforms/upcloud.md
  website/content/v1.8/talos-guides/install/cloud-platforms/vultr.md
  website/content/v1.8/talos-guides/install/local-platforms/virtualbox.md
  website/content/v1.8/talos-guides/install/virtualized-platforms/proxmox.md
  website/content/v1.8/talos-guides/install/virtualized-platforms/vagrant-libvirt.md
  website/content/v1.8/talos-guides/install/virtualized-platforms/vmware.md
Labels: status/ok-to-test, status/ok-to-merge

#9148 docs: add high-level overlay development guide
  website/content/v1.8/advanced/overlays.md
Labels: status/ok-to-merge

#9179 fix: retry with another upstream if the previous failed.
  internal/pkg/dns/dns.go
  internal/pkg/dns/dns_test.go
Labels: status/ok-to-test, status/ok-to-merge

#9106 chore: replace `if` blocks with `min`/`max` functions
  hack/gotagsrewrite/main.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_monitoring.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/adapters/perf/cpu.go
  internal/app/machined/pkg/controllers/network/operator/dhcp4.go
  internal/app/machined/pkg/controllers/network/operator/dhcp6.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events.go
  internal/pkg/containers/cri/cri.go
  internal/pkg/dashboard/components/components.go
  internal/pkg/dashboard/components/graphs.go
Labels: status/ok-to-test, status/ok-to-merge, integration/misc

#9188 chore: improve `cluster create` UX on aarch64
  pkg/provision/providers/qemu/arch.go
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/qemu/node.go
Labels: status/ok-to-test, status/ok-to-merge

#9189 docs: fix incorrect path for openebs in documentation
  website/content/v1.7/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva.md
Labels: status/ok-to-merge

#9198 chore: restructure k8s component health checks
  pkg/cluster/check/default.go
Labels: status/ok-to-test, status/ok-to-merge

#9200 fix: bind HostDNS to 169.254.x link-local address
  api/api.descriptors
  api/resource/definitions/k8s/k8s.proto
  hack/release.toml
  internal/app/machined/pkg/controllers/k8s/control_plane.go
  internal/app/machined/pkg/controllers/k8s/manifest.go
  internal/app/machined/pkg/controllers/k8s/templates.go
  internal/app/machined/pkg/controllers/k8s/templates/talos-host-dns-svc-template.yaml
  internal/app/machined/pkg/controllers/network/hostdns_config.go
  pkg/machinery/api/resource/definitions/k8s/k8s.pb.go
  pkg/machinery/api/resource/definitions/k8s/k8s_vtproto.pb.go
  pkg/machinery/constants/constants.go
  pkg/machinery/resources/k8s/manifests_config.go
  website/content/v1.8/reference/api.md
  website/content/v1.8/talos-guides/network/host-dns.md
Labels: status/ok-to-test, status/ok-to-merge

#9205 chore: update protoc-gen-doc
  Dockerfile
  Makefile
Labels: status/ok-to-test, status/ok-to-merge

#9203 chore: make qemu check flag consistent with code
  .github/workflows/ci.yaml
  .github/workflows/integration-cilium-cron.yaml
  .kres.yaml
  cmd/talosctl/cmd/mgmt/cluster/create.go
  hack/test/e2e-qemu.sh
  website/content/v1.8/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9202 fix: always handle `PermissionDenied` in dashboard resource watches
  internal/pkg/dashboard/resourcedata/resourcedata.go
Labels: status/ok-to-test, status/ok-to-merge

#9208 docs: Update kubespan.md - fix typo
  website/content/v1.7/talos-guides/network/kubespan.md
  website/content/v1.8/talos-guides/network/kubespan.md
Labels: status/ok-to-merge

#9213 fix: drop /opt mount for containers/tink
  internal/integration/k8s/tink.go
  website/content/v1.8/talos-guides/install/cloud-platforms/kubernetes.md
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu

#9219 fix: add NVMe target kernel modules
  hack/modules-amd64.txt
  hack/modules-arm64.txt
Labels: status/ok-to-test, status/ok-to-merge

#9220 fix: bump go-smbios for broken SMIOS tables
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#9226 fix: add missing host/nvme-rdma
  hack/modules-amd64.txt
  hack/modules-arm64.txt
Labels: status/ok-to-test, status/ok-to-merge

#9218 chore: add java package to protos
  api/cluster/cluster.proto
  api/common/common.proto
  api/inspect/inspect.proto
  api/machine/machine.proto
  api/resource/config/config.proto
  api/resource/definitions/block/block.proto
  api/resource/definitions/cluster/cluster.proto
  api/resource/definitions/cri/cri.proto
  api/resource/definitions/enums/enums.proto
  api/resource/definitions/etcd/etcd.proto
  api/resource/definitions/extensions/extensions.proto
  api/resource/definitions/files/files.proto
  api/resource/definitions/hardware/hardware.proto
  api/resource/definitions/k8s/k8s.proto
  api/resource/definitions/kubeaccess/kubeaccess.proto
  api/resource/definitions/kubespan/kubespan.proto
  api/resource/definitions/network/network.proto
  api/resource/definitions/perf/perf.proto
  api/resource/definitions/proto/proto.proto
  api/resource/definitions/runtime/runtime.proto
  api/resource/definitions/secrets/secrets.proto
  api/resource/definitions/siderolink/siderolink.proto
  api/resource/definitions/time/time.proto
  api/resource/definitions/v1alpha1/v1alpha1.proto
  api/resource/network/device_config.proto
  api/security/security.proto
  api/storage/storage.proto
  api/time/time.proto
  hack/structprotogen/consts/consts.go
  hack/structprotogen/proto/proto.go
  pkg/machinery/api/cluster/cluster.pb.go
  pkg/machinery/api/common/common.pb.go
  pkg/machinery/api/inspect/inspect.pb.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/resource/config/config.pb.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/cluster/cluster.pb.go
  pkg/machinery/api/resource/definitions/cri/cri.pb.go
  pkg/machinery/api/resource/definitions/enums/enums.pb.go
  pkg/machinery/api/resource/definitions/etcd/etcd.pb.go
  pkg/machinery/api/resource/definitions/extensions/extensions.pb.go
  pkg/machinery/api/resource/definitions/files/files.pb.go
  pkg/machinery/api/resource/definitions/hardware/hardware.pb.go
  pkg/machinery/api/resource/definitions/k8s/k8s.pb.go
  pkg/machinery/api/resource/definitions/kubeaccess/kubeaccess.pb.go
  pkg/machinery/api/resource/definitions/kubespan/kubespan.pb.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/perf/perf.pb.go
  pkg/machinery/api/resource/definitions/proto/proto.pb.go
  pkg/machinery/api/resource/definitions/runtime/runtime.pb.go
  pkg/machinery/api/resource/definitions/secrets/secrets.pb.go
  pkg/machinery/api/resource/definitions/siderolink/siderolink.pb.go
  pkg/machinery/api/resource/definitions/time/time.pb.go
  pkg/machinery/api/resource/definitions/v1alpha1/v1alpha1.pb.go
  pkg/machinery/api/resource/network/device_config.pb.go
  pkg/machinery/api/security/security.pb.go
  pkg/machinery/api/storage/storage.pb.go
  pkg/machinery/api/time/time.pb.go
Labels: status/ok-to-merge

#9230 fix: merge extension service config files by `mountPath`
  pkg/machinery/config/configpatcher/testdata/multidoc/config.yaml
  pkg/machinery/config/configpatcher/testdata/multidoc/expected.yaml
  pkg/machinery/config/configpatcher/testdata/multidoc/strategic2.yaml
  pkg/machinery/config/types/runtime/extensions/service_config.go
  pkg/machinery/config/types/runtime/extensions/service_config_test.go
  website/content/v1.8/talos-guides/configuration/patching.md
Labels: status/ok-to-test, status/ok-to-merge

#9233 fix: host DNS access with firewall enabled
  internal/app/machined/pkg/controllers/network/nftables_chain_config.go
  internal/integration/api/common.go
  internal/integration/base/k8s.go
  pkg/cluster/check/default.go
  pkg/cluster/check/kubernetes.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu-encrypted-vip, integration/misc-0

#9235 feat: add Cisco fnic driver
  Makefile
  hack/modules-amd64.txt
  pkg/machinery/gendata/data/pkgs
  website/content/v1.4/advanced/verifying-images.md
  website/content/v1.5/advanced/verifying-images.md
  website/content/v1.6/advanced/verifying-images.md
  website/content/v1.7/advanced/verifying-images.md
  website/content/v1.7/talos-guides/install/bare-metal-platforms/secureboot.md
  website/content/v1.8/advanced/verifying-images.md
  website/content/v1.8/talos-guides/install/bare-metal-platforms/secureboot.md
Labels: status/ok-to-test, status/ok-to-merge

#9204 Apache Cloudstack support
  Makefile
  hack/release.toml
  internal/app/machined/pkg/runtime/v1alpha1/platform/cloudstack/cloudstack.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/cloudstack/cloudstack_test.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/cloudstack/metadata.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/cloudstack/testdata/expected.yaml
  internal/app/machined/pkg/runtime/v1alpha1/platform/cloudstack/testdata/metadata.json
  internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
  pkg/imager/profile/default.go
  website/content/v1.8/introduction/support-matrix.md
  website/content/v1.8/talos-guides/install/cloud-platforms/cloudstack.md
Labels: status/ok-to-merge, integration/images

#9222 chore: drop console `ttyS0` argument.
  .github/workflows/ci.yaml
  .github/workflows/integration-image-factory-cron.yaml
  .github/workflows/integration-trusted-boot-cron.yaml
  .kres.yaml
  cmd/installer/pkg/install/install.go
  hack/release.toml
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
  pkg/imager/imager.go
  pkg/machinery/imager/quirks/quirks.go
  website/content/v1.8/talos-guides/configuration/logging.md
  website/content/v1.8/talos-guides/install/bare-metal-platforms/matchbox.md
  website/content/v1.8/talos-guides/install/bare-metal-platforms/secureboot.md
Labels: status/ok-to-merge, integration/trusted-boot

#9238 feat: update Flannel to v0.25.6
  hack/release.toml
  pkg/flannel/template.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#9239 chore: aarch64 qemu local secureboot support
  pkg/provision/providers/qemu/arch.go
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/qemu/node.go
Labels: status/ok-to-test, status/ok-to-merge, integration/trusted-boot

#9240 chore: drop calico from interactive installer
  internal/pkg/tui/installer/state.go
Labels: status/ok-to-test, status/ok-to-merge

#9247 chore: bump dependencies
  Makefile
  cmd/talosctl/cmd/talos/get.go
  cmd/talosctl/pkg/talos/helpers/resources.go
  go.mod
  go.sum
  hack/release.toml
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/controllers/kubeaccess/serviceaccount.go
  internal/app/machined/pkg/controllers/kubespan/routing_rules.go
  internal/app/machined/pkg/controllers/time/sync.go
  internal/app/machined/pkg/system/events/events_test.go
  internal/app/machined/pkg/system/service_events.go
  internal/app/machined/pkg/system/system.go
  internal/app/poweroff/main.go
  internal/integration/api/diskusage.go
  internal/integration/base/api.go
  pkg/machinery/api/cluster/cluster.pb.go
  pkg/machinery/api/cluster/cluster_grpc.pb.go
  pkg/machinery/api/common/common.pb.go
  pkg/machinery/api/inspect/inspect.pb.go
  pkg/machinery/api/inspect/inspect_grpc.pb.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/machine/machine_grpc.pb.go
  pkg/machinery/api/resource/config/config.pb.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/cluster/cluster.pb.go
  pkg/machinery/api/resource/definitions/cri/cri.pb.go
  pkg/machinery/api/resource/definitions/enums/enums.pb.go
  pkg/machinery/api/resource/definitions/etcd/etcd.pb.go
  pkg/machinery/api/resource/definitions/extensions/extensions.pb.go
  pkg/machinery/api/resource/definitions/files/files.pb.go
  pkg/machinery/api/resource/definitions/hardware/hardware.pb.go
  pkg/machinery/api/resource/definitions/k8s/k8s.pb.go
  pkg/machinery/api/resource/definitions/kubeaccess/kubeaccess.pb.go
  pkg/machinery/api/resource/definitions/kubespan/kubespan.pb.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/perf/perf.pb.go
  pkg/machinery/api/resource/definitions/proto/proto.pb.go
  pkg/machinery/api/resource/definitions/runtime/runtime.pb.go
  pkg/machinery/api/resource/definitions/secrets/secrets.pb.go
  pkg/machinery/api/resource/definitions/siderolink/siderolink.pb.go
  pkg/machinery/api/resource/definitions/time/time.pb.go
  pkg/machinery/api/resource/definitions/v1alpha1/v1alpha1.pb.go
  pkg/machinery/api/resource/network/device_config.pb.go
  pkg/machinery/api/security/security.pb.go
  pkg/machinery/api/security/security_grpc.pb.go
  pkg/machinery/api/storage/storage.pb.go
  pkg/machinery/api/storage/storage_grpc.pb.go
  pkg/machinery/api/time/time.pb.go
  pkg/machinery/api/time/time_grpc.pb.go
  pkg/machinery/client/resources.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/extras
  pkg/machinery/gendata/data/pkgs
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/amd64/snp.efi
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/arm64/snp.efi
Labels: status/ok-to-test, status/ok-to-merge, integration/cilium, integration/extensions, integration/misc-1

#9246 docs: kubeProxyReplacement from "disabled" to "false"
  website/content/v1.7/kubernetes-guides/network/deploying-cilium.md
Labels: status/ok-to-merge

#9248 docs(hetzner): fix invalid input in field user_data
  website/content/v1.8/talos-guides/install/cloud-platforms/hetzner.md
Labels: status/ok-to-merge

#9250 chore: bring in `uio` modules
  Makefile
  hack/modules-amd64.txt
  hack/modules-arm64.txt
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#9244 chore: pause sequencer when talos installed and iso booted
  hack/release.toml
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  pkg/imager/imager.go
  pkg/machinery/constants/constants.go
  pkg/machinery/imager/quirks/quirks.go
  website/content/v1.8/reference/kernel.md
Labels: status/ok-to-test, status/ok-to-merge

#9251 fix: correctly add console args for ttyS0
  pkg/imager/imager.go
  pkg/imager/imager_test.go
Labels: status/ok-to-test, status/ok-to-merge

#9252 release(v1.8.0-alpha.2): prepare release
  CHANGELOG.md
  Makefile
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.8/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9253 fix: build of talosctl on non-Linux arches
  cmd/installer/pkg/install/install.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/controllers/block/volume_config.go
  internal/app/machined/pkg/controllers/block/volume_config_test.go
  internal/app/machined/pkg/controllers/hardware/system.go
  internal/app/machined/pkg/controllers/hardware/system_test.go
  internal/app/machined/pkg/controllers/runtime/drop_upgrade_fallback.go
  internal/app/machined/pkg/controllers/runtime/drop_upgrade_fallback_test.go
  internal/app/machined/pkg/controllers/runtime/unique_token.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal_test.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/url/url_test.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/url/value.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_state.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/machined/revert.go
  internal/pkg/dashboard/configurl.go
  internal/pkg/dashboard/networkconfig.go
  internal/pkg/meta/meta_test.go
  pkg/machinery/gendata/data/tag
  pkg/machinery/meta/constants.go
  website/content/v1.8/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge
