Repository siderolabs/talos, pull requests merged in 2024-06, with the labels that each got.

#8844 chore: use bun instead of npm
  Dockerfile
Labels: status/ok-to-test, status/ok-to-merge

#8840 feat: update Flannel to v0.25.3
  hack/release.toml
  pkg/flannel/template.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#8578 fix: downgrade Azure IMDS required version
  internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/azure/metadata.go
  pkg/download/download.go
  pkg/download/download_test.go
Labels: status/ok-to-test, status/ok-to-merge

#8855 fix: add upgrade errata for arm64/zboot kernels
  cmd/installer/pkg/install/errata.go
  cmd/installer/pkg/install/install.go
Labels: status/ok-to-test, status/ok-to-merge

#8853 chore: add stale and lock issue workflows
  .github/workflows/lock.yaml
  .github/workflows/stale.yaml
Labels: status/ok-to-test, status/ok-to-merge

#8870 chore: update Go to 1.22.4, other updates
  .golangci.yml
  Makefile
  cmd/talosctl/pkg/talos/helpers/confirm.go
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/docgen/go.mod
  hack/docgen/go.sum
  hack/gotagsrewrite/go.mod
  hack/module-sig-verify/go.mod
  hack/release.toml
  hack/structprotogen/go.mod
  hack/structprotogen/go.sum
  internal/app/apid/main.go
  internal/app/apid/pkg/backend/apid.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_time_test.go
  internal/app/machined/pkg/controllers/runtime/events_sink.go
  internal/app/machined/pkg/controllers/siderolink/manager.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/trustd/main.go
  internal/pkg/cri/client.go
  internal/pkg/encryption/keys/kms.go
  internal/pkg/etcd/etcd.go
  internal/pkg/secureboot/database/database.go
  internal/pkg/secureboot/pesign/pesign.go
  pkg/grpc/middleware/auth/basic/basic.go
  pkg/grpc/proxy/backend/local.go
  pkg/machinery/client/connection.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/extras
  pkg/machinery/gendata/data/pkgs
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/amd64/snp.efi
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/arm64/snp.efi
Labels: status/ok-to-test, status/ok-to-merge

#8869 fix: clean up VM runners on cluster destroy
  pkg/provision/providers/vm/process.go
Labels: status/ok-to-test, status/ok-to-merge

#8797 feat: implement Talos diagnostics
  api/resource/definitions/runtime/runtime.proto
  hack/release.toml
  internal/app/machined/pkg/controllers/runtime/diagnostics.go
  internal/app/machined/pkg/controllers/runtime/diagnostics_logger.go
  internal/app/machined/pkg/controllers/runtime/internal/diagnostics/address_overlap.go
  internal/app/machined/pkg/controllers/runtime/internal/diagnostics/address_overlap_test.go
  internal/app/machined/pkg/controllers/runtime/internal/diagnostics/diagnostic.go
  internal/app/machined/pkg/controllers/runtime/internal/diagnostics/kubelet_csr_not_approved.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/pkg/dashboard/components/diagnostics.go
  internal/pkg/dashboard/components/horizontalline.go
  internal/pkg/dashboard/components/logviewer.go
  internal/pkg/dashboard/resourcedata/resourcedata.go
  internal/pkg/dashboard/summary.go
  pkg/cluster/check/default.go
  pkg/cluster/check/diagnostics.go
  pkg/machinery/api/resource/definitions/runtime/runtime.pb.go
  pkg/machinery/api/resource/definitions/runtime/runtime_vtproto.pb.go
  pkg/machinery/resources/runtime/deep_copy.generated.go
  pkg/machinery/resources/runtime/diagnostic.go
  pkg/machinery/resources/runtime/runtime.go
  pkg/machinery/resources/runtime/runtime_test.go
  website/content/v1.8/reference/api.md
  website/layouts/index.netlify_redirect
Labels: status/ok-to-test, status/ok-to-merge

#8863 Fixed typo in parameter for installing QEMU guest agent support
  website/content/v1.7/talos-guides/install/virtualized-platforms/proxmox.md
  website/content/v1.8/talos-guides/install/virtualized-platforms/proxmox.md
Labels: status/ok-to-merge

#8872 fix: update the cgroups for Talos core services
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/apid.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/machined/pkg/system/services/extension.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/app/machined/pkg/system/services/trustd.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu

#8861 fix: volume discovery improvements
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/block/discovery.go
  internal/integration/api/volumes.go
  internal/integration/base/api.go
  internal/integration/base/k8s.go
  internal/integration/k8s/tink.go
Labels: status/ok-to-test, status/ok-to-merge

#8812 chore(ci): drop crashdump, save logs as artifacts
  .github/workflows/ci.yaml
  .github/workflows/integration-aws-cron.yaml
  .github/workflows/integration-aws-nvidia-nonfree-cron.yaml
  .github/workflows/integration-aws-nvidia-oss-cron.yaml
  .github/workflows/integration-azure-cron.yaml
  .github/workflows/integration-cilium-cron.yaml
  .github/workflows/integration-cloud-images-cron.yaml
  .github/workflows/integration-equinix-metal-cron.yaml
  .github/workflows/integration-extensions-cron.yaml
  .github/workflows/integration-image-factory-cron.yaml
  .github/workflows/integration-images-cron.yaml
  .github/workflows/integration-misc-0-cron.yaml
  .github/workflows/integration-misc-1-cron.yaml
  .github/workflows/integration-misc-2-cron.yaml
  .github/workflows/integration-misc-3-cron.yaml
  .github/workflows/integration-misc-4-cron.yaml
  .github/workflows/integration-provision-0-cron.yaml
  .github/workflows/integration-provision-1-cron.yaml
  .github/workflows/integration-provision-2-cron.yaml
  .github/workflows/integration-qemu-cron.yaml
  .github/workflows/integration-qemu-csi-cron.yaml
  .github/workflows/integration-qemu-encrypted-vip-cron.yaml
  .github/workflows/integration-qemu-race-cron.yaml
  .github/workflows/integration-reproducibility-test-cron.yaml
  .github/workflows/integration-trusted-boot-cron.yaml
  .kres.yaml
  hack/test/e2e-docker.sh
  hack/test/e2e-image-factory.sh
  hack/test/e2e-iso.sh
  hack/test/e2e-qemu.sh
Labels: status/ok-to-test, status/ok-to-merge

#8876 feat: provide disk detection based on new blockdevices
  api/resource/definitions/block/block.proto
  cmd/talosctl/cmd/mgmt/cluster/create.go
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/block/disks.go
  internal/app/machined/pkg/controllers/block/system_disk.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/app/storaged/server.go
  internal/integration/api/volumes.go
  internal/integration/cli/disk.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/block/block_vtproto.pb.go
  pkg/machinery/resources/block/block.go
  pkg/machinery/resources/block/block_test.go
  pkg/machinery/resources/block/deep_copy.generated.go
  pkg/machinery/resources/block/disk.go
  pkg/machinery/resources/block/system_disk.go
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/qemu/node.go
  pkg/provision/request.go
  website/content/v1.8/reference/api.md
  website/content/v1.8/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#8493 fix: initial assignment of alias IP in hcloud (Hetzner)
  internal/app/machined/pkg/controllers/network/operator/vip/hcloud.go
  internal/app/machined/pkg/controllers/network/operator_vip_config.go
Labels: status/ok-to-merge

#8877 chore: bump our coredns fork
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#8887 fix: detect CD devices, fix user disks wipe test
  api/resource/definitions/block/block.proto
  api/storage/storage.proto
  go.mod
  go.sum
  go.work
  internal/app/machined/pkg/controllers/block/disks.go
  internal/app/storaged/server.go
  internal/integration/api/reset.go
  internal/integration/api/volumes.go
  internal/integration/base/api.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/block/block_vtproto.pb.go
  pkg/machinery/api/storage/storage.pb.go
  pkg/machinery/resources/block/disk.go
  website/content/v1.8/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge

#8889 chore: drop k8s timeout in the default kubeconfig
  internal/integration/base/discovery_k8s.go
  internal/integration/base/k8s.go
  pkg/cluster/kubernetes.go
  pkg/cluster/sonobuoy/sonobuoy.go
  pkg/kubernetes/kubernetes.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu

#8880 chore: replace sync.Map with concurrent.HashTrieMap
  go.mod
  go.sum
  internal/app/apid/pkg/backend/apid_factory.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#8879 chore: fix our dns server implementation
  internal/pkg/dns/dns.go
Labels: status/ok-to-test, status/ok-to-merge, integration/misc

#8890 test: fix the integration test for no META name
  internal/integration/api/volumes.go
Labels: status/ok-to-test, status/ok-to-merge, integration/aws, integration/misc-2

#8878 feat: use hydrophone instead of sonobuoy
  cmd/talosctl/cmd/talos/conformance.go
  cmd/talosctl/cmd/talos/health.go
  go.mod
  go.sum
  internal/integration/provision/provision.go
  pkg/cluster/hydrophone/hydrophone.go
  pkg/cluster/hydrophone/product.go
  pkg/cluster/sonobuoy/sonobuoy.go
  pkg/provision/providers/vm/process.go
Labels: status/ok-to-test, status/ok-to-merge

#8892 chore(ci): add conformance pipelines
  .github/workflows/ci.yaml
  .github/workflows/integration-conformance-cron.yaml
  .github/workflows/slack-notify.yaml
  .kres.yaml
  hack/test/e2e-cloud-tf.sh
Labels: status/ok-to-test, status/ok-to-merge, integration/conformance

#8896 chore: update Go modules
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#8906 chore: upgrade to rtnetlink/v2 library
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/network/address_spec.go
  internal/app/machined/pkg/controllers/network/address_spec_test.go
  internal/app/machined/pkg/controllers/network/address_status.go
  internal/app/machined/pkg/controllers/network/link_spec.go
  internal/app/machined/pkg/controllers/network/link_status.go
  internal/app/machined/pkg/controllers/network/link_status_test.go
  internal/app/machined/pkg/controllers/network/nftables_chain_test.go
  internal/app/machined/pkg/controllers/network/operator/dhcp6.go
  internal/app/machined/pkg/controllers/network/route_spec.go
  internal/app/machined/pkg/controllers/network/route_spec_test.go
  internal/app/machined/pkg/controllers/network/route_status.go
  internal/app/machined/pkg/controllers/network/watch/rtnetlink.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/machinery/nethelpers/operstate.go
  pkg/provision/providers/vm/network.go
Labels: status/ok-to-test, status/ok-to-merge

#8909 feat: show siderolink status on dashboard
  api/resource/definitions/siderolink/siderolink.proto
  internal/app/machined/pkg/controllers/runtime/diagnostics.go
  internal/app/machined/pkg/controllers/siderolink/manager.go
  internal/app/machined/pkg/controllers/siderolink/siderolink.go
  internal/app/machined/pkg/controllers/siderolink/status.go
  internal/app/machined/pkg/controllers/siderolink/status_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/pkg/dashboard/components/components.go
  internal/pkg/dashboard/components/kubernetesinfo.go
  internal/pkg/dashboard/components/networkinfo.go
  internal/pkg/dashboard/components/talosinfo.go
  internal/pkg/dashboard/resourcedata/resourcedata.go
  internal/pkg/dashboard/summary.go
  pkg/machinery/api/resource/definitions/siderolink/siderolink.pb.go
  pkg/machinery/api/resource/definitions/siderolink/siderolink_vtproto.pb.go
  pkg/machinery/resources/runtime/diagnostic.go
  pkg/machinery/resources/siderolink/deep_copy.generated.go
  pkg/machinery/resources/siderolink/siderolink.go
  pkg/machinery/resources/siderolink/siderolink_status.go
  website/content/v1.8/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge

#8905 chore: use new disks api for iscsi tests
  internal/integration/api/extensions_qemu.go
Labels: status/ok-to-test, status/ok-to-merge, integration/extensions

#8930 release(v1.7.5): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.7/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#8875 chore(ci): run e2e-aws-nvidia with zfs extension enabled
  .github/workflows/ci.yaml
  .github/workflows/integration-aws-nvidia-oss-cron.yaml
  .kres.yaml
  hack/test/e2e-aws-prepare.sh
  hack/test/tfvars/nvidia.yaml
  website/content/v1.8/talos-guides/configuration/nvidia-gpu-proprietary.md
  website/content/v1.8/talos-guides/configuration/nvidia-gpu.md
Labels: status/ok-to-test, status/ok-to-merge, integration/aws-nvidia-oss

#8874 chore: output more info when `ExecuteCommandInPod` fails
  internal/integration/api/common.go
  internal/integration/base/k8s.go
Labels: status/ok-to-test, status/ok-to-merge, integration/misc, integration/trusted-boot

#8938 chore(ci): fix cluster name generation
  hack/test/e2e-aws-prepare.sh
Labels: status/ok-to-test, status/ok-to-merge

#8939 Typo: "As a safety messure Talos... -> As a safety measure, Talos..."
  website/content/v1.0/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.1/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.2/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.3/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.4/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.5/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.6/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.7/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.8/kubernetes-guides/network/deploying-cilium.md
Labels: status/ok-to-merge

#8937 feat: add apparmor pkg
  Dockerfile
  Makefile
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-merge

#8946 chore: handle documents diff in `apply-config` dry run
  cmd/talosctl/cmd/talos/apply-config.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/integration/api/apply-config.go
Labels: status/ok-to-test, status/ok-to-merge
