Repository siderolabs/talos, pull requests merged in 2024-11, with the labels that each got.

#9608 chore: drop runc memfd bind added in #9069
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
Labels: status/ok-to-test, status/ok-to-merge

#9620 feat: add auditd service
  go.mod
  go.sum
  hack/release.toml
  internal/app/auditd/auditd.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/services/auditd.go
  internal/integration/api/logs.go
Labels: status/ok-to-test, status/ok-to-merge

#9626 feat: Add Windows ARM64 build for talosctl
  .github/workflows/ci.yaml
  .kres.yaml
  Dockerfile
  Makefile
Labels: status/ok-to-merge

#9629 fix: talosctl windows arm64
  Dockerfile
Labels: status/ok-to-test, status/ok-to-merge

#9627 fix: make route normalization keep family
  internal/app/machined/pkg/controllers/network/route_config.go
  pkg/machinery/resources/network/route_spec.go
  pkg/machinery/resources/network/route_spec_test.go
Labels: status/ok-to-test, status/ok-to-merge

#9628 fix: mount /sys/kernel/security conditionally
  internal/app/machined/pkg/system/services/kubelet.go
Labels: status/ok-to-test, status/ok-to-merge, integration/misc-4

#9634 fix: update permissions for logging directories in /var
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/ok-to-test, status/ok-to-merge

#9617 feat: machined: initial SELinux bring-up
  .dockerignore
  Dockerfile
  hack/labeled-squashfs.sh
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/system/runner/containerd/containerd.go
  internal/app/machined/pkg/system/runner/process/process.go
  internal/app/machined/pkg/system/runner/runner.go
  internal/app/machined/pkg/system/services/apid.go
  internal/app/machined/pkg/system/services/containerd.go
  internal/app/machined/pkg/system/services/cri.go
  internal/app/machined/pkg/system/services/dashboard.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/app/machined/pkg/system/services/trustd.go
  internal/app/machined/pkg/system/services/udevd.go
  internal/integration/api/selinux.go
  internal/pkg/install/install.go
  internal/pkg/mount/switchroot/switchroot.go
  internal/pkg/mount/v2/pseudo.go
  internal/pkg/selinux/policy/file_contexts
  internal/pkg/selinux/policy/policy.33
  internal/pkg/selinux/policy/selinux/common/classmaps.cil
  internal/pkg/selinux/policy/selinux/common/network.cil
  internal/pkg/selinux/policy/selinux/common/typeattributes.cil
  internal/pkg/selinux/policy/selinux/immutable/classes.cil
  internal/pkg/selinux/policy/selinux/immutable/fs.cil
  internal/pkg/selinux/policy/selinux/immutable/preamble.cil
  internal/pkg/selinux/policy/selinux/immutable/roles.cil
  internal/pkg/selinux/policy/selinux/immutable/sids.cil
  internal/pkg/selinux/policy/selinux/services/cri.cil
  internal/pkg/selinux/policy/selinux/services/dashboard.cil
  internal/pkg/selinux/policy/selinux/services/kubelet.cil
  internal/pkg/selinux/policy/selinux/services/machined.cil
  internal/pkg/selinux/policy/selinux/services/selinux.cil
  internal/pkg/selinux/policy/selinux/services/system-containerd.cil
  internal/pkg/selinux/policy/selinux/services/system-containers.cil
  internal/pkg/selinux/policy/selinux/services/udev.cil
  internal/pkg/selinux/selinux.go
  pkg/imager/imager.go
  pkg/imager/imager_test.go
  pkg/machinery/constants/constants.go
  pkg/machinery/imager/quirks/quirks.go
  pkg/provision/providers/qemu/node.go
Labels: status/ok-to-test, status/ok-to-merge

#9636 chore: update go-auditlib
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#9645 feat: update Linux 6.6.59, runc 1.2.1
  Makefile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/release.toml
  internal/app/machined/pkg/controllers/secrets/data/ca-certificates
  internal/integration/k8s/constants.go
  pkg/machinery/api/cluster/cluster.pb.go
  pkg/machinery/api/cluster/cluster_grpc.pb.go
  pkg/machinery/api/common/common.pb.go
  pkg/machinery/api/inspect/inspect.pb.go
  pkg/machinery/api/inspect/inspect_grpc.pb.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/machine/machine_grpc.pb.go
  pkg/machinery/api/resource/config/config.pb.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/cluster/cluster.pb.go
  pkg/machinery/api/resource/definitions/cri/cri.pb.go
  pkg/machinery/api/resource/definitions/enums/enums.pb.go
  pkg/machinery/api/resource/definitions/etcd/etcd.pb.go
  pkg/machinery/api/resource/definitions/extensions/extensions.pb.go
  pkg/machinery/api/resource/definitions/files/files.pb.go
  pkg/machinery/api/resource/definitions/hardware/hardware.pb.go
  pkg/machinery/api/resource/definitions/k8s/k8s.pb.go
  pkg/machinery/api/resource/definitions/kubeaccess/kubeaccess.pb.go
  pkg/machinery/api/resource/definitions/kubespan/kubespan.pb.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/perf/perf.pb.go
  pkg/machinery/api/resource/definitions/proto/proto.pb.go
  pkg/machinery/api/resource/definitions/runtime/runtime.pb.go
  pkg/machinery/api/resource/definitions/secrets/secrets.pb.go
  pkg/machinery/api/resource/definitions/siderolink/siderolink.pb.go
  pkg/machinery/api/resource/definitions/time/time.pb.go
  pkg/machinery/api/resource/definitions/v1alpha1/v1alpha1.pb.go
  pkg/machinery/api/resource/network/device_config.pb.go
  pkg/machinery/api/security/security.pb.go
  pkg/machinery/api/security/security_grpc.pb.go
  pkg/machinery/api/storage/storage.pb.go
  pkg/machinery/api/storage/storage_grpc.pb.go
  pkg/machinery/api/time/time.pb.go
  pkg/machinery/api/time/time_grpc.pb.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/amd64/snp.efi
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/arm64/snp.efi
Labels: status/ok-to-test, status/ok-to-merge

#9640 feat: label system socket and runtime files
  internal/app/apid/main.go
  internal/app/machined/pkg/controllers/etcd/pki.go
  internal/app/machined/pkg/controllers/k8s/render_config_static_pods.go
  internal/app/machined/pkg/controllers/k8s/render_secrets_static_pod.go
  internal/app/machined/pkg/system/services/apid.go
  internal/app/machined/pkg/system/services/machined.go
  internal/app/machined/pkg/system/services/trustd.go
  internal/integration/api/selinux.go
  internal/pkg/logind/broker.go
  internal/pkg/selinux/policy/policy.33
  internal/pkg/selinux/policy/selinux/common/classmaps.cil
  internal/pkg/selinux/policy/selinux/services/cri.cil
  internal/pkg/selinux/policy/selinux/services/machined.cil
  internal/pkg/selinux/policy/selinux/services/system-containers.cil
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#9643 chore: generate support zip for crashdump
  internal/integration/integration_test.go
  internal/integration/provision/provision.go
  pkg/cluster/crashdump.go
  pkg/provision/access/adapter.go
  pkg/provision/providers/docker/crashdump.go
  pkg/provision/providers/docker/create.go
  pkg/provision/providers/docker/destroy.go
  pkg/provision/providers/docker/reflect.go
  pkg/provision/providers/docker/result.go
  pkg/provision/providers/vm/crashdump.go
Labels: status/ok-to-test, status/ok-to-merge

#9649 feat: add dm-cache dm-cache-smq kernel modules
  Makefile
  hack/modules-amd64.txt
  hack/modules-arm64.txt
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#9653 docs: update manual k8s upgrade docs
  website/content/v1.7/kubernetes-guides/upgrading-kubernetes.md
  website/content/v1.8/kubernetes-guides/upgrading-kubernetes.md
  website/content/v1.9/kubernetes-guides/upgrading-kubernetes.md
Labels: status/ok-to-test, status/ok-to-merge

#9655 feat: update Kubernetes to v1.32.0-beta.0
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/v1.9/_index.md
  website/content/v1.9/reference/cli.md
  website/content/v1.9/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge, integration/provision

#9650 fix: selinux handling and apparmor tests
  Makefile
  hack/test/e2e-qemu.sh
  internal/integration/k8s/apparmor.go
  internal/pkg/install/install.go
  internal/pkg/mount/v2/pseudo.go
  pkg/imager/imager.go
  pkg/provision/providers/qemu/node.go
Labels: status/ok-to-test, status/ok-to-merge, integration/misc-4

#9661 fix: install disk matcher error
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
Labels: status/ok-to-test, status/ok-to-merge

#9659 docs: add apparmor enablement release notes
  hack/release.toml
Labels: status/ok-to-test, status/ok-to-merge

#9660 chore: update pkgs to ones built with gcc 14.2
  Makefile
  pkg/machinery/gendata/data/pkgs
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/amd64/snp.efi
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/arm64/snp.efi
Labels: status/ok-to-test, status/ok-to-merge

#9662 docs: add docs on usernamespace support in k8s
  .github/workflows/ci.yaml
  .github/workflows/integration-misc-4-cron.yaml
  .kres.yaml
  hack/release.toml
  hack/test/patches/usernamespace.yaml
  internal/integration/k8s/testdata/usernamespace.yaml
  internal/integration/k8s/usernamespace.go
  website/content/v1.9/kubernetes-guides/configuration/usernamespace.md
Labels: status/ok-to-test, status/ok-to-merge, integration/misc-4

#9658 feat: check bridged interfaces should not have addresses
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
Labels: status/ok-to-merge

#9665 feat: display current CPU frequency on dashboard
  api/machine/machine.proto
  internal/app/machined/internal/server/v1alpha1/v1alpha1_monitoring.go
  internal/app/machined/pkg/system/services/machined.go
  internal/integration/api/monitoring.go
  internal/pkg/dashboard/apidata/node.go
  internal/pkg/dashboard/apidata/source.go
  internal/pkg/dashboard/components/header.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/machine/machine_grpc.pb.go
  pkg/machinery/api/machine/machine_vtproto.pb.go
  website/content/v1.9/reference/api.md
Labels: status/ok-to-merge

#9670 fix(ci): skip test if `UserNamespacesSupport` feature gate is not set
  internal/integration/api/extensions_qemu.go
  internal/integration/k8s/usernamespace.go
Labels: status/ok-to-test, status/ok-to-merge, integration/extensions

#9672 release(v1.9.0-alpha.1): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge, integration/misc, integration/qemu, integration/trusted-boot, integration/aws

#9667 chore(ci): save support zip always after tests
  .github/workflows/ci.yaml
  .github/workflows/integration-cilium-cron.yaml
  .github/workflows/integration-conformance-cron.yaml
  .github/workflows/integration-extensions-cron.yaml
  .github/workflows/integration-image-factory-cron.yaml
  .github/workflows/integration-misc-0-cron.yaml
  .github/workflows/integration-misc-1-cron.yaml
  .github/workflows/integration-misc-2-cron.yaml
  .github/workflows/integration-misc-3-cron.yaml
  .github/workflows/integration-misc-4-cron.yaml
  .github/workflows/integration-provision-0-cron.yaml
  .github/workflows/integration-provision-1-cron.yaml
  .github/workflows/integration-provision-2-cron.yaml
  .github/workflows/integration-qemu-cron.yaml
  .github/workflows/integration-qemu-csi-longhorn-cron.yaml
  .github/workflows/integration-qemu-csi-rook-ceph-cron.yaml
  .github/workflows/integration-qemu-encrypted-vip-cron.yaml
  .github/workflows/integration-qemu-race-cron.yaml
  .github/workflows/integration-trusted-boot-cron.yaml
  .kres.yaml
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/mgmt/cluster/destroy.go
  hack/test/e2e-docker.sh
  hack/test/e2e-image-factory.sh
  hack/test/e2e-iso.sh
  hack/test/e2e-qemu.sh
  internal/integration/integration_test.go
  internal/integration/provision/provision.go
  pkg/cluster/crashdump.go
  pkg/provision/options.go
  pkg/provision/providers/docker/crashdump.go
  pkg/provision/providers/docker/destroy.go
  pkg/provision/providers/qemu/destroy.go
  pkg/provision/providers/vm/crashdump.go
  website/content/v1.9/advanced/developing-talos.md
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9676 test: fix unpriviliged process runner test
  internal/app/machined/pkg/system/runner/process/process.go
Labels: status/ok-to-test, status/ok-to-merge

#9677 chore: fix nil pointer dereference in AWS uploader
  hack/cloud-image-uploader/aws.go
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
Labels: status/ok-to-merge

#9679 release(v1.9.0-alpha.2): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9673 chore: clean dns code
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/network/dns_resolve_cache.go
  internal/app/machined/pkg/controllers/network/etcfile.go
  internal/app/machined/pkg/controllers/network/hostdns_config.go
  internal/app/machined/pkg/xcontext/xcontext.go
  internal/pkg/dns/dns.go
  internal/pkg/dns/dns_test.go
  internal/pkg/dns/manager.go
  internal/pkg/dns/runnner.go
Labels: kind/refactor, area/networking, status/ok-to-test, status/ok-to-merge, integration/misc, integration/qemu

#9684 docs: use single tags option for the controlplane nodes
  website/content/v1.8/talos-guides/install/cloud-platforms/gcp.md
  website/content/v1.9/talos-guides/install/cloud-platforms/gcp.md
Labels: status/ok-to-merge

#9693 docs: add missing `--talosconfig` parameter to end of Hetzner guide
  website/content/v1.8/talos-guides/install/cloud-platforms/hetzner.md
  website/content/v1.9/talos-guides/install/cloud-platforms/hetzner.md
Labels: status/ok-to-merge

#9666 feat: rewrite install disk selector to use CEL expressions
  hack/release.toml
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/controllers/block/volume_manager.go
  internal/app/machined/pkg/controllers/config/acquire.go
  internal/app/machined/pkg/controllers/config/acquire_test.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/maintenance/server.go
  internal/integration/api/generate-config.go
  pkg/machinery/cel/build.go
  pkg/machinery/cel/build_test.go
  pkg/machinery/cel/celenv/celenv.go
  pkg/machinery/cel/celenv/celenv_test.go
  pkg/machinery/config/config/machine.go
  pkg/machinery/config/config/validate.go
  pkg/machinery/config/configloader/configloader_test.go
  pkg/machinery/config/container/container.go
  pkg/machinery/config/provider.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/block/blockhelpers/blockhelpers.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_marshal_test.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider_test.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/machinery/proto/resource.go
  website/content/v1.9/reference/configuration/v1alpha1/config.md
  website/content/v1.9/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge

#9696 fix: use imager incoming version for extension validation
  cmd/installer/pkg/install/extensions.go
  pkg/imager/extensions/extensions.go
  pkg/machinery/extensions/extensions_test.go
  pkg/machinery/extensions/validate.go
  pkg/machinery/imager/quirks/quirks.go
Labels: status/ok-to-test, status/ok-to-merge

#9698 Fix QEMU Provisioner on ArchLinux
  pkg/provision/providers/qemu/arch.go
Labels: status/ok-to-merge

#9705 Fix a typo
  website/content/v1.8/talos-guides/install/cloud-platforms/vultr.md
  website/content/v1.9/talos-guides/install/cloud-platforms/vultr.md
Labels: status/ok-to-merge

#9707 chore: update pkgs/tools/extras for Go 1.23.3
  .golangci.yml
  Dockerfile
  Makefile
  go.mod
  go.sum
  go.work
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/docgen/go.mod
  hack/docgen/go.sum
  hack/gotagsrewrite/go.mod
  hack/module-sig-verify/go.mod
  hack/module-sig-verify/go.sum
  hack/release.toml
  hack/structprotogen/go.mod
  hack/structprotogen/go.sum
  internal/app/apid/pkg/backend/apid_test.go
  internal/app/apid/pkg/provider/provider.go
  internal/app/machined/pkg/controllers/k8s/extra_manifest_test.go
  internal/app/machined/pkg/controllers/k8s/kubeprism_config_test.go
  internal/app/machined/pkg/controllers/k8s/manifest_test.go
  internal/app/machined/pkg/controllers/kubeaccess/serviceaccount/crd_controller.go
  internal/app/machined/pkg/controllers/network/address_merge.go
  internal/app/machined/pkg/controllers/network/hardware_addr.go
  internal/app/machined/pkg/controllers/network/hostname_merge.go
  internal/app/machined/pkg/controllers/network/hostname_spec.go
  internal/app/machined/pkg/controllers/network/hostname_spec_test.go
  internal/app/machined/pkg/controllers/network/link_config.go
  internal/app/machined/pkg/controllers/network/link_merge.go
  internal/app/machined/pkg/controllers/network/node_address.go
  internal/app/machined/pkg/controllers/network/operator/vip.go
  internal/app/machined/pkg/controllers/network/operator_config.go
  internal/app/machined/pkg/controllers/network/operator_merge.go
  internal/app/machined/pkg/controllers/network/operator_spec.go
  internal/app/machined/pkg/controllers/network/platform_config.go
  internal/app/machined/pkg/controllers/network/resolver_spec_test.go
  internal/app/machined/pkg/controllers/network/route_merge.go
  internal/app/machined/pkg/controllers/network/route_spec.go
  internal/app/machined/pkg/controllers/network/timeserver_merge.go
  internal/app/machined/pkg/controllers/network/timeserver_spec.go
  internal/app/machined/pkg/controllers/network/timeserver_spec_test.go
  internal/app/machined/pkg/controllers/time/sync_test.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/trustd/internal/provider/provider.go
  internal/integration/api/reboot.go
  internal/integration/k8s/constants.go
  pkg/chunker/chunker.go
  pkg/imager/profile/internal/signer/aws/pcr.go
  pkg/machinery/config/config/cluster.go
  pkg/machinery/config/config/machine.go
  pkg/machinery/config/configloader/internal/decoder/decoder_test.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_unstructured.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/extras
  pkg/machinery/gendata/data/pkgs
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#9709 refactor: move early initialization functions to pre-initialize phase
  internal/app/machined/main.go
  internal/app/machined/pkg/runtime/controller.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/startup/cgroups.go
  internal/app/machined/pkg/startup/ima.go
  internal/app/machined/pkg/startup/os_release.go
  internal/app/machined/pkg/startup/startup.go
  internal/app/machined/pkg/startup/tasks.go
  internal/pkg/mount/v2/pseudo.go
Labels: status/ok-to-test, status/ok-to-merge

#9712 feat: update etcd to v3.5.17
  go.mod
  go.sum
  pkg/machinery/constants/constants.go
  website/content/v1.9/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#9717 release(v1.8.3): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.8/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9718 fix: install on non-empty disk
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#9716 feat: implement tracking of blockdevice secondaries
  api/resource/definitions/block/block.proto
  internal/app/machined/pkg/controllers/block/devices.go
  internal/app/machined/pkg/controllers/block/disks.go
  internal/app/machined/pkg/controllers/block/internal/sysblock/sysblock.go
  internal/integration/api/volumes.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/block/block_vtproto.pb.go
  pkg/machinery/resources/block/deep_copy.generated.go
  pkg/machinery/resources/block/device.go
  pkg/machinery/resources/block/disk.go
  website/content/v1.9/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge

#9683 feat: add on-link option for no cloud routes
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/expected-v2.yaml
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/metadata-v2-cloud-init.yaml
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/metadata-v2-nocloud.yaml
Labels: status/ok-to-merge

#9723 fix: registry mirror fallback handling
  hack/release.toml
  internal/pkg/containers/cri/containerd/hosts.go
  internal/pkg/containers/cri/containerd/hosts_test.go
  internal/pkg/containers/image/resolver.go
  internal/pkg/containers/image/resolver_test.go
  pkg/machinery/config/config/machine.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  website/content/v1.9/reference/configuration/v1alpha1/config.md
  website/content/v1.9/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge

#9730 fix: register controlplane node with NoSchedule taint
  api/resource/definitions/k8s/k8s.proto
  internal/app/machined/pkg/controllers/k8s/kubelet_config.go
  internal/app/machined/pkg/controllers/k8s/kubelet_spec.go
  internal/app/machined/pkg/controllers/k8s/kubelet_spec_test.go
  pkg/machinery/api/resource/definitions/k8s/k8s.pb.go
  pkg/machinery/api/resource/definitions/k8s/k8s_vtproto.pb.go
  pkg/machinery/resources/k8s/kubelet_config.go
  website/content/v1.9/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge

#9742 chore: remove replace for safchain/ethtool
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#9745 fix: allow CEL expressions config merge
  pkg/machinery/cel/cel.go
  pkg/machinery/config/types/block/volume_config_test.go
Labels: status/ok-to-test, status/ok-to-merge

#9737 refactor: remove SELinux client_u and client_r
  internal/pkg/selinux/policy/policy.33
  internal/pkg/selinux/policy/selinux/common/typeattributes.cil
  internal/pkg/selinux/policy/selinux/immutable/roles.cil
  internal/pkg/selinux/policy/selinux/services/cri.cil
  internal/pkg/selinux/policy/selinux/services/dashboard.cil
  internal/pkg/selinux/policy/selinux/services/machined.cil
  internal/pkg/selinux/policy/selinux/services/system-containerd.cil
  internal/pkg/selinux/policy/selinux/services/udev.cil
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#9747 feat: add permanent hardware addr to device selectors
  hack/release.toml
  internal/app/machined/pkg/controllers/network/device_config.go
  internal/app/machined/pkg/controllers/network/device_config_test.go
  pkg/machinery/config/config/machine.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  website/content/v1.9/reference/configuration/v1alpha1/config.md
  website/content/v1.9/schemas/config.schema.json
  website/content/v1.9/talos-guides/network/device-selector.md
Labels: status/ok-to-test, status/ok-to-merge

#9440 Update replicated-local-storage-with-openebs.md
  website/content/v1.8/kubernetes-guides/configuration/replicated-local-storage-with-openebs.md
  website/content/v1.9/kubernetes-guides/configuration/replicated-local-storage-with-openebs.md
Labels: status/ok-to-merge

#9750 chore: remove i915/amdgpu drivers
  hack/modules-amd64.txt
  hack/release.toml
Labels: status/ok-to-test, status/ok-to-merge

#9733 feat: image cache gen
  cmd/talosctl/cmd/talos/image.go
  cmd/talosctl/cmd/talos/processes.go
  internal/integration/cli/image.go
  pkg/imager/cache/cache.go
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9757 fix: missing config and platform manifest
  pkg/imager/cache/cache.go
Labels: status/ok-to-test, status/ok-to-merge

#9756 fix: small fixes for image cache generation
  internal/integration/cli/image.go
  pkg/imager/cache/cache.go
Labels: status/ok-to-test, status/ok-to-merge

#9761 fix: no longer leak `Close` reader.
  pkg/imager/cache/cache.go
Labels: status/ok-to-test, status/ok-to-merge

#9758 fix: don't activate LVM volumes in agent mode
  internal/app/machined/pkg/controllers/block/lvm.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
Labels: status/ok-to-test, status/ok-to-merge

#9755 feat: implement block device wipe
  api/storage/storage.proto
  cmd/talosctl/cmd/talos/disks.go
  cmd/talosctl/cmd/talos/wipe.go
  go.mod
  go.sum
  hack/release.toml
  internal/app/machined/pkg/controllers/block/internal/volumes/encrypt.go
  internal/app/machined/pkg/system/services/machined.go
  internal/app/maintenance/server.go
  internal/app/storaged/server.go
  internal/integration/api/wipe.go
  internal/integration/cli/disk.go
  pkg/machinery/api/storage/storage.pb.go
  pkg/machinery/api/storage/storage_grpc.pb.go
  pkg/machinery/api/storage/storage_vtproto.pb.go
  pkg/machinery/client/client.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  website/content/v1.9/reference/api.md
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9763 Update getting-started.md - add missing talosconfig parameter
  website/content/v1.6/introduction/getting-started.md
  website/content/v1.7/introduction/getting-started.md
  website/content/v1.8/introduction/getting-started.md
  website/content/v1.9/introduction/getting-started.md
Labels: status/ok-to-merge

#9764 feat: add e2fsprogs to talos rootfs
  Dockerfile
  Makefile
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
  pkg/makefs/ext4.go
  pkg/makefs/ext4_test.go
Labels: status/ok-to-test, status/ok-to-merge

#9762 refactor: optimize flags and SetLabel
  internal/pkg/selinux/selinux.go
Labels: status/ok-to-test, status/ok-to-merge

#9772 fix: add directory entries and filemode to tarball
  pkg/imager/cache/cache.go
  pkg/imager/filemap/filemap.go
  pkg/imager/filemap/filemap_test.go
  pkg/imager/out.go
Labels: status/ok-to-test, status/ok-to-merge

#9648 feat: label mounts and data directories
  api/resource/definitions/block/block.proto
  internal/app/machined/pkg/controllers/block/user_disk_config.go
  internal/app/machined/pkg/controllers/block/volume_config.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/startup/tasks.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/machined/pkg/system/services/extension.go
  internal/integration/api/selinux.go
  internal/integration/k8s/tink.go
  internal/pkg/mount/system.go
  internal/pkg/mount/v2/mount.go
  internal/pkg/mount/v2/overlay.go
  internal/pkg/mount/v2/pseudo.go
  internal/pkg/selinux/policy/file_contexts
  internal/pkg/selinux/policy/policy.33
  internal/pkg/selinux/policy/selinux/common/files.cil
  internal/pkg/selinux/policy/selinux/common/typeattributes.cil
  internal/pkg/selinux/policy/selinux/services/cri.cil
  internal/pkg/selinux/policy/selinux/services/kubelet.cil
  internal/pkg/selinux/policy/selinux/services/system-containerd.cil
  internal/pkg/selinux/policy/selinux/services/udev.cil
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/block/block_vtproto.pb.go
  pkg/machinery/constants/constants.go
  pkg/machinery/resources/block/volume_config.go
  pkg/provision/providers/docker/node.go
  website/content/v1.9/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge

#9774 chore: image cache generator improvements
  cmd/talosctl/cmd/talos/image.go
  pkg/imager/cache/cache.go
  pkg/imager/filemap/filemap_test.go
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9722 feat: registry proxy
  internal/app/machined/pkg/system/services/kubelet.go
  internal/app/machined/pkg/system/services/registry/app/main.go
  internal/app/machined/pkg/system/services/registry/fs.go
  internal/app/machined/pkg/system/services/registry/params.go
  internal/app/machined/pkg/system/services/registry/readers.go
  internal/app/machined/pkg/system/services/registry/registry.go
  internal/app/machined/pkg/system/services/registry/store.go
  internal/app/machined/pkg/system/services/registryd.go
  pkg/imager/cache/cache.go
Labels: status/ok-to-test, status/ok-to-merge

#9768 feat: implement image cache configuration
  api/resource/definitions/cri/cri.proto
  api/resource/definitions/enums/enums.proto
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/block/internal/volumes/format.go
  internal/app/machined/pkg/controllers/block/volume_config.go
  internal/app/machined/pkg/controllers/cri/cri.go
  internal/app/machined/pkg/controllers/cri/image_cache_config.go
  internal/app/machined/pkg/controllers/cri/image_cache_config_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/app/machined/pkg/system/services/registry/registry.go
  internal/app/machined/pkg/system/services/registryd.go
  internal/pkg/mount/system.go
  pkg/machinery/api/resource/definitions/cri/cri.pb.go
  pkg/machinery/api/resource/definitions/cri/cri_vtproto.pb.go
  pkg/machinery/api/resource/definitions/enums/enums.pb.go
  pkg/machinery/config/config/machine.go
  pkg/machinery/config/config/volume.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/block/volume_config.go
  pkg/machinery/config/types/block/volume_config_test.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_features.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/constants/constants.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/machinery/resources/cri/cri.go
  pkg/machinery/resources/cri/cri_test.go
  pkg/machinery/resources/cri/deep_copy.generated.go
  pkg/machinery/resources/cri/image_cache_config.go
  pkg/machinery/resources/cri/imagecachestatus.go
  pkg/machinery/resources/cri/imagecachestatus_enumer.go
  pkg/machinery/resources/cri/seccomp_profile.go
  website/content/v1.9/reference/api.md
  website/content/v1.9/reference/configuration/v1alpha1/config.md
  website/content/v1.9/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge

#9779 feat: udev: label device nodes
  Dockerfile
  hack/udevd/90-selinux.rules
  internal/integration/api/selinux.go
  internal/pkg/selinux/policy/policy.33
  internal/pkg/selinux/policy/selinux/services/udev.cil
Labels: status/ok-to-test, status/ok-to-merge

#9785 chore: fix dockerfile warnings
  Dockerfile
Labels: status/ok-to-test, status/ok-to-merge

#9788 fix: show SELinux labels on pseudo-fs
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
Labels: status/ok-to-test, status/ok-to-merge

#9793 release(v1.9.0-alpha.3): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9792 fix: make immage cache config apply immediately
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
  website/content/v1.8/talos-guides/configuration/editing-machine-configuration.md
  website/content/v1.9/talos-guides/configuration/editing-machine-configuration.md
Labels: status/ok-to-test, status/ok-to-merge

#9778 feat: support generating disk images with image cache
  Dockerfile
  cmd/installer/cmd/imager/root.go
  cmd/installer/pkg/install/install.go
  internal/pkg/partition/constants.go
  internal/pkg/partition/format.go
  internal/pkg/partition/partition.go
  pkg/imager/cache/cache.go
  pkg/imager/out.go
Labels: status/ok-to-test, status/ok-to-merge

#9798 fix: systemd-udevd restore old naming behavior
  Dockerfile
  hack/udevd/80-net-name-slot.rules
  hack/udevd/99-default.link
Labels: status/ok-to-test, status/ok-to-merge

#9800 fix: return proper number from the `timeStampWriter`
  internal/app/machined/pkg/runtime/logging/circular.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
  internal/app/machined/pkg/system/runner/goroutine/goroutine.go
Labels: status/ok-to-test, status/ok-to-merge

#9801 fix: small logrus fixes
  internal/pkg/containers/image/image.go
  pkg/machinery/resources/time/condition.go
Labels: status/ok-to-test, status/ok-to-merge

#9802 fix: properly halt installation if Talos already installed
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/ok-to-test, status/ok-to-merge

#9782 docs: add kubevirt install
  website/content/v1.8/advanced/install-kubevirt.md
  website/content/v1.9/advanced/install-kubevirt.md
Labels: status/ok-to-test, status/ok-to-merge

#9810 fix: make Talos META partition match more precise
  internal/app/machined/pkg/controllers/block/discovery.go
  internal/app/machined/pkg/controllers/block/volume_config.go
  internal/app/machined/pkg/controllers/block/volume_config_test.go
Labels: status/ok-to-test, status/ok-to-merge, integration/misc-2

#9812 fix: nocloud network link matching on MAC addresses
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud_test.go
Labels: status/ok-to-test, status/ok-to-merge

#9815 chore: update image cache config
  .github/ISSUE_TEMPLATE/config.yml
  internal/app/machined/pkg/controllers/cri/image_cache_config.go
  internal/app/machined/pkg/controllers/cri/image_cache_config_test.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
  pkg/machinery/config/config/machine.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/v1alpha1/v1alpha1_features.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  website/content/v1.9/reference/configuration/v1alpha1/config.md
  website/content/v1.9/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge

#9813 fix: make `system_disk` condition work properly before install
  cmd/talosctl/cmd/talos/image.go
  internal/app/machined/pkg/controllers/block/internal/volumes/locate.go
  internal/app/machined/pkg/controllers/block/internal/volumes/volumes.go
  internal/app/machined/pkg/controllers/block/volume_manager.go
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9818 fix: wait for udevd before starting sync
  internal/app/machined/pkg/controllers/time/sync.go
  internal/app/machined/pkg/controllers/time/sync_test.go
  internal/pkg/ntp/ntp.go
  internal/pkg/ntp/ntp_test.go
  internal/pkg/ntp/rtc.go
Labels: status/ok-to-test, status/ok-to-merge

#9780 chore: split `config.Registries` into the separate resource.
  api/resource/definitions/cri/cri.proto
  hack/structprotogen/proto/proto.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_images.go
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/controllers/cri/registries_config.go
  internal/app/machined/pkg/controllers/cri/registries_config_test.go
  internal/app/machined/pkg/controllers/files/cri_registry_config.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/app/machined/pkg/system/services/registry/app/main.go
  internal/app/machined/pkg/system/services/registry/fs.go
  internal/app/machined/pkg/system/services/registry/params.go
  internal/app/machined/pkg/system/services/registry/registry.go
  internal/app/machined/pkg/system/services/registry/registry_test.go
  internal/app/machined/pkg/system/services/registryd.go
  internal/pkg/containers/image/image.go
  internal/pkg/extensions/pull.go
  internal/pkg/install/install.go
  internal/pkg/install/pull.go
  pkg/machinery/api/resource/definitions/cri/cri.pb.go
  pkg/machinery/api/resource/definitions/cri/cri_vtproto.pb.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/resources/cri/cri.go
  pkg/machinery/resources/cri/cri_test.go
  pkg/machinery/resources/cri/deep_copy.generated.go
  pkg/machinery/resources/cri/registries_config.go
  website/content/v1.9/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge

#9797 feat: update Linux to 6.12.1
  Makefile
  hack/modules-amd64.txt
  hack/modules-arm64.txt
  hack/release.toml
  hack/test/e2e-qemu.sh
  internal/integration/api/selinux.go
  pkg/machinery/api/cluster/cluster.pb.go
  pkg/machinery/api/common/common.pb.go
  pkg/machinery/api/inspect/inspect.pb.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/resource/config/config.pb.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/cluster/cluster.pb.go
  pkg/machinery/api/resource/definitions/cri/cri.pb.go
  pkg/machinery/api/resource/definitions/enums/enums.pb.go
  pkg/machinery/api/resource/definitions/etcd/etcd.pb.go
  pkg/machinery/api/resource/definitions/extensions/extensions.pb.go
  pkg/machinery/api/resource/definitions/files/files.pb.go
  pkg/machinery/api/resource/definitions/hardware/hardware.pb.go
  pkg/machinery/api/resource/definitions/k8s/k8s.pb.go
  pkg/machinery/api/resource/definitions/kubeaccess/kubeaccess.pb.go
  pkg/machinery/api/resource/definitions/kubespan/kubespan.pb.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/perf/perf.pb.go
  pkg/machinery/api/resource/definitions/proto/proto.pb.go
  pkg/machinery/api/resource/definitions/runtime/runtime.pb.go
  pkg/machinery/api/resource/definitions/secrets/secrets.pb.go
  pkg/machinery/api/resource/definitions/siderolink/siderolink.pb.go
  pkg/machinery/api/resource/definitions/time/time.pb.go
  pkg/machinery/api/resource/definitions/v1alpha1/v1alpha1.pb.go
  pkg/machinery/api/resource/network/device_config.pb.go
  pkg/machinery/api/security/security.pb.go
  pkg/machinery/api/storage/storage.pb.go
  pkg/machinery/api/time/time.pb.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#9817 chore: move enabling SELinux by default to 1.10
  hack/release.toml
  pkg/imager/imager.go
  pkg/imager/imager_test.go
  pkg/machinery/imager/quirks/quirks.go
  pkg/provision/providers/qemu/node.go
Labels: status/ok-to-test, status/ok-to-merge, integration/misc-4

#9816 feat: add api-server authorization config
  api/resource/definitions/k8s/k8s.proto
  go.mod
  go.sum
  hack/release.toml
  internal/app/machined/pkg/controllers/k8s/control_plane.go
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod_test.go
  internal/app/machined/pkg/controllers/k8s/control_plane_test.go
  internal/app/machined/pkg/controllers/k8s/render_config_static_pods.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/machinery/api/resource/definitions/k8s/k8s.pb.go
  pkg/machinery/api/resource/definitions/k8s/k8s_vtproto.pb.go
  pkg/machinery/config/config/cluster.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/v1alpha1/v1alpha1_apiserverconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_authorizaationconfigauthorizer.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_examples.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/machinery/resources/k8s/authorization_config.go
  pkg/machinery/resources/k8s/deep_copy.generated.go
  pkg/machinery/resources/k8s/k8s.go
  website/content/v1.9/reference/api.md
  website/content/v1.9/reference/configuration/v1alpha1/config.md
  website/content/v1.9/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge, integration/provision

#9832 chore: deprecate cgroupsv1 in non-container mode
  hack/release.toml
  internal/app/machined/pkg/startup/cgroups.go
  internal/app/machined/pkg/startup/tasks.go
  internal/pkg/mount/v2/cgroups.go
  website/content/v1.9/reference/kernel.md
Labels: status/ok-to-test, status/ok-to-merge

#9830 fix: multiple issues with opening encrypted volumes
  api/resource/definitions/block/block.proto
  internal/app/machined/pkg/controllers/block/internal/volumes/close.go
  internal/app/machined/pkg/controllers/block/internal/volumes/encrypt.go
  internal/app/machined/pkg/controllers/block/internal/volumes/volumes.go
  internal/app/machined/pkg/controllers/block/volume_manager.go
  internal/integration/api/apply-config.go
  internal/pkg/encryption/encryption.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/block/block_vtproto.pb.go
  pkg/machinery/resources/block/deep_copy.generated.go
  pkg/machinery/resources/block/volume_status.go
  website/content/v1.9/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge

#9833 fix: do not extract xattrs in unsquashfs
  internal/pkg/extensions/kernel_modules.go
Labels: status/ok-to-test, status/ok-to-merge

#9828 chore: support saving cluster logs on destroy
  .github/workflows/ci.yaml
  .github/workflows/integration-cilium-cron.yaml
  .github/workflows/integration-conformance-cron.yaml
  .github/workflows/integration-extensions-cron.yaml
  .github/workflows/integration-image-factory-cron.yaml
  .github/workflows/integration-misc-0-cron.yaml
  .github/workflows/integration-misc-1-cron.yaml
  .github/workflows/integration-misc-2-cron.yaml
  .github/workflows/integration-misc-3-cron.yaml
  .github/workflows/integration-misc-4-cron.yaml
  .github/workflows/integration-provision-0-cron.yaml
  .github/workflows/integration-provision-1-cron.yaml
  .github/workflows/integration-provision-2-cron.yaml
  .github/workflows/integration-qemu-cron.yaml
  .github/workflows/integration-qemu-csi-longhorn-cron.yaml
  .github/workflows/integration-qemu-csi-rook-ceph-cron.yaml
  .github/workflows/integration-qemu-encrypted-vip-cron.yaml
  .github/workflows/integration-qemu-race-cron.yaml
  .github/workflows/integration-trusted-boot-cron.yaml
  .github/workflows/slack-notify.yaml
  .kres.yaml
  cmd/talosctl/cmd/mgmt/cluster/create.go
  cmd/talosctl/cmd/mgmt/cluster/destroy.go
  hack/test/e2e-image-factory.sh
  hack/test/e2e-iso.sh
  hack/test/e2e-qemu.sh
  pkg/cluster/logsaarchive.go
  pkg/imager/filemap/filemap.go
  pkg/provision/options.go
  pkg/provision/providers/docker/crashdump.go
  pkg/provision/providers/docker/destroy.go
  pkg/provision/providers/qemu/destroy.go
  pkg/provision/providers/vm/crashdump.go
  pkg/provision/provision.go
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#9834 feat: support overriding base OCI spec for CRI
  Dockerfile
  hack/cri-plugin.part
  hack/release.toml
  internal/app/machined/pkg/controllers/files/cri_base_runtime_spec.go
  internal/app/machined/pkg/controllers/files/cri_base_runtime_spec_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/integration/api/common.go
  internal/integration/base/api.go
  internal/integration/base/k8s.go
  pkg/machinery/config/config/machine.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/v1alpha1/v1alpha1_examples.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
  pkg/machinery/constants/constants.go
  website/content/v1.9/advanced/oci-base-spec.md
  website/content/v1.9/reference/configuration/v1alpha1/config.md
  website/content/v1.9/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu

#9840 chore: update pkgs/extras to final 1.9.0 tags
  Makefile
  pkg/machinery/gendata/data/extras
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#9842 fix: don't reset health status if service doesn't support health checks
  internal/app/machined/pkg/system/service_runner.go
Labels: status/ok-to-test, status/ok-to-merge

#9844 feat: add support for custom search domains
  api/resource/definitions/network/network.proto
  hack/release.toml
  internal/app/machined/pkg/controllers/network/etcfile.go
  internal/app/machined/pkg/controllers/network/etcfile_test.go
  internal/app/machined/pkg/controllers/network/resolver_config.go
  internal/app/machined/pkg/controllers/network/resolver_config_test.go
  internal/app/machined/pkg/controllers/network/resolver_merge.go
  internal/app/machined/pkg/controllers/network/resolver_merge_test.go
  internal/app/machined/pkg/controllers/network/resolver_spec.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/network/network_vtproto.pb.go
  pkg/machinery/config/config/machine.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/v1alpha1/v1alpha1_examples.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/resources/network/deep_copy.generated.go
  pkg/machinery/resources/network/resolver_spec.go
  pkg/machinery/resources/network/resolver_spec_test.go
  pkg/machinery/resources/network/resolver_status.go
  website/content/v1.9/reference/api.md
  website/content/v1.9/reference/configuration/v1alpha1/config.md
  website/content/v1.9/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge
