Repository siderolabs/talos, pull requests merged in 2025-05, with the labels that each got.

#10849 chore(ci): add extensions test for Youki runtime
  internal/integration/api/extensions_qemu.go
Labels: status/ok-to-test, status/ok-to-merge, integration/extensions

#10827 split the `cluster create` command into it's own package
  cmd/talosctl/cmd/mgmt/cluster/cluster.go
  cmd/talosctl/cmd/mgmt/cluster/create/create.go
  cmd/talosctl/cmd/mgmt/cluster/create/create_linux.go
  cmd/talosctl/cmd/mgmt/cluster/create/create_other.go
  cmd/talosctl/cmd/mgmt/cluster/destroy.go
  cmd/talosctl/cmd/mgmt/cluster/show.go
  cmd/talosctl/cmd/root.go
  pkg/provision/providers/factory.go
Labels: status/ok-to-test, status/ok-to-merge

#10850 chore: cross platform qemu preflight checks
  pkg/provision/providers/qemu/arch.go
  pkg/provision/providers/qemu/arch_darwin.go
  pkg/provision/providers/qemu/arch_linux.go
  pkg/provision/providers/qemu/create.go
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/qemu/node.go
  pkg/provision/providers/qemu/preflight.go
  pkg/provision/providers/qemu/preflight_darwin.go
  pkg/provision/providers/qemu/preflight_linux.go
Labels: status/ok-to-test, status/ok-to-merge

#10852 test: update hydrophone to 0.7.0
  go.mod
  go.sum
  pkg/cluster/hydrophone/hydrophone.go
Labels: status/ok-to-test, status/ok-to-merge

#10854 release(v1.11.0-alpha.0): prepare release
  .conform.yaml
  .kres.yaml
  CHANGELOG.md
  go.mod
  hack/release.toml
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/gendata/data/tag
  pkg/machinery/version/os-release
  website/content/v1.11/reference/cli.md
  website/content/v1.11/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge

#10844 docs: add registryd debug command
  website/content/v1.10/talos-guides/configuration/image-cache.md
  website/content/v1.9/talos-guides/configuration/image-cache.md
Labels: status/ok-to-test, status/ok-to-merge

#10860 fix(ci): provision tests
  .github/workflows/ci.yaml
  .github/workflows/integration-provision-0-cron.yaml
  .kres.yaml
  cmd/talosctl/cmd/mgmt/cluster/create/create.go
  hack/test/e2e-qemu.sh
  hack/test/provision-tests.sh
  internal/integration/provision/upgrade.go
  pkg/provision/providers/qemu/node.go
Labels: status/ok-to-test, status/ok-to-merge

#10865 fix: do correct backoff for nocloud reconcile
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud.go
Labels: status/ok-to-test, status/ok-to-merge

#10864 fix: drop libseccomp from rootfs
  Dockerfile
  Makefile
Labels: status/ok-to-test, status/ok-to-merge

#10862 chore: calculate vmnet interface name preemptively
  pkg/provision/providers/vm/network.go
  pkg/provision/providers/vm/network_darwin.go
  pkg/provision/providers/vm/network_test.go
Labels: status/ok-to-test, status/ok-to-merge

#10873 fix(ci): provision cron jobs
  .github/workflows/ci.yaml
  .github/workflows/integration-provision-0-cron.yaml
  .kres.yaml
Labels: status/ok-to-test, status/ok-to-merge

#10856 chore: split cluster create command options
  cmd/talosctl/cmd/mgmt/cluster/create/command.go
  cmd/talosctl/cmd/mgmt/cluster/create/create.go
Labels: status/ok-to-test, status/ok-to-merge

#10875 fix: ignore http proxy on grpc socket dial
  .github/workflows/ci.yaml
  .github/workflows/integration-misc-1-cron.yaml
  .kres.yaml
  hack/test/e2e-qemu.sh
  internal/app/apid/main.go
  internal/app/trustd/main.go
  pkg/machinery/client/connection.go
Labels: status/ok-to-test, status/ok-to-merge, integration/misc-1

#10888 fix: skip PCR extension if TPM1.2 is found
  .github/workflows/ci.yaml
  .github/workflows/integration-misc-2-cron.yaml
  .kres.yaml
  cmd/talosctl/cmd/mgmt/cluster/create/command.go
  cmd/talosctl/cmd/mgmt/cluster/create/create.go
  hack/test/e2e-qemu.sh
  internal/pkg/rng/tpm.go
  internal/pkg/secureboot/tpm2/pcr.go
  pkg/provision/options.go
  pkg/provision/providers/qemu/destroy.go
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/qemu/node.go
  pkg/provision/providers/qemu/preflight_linux.go
  pkg/provision/providers/qemu/tpm2.go
  pkg/provision/result.go
  website/content/v1.11/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge, integration/misc-2

#10891 fix: generating iso greater than 4 gig
  pkg/imager/iso/grub.go
  pkg/imager/iso/hybrid.go
  pkg/imager/iso/uefi.go
Labels: status/ok-to-test, status/ok-to-merge

#10898 fix: replace downloaded asset paths correctly in cluster create cmd
  cmd/talosctl/cmd/mgmt/cluster/create/create.go
Labels: status/ok-to-test, status/ok-to-merge

#10901 release(v1.9.6): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#10874 fix: suppress duplicate platform config updates
  internal/app/machined/pkg/controllers/network/platform_config.go
  internal/app/machined/pkg/controllers/network/platform_config_test.go
  internal/app/machined/pkg/runtime/platform.go
  internal/app/machined/pkg/runtime/platform_test.go
Labels: status/ok-to-test, status/ok-to-merge

#10903 fix: interactive installer config gen
  internal/pkg/configuration/configuration.go
Labels: status/ok-to-test, status/ok-to-merge

#10906 fix: deny apply config requests without v1alpha1 in "normal" mode
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/integration/api/apply-config.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu

#10879 docs: add registryd debug command
  website/content/v1.11/talos-guides/configuration/image-cache.md
Labels: status/ok-to-test, status/ok-to-merge

#10904 docs: fix search on base talos.dev
  website/layouts/partials/hooks/body-end.html
Labels: status/ok-to-test, status/ok-to-merge

#10913 docs: remove azure image gallery instructions
  website/content/v1.10/talos-guides/install/cloud-platforms/azure.md
  website/content/v1.11/talos-guides/install/cloud-platforms/azure.md
  website/content/v1.5/talos-guides/install/cloud-platforms/azure.md
  website/content/v1.6/talos-guides/install/cloud-platforms/azure.md
  website/content/v1.7/talos-guides/install/cloud-platforms/azure.md
  website/content/v1.8/talos-guides/install/cloud-platforms/azure.md
  website/content/v1.9/talos-guides/install/cloud-platforms/azure.md
Labels: status/ok-to-test, status/ok-to-merge

#10914 fix: multiple logic issues in platform network config controller
  internal/app/machined/pkg/controllers/network/platform_config.go
Labels: status/ok-to-test, status/ok-to-merge, integration/aws, integration/aws-nvidia-oss, integration/gcp

#10919 release(v1.10.1): prepare release
  CHANGELOG.md
  go.mod
  hack/release.toml
  pkg/machinery/gendata/data/tag
  pkg/machinery/version/os-release
  website/content/v1.10/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#10900 chore: make qemu lb address bind work on darwin
  pkg/provision/providers/vm/loadbalancer.go
  pkg/provision/providers/vm/loadbalancer_darwin.go
  pkg/provision/providers/vm/loadbalancer_linux.go
Labels: status/ok-to-test, status/ok-to-merge

#10944 fix: improve volume mounter automaton
  internal/app/machined/pkg/automaton/blockautomaton/volume_mount.go
  internal/app/machined/pkg/automaton/blockautomaton/volume_mount_test.go
  internal/app/machined/pkg/controllers/config/acquire_test.go
  internal/app/machined/pkg/controllers/network/platform_config_test.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu, integration/aws

#10967 fix: k8s 1.32->1.33 upgrade check
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#10969 feat: bump dependencies
  Dockerfile
  Makefile
  go.mod
  go.sum
  go.work
  hack/docgen/go.mod
  hack/docgen/go.sum
  hack/release.toml
  hack/structprotogen/go.mod
  hack/structprotogen/go.sum
  internal/integration/k8s/constants.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
  pkg/machinery/gendata/data/tools
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/amd64/snp.efi
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/arm64/snp.efi
Labels: status/ok-to-test, status/ok-to-merge, integration/aws-nvidia-oss

#10964 test: fix some flaky tests
  internal/app/machined/pkg/controllers/network/cmdline_test.go
  internal/app/machined/pkg/system/runner/process/process.go
  internal/app/machined/pkg/system/runner/process/process_test.go
  internal/pkg/dns/dns_test.go
Labels: status/ok-to-test, status/ok-to-merge

#10996 fix: upgrade go-kubernetes for DRA flag bug
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#10997 test: fix the process runner log collection
  internal/app/machined/pkg/system/runner/process/process.go
  internal/app/machined/pkg/system/runner/process/process_test.go
Labels: status/ok-to-test, status/ok-to-merge

#11005 chore: update deps for cloud-image-uploader
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#11006 chore: rotate aws iam credentials
  .secrets.yaml
Labels: status/ok-to-test, status/ok-to-merge, integration/aws

#11000 chore: dump qemu pachine ipam records on darwin
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/qemu/launch_darwin.go
  pkg/provision/providers/qemu/launch_linux.go
Labels: status/ok-to-test, status/ok-to-merge

#11008 chore: update cloud-image-uploader dependencies
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#11004 docs: remove `preserve` flag mention in upgrade notes
  website/content/v1.10/talos-guides/upgrading-talos.md
  website/content/v1.11/talos-guides/upgrading-talos.md
Labels: status/ok-to-merge

#11016 Fix typo in docs
  website/content/v1.10/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.11/kubernetes-guides/network/deploying-cilium.md
Labels: status/ok-to-merge

#11013 Tidy up cluster create flags
  cmd/talosctl/cmd/mgmt/cluster/create/command.go
  cmd/talosctl/cmd/mgmt/cluster/create/command_test.go
  website/content/v1.11/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#11017 fix: consistently apply dynamic grpc proxy dialer
  internal/app/machined/pkg/controllers/runtime/events_sink.go
  internal/app/machined/pkg/controllers/siderolink/manager.go
  internal/pkg/encryption/keys/kms.go
  pkg/grpc/middleware/auth/basic/basic.go
  pkg/grpc/proxy/backend/local.go
Labels: status/ok-to-test, status/ok-to-merge, integration/misc-1

#11018 fix: selinux detection
  internal/pkg/selinux/selinux.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu-enforcing, integration/misc-enforcing

#11025 chore(ci): drop azure keys
  .secrets.yaml
  Makefile
Labels: status/ok-to-test, status/ok-to-merge

#11033 feat: update default Kubernetes to v1.33.1
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/v1.11/reference/cli.md
  website/content/v1.11/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge, integration/provision-2

#11036 release(v1.10.2): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  pkg/machinery/version/os-release
  website/content/v1.10/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#11051 test: fix DHCP unicast failures in QEMU environment
  pkg/provision/providers/vm/dhcpd.go
  pkg/provision/providers/vm/internal/ethtool/ethtool_linux.go
  pkg/provision/providers/vm/internal/ethtool/ethtool_other.go
Labels: status/ok-to-test, status/ok-to-merge, integration/conformance

#11037 Fix typo in docs
  website/content/v1.2/talos-guides/install/cloud-platforms/aws.md
  website/content/v1.3/talos-guides/install/cloud-platforms/aws.md
  website/content/v1.4/talos-guides/install/cloud-platforms/aws.md
  website/content/v1.5/talos-guides/install/cloud-platforms/aws.md
  website/content/v1.6/talos-guides/install/cloud-platforms/aws.md
Labels: status/ok-to-merge

#11039 Fix formatting in docs
  website/content/v1.10/talos-guides/configuration/disk-encryption.md
  website/content/v1.11/talos-guides/configuration/disk-encryption.md
Labels: status/ok-to-merge

#11024 feat: update containerd to 2.1.0
  Makefile
  go.mod
  go.sum
  hack/containerd.toml
  hack/cri-containerd.toml
  hack/cri-plugin.part
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge, integration/extensions, integration/misc-3, integration/misc-enforcing

#11055 refactor: bring owned.State from COSI to simplify tests
  go.mod
  go.sum
  internal/app/machined/pkg/automaton/blockautomaton/volume_mount_test.go
  internal/app/machined/pkg/controllers/network/generic_merge.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#11040 Update virtualbox.md - better workflow
  website/content/v1.10/talos-guides/install/local-platforms/virtualbox.md
  website/content/v1.11/talos-guides/install/local-platforms/virtualbox.md
Labels: status/ok-to-merge

#11063 fix: bump apid memory limit
  internal/integration/api/apid.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu, integration/gcp

#11053 fix: use vmdk-convert istead of qemu-img to create VMDK for OVA files
  Dockerfile
  Makefile
  pkg/imager/ova/ova.go
  pkg/imager/vmdkconvert/vmdkconvert.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-merge, integration/images

#11067 fix: make disk size check work on old Talos
  pkg/cluster/check/nodes.go
Labels: status/ok-to-test, status/ok-to-merge, integration/image-factory

#10946 Update disk-management.md
  website/content/v1.10/talos-guides/configuration/disk-management.md
  website/content/v1.11/talos-guides/configuration/disk-management.md
Labels: status/ok-to-merge

#11071 feat: update containerd to v2.1.1
  Makefile
  go.mod
  go.sum
  hack/containerd.toml
  hack/cri-containerd.toml
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: integration/extensions

#11073 chore: clean up `/usr/bin`
  Makefile
  hack/cleanup.sh
  pkg/machinery/gendata/data/pkgs
  pkg/makefs/xfs_test.go
Labels: integration/cilium, integration/qemu-csi, integration/extensions

#11066 chore: add vmnet support (darwin/qemu)
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/qemu/launch_darwin.go
  pkg/provision/providers/qemu/launch_linux.go
  pkg/provision/providers/qemu/node.go
Labels: status/ok-to-test, status/ok-to-merge

#11079 fix: metal-iso reproducibility
  Makefile
  pkg/imager/iso/uefi.go
Labels: status/ok-to-test, status/ok-to-merge, integration/reproducibility-test

#11082 chore: use custom dhcpd server on macos qemu
  pkg/provision/providers/qemu/create.go
  pkg/provision/providers/vm/dhcpd.go
  pkg/provision/providers/vm/dhcpd_darwin.go
  pkg/provision/providers/vm/dhcpd_linux.go
Labels: status/ok-to-test, status/ok-to-merge

#11077 fix: allow any PKI in Talos API
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/secrets/api.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu

#11088 feat: modularize more arm64 kernel
  Makefile
  hack/modules-arm64.txt
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#11089 fix: nocloud metadata for hostname
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud_test.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/in-v1-pnap.yaml
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/in-v1.yaml
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/in-v2-cloud-init.yaml
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/in-v2-nocloud.yaml
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/in-v2-serverscom.yaml
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/metadata-nocloud.yaml
Labels: status/ok-to-test, status/ok-to-merge

#11087 chore: add a check for unsupported darwin flags
  cmd/talosctl/cmd/mgmt/cluster/create/command.go
Labels: status/ok-to-test, status/ok-to-merge

#11095 fix(ci): iso reproducibility file permissions
  Makefile
Labels: status/ok-to-merge, integration/reproducibility-test

#11100 fix(ci): reproducibility test
  Makefile
Labels: status/ok-to-test, status/ok-to-merge

#11096 Fix CIDR name
  website/content/v1.10/introduction/troubleshooting.md
  website/content/v1.11/introduction/troubleshooting.md
Labels: status/ok-to-merge

#11092 docs: use the cilium-cli image repo in the job installation manifest
  website/content/v1.10/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.11/kubernetes-guides/network/deploying-cilium.md
Labels: status/ok-to-merge

#11107 docs: macos qemu provider
  website/content/v1.11/talos-guides/install/local-platforms/qemu.md
Labels: status/ok-to-test, status/ok-to-merge

#11113 release(v1.10.3): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  pkg/machinery/version/os-release
  website/content/v1.10/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#11110 feat: support qemu provisioner on darwin
  hack/release.toml
Labels: status/ok-to-test, status/ok-to-merge
