Repository siderolabs/talos, pull requests merged in 2025-08, with the labels that each got.

#11482 feat: bootedentry resource
  api/resource/definitions/runtime/runtime.proto
  internal/app/machined/pkg/controllers/runtime/booted_entry.go
  internal/app/machined/pkg/controllers/runtime/security_state.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/efivars.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/machinery/api/resource/definitions/runtime/runtime.pb.go
  pkg/machinery/api/resource/definitions/runtime/runtime_vtproto.pb.go
  pkg/machinery/resources/runtime/booted_entry_status.go
  pkg/machinery/resources/runtime/deep_copy.generated.go
  pkg/machinery/resources/runtime/runtime.go
  pkg/machinery/resources/runtime/runtime_test.go
  website/content/v1.11/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge

#11435 feat: implement encryption locking to STATE
  api/resource/definitions/block/block.proto
  api/resource/definitions/secrets/secrets.proto
  cmd/talosctl/cmd/mgmt/cluster/create/create.go
  hack/release.toml
  internal/app/machined/pkg/adapters/cluster/identity_test.go
  internal/app/machined/pkg/adapters/secrets/encryption_salt.go
  internal/app/machined/pkg/adapters/secrets/encryption_salt_test.go
  internal/app/machined/pkg/adapters/secrets/secrets.go
  internal/app/machined/pkg/controllers/block/internal/volumes/close.go
  internal/app/machined/pkg/controllers/block/internal/volumes/encrypt.go
  internal/app/machined/pkg/controllers/block/internal/volumes/volumes.go
  internal/app/machined/pkg/controllers/block/volume_config.go
  internal/app/machined/pkg/controllers/block/volume_manager.go
  internal/app/machined/pkg/controllers/secrets/encryption_salt.go
  internal/app/machined/pkg/controllers/secrets/encryption_salt_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/integration/api/reset.go
  internal/pkg/encryption/encryption.go
  internal/pkg/encryption/helpers/helpers.go
  internal/pkg/encryption/keys/keys.go
  internal/pkg/encryption/keys/nodeid_test.go
  internal/pkg/encryption/keys/options.go
  internal/pkg/encryption/keys/salted.go
  internal/pkg/encryption/keys/salted_test.go
  internal/pkg/encryption/keys/static_test.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/block/block_vtproto.pb.go
  pkg/machinery/api/resource/definitions/secrets/secrets.pb.go
  pkg/machinery/api/resource/definitions/secrets/secrets_vtproto.pb.go
  pkg/machinery/config/config/machine.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/block/block_doc.go
  pkg/machinery/config/types/block/deep_copy.generated.go
  pkg/machinery/config/types/block/encryption.go
  pkg/machinery/config/types/block/volume_config.go
  pkg/machinery/config/types/block/volume_config_test.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/constants/constants.go
  pkg/machinery/resources/block/volume_config.go
  pkg/machinery/resources/secrets/deep_copy.generated.go
  pkg/machinery/resources/secrets/encryption_salt.go
  pkg/machinery/resources/secrets/secrets.go
  pkg/machinery/resources/secrets/secrets_test.go
  website/content/v1.11/reference/api.md
  website/content/v1.11/reference/configuration/block/rawvolumeconfig.md
  website/content/v1.11/reference/configuration/block/swapvolumeconfig.md
  website/content/v1.11/reference/configuration/block/uservolumeconfig.md
  website/content/v1.11/reference/configuration/block/volumeconfig.md
  website/content/v1.11/schemas/config.schema.json
  website/content/v1.11/talos-guides/configuration/disk-encryption.md
Labels: status/ok-to-test, status/ok-to-merge, integration/misc, integration/qemu, integration/trusted-boot, integration/qemu-encrypted-vip

#11492 chore: run rekres
  .github/workflows/slack-notify.yaml
Labels: status/ok-to-test, status/ok-to-merge

#11486 fix: one more attempt to fix volume mount race on restart
  internal/app/machined/pkg/system/service_runner.go
  internal/app/machined/pkg/system/volumes.go
Labels: status/ok-to-test, status/ok-to-merge

#11498 release(v1.11.0-beta.1): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  pkg/machinery/version/os-release
  website/content/v1.11/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#11497 docs: add what is new notes for 1.11
  website/content/v1.10/_index.md
  website/content/v1.11/_index.md
  website/content/v1.11/introduction/support-matrix.md
  website/content/v1.11/introduction/what-is-new/index.md
  website/content/v1.11/talos-guides/upgrading-talos.md
Labels: status/ok-to-test, status/ok-to-merge

#11515 fix: unmarshal encryption STATE from META
  internal/app/machined/pkg/controllers/block/encryption_meta.go
  internal/app/machined/pkg/controllers/block/encryption_meta_test.go
  internal/app/machined/pkg/controllers/block/volume_config.go
  internal/integration/provision/provision.go
  internal/integration/provision/upgrade.go
Labels: status/ok-to-test, status/ok-to-merge, integration/provision

#11518 refactor: fix deadcode elimination with godbus
  internal/pkg/logind/dbus.go
  internal/pkg/logind/logind.go
  internal/pkg/logind/service.go
Labels: status/ok-to-test, status/ok-to-merge

#11530 feat: add a pause function to dashboard
  internal/pkg/dashboard/components/footer.go
  internal/pkg/dashboard/dashboard.go
Labels: status/ok-to-test, status/ok-to-merge

#11533 chore: add deadcode elimination linter
  Dockerfile
  Makefile
  tools/go.mod
  tools/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#11527 Update deploying-cilium.md
  website/content/v1.10/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.11/kubernetes-guides/network/deploying-cilium.md
Labels: status/ok-to-merge

#11548 docs: fix clone URL to include `.git`
  website/content/v1.10/advanced/kernel-module.md
  website/content/v1.11/advanced/kernel-module.md
Labels: status/ok-to-merge

#11552 feat: update default Kubernetes to v1.34.0-rc.1
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/v1.11/_index.md
  website/content/v1.11/introduction/what-is-new/index.md
  website/content/v1.11/reference/cli.md
  website/content/v1.11/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge, integration/provision

#11557 release(v1.11.0-beta.2): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  pkg/machinery/version/os-release
  website/content/v1.11/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#11571 fix: set secs field in DHCPv4 packets
  internal/app/machined/pkg/controllers/network/operator/dhcp4.go
Labels: status/ok-to-test, status/ok-to-merge

#11583 fix: darwin build
  pkg/provision/providers/qemu/node_darwin.go
Labels: status/ok-to-test, status/ok-to-merge

#11584 chore: re-enable vulncheck
  Makefile
Labels: status/ok-to-test, status/ok-to-merge

#11532 feat: add a user facing docker command
  cmd/talosctl/cmd/mgmt/cluster/cluster.go
  cmd/talosctl/cmd/mgmt/cluster/create/cmd.go
  cmd/talosctl/cmd/mgmt/cluster/create/cmd_dev.go
  cmd/talosctl/cmd/mgmt/cluster/create/cmd_docker.go
  cmd/talosctl/cmd/mgmt/cluster/create/command.go
  cmd/talosctl/cmd/mgmt/cluster/create/command_test.go
  cmd/talosctl/cmd/mgmt/cluster/create/create.go
  cmd/talosctl/cmd/mgmt/cluster/create/create_dev.go
  cmd/talosctl/cmd/mgmt/cluster/create/create_docker.go
  cmd/talosctl/cmd/mgmt/cluster/create/create_test.go
  cmd/talosctl/pkg/mgmt/helpers/image.go
  hack/test/e2e-docker.sh
  website/content/v1.12/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#11556 feat: use key provider with fallback option for auth type SideroV1
  cmd/talosctl/cmd/talos/root.go
  cmd/talosctl/pkg/talos/global/client.go
  go.mod
  go.sum
  pkg/machinery/client/connection.go
  pkg/machinery/client/options.go
  pkg/machinery/constants/constants.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  website/content/v1.11/learn-more/talosctl.md
  website/content/v1.11/reference/cli.md
  website/content/v1.12/learn-more/talosctl.md
  website/content/v1.12/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#11592 feat: update Linux to 6.12.41
  Makefile
  hack/modules-amd64.txt
  hack/modules-arm64.txt
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
  website/content/v1.11/introduction/what-is-new/index.md
Labels: status/ok-to-test, status/ok-to-merge

#11615 docs: apply fixes for what is new
  .github/workflows/ci.yaml
  .github/workflows/grype-scan-cron.yaml
  .github/workflows/integration-aws-cron.yaml
  .github/workflows/integration-aws-nvidia-nonfree-lts-cron.yaml
  .github/workflows/integration-aws-nvidia-nonfree-production-cron.yaml
  .github/workflows/integration-aws-nvidia-oss-lts-cron.yaml
  .github/workflows/integration-aws-nvidia-oss-production-cron.yaml
  .github/workflows/integration-cilium-cron.yaml
  .github/workflows/integration-conformance-cron.yaml
  .github/workflows/integration-conformance-enforcing-cron.yaml
  .github/workflows/integration-extensions-cron.yaml
  .github/workflows/integration-gcp-cron.yaml
  .github/workflows/integration-image-cache-cron.yaml
  .github/workflows/integration-image-factory-cron.yaml
  .github/workflows/integration-images-cron.yaml
  .github/workflows/integration-misc-0-cron.yaml
  .github/workflows/integration-misc-1-cron.yaml
  .github/workflows/integration-misc-1-enforcing-cron.yaml
  .github/workflows/integration-misc-2-cron.yaml
  .github/workflows/integration-misc-3-cron.yaml
  .github/workflows/integration-misc-3-enforcing-cron.yaml
  .github/workflows/integration-misc-4-cron.yaml
  .github/workflows/integration-misc-4-enforcing-cron.yaml
  .github/workflows/integration-provision-0-cron.yaml
  .github/workflows/integration-provision-1-cron.yaml
  .github/workflows/integration-provision-2-cron.yaml
  .github/workflows/integration-qemu-cron.yaml
  .github/workflows/integration-qemu-csi-longhorn-cron.yaml
  .github/workflows/integration-qemu-csi-openebs-cron.yaml
  .github/workflows/integration-qemu-csi-rook-ceph-cron.yaml
  .github/workflows/integration-qemu-encrypted-vip-cron.yaml
  .github/workflows/integration-qemu-enforcing-cron.yaml
  .github/workflows/integration-qemu-race-cron.yaml
  .github/workflows/integration-reproducibility-test-cron.yaml
  .github/workflows/integration-trusted-boot-cron.yaml
  .github/workflows/integration-trusted-boot-enforcing-cron.yaml
  hack/release.toml
  website/content/v1.11/introduction/what-is-new/index.md
Labels: status/ok-to-test, status/ok-to-merge

#11618 test: don't run nvidia tests on integration/aws
  .github/workflows/ci.yaml
  .kres.yaml
Labels: status/ok-to-test, status/ok-to-merge

#11617 refactor: split the PlatformConfigController
  api/resource/definitions/enums/enums.proto
  api/resource/definitions/network/network.proto
  internal/app/machined/pkg/controllers/network/node_address_test.go
  internal/app/machined/pkg/controllers/network/platform_config.go
  internal/app/machined/pkg/controllers/network/platform_config_apply.go
  internal/app/machined/pkg/controllers/network/platform_config_apply_test.go
  internal/app/machined/pkg/controllers/network/platform_config_load.go
  internal/app/machined/pkg/controllers/network/platform_config_load_test.go
  internal/app/machined/pkg/controllers/network/platform_config_store.go
  internal/app/machined/pkg/controllers/network/platform_config_store_test.go
  internal/app/machined/pkg/controllers/network/platform_config_test.go
  internal/app/machined/pkg/runtime/platform.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  pkg/machinery/api/resource/definitions/enums/enums.pb.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/network/network_vtproto.pb.go
  pkg/machinery/resources/network/address_spec.go
  pkg/machinery/resources/network/deep_copy.generated.go
  pkg/machinery/resources/network/network_test.go
  pkg/machinery/resources/network/platform_config.go
  pkg/machinery/resources/network/platform_config_test.go
  tools/structprotogen/proto/proto.go
  website/content/v1.12/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge, integration/aws, integration/gcp

#11628 fix: make --with-uuid-hostnames functionality available to qemu provider
  cmd/talosctl/cmd/mgmt/cluster/create/cmd.go
  cmd/talosctl/cmd/mgmt/cluster/create/cmd_dev.go
  cmd/talosctl/cmd/mgmt/cluster/create/create.go
  cmd/talosctl/cmd/mgmt/cluster/create/create_dev.go
  cmd/talosctl/cmd/mgmt/cluster/create/create_test.go
Labels: status/ok-to-test, status/ok-to-merge

#11620 chore: use new filesystem api on STATE partition
  internal/app/machined/pkg/controllers/cluster/node_identity.go
  internal/app/machined/pkg/controllers/kubespan/identity.go
  internal/app/machined/pkg/controllers/secrets/encryption_salt.go
  internal/app/machined/pkg/controllers/utils.go
  internal/pkg/xfs/fsopen/fsopen_linux.go
  internal/pkg/xfs/fsopen/options_linux.go
  internal/pkg/xfs/fsopen_test.go
  internal/pkg/xfs/opentree/opentree_linux.go
  internal/pkg/xfs/opentree_test.go
  internal/pkg/xfs/root.go
  internal/pkg/xfs/root_test.go
  internal/pkg/xfs/root_unix.go
Labels: status/ok-to-test, status/ok-to-merge

#11632 test: fix the Image Factory PXE boot test
  .github/workflows/ci.yaml
  .github/workflows/integration-image-factory-cron.yaml
  .kres.yaml
  hack/test/e2e-image-factory.sh
Labels: status/ok-to-test, status/ok-to-merge

#11623 feat: add a user-facing create qemu command
  cmd/talosctl/cmd/mgmt/cluster/cluster.go
  cmd/talosctl/cmd/mgmt/cluster/create/cmd.go
  cmd/talosctl/cmd/mgmt/cluster/create/cmd_dev.go
  cmd/talosctl/cmd/mgmt/cluster/create/cmd_docker.go
  cmd/talosctl/cmd/mgmt/cluster/create/cmd_qemu.go
  cmd/talosctl/cmd/mgmt/cluster/create/create_dev.go
  cmd/talosctl/cmd/mgmt/cluster/destroy.go
  cmd/talosctl/cmd/mgmt/cluster/show.go
  website/content/v1.12/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#11638 feat: update Kubernetes default to v1.34.0-rc.2
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/v1.11/introduction/what-is-new/index.md
  website/content/v1.12/reference/cli.md
  website/content/v1.12/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge, integration/conformance

#11639 feat: update NVIDIA drivers and kernel
  Makefile
  pkg/machinery/gendata/data/pkgs
  website/content/v1.12/_index.md
  website/content/v1.12/introduction/support-matrix.md
Labels: status/ok-to-test, status/ok-to-merge

#11674 release(v1.10.7): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  pkg/machinery/version/os-release
  website/content/v1.10/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#11680 feat: add SOCKS5 proxy support to dynamic proxy dialer
  go.mod
  go.sum
  pkg/machinery/client/dialer/dialer_test.go
  pkg/machinery/client/dialer/proxy.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-merge

#11523 docs: add sbc unofficial ports docs
  website/content/v1.10/talos-guides/install/single-board-computers/unofficial.md
  website/content/v1.11/talos-guides/install/single-board-computers/unofficial.md
  website/content/v1.12/talos-guides/install/single-board-computers/unofficial.md
Labels: status/ok-to-merge

#11692 test: ignore one leaking goroutine
  internal/app/machined/pkg/controllers/network/dns_resolve_cache_test.go
  internal/app/machined/pkg/controllers/network/network_test.go
Labels: status/ok-to-test, status/ok-to-merge

#11684 chore: update some tools
  internal/app/machined/pkg/controllers/cri/seccomp_profile_file_test.go
  pkg/machinery/api/cluster/cluster.pb.go
  pkg/machinery/api/common/common.pb.go
  pkg/machinery/api/inspect/inspect.pb.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/resource/config/config.pb.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/cluster/cluster.pb.go
  pkg/machinery/api/resource/definitions/cri/cri.pb.go
  pkg/machinery/api/resource/definitions/enums/enums.pb.go
  pkg/machinery/api/resource/definitions/etcd/etcd.pb.go
  pkg/machinery/api/resource/definitions/extensions/extensions.pb.go
  pkg/machinery/api/resource/definitions/files/files.pb.go
  pkg/machinery/api/resource/definitions/hardware/hardware.pb.go
  pkg/machinery/api/resource/definitions/k8s/k8s.pb.go
  pkg/machinery/api/resource/definitions/kubeaccess/kubeaccess.pb.go
  pkg/machinery/api/resource/definitions/kubespan/kubespan.pb.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/perf/perf.pb.go
  pkg/machinery/api/resource/definitions/proto/proto.pb.go
  pkg/machinery/api/resource/definitions/runtime/runtime.pb.go
  pkg/machinery/api/resource/definitions/secrets/secrets.pb.go
  pkg/machinery/api/resource/definitions/siderolink/siderolink.pb.go
  pkg/machinery/api/resource/definitions/time/time.pb.go
  pkg/machinery/api/resource/definitions/v1alpha1/v1alpha1.pb.go
  pkg/machinery/api/resource/network/device_config.pb.go
  pkg/machinery/api/security/security.pb.go
  pkg/machinery/api/storage/storage.pb.go
  pkg/machinery/api/time/time.pb.go
  tools/go.mod
  tools/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#11700 fix: update xz module (security)
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#11701 fix: drop linux/armv7 build
  .github/workflows/ci.yaml
  .github/workflows/grype-scan-cron.yaml
  .github/workflows/integration-aws-cron.yaml
  .github/workflows/integration-aws-nvidia-nonfree-lts-cron.yaml
  .github/workflows/integration-aws-nvidia-nonfree-production-cron.yaml
  .github/workflows/integration-aws-nvidia-oss-lts-cron.yaml
  .github/workflows/integration-aws-nvidia-oss-production-cron.yaml
  .github/workflows/integration-cilium-cron.yaml
  .github/workflows/integration-conformance-cron.yaml
  .github/workflows/integration-conformance-enforcing-cron.yaml
  .github/workflows/integration-extensions-cron.yaml
  .github/workflows/integration-gcp-cron.yaml
  .github/workflows/integration-image-cache-cron.yaml
  .github/workflows/integration-image-factory-cron.yaml
  .github/workflows/integration-images-cron.yaml
  .github/workflows/integration-misc-0-cron.yaml
  .github/workflows/integration-misc-1-cron.yaml
  .github/workflows/integration-misc-1-enforcing-cron.yaml
  .github/workflows/integration-misc-2-cron.yaml
  .github/workflows/integration-misc-3-cron.yaml
  .github/workflows/integration-misc-3-enforcing-cron.yaml
  .github/workflows/integration-misc-4-cron.yaml
  .github/workflows/integration-misc-4-enforcing-cron.yaml
  .github/workflows/integration-provision-0-cron.yaml
  .github/workflows/integration-provision-1-cron.yaml
  .github/workflows/integration-provision-2-cron.yaml
  .github/workflows/integration-qemu-cron.yaml
  .github/workflows/integration-qemu-csi-longhorn-cron.yaml
  .github/workflows/integration-qemu-csi-openebs-cron.yaml
  .github/workflows/integration-qemu-csi-rook-ceph-cron.yaml
  .github/workflows/integration-qemu-encrypted-vip-cron.yaml
  .github/workflows/integration-qemu-enforcing-cron.yaml
  .github/workflows/integration-qemu-race-cron.yaml
  .github/workflows/integration-reproducibility-test-cron.yaml
  .github/workflows/integration-trusted-boot-cron.yaml
  .github/workflows/integration-trusted-boot-enforcing-cron.yaml
  .kres.yaml
  Dockerfile
Labels: status/ok-to-test, status/ok-to-merge, integration/reproducibility-test

#11699 feat: update CoreDNS to 1.12.3
  go.mod
  go.sum
  hack/release.toml
  pkg/machinery/constants/constants.go
  website/content/v1.12/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge
