Repository siderolabs/talos, pull requests merged in 2025-06, with the labels that each got.

#11131 fix(talosctl): correct --help output for dashboard command
  cmd/talosctl/cmd/talos/dashboard.go
  website/content/v1.11/reference/cli.md
Labels: status/ok-to-merge

#11136 fix: upgrade grpc library to the latest 1.71.x
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: integration/misc

#11137 feat: drop IMA support
  Makefile
  hack/release.toml
  internal/app/machined/pkg/startup/ima.go
  internal/app/machined/pkg/startup/startup.go
  pkg/imager/imager_test.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
  pkg/machinery/imager/quirks/quirks.go
  pkg/machinery/kernel/kernel.go
  pkg/machinery/kernel/kernel_test.go
  website/content/v1.11/talos-guides/configuration/logging.md
  website/content/v1.11/talos-guides/install/bare-metal-platforms/secureboot.md
  website/content/v1.11/talos-guides/install/boot-assets.md
  website/content/v1.11/talos-guides/install/single-board-computers/rpi_generic.md
Labels: status/ok-to-test, status/ok-to-merge

#11146 fix: marshal resource byte slices as strings in YAML
  internal/app/machined/pkg/controllers/block/volume_config_test.go
  pkg/machinery/resources/block/volume_config.go
  pkg/machinery/resources/files/etcfile_spec.go
  pkg/machinery/yamlutils/yamlutils.go
  pkg/machinery/yamlutils/yamlutils_test.go
Labels: status/ok-to-test, status/ok-to-merge

#11163 feat: update Flannel to 0.27.0
  hack/release.toml
  pkg/flannel/template.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#11174 chore: update Go to 1.24.4
  Makefile
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
  pkg/machinery/gendata/data/tools
Labels: status/ok-to-test, status/ok-to-merge

#11182 fix: update siderolink library for wgtunnel panic fix
  go.mod
  go.sum
  go.work
Labels: status/ok-to-test, status/ok-to-merge, integration/misc-4, integration/misc-4-enforcing

#11181 fix: correctl close encrypted volumes
  internal/app/machined/pkg/controllers/block/internal/volumes/close.go
Labels: status/ok-to-test, status/ok-to-merge

#11180 Update kvm.md
  website/content/v1.10/talos-guides/install/virtualized-platforms/kvm.md
  website/content/v1.11/talos-guides/install/virtualized-platforms/kvm.md
Labels: status/ok-to-merge

#11202 docs: expand documentation description
  pkg/machinery/config/encoder/markdown.go
  website/assets/scss/_styles_project.scss
  website/content/v1.11/reference/configuration/block/swapvolumeconfig.md
  website/content/v1.11/reference/configuration/block/uservolumeconfig.md
  website/content/v1.11/reference/configuration/block/volumeconfig.md
  website/content/v1.11/reference/configuration/network/ethernetconfig.md
  website/content/v1.11/reference/configuration/network/kubespanendpointsconfig.md
  website/content/v1.11/reference/configuration/network/networkruleconfig.md
  website/content/v1.11/reference/configuration/runtime/kmsglogconfig.md
  website/content/v1.11/reference/configuration/runtime/watchdogtimerconfig.md
  website/content/v1.11/reference/configuration/security/trustedrootsconfig.md
  website/content/v1.11/reference/configuration/siderolink/siderolinkconfig.md
  website/content/v1.11/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#11204 fix: userspace wireguard library overrides
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge, integration/misc-4

#11209 arm64 support for platform vmware
  go.mod
  go.sum
  hack/release.toml
  internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_other.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_supported.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-merge

#11211 chore: add user-space InfiniBand modules
  hack/modules-amd64.txt
  hack/modules-arm64.txt
Labels: status/ok-to-merge

#11124 docs(sbom): create SBOM for Go dependencies
  .dockerignore
  .github/workflows/ci.yaml
  .github/workflows/lock.yml
  .github/workflows/stale.yml
  .kres.yaml
  Dockerfile
  Makefile
  go.work
  tools/go.mod
  tools/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#11091 docs: add docs for creating kernel modules
  website/content/v1.10/advanced/kernel-module.md
  website/content/v1.11/advanced/kernel-module.md
Labels: status/ok-to-test, status/ok-to-merge

#11262 fix: set default MTU on Azure to 1400
  hack/release.toml
  internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/azure/testdata/expected.yaml
Labels: status/ok-to-test, status/ok-to-merge

#11208 feat: enforce Kubernetes version compatibility
  cmd/installer/pkg/install/preflight.go
  cmd/installer/pkg/install/preflight_test.go
  hack/release.toml
  internal/integration/provision/k8s_compatibility.go
  pkg/cluster/kubernetes/compat.go
  pkg/cluster/kubernetes/talos_managed.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
Labels: status/ok-to-test, status/ok-to-merge

#11263 fix: treat context canceled as expected error on image pull
  internal/pkg/containers/image/image.go
Labels: status/ok-to-test, status/ok-to-merge

#11264 feat: update Linux to 6.12.35, containerd to 2.1.3
  Makefile
  go.mod
  go.sum
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu, integration/extensions

#11266 fix: etcd recover with multiple advertised addresses
  internal/app/machined/pkg/system/services/etcd.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu

#11231 docs: add vc4 memory documentation
  website/content/v1.10/talos-guides/install/single-board-computers/rpi_generic.md
  website/content/v1.11/talos-guides/install/single-board-computers/rpi_generic.md
Labels: status/ok-to-merge

#11199 feat: implement zswap support
  api/resource/definitions/block/block.proto
  cmd/talosctl/cmd/talos/cgroupsprinter/presets/swap.yaml
  hack/release.toml
  hack/test/patches/ephemeral-nvme.yaml
  internal/app/machined/pkg/controllers/block/zswap_config.go
  internal/app/machined/pkg/controllers/block/zswap_status.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/app/machined/pkg/startup/cgroups.go
  internal/integration/api/volumes.go
  internal/pkg/cgroups/cgroups.go
  internal/pkg/mount/v2/pseudo.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/block/block_vtproto.pb.go
  pkg/machinery/config/config/config.go
  pkg/machinery/config/config/volume.go
  pkg/machinery/config/container/container.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/block/block.go
  pkg/machinery/config/types/block/block_doc.go
  pkg/machinery/config/types/block/deep_copy.generated.go
  pkg/machinery/config/types/block/testdata/zswapconfig_full.yaml
  pkg/machinery/config/types/block/testdata/zswapconfig_min.yaml
  pkg/machinery/config/types/block/zswap_config.go
  pkg/machinery/config/types/block/zswap_config_test.go
  pkg/machinery/resources/block/block.go
  pkg/machinery/resources/block/block_test.go
  pkg/machinery/resources/block/deep_copy.generated.go
  pkg/machinery/resources/block/zswap_status.go
  website/content/v1.11/reference/api.md
  website/content/v1.11/reference/configuration/block/zswapconfig.md
  website/content/v1.11/schemas/config.schema.json
  website/content/v1.11/talos-guides/configuration/swap.md
Labels: status/ok-to-test, status/ok-to-merge
