Repository siderolabs/talos, pull requests merged in 2025-04, with the labels that each got.

#10621 fix: image cache generation on Windows
  cmd/talosctl/cmd/talos/image.go
  pkg/imager/cache/cache.go
  pkg/imager/filemap/filemap.go
  website/content/v1.10/reference/cli.md
Labels: integration/image-cache

#10625 test: fix enforcing steps in cron
  .github/workflows/ci.yaml
  .github/workflows/integration-conformance-enforcing-cron.yaml
  .github/workflows/integration-misc-1-enforcing-cron.yaml
  .github/workflows/integration-misc-3-enforcing-cron.yaml
  .github/workflows/integration-misc-4-enforcing-cron.yaml
  .github/workflows/integration-qemu-enforcing-cron.yaml
  .github/workflows/integration-trusted-boot-enforcing-cron.yaml
  .kres.yaml
  hack/test/e2e-qemu.sh
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu-enforcing, integration/conformance-enforcing, integration/trusted-boot-enforcing, integration/misc-enforcing

#10628 fix: use proper read-only bind mounts in init
  internal/app/init/main.go
  internal/app/machined/pkg/controllers/files/etcfile.go
  internal/pkg/mount/v2/bind.go
Labels: status/ok-to-test, status/ok-to-merge, integration/extensions

#10633 test: more extension modules
  Makefile
  hack/modules-amd64.txt
  hack/modules-arm64.txt
  hack/test/patches/extensions.yaml
  internal/integration/api/extensions_qemu.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge, integration/aws

#10623 feat: support xfs mkfs config version
  Dockerfile
  cmd/installer/pkg/install/install.go
  hack/cleanup.sh
  internal/app/machined/pkg/controllers/block/internal/volumes/format.go
  internal/pkg/partition/format.go
  pkg/machinery/imager/quirks/quirks.go
  pkg/machinery/imager/quirks/quirks_test.go
  pkg/makefs/makefs.go
  pkg/makefs/xfs.go
Labels: status/ok-to-test, status/ok-to-merge

#10622 feat: add vc4 documentation
  website/content/v1.10/talos-guides/install/single-board-computers/rpi_generic.md
Labels: status/ok-to-merge

#10636 fix: race in the volume mount status handling
  internal/app/machined/pkg/controllers/block/mount_status.go
  internal/app/machined/pkg/controllers/block/mount_status_test.go
  internal/app/machined/pkg/system/service_runner.go
  internal/app/machined/pkg/system/volumes.go
Labels: status/ok-to-test, status/ok-to-merge

#10642 chore: small developer improvements
  .github/workflows/integration-aws-nvidia-oss-cron.yaml
  .kres.yaml
  Makefile
Labels: status/ok-to-test, status/ok-to-merge

#10640 fix: Avoid printing terminating null byte in SELinux context
  cmd/talosctl/cmd/talos/list.go
Labels: status/ok-to-merge

#10639 feat: expose if system is booted with UKI
  .github/workflows/ci.yaml
  .github/workflows/integration-misc-2-cron.yaml
  .kres.yaml
  api/resource/definitions/runtime/runtime.proto
  internal/app/machined/pkg/controllers/runtime/security_state.go
  internal/integration/api/trustedboot.go
  internal/integration/api/uki.go
  internal/integration/base/base.go
  internal/integration/integration_test.go
  pkg/machinery/api/resource/definitions/runtime/runtime.pb.go
  pkg/machinery/api/resource/definitions/runtime/runtime_vtproto.pb.go
  pkg/machinery/resources/runtime/security_status.go
  website/content/v1.10/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge

#10644 fix: handling of override path for registry mirrors
  api/api.descriptors
  api/resource/definitions/cri/cri.proto
  internal/app/machined/pkg/controllers/cri/registries_config.go
  internal/app/machined/pkg/controllers/cri/registries_config_test.go
  internal/pkg/containers/cri/containerd/hosts.go
  internal/pkg/containers/image/resolver.go
  pkg/machinery/api/resource/definitions/cri/cri.pb.go
  pkg/machinery/api/resource/definitions/cri/cri_vtproto.pb.go
  pkg/machinery/config/config/machine.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/resources/cri/deep_copy.generated.go
  pkg/machinery/resources/cri/registries_config.go
  website/content/v1.10/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge, integration/image-cache

#10660 docs: improve references to config patches
  website/content/v1.10/talos-guides/configuration/patching.md
  website/content/v1.10/talos-guides/install/bare-metal-platforms/matchbox.md
  website/content/v1.10/talos-guides/install/cloud-platforms/gcp.md
  website/content/v1.10/talos-guides/install/cloud-platforms/hetzner.md
  website/content/v1.10/talos-guides/install/cloud-platforms/openstack.md
  website/content/v1.10/talos-guides/install/cloud-platforms/oracle.md
  website/content/v1.10/talos-guides/install/cloud-platforms/upcloud.md
Labels: status/ok-to-test, status/ok-to-merge

#10662 fix: uki boot detection
  .github/workflows/ci.yaml
  .github/workflows/integration-gcp-cron.yaml
  .kres.yaml
  cmd/talosctl/cmd/talos/list.go
  hack/cloud-image-uploader/gcp.go
  internal/app/machined/pkg/controllers/runtime/security_state.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/efivars.go
  internal/integration/api/common.go
  internal/integration/api/uki.go
  internal/integration/base/base.go
  internal/integration/integration_test.go
Labels: status/ok-to-test, status/ok-to-merge, integration/gcp

#10657 feat: prefer uefi boot for aws ami's
  .github/workflows/ci.yaml
  .github/workflows/integration-gcp-cron.yaml
  .kres.yaml
  hack/cloud-image-uploader/aws.go
Labels: status/ok-to-test, status/ok-to-merge, integration/aws

#10643 feat: add support for instance tags on AWS
  api/resource/definitions/runtime/runtime.proto
  hack/test/tfvars/aws.jq
  internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/aws/metadata.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/aws/testdata/expected.yaml
  internal/app/machined/pkg/runtime/v1alpha1/platform/aws/testdata/metadata.json
  internal/integration/api/platform.go
  pkg/machinery/api/resource/definitions/runtime/runtime.pb.go
  pkg/machinery/api/resource/definitions/runtime/runtime_vtproto.pb.go
  pkg/machinery/resources/runtime/deep_copy.generated.go
  pkg/machinery/resources/runtime/platform_metadata.go
  website/content/v1.10/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge, integration/aws

#10663 feat: add support for GCP instance tags
  internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/metadata.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/testdata/expected.yaml
  internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/testdata/metadata.json
  internal/integration/api/platform.go
Labels: status/ok-to-test, status/ok-to-merge, integration/gcp

#10664 fix: skip lvm activation if meta is not found
  internal/app/machined/pkg/controllers/block/lvm.go
Labels: integration/qemu

#10694 feat: update Flannel to v0.26.6
  hack/release.toml
  pkg/flannel/template.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#10695 feat: add Hisilicon arm drivers
  Makefile
  hack/modules-arm64.txt
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#10703 feat: add a version resource
  internal/app/machined/pkg/controllers/runtime/version.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/integration/api/version.go
  pkg/machinery/resources/cri/image_cache_config.go
  pkg/machinery/resources/cri/registries_config.go
  pkg/machinery/resources/cri/seccomp_profile.go
  pkg/machinery/resources/runtime/deep_copy.generated.go
  pkg/machinery/resources/runtime/runtime.go
  pkg/machinery/resources/runtime/version.go
Labels: status/ok-to-test, status/ok-to-merge

#10711 test: add negative tests for SELinux
  internal/integration/api/selinux.go
  internal/integration/base/k8s.go
  internal/pkg/selinux/policy/policy.33
  internal/pkg/selinux/policy/selinux/common/processes.cil
Labels: status/ok-to-test, status/ok-to-merge

#10715 feat: update Linux to 6.12.23
  Dockerfile
  Makefile
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/extras
  pkg/machinery/gendata/data/pkgs
  pkg/machinery/gendata/gendata.go
  pkg/machinery/version/version.go
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/arm64/snp.efi
Labels: status/ok-to-test, status/ok-to-merge, integration/extensions

#10718 chore: bump dependencies
  .golangci.yml
  Makefile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/docgen/go.mod
  hack/docgen/go.sum
  hack/release.toml
  hack/structprotogen/go.mod
  hack/structprotogen/go.sum
  internal/app/machined/pkg/controllers/k8s/control_plane.go
  internal/app/machined/pkg/controllers/k8s/control_plane_test.go
  internal/app/machined/pkg/controllers/k8s/k8s.go
  internal/app/machined/pkg/controllers/k8s/kubelet_spec.go
  internal/app/machined/pkg/controllers/network/link_merge_test.go
  pkg/machinery/config/types/network/ethernet.go
  pkg/machinery/config/types/network/kubespan_endpoints.go
  pkg/machinery/config/types/network/rule_config.go
  pkg/machinery/config/types/runtime/kmsg_log.go
  pkg/machinery/config/types/runtime/watchdog_timer.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
  pkg/machinery/gendata/data/tools
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/provision/providers/vm/network.go
  website/content/v1.10/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge, integration/misc, integration/qemu, integration/cilium, integration/qemu-csi

#10704 fix: upgrades with bios
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/install.go
Labels: status/ok-to-test, status/ok-to-merge

#10722 feat: update base CoreDNS code in host DNS to 1.12.1
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#10721 release(v1.10.0-beta.0): prepare release
  .github/workflows/ci.yaml
  .github/workflows/integration-aws-nvidia-nonfree-cron.yaml
  .github/workflows/integration-aws-nvidia-oss-cron.yaml
  .github/workflows/integration-extensions-cron.yaml
  .github/workflows/integration-qemu-csi-longhorn-cron.yaml
  .kres.yaml
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  pkg/machinery/version/os-release
  website/content/v1.10/reference/cli.md
Labels: status/ok-to-merge, integration/extensions

#10730 Docs improvements
  website/content/v1.0/introduction/theila.md
  website/content/v1.1/introduction/theila.md
  website/content/v1.10/talos-guides/configuration/patching.md
  website/content/v1.2/talos-guides/configuration/patching.md
  website/content/v1.3/kubernetes-guides/configuration/storage.md
  website/content/v1.3/talos-guides/configuration/patching.md
  website/content/v1.4/kubernetes-guides/configuration/storage.md
  website/content/v1.4/talos-guides/configuration/patching.md
  website/content/v1.5/talos-guides/configuration/patching.md
  website/content/v1.6/talos-guides/configuration/patching.md
  website/content/v1.7/talos-guides/configuration/patching.md
  website/content/v1.8/talos-guides/configuration/patching.md
  website/content/v1.9/talos-guides/configuration/patching.md
  website/layouts/_default/_markup/render-heading.html
Labels: status/ok-to-merge

#10732 feat: support address priority
  api/resource/definitions/network/network.proto
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/network/address_spec.go
  internal/app/machined/pkg/controllers/network/address_spec_test.go
  internal/app/machined/pkg/controllers/network/address_status.go
  internal/app/machined/pkg/controllers/network/address_status_test.go
  internal/app/machined/pkg/controllers/network/nftables_chain_test.go
  internal/app/machined/pkg/controllers/network/operator/dhcp4.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/network/network_vtproto.pb.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/machinery/resources/network/address_spec.go
  pkg/machinery/resources/network/address_status.go
  website/content/v1.10/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge

#10735 feat: update Kubernetes to 1.33.0-rc.1
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/v1.10/reference/cli.md
  website/content/v1.10/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge, integration/provision

#10736 docs: fix search
  website/layouts/partials/hooks/body-end.html
Labels: status/ok-to-merge

#10739 fix: prefer new `MountStatus` resource
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/machinery/resources/runtime/mount_status.go
Labels: status/ok-to-test, status/ok-to-merge

#10733 Update kubeprism.md
  website/content/v1.10/kubernetes-guides/configuration/kubeprism.md
  website/content/v1.9/kubernetes-guides/configuration/kubeprism.md
Labels: status/ok-to-test, status/ok-to-merge

#10740 feat: update Flannel to v0.26.7
  hack/release.toml
  pkg/flannel/template.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#10741 feat: add new SBCs
  pkg/machinery/platforms/sbcs.go
Labels: status/ok-to-test, status/ok-to-merge

#10746 fix: grub efi platform install
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/install.go
Labels: status/ok-to-test, status/ok-to-merge

#10748 fix: grub EFI mount point
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/install.go
Labels: status/ok-to-test, status/ok-to-merge

#10758 docs: add a dark theme
  website/assets/scss/_sidebar-toc.scss
  website/assets/scss/_sidebar-tree.scss
  website/assets/scss/_styles_project.scss
  website/assets/scss/_variables_project.scss
  website/hugo.toml
  website/layouts/_default/_markup/render-codeblock.html
  website/layouts/partials/hooks/body-end.html
  website/layouts/partials/hooks/head-end.html
Labels: status/ok-to-merge

#10762 chore(docs): fixed typo at OpenEBS Mayastor worker patches
  website/content/v1.9/kubernetes-guides/configuration/storage.md
Labels: status/ok-to-merge

#10747 feat: support encryption config for user volumes
  cmd/talosctl/cmd/mgmt/cluster/create.go
  hack/test/e2e-qemu.sh
  internal/app/machined/pkg/controllers/block/user_volume_config.go
  internal/app/machined/pkg/controllers/block/user_volume_config_test.go
  internal/app/machined/pkg/controllers/block/volume_config.go
  pkg/machinery/config/config/machine.go
  pkg/machinery/config/config/volume.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/block/block.go
  pkg/machinery/config/types/block/block_doc.go
  pkg/machinery/config/types/block/deep_copy.generated.go
  pkg/machinery/config/types/block/encryption.go
  pkg/machinery/config/types/block/testdata/uservolumeconfig_encrypted.yaml
  pkg/machinery/config/types/block/user_volume_config.go
  pkg/machinery/config/types/block/user_volume_config_test.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  website/content/v1.10/reference/cli.md
  website/content/v1.10/reference/configuration/block/uservolumeconfig.md
  website/content/v1.10/schemas/config.schema.json
  website/content/v1.10/talos-guides/configuration/disk-management.md
Labels: status/ok-to-test, status/ok-to-merge, integration/trusted-boot, integration/qemu-encrypted-vip

#10772 docs: correct flannel extra args example
  website/content/v1.10/talos-guides/install/virtualized-platforms/vmware.md
  website/content/v1.9/talos-guides/install/virtualized-platforms/vmware.md
Labels: status/ok-to-test, status/ok-to-merge

#10773 release(v1.10.0-beta.1): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  pkg/machinery/version/os-release
  website/content/v1.10/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#10770 fix: extension services logging to console
  internal/app/machined/pkg/system/runner/containerd/containerd.go
  internal/app/machined/pkg/system/runner/process/process.go
Labels: status/ok-to-test, status/ok-to-merge

#10774 feat: update Linux 6.12.24, containerd 2.0.5
  Makefile
  go.mod
  go.sum
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#10779 chore(ci): add provision test with bios
  internal/integration/provision/provision.go
  internal/integration/provision/upgrade.go
  pkg/machinery/client/client.go
Labels: status/ok-to-test, status/ok-to-merge, integration/provision-0, integration/provision

#10783 fix: fix Gvisor tests with containerd patch
  Makefile
  internal/integration/api/extensions_qemu.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge, integration/extensions

#10784 docs: add what is new for 1.10
  website/content/v1.10/_index.md
  website/content/v1.10/introduction/support-matrix.md
  website/content/v1.10/introduction/what-is-new/index.md
  website/content/v1.10/talos-guides/install/bare-metal-platforms/bootloader.md
  website/content/v1.10/talos-guides/install/boot-assets.md
  website/content/v1.10/talos-guides/upgrading-talos.md
Labels: status/ok-to-test, status/ok-to-merge

#10781 docs: hetzner: add note about public iso
  website/content/v1.10/talos-guides/install/cloud-platforms/hetzner.md
  website/content/v1.9/talos-guides/install/cloud-platforms/hetzner.md
Labels: status/ok-to-merge

#10788 fix: force DNS runner shutdown on timeout
  internal/pkg/dns/runnner.go
Labels: status/ok-to-test, status/ok-to-merge

#10789 feat: update Kubernetes to 1.33.0
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/v1.10/reference/cli.md
  website/content/v1.10/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#10792 fix: handle correctly changing platform network config
  internal/app/machined/pkg/controllers/network/platform_config.go
  internal/integration/api/platform.go
Labels: status/ok-to-test, status/ok-to-merge, integration/aws

#10793 chore: show bound driver in pcidevices info
  api/resource/definitions/hardware/hardware.proto
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/hardware/pcidevices.go
  pkg/machinery/api/resource/definitions/hardware/hardware.pb.go
  pkg/machinery/api/resource/definitions/hardware/hardware_vtproto.pb.go
  pkg/machinery/resources/hardware/pcidevice.go
  website/content/v1.10/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge

#10750 fix: sync PCR extension with volume provisioning lifecycle
  internal/app/machined/pkg/controllers/block/internal/volumes/close.go
  internal/app/machined/pkg/controllers/block/internal/volumes/encrypt.go
  internal/app/machined/pkg/controllers/block/internal/volumes/volumes.go
  internal/app/machined/pkg/controllers/block/volume_manager.go
  internal/app/machined/pkg/controllers/hardware/pcr_status.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/integration/api/hardware.go
  internal/pkg/encryption/encryption.go
  internal/pkg/encryption/helpers/helpers.go
  internal/pkg/encryption/keys/keys.go
  internal/pkg/encryption/keys/options.go
  internal/pkg/encryption/keys/tpm2.go
  pkg/machinery/resources/hardware/deep_copy.generated.go
  pkg/machinery/resources/hardware/hardware.go
  pkg/machinery/resources/hardware/hardware_test.go
  pkg/machinery/resources/hardware/pcr_status.go
Labels: status/ok-to-test, status/ok-to-merge, integration/trusted-boot

#10799 fix(ci): bios provision test
  hack/test/provision-tests.sh
  internal/integration/provision/provision.go
  internal/integration/provision/upgrade.go
Labels: status/ok-to-test, status/ok-to-merge, integration/provision-0

#10800 feat(kernel): add bcache kernel module to core talos
  Makefile
  hack/modules-amd64.txt
  hack/modules-arm64.txt
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-merge

#10803 feat: allow SideroLink unique token in machine config
  internal/app/machined/pkg/controllers/runtime/unique_token.go
  internal/app/machined/pkg/controllers/runtime/unique_token_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  pkg/machinery/config/config/siderolink.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/siderolink/siderolink.go
  pkg/machinery/config/types/siderolink/siderolink_doc.go
  website/content/v1.10/reference/configuration/siderolink/siderolinkconfig.md
  website/content/v1.10/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge, integration/misc-4

#10810 fix: handling of encryption type mismatch
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu, integration/qemu-encrypted-vip

#10816 fix: disk image generation with image cache
  Dockerfile
Labels: status/ok-to-test, status/ok-to-merge, integration/images, integration/image-cache

#10815 fix: preserve kubelet image suffix
  pkg/cluster/kubernetes/kubelet.go
  pkg/cluster/kubernetes/talos_managed.go
Labels: status/ok-to-merge

#10824 fix: relax etcd APIs RBAC requirements
  internal/app/machined/pkg/system/services/machined.go
  internal/integration/cli/config.go
Labels: status/ok-to-test, status/ok-to-merge

#10835 test: replace platform metadata test
  internal/integration/api/platform.go
Labels: status/ok-to-test, status/ok-to-merge, integration/misc, integration/misc-enforcing

#10820 chore: make qemu provider build on darwin
  cmd/talosctl/cmd/mgmt/dhcpd_launch.go
  cmd/talosctl/cmd/mgmt/qemu_launch.go
  go.mod
  go.sum
  pkg/provision/providers/qemu.go
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/qemu/launch_darwin.go
  pkg/provision/providers/qemu/launch_linux.go
  pkg/provision/providers/qemu_other.go
  pkg/provision/providers/vm/disk.go
  pkg/provision/providers/vm/network_darwin.go
  pkg/provision/providers/vm/network_linux.go
Labels: status/ok-to-test, status/ok-to-merge

#10840 release(v1.10.0): prepare release
  CHANGELOG.md
  go.mod
  hack/release.toml
  pkg/machinery/gendata/data/tag
  pkg/machinery/version/os-release
  website/content/v1.10/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#10839 docs: activate Talos 1.10 docs
  website/content/v1.10/_index.md
  website/content/v1.9/_index.md
  website/hugo.toml
Labels: status/ok-to-test, status/ok-to-merge
