Repository siderolabs/talos, pull requests merged in 2025-10, with the labels that each got.

#11932 release(v1.12.0-alpha.1): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  pkg/machinery/version/os-release
  website/content/v1.12/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#11949 fix: revert "chore: use new mount/v3 package in efivarfs"
  internal/pkg/efivarfs/efivarfs.go
Labels: status/ok-to-test, status/ok-to-merge

#11951 feat: generate list of images required to build talos
  cmd/talosctl/cmd/talos/image.go
  cmd/talosctl/pkg/talos/artifacts/arch.go
  cmd/talosctl/pkg/talos/artifacts/fetch.go
  cmd/talosctl/pkg/talos/artifacts/images.go
  cmd/talosctl/pkg/talos/helpers/flags.go
  internal/integration/cli/image.go
  pkg/images/images.go
  pkg/images/list.go
  website/content/v1.12/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#11950 fix: minor improvements to mounts
  internal/app/machined/pkg/controllers/block/mount.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
  internal/pkg/mount/v3/manager.go
  internal/pkg/mount/v3/point.go
Labels: status/ok-to-test, status/ok-to-merge

#11959 fix: provide nocloud metadata with missing network config
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud_test.go
Labels: status/ok-to-test, status/ok-to-merge

#11975 docs: updated the kubespan docs
  website/content/v1.10/talos-guides/network/kubespan.md
  website/content/v1.11/kubernetes-guides/upgrading-kubernetes.md
  website/content/v1.11/talos-guides/network/kubespan.md
  website/content/v1.12/kubernetes-guides/upgrading-kubernetes.md
  website/content/v1.12/talos-guides/network/kubespan.md
Labels: status/ok-to-test, status/ok-to-merge

#11908 Update prodnotes.md
  website/content/v1.11/introduction/prodnotes.md
  website/content/v1.12/introduction/prodnotes.md
Labels: status/ok-to-merge

#11957 feat: update Linux to 6.17
  Makefile
  hack/modules-amd64.txt
  hack/modules-arm64.txt
  hack/release.toml
  internal/app/machined/pkg/controllers/secrets/data/ca-certificates
  internal/integration/api/sbom.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
  pkg/machinery/gendata/data/tools
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/amd64/snp.efi
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/arm64/snp.efi
Labels: status/ok-to-test, status/ok-to-merge

#11976 feat: add disk.EnableUUID to generated ova
  pkg/imager/ova/ova.go
Labels: status/ok-to-merge

#11966 docs: Add Project Calico to networking options
  website/content/v1.11/kubernetes-guides/network/deploying-calico.md
  website/content/v1.12/kubernetes-guides/network/deploying-calico.md
Labels: status/ok-to-merge

#11981 chore(ci): run only nvidia tests for NVIDIA workflows
  .github/workflows/ci.yaml
  .github/workflows/integration-aws-nvidia-nonfree-lts-cron.yaml
  .github/workflows/integration-aws-nvidia-nonfree-production-cron.yaml
  .github/workflows/integration-aws-nvidia-oss-lts-cron.yaml
  .github/workflows/integration-aws-nvidia-oss-production-cron.yaml
  .github/workflows/stale.yml
  .kres.yaml
Labels: status/ok-to-test, status/ok-to-merge, integration/aws-nvidia
