Repository siderolabs/talos, pull requests merged in 2025-02, with the labels that each got.

#10278 fix: installer with SecureBoot should contain UKIs
  pkg/imager/out.go
Labels: status/ok-to-test, status/ok-to-merge

#10279 fix: build of Talos on non-Linux host
  Dockerfile
Labels: status/ok-to-test, status/ok-to-merge

#10276 fix: duplicate qemu drive ids
  pkg/provision/providers/qemu/launch.go
Labels: status/ok-to-merge

#10280 chore: remove containerd importer
  internal/app/machined/pkg/system/runner/containerd/import.go
  internal/pkg/containers/image/image.go
Labels: status/ok-to-test, status/ok-to-merge

#10284 chore: track opened grpc connections
  internal/app/machined/internal/server/v1alpha1/v1alpha1_time_test.go
  internal/pkg/cri/client.go
  internal/pkg/encryption/keys/kms.go
  pkg/grpc/gen/remote.go
  pkg/machinery/client/client_test.go
  pkg/machinery/client/grpc_connection_wrapper.go
Labels: status/ok-to-test, status/ok-to-merge

#10290 feat: provide initial support for ethtool configuration
  .golangci.yml
  api/resource/definitions/network/network.proto
  cmd/talosctl/cmd/talos/output/table.go
  go.mod
  go.sum
  go.work
  hack/cloud-image-uploader/go.mod
  hack/docgen/go.mod
  hack/gotagsrewrite/go.mod
  hack/module-sig-verify/go.mod
  hack/release.toml
  hack/structprotogen/go.mod
  internal/app/apid/pkg/director/local_address.go
  internal/app/apid/pkg/provider/provider.go
  internal/app/machined/pkg/controllers/network/ethernet_config.go
  internal/app/machined/pkg/controllers/network/ethernet_spec.go
  internal/app/machined/pkg/controllers/network/ethernet_status.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/url/map.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/url/url.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/app/trustd/internal/provider/provider.go
  internal/integration/api/ethernet.go
  internal/pkg/dashboard/resourcedata/resourcedata.go
  pkg/cluster/check/events.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/network/network_vtproto.pb.go
  pkg/machinery/config/config/config.go
  pkg/machinery/config/config/network.go
  pkg/machinery/config/container/container.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/network/deep_copy.generated.go
  pkg/machinery/config/types/network/ethernet.go
  pkg/machinery/config/types/network/ethernet_test.go
  pkg/machinery/config/types/network/network.go
  pkg/machinery/config/types/network/network_doc.go
  pkg/machinery/config/types/network/testdata/ethernetconfig.yaml
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/machinery/resources/network/address_spec.go
  pkg/machinery/resources/network/deep_copy.generated.go
  pkg/machinery/resources/network/ethernet_spec.go
  pkg/machinery/resources/network/ethernet_status.go
  pkg/machinery/resources/network/network_test.go
  website/content/v1.10/reference/api.md
  website/content/v1.10/reference/configuration/network/ethernetconfig.md
  website/content/v1.10/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge

#10298 fix: extracting cmdline multi profile UKIs
  internal/pkg/uki/internal/pe/extract.go
  internal/pkg/uki/internal/pe/extract_test.go
  internal/pkg/uki/internal/pe/pe_test.go
Labels: status/ok-to-test, status/ok-to-merge

#10305 chore: upgrade siderolabs/go-loadbalancer
  cmd/talosctl/cmd/mgmt/loadbalancer_launch.go
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge

#10307 feat: use bootstrapped packages for building Talos
  Dockerfile
  Makefile
  go.mod
  go.work
  hack/cleanup.sh
  hack/cloud-image-uploader/go.mod
  hack/docgen/go.mod
  hack/gotagsrewrite/go.mod
  hack/labeled-squashfs.sh
  hack/module-sig-verify/go.mod
  hack/release.toml
  hack/structprotogen/go.mod
  internal/app/init/main.go
  internal/app/machined/pkg/controllers/k8s/templates/kube-proxy-template.yaml
  internal/app/machined/pkg/system/runner/process/process_test.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/integration/base/api.go
  internal/pkg/extensions/compress.go
  internal/pkg/extensions/extensions_test.go
  internal/pkg/extensions/kernel_modules.go
  internal/pkg/extensions/testdata/good/extension1/rootfs/usr/lib/firmware/amd/cpu
  internal/pkg/extensions/testdata/good/extension1/rootfs/usr/lib/ld-linux-x86-64.so.2
  internal/pkg/mount/switchroot/switchroot.go
  internal/pkg/selinux/policy/file_contexts
  internal/pkg/selinux/policy/policy.33
  internal/pkg/selinux/policy/selinux/services/machined.cil
  internal/pkg/selinux/policy/selinux/services/system-containerd.cil
  internal/pkg/selinux/policy/selinux/services/udev.cil
  pkg/imager/extensions/contents.go
  pkg/imager/extensions/extensions.go
  pkg/machinery/constants/constants.go
  pkg/machinery/extensions/extensions.go
  pkg/machinery/extensions/extensions_test.go
  pkg/machinery/extensions/testdata/bad/usrmerge/manifest.yaml
  pkg/machinery/extensions/testdata/bad/usrmerge/rootfs/usr/lib64/a.so
  pkg/machinery/extensions/testdata/good/extension1/rootfs/usr/lib/firmware/amd/cpu
  pkg/machinery/extensions/testdata/good/extension1/rootfs/usr/lib/ld-linux-x86-64.so.2
  pkg/machinery/gendata/data/extras
  pkg/machinery/gendata/data/pkgs
  pkg/machinery/go.mod
  pkg/machinery/imager/quirks/quirks.go
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/amd64/snp.efi
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/arm64/snp.efi
  website/content/v1.10/advanced/proprietary-kernel-modules.md
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu

#10326 feat: implement features in `ethtool`-like support
  api/resource/definitions/network/network.proto
  go.mod
  go.sum
  hack/structprotogen/types/types.go
  internal/app/machined/pkg/controllers/network/ethernet_config.go
  internal/app/machined/pkg/controllers/network/ethernet_spec.go
  internal/app/machined/pkg/controllers/network/ethernet_status.go
  internal/integration/api/ethernet.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/network/network_vtproto.pb.go
  pkg/machinery/config/config/network.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/network/deep_copy.generated.go
  pkg/machinery/config/types/network/ethernet.go
  pkg/machinery/config/types/network/ethernet_test.go
  pkg/machinery/config/types/network/network_doc.go
  pkg/machinery/config/types/network/testdata/ethernetconfig.yaml
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/machinery/resources/network/deep_copy.generated.go
  pkg/machinery/resources/network/ethernet_spec.go
  pkg/machinery/resources/network/ethernet_status.go
  website/content/v1.10/reference/api.md
  website/content/v1.10/reference/configuration/network/ethernetconfig.md
  website/content/v1.10/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge

#10318 docs: fix a typo in Wireguard docs
  website/content/v1.10/talos-guides/network/wireguard-network.md
  website/content/v1.9/talos-guides/network/wireguard-network.md
Labels: status/ok-to-merge

#10062 refactor: implement volume mount controller
  api/resource/definitions/block/block.proto
  internal/app/machined/pkg/controllers/block/internal/volumes/locate.go
  internal/app/machined/pkg/controllers/block/mount.go
  internal/app/machined/pkg/controllers/block/mount_request.go
  internal/app/machined/pkg/controllers/block/mount_request_test.go
  internal/app/machined/pkg/controllers/block/mount_status.go
  internal/app/machined/pkg/controllers/cri/image_cache_config.go
  internal/app/machined/pkg/controllers/cri/image_cache_config_test.go
  internal/app/machined/pkg/controllers/ctest/ctest.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/pkg/mount/system.go
  internal/pkg/mount/v2/mount.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/block/block_vtproto.pb.go
  pkg/machinery/resources/block/block.go
  pkg/machinery/resources/block/block_test.go
  pkg/machinery/resources/block/deep_copy.generated.go
  pkg/machinery/resources/block/mount_request.go
  pkg/machinery/resources/block/mount_status.go
  pkg/machinery/resources/block/volume_config.go
  pkg/machinery/resources/block/volume_mount_request.go
  pkg/machinery/resources/block/volume_mount_status.go
  pkg/machinery/resources/block/volume_status.go
  website/content/v1.10/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge, integration/image-cache

#10330 feat: update Linux to 6.12.13
  Makefile
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge, integration/extensions, integration/aws-nvidia-oss, integration/qemu-csi-longhorn

#10316 feat: multi profile UKIs
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/install.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/sdboot.go
  internal/pkg/secureboot/tpm2/unseal.go
  internal/pkg/uki/generate.go
  internal/pkg/uki/internal/pe/extract.go
  internal/pkg/uki/internal/pe/extract_test.go
  internal/pkg/uki/internal/pe/pe_test.go
  internal/pkg/uki/internal/pe/testdata/addonx64.efi.stub
  internal/pkg/uki/internal/pe/testdata/linuxx64.efi.stub
  internal/pkg/uki/internal/pe/testdata/sd-stub-amd64.efi
  internal/pkg/uki/sbat.go
  internal/pkg/uki/sbat_test.go
  internal/pkg/uki/uki.go
  internal/pkg/uki/uki_test.go
  internal/pkg/zboot/zboot.go
  pkg/machinery/imager/quirks/quirks.go
Labels: status/ok-to-test, status/ok-to-merge, integration/trusted-boot, integration/misc-0

#10333 feat: implement the last ethtool feature - channels
  api/resource/definitions/network/network.proto
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/network/ethernet_config.go
  internal/app/machined/pkg/controllers/network/ethernet_config_test.go
  internal/app/machined/pkg/controllers/network/ethernet_spec.go
  internal/app/machined/pkg/controllers/network/ethernet_status.go
  internal/integration/api/ethernet.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/network/network_vtproto.pb.go
  pkg/machinery/config/config/network.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/network/deep_copy.generated.go
  pkg/machinery/config/types/network/ethernet.go
  pkg/machinery/config/types/network/ethernet_test.go
  pkg/machinery/config/types/network/network_doc.go
  pkg/machinery/config/types/network/testdata/ethernetconfig.yaml
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/machinery/resources/network/deep_copy.generated.go
  pkg/machinery/resources/network/ethernet_spec.go
  pkg/machinery/resources/network/ethernet_status.go
  website/content/v1.10/reference/api.md
  website/content/v1.10/reference/configuration/network/ethernetconfig.md
  website/content/v1.10/schemas/config.schema.json
  website/content/v1.10/talos-guides/network/ethernet-config.md
Labels: status/ok-to-test, status/ok-to-merge

#10336 fix: handling of empty registry config
  internal/app/machined/pkg/controllers/cri/registries_config.go
  internal/app/machined/pkg/controllers/cri/registries_config_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
Labels: status/ok-to-test, status/ok-to-merge

#10340 fix: ignore errors to stop pods
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/ok-to-test, status/ok-to-merge

#10337 feat: support uki profiles via imager
  internal/pkg/uki/generate.go
  internal/pkg/uki/uki.go
  internal/pkg/uki/uki_test.go
  pkg/imager/imager.go
Labels: status/ok-to-test, status/ok-to-merge

#10343 fix: fix diff printing
  pkg/machinery/config/configdiff/configdiff.go
  pkg/machinery/config/configdiff/configdiff_test.go
Labels: status/ok-to-merge

#10351 fix: path for ca-certificates
  Dockerfile
Labels: status/ok-to-test, status/ok-to-merge

#10353 fix: blockdevice transport detection
  cmd/talosctl/cmd/mgmt/cluster/create.go
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/provision/providers/qemu/launch.go
  pkg/provision/request.go
  website/content/v1.10/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#10354 fix: make ingress firewall filter traffic to nodeports
  hack/release.toml
  internal/app/machined/pkg/controllers/network/nftables_chain_config.go
  internal/app/machined/pkg/controllers/network/nftables_chain_config_test.go
Labels: status/ok-to-test, status/ok-to-merge, integration/cilium

#10358 feat: update Kubernetes to 1.32.2
  Makefile
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/v1.10/reference/cli.md
  website/content/v1.10/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#10359 Fix typo in Makefile target talosctl-freebsd-arm64
  Makefile
Labels: status/ok-to-merge

#10361 chore: fix spurious generate failures
  pkg/flannel/flannel.go
  pkg/machinery/version/osrelease.go
Labels: status/ok-to-test, status/ok-to-merge

#10355 Update getting-started.md
  website/content/v1.10/introduction/getting-started.md
  website/content/v1.9/introduction/getting-started.md
Labels: status/ok-to-merge

#10370 feat: support noclooud instance-id from dmi
  internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go
Labels: status/ok-to-merge

#10374 Ignore digest part of images when checking version in pre-flight
  cmd/installer/pkg/install/preflight.go
  cmd/installer/pkg/install/preflight_test.go
Labels: status/ok-to-merge

#10365 docs: add a note about syslog sending messages to services
  website/content/v1.10/talos-guides/configuration/logging.md
  website/content/v1.9/talos-guides/configuration/logging.md
Labels: status/ok-to-merge

#10382 fix(ci): fix intergration-misc crons
  .github/workflows/ci.yaml
  .github/workflows/integration-misc-0-cron.yaml
  .github/workflows/integration-misc-2-cron.yaml
  .kres.yaml
Labels: status/ok-to-test, status/ok-to-merge

#10381 chore: update Go to 1.24, update pkgs
  Dockerfile
  Makefile
  go.mod
  go.sum
  go.work
  hack/cloud-image-uploader/go.mod
  hack/docgen/go.mod
  hack/gotagsrewrite/go.mod
  hack/labeled-squashfs.sh
  hack/module-sig-verify/go.mod
  hack/release.toml
  hack/structprotogen/go.mod
  pkg/machinery/api/cluster/cluster.pb.go
  pkg/machinery/api/common/common.pb.go
  pkg/machinery/api/inspect/inspect.pb.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/resource/config/config.pb.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/cluster/cluster.pb.go
  pkg/machinery/api/resource/definitions/cri/cri.pb.go
  pkg/machinery/api/resource/definitions/enums/enums.pb.go
  pkg/machinery/api/resource/definitions/etcd/etcd.pb.go
  pkg/machinery/api/resource/definitions/extensions/extensions.pb.go
  pkg/machinery/api/resource/definitions/files/files.pb.go
  pkg/machinery/api/resource/definitions/hardware/hardware.pb.go
  pkg/machinery/api/resource/definitions/k8s/k8s.pb.go
  pkg/machinery/api/resource/definitions/kubeaccess/kubeaccess.pb.go
  pkg/machinery/api/resource/definitions/kubespan/kubespan.pb.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/perf/perf.pb.go
  pkg/machinery/api/resource/definitions/proto/proto.pb.go
  pkg/machinery/api/resource/definitions/runtime/runtime.pb.go
  pkg/machinery/api/resource/definitions/secrets/secrets.pb.go
  pkg/machinery/api/resource/definitions/siderolink/siderolink.pb.go
  pkg/machinery/api/resource/definitions/time/time.pb.go
  pkg/machinery/api/resource/definitions/v1alpha1/v1alpha1.pb.go
  pkg/machinery/api/resource/network/device_config.pb.go
  pkg/machinery/api/security/security.pb.go
  pkg/machinery/api/storage/storage.pb.go
  pkg/machinery/api/time/time.pb.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
  pkg/machinery/go.mod
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/amd64/snp.efi
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/arm64/snp.efi
Labels: status/ok-to-test, status/ok-to-merge, integration/reproducibility-test

#10395 chore: update enumer to a version that fixes Go 1.24 compatibility
  Dockerfile
  Makefile
Labels: status/ok-to-test, status/ok-to-merge

#10398 feat: add description to schema object defs
  hack/docgen/schema.go
  pkg/machinery/config/schemas/config.schema.json
  website/content/v1.10/schemas/config.schema.json
Labels: status/ok-to-merge

#10375 docs: remove typo on resetting a machine page
  website/content/v1.10/talos-guides/resetting-a-machine.md
  website/content/v1.9/talos-guides/resetting-a-machine.md
Labels: status/ok-to-test, status/ok-to-merge

#10418 fix: multiple fixes for dashboard/no data
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  internal/pkg/dashboard/apidata/node.go
  internal/pkg/dashboard/apidata/source.go
  internal/pkg/dashboard/components/header.go
Labels: status/ok-to-test, status/ok-to-merge

#10438 chore: stop doing generate on each build
  Dockerfile
Labels: status/ok-to-test, status/ok-to-merge

#10435 fix: correctly map link names/aliases when using VIP operator
  internal/app/machined/pkg/controllers/network/address_config.go
  internal/app/machined/pkg/controllers/network/cmdline.go
  internal/app/machined/pkg/controllers/network/cmdline_test.go
  internal/app/machined/pkg/controllers/network/dns_resolve_cache_test.go
  internal/app/machined/pkg/controllers/network/hostname_config.go
  internal/app/machined/pkg/controllers/network/link_config.go
  internal/app/machined/pkg/controllers/network/link_config_test.go
  internal/app/machined/pkg/controllers/network/operator_config.go
  internal/app/machined/pkg/controllers/network/operator_config_test.go
  internal/app/machined/pkg/controllers/network/operator_vip_config.go
  internal/app/machined/pkg/controllers/network/operator_vip_config_test.go
  internal/app/machined/pkg/controllers/network/resolver_config.go
  internal/app/machined/pkg/controllers/network/route_config.go
  internal/app/machined/pkg/controllers/network/timeserver_config.go
  pkg/machinery/resources/network/link_name_resolver.go
  pkg/machinery/resources/network/link_name_resolver_test.go
  pkg/machinery/resources/network/link_status.go
Labels: status/ok-to-test, status/ok-to-merge

#10436 fix: handle dynamic HTTP proxy settings for discovery client
  cmd/talosctl/cmd/mgmt/debug/air-gapped.go
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/cluster/discovery_service.go
  pkg/grpc/dialer/proxy.go
Labels: status/ok-to-test, status/ok-to-merge

#10437 fix: block NodePort services with ingress firewall
  internal/app/machined/pkg/controllers/network/nftables_chain_config.go
  internal/app/machined/pkg/controllers/network/nftables_chain_config_test.go
  internal/integration/api/firewall.go
  internal/integration/api/testdata/nodeport.yaml
Labels: status/ok-to-test, status/ok-to-merge, integration/cilium, integration/misc-0
