Repository siderolabs/talos, pull requests merged in 2025-09, with the labels that each got.

#11712 release(v1.11.0): prepare release
  CHANGELOG.md
  go.mod
  hack/release.toml
  pkg/machinery/gendata/data/tag
  pkg/machinery/version/os-release
  website/content/v1.11/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#11718 docs: activate Talos v1.11 docs by default
  website/content/v1.10/_index.md
  website/content/v1.11/_index.md
  website/hugo.toml
Labels: status/ok-to-test, status/ok-to-merge

#11711 docs: update qemu and docker docs
  website/content/v1.12/talos-guides/install/local-platforms/docker.md
  website/content/v1.12/talos-guides/install/local-platforms/qemu.md
Labels: status/ok-to-test, status/ok-to-merge

#11721 feat: add a cgroup preset for PSI and --skip-cri-resolve
  cmd/talosctl/cmd/talos/cgroups.go
  cmd/talosctl/cmd/talos/cgroupsprinter/presets/psi.yaml
  cmd/talosctl/cmd/talos/cgroupsprinter/presets_test.go
  website/content/v1.12/advanced/cgroups-analysis.md
  website/content/v1.12/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#11726 chore: update dependencies
  Makefile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/test/e2e.sh
  internal/integration/api/constants.go
  internal/integration/k8s/constants.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  tools/docgen/go.mod
  tools/docgen/go.sum
  tools/go.mod
  tools/go.sum
  tools/gotagsrewrite/go.mod
  tools/gotagsrewrite/go.sum
  tools/structprotogen/go.mod
  tools/structprotogen/go.sum
Labels: status/ok-to-test, status/ok-to-merge, integration/cilium

#11734 release(v1.12.0-alpha.0): prepare release
  .conform.yaml
  .kres.yaml
  CHANGELOG.md
  go.mod
  pkg/imager/profile/profile_test.go
  pkg/imager/profile/testdata/akamai-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/akamai-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/aws-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/aws-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/azure-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/azure-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/cloudstack-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/cloudstack-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/digital-ocean-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/digital-ocean-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/exoscale-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/exoscale-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/gcp-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/gcp-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/hcloud-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/hcloud-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/installer-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/installer-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/iso-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/iso-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/metal-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/metal-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/metal-uki-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/metal-uki-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/nocloud-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/nocloud-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/opennebula-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/opennebula-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/openstack-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/openstack-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/oracle-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/oracle-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/scaleway-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/scaleway-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/secureboot-installer-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/secureboot-installer-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/secureboot-iso-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/secureboot-iso-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/secureboot-metal-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/secureboot-metal-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/secureboot-metal-uki-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/secureboot-metal-uki-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/upcloud-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/upcloud-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/vmware-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/vmware-arm64-1.12.0.yaml
  pkg/imager/profile/testdata/vultr-amd64-1.12.0.yaml
  pkg/imager/profile/testdata/vultr-arm64-1.12.0.yaml
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/gendata/data/tag
  pkg/machinery/version/os-release
  website/content/v1.12/reference/cli.md
  website/content/v1.12/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge

#11736 feat: update Linux kernel (memcg_v1, ublk)
  Makefile
  hack/modules-amd64.txt
  hack/modules-arm64.txt
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#11745 docs: add docs on cilium's compatibility with kubespan
  website/content/v1.10/talos-guides/network/kubespan.md
  website/content/v1.11/talos-guides/network/kubespan.md
  website/content/v1.12/talos-guides/network/kubespan.md
Labels: status/ok-to-test, status/ok-to-merge

#11751 docs: clarify that install-cni image is deprecated
  website/content/v1.10/kubernetes-guides/network/multus.md
  website/content/v1.11/kubernetes-guides/network/multus.md
  website/content/v1.12/kubernetes-guides/network/multus.md
Labels: status/ok-to-test, status/ok-to-merge

#11750 refactor: update COSI to 1.11.0
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge

#11647 chore: refactor mount package
  internal/app/init/main.go
  internal/app/machined/main.go
  internal/app/machined/pkg/controllers/block/internal/volumes/format.go
  internal/app/machined/pkg/controllers/block/mount.go
  internal/app/machined/pkg/controllers/files/etcfile.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/probe.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/revert.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/mount/mount.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/sdboot.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/startup/tasks.go
  internal/app/machined/pkg/system/services/extension.go
  internal/pkg/mount/switchroot/switchroot.go
  internal/pkg/mount/v2/cgroups.go
  internal/pkg/mount/v2/mount.go
  internal/pkg/mount/v2/points.go
  internal/pkg/mount/v2/pseudo.go
  internal/pkg/mount/v2/repair.go
  internal/pkg/mount/v2/repair_test.go
  internal/pkg/mount/v2/squashfs.go
  internal/pkg/mount/v3/all.go
  internal/pkg/mount/v3/helpers.go
  internal/pkg/mount/v3/manager.go
  internal/pkg/mount/v3/managers.go
  internal/pkg/mount/v3/mount.go
  internal/pkg/mount/v3/point.go
  internal/pkg/mount/v3/unmount.go
  internal/pkg/xfs/fsopen/fsopen_linux.go
  internal/pkg/xfs/fsopen/options_linux.go
  internal/pkg/xfs/fsopen_test.go
  internal/pkg/xfs/opentree/opentree_linux.go
  internal/pkg/xfs/opentree_test.go
  internal/pkg/xfs/root.go
  internal/pkg/xfs/root_unix.go
  pkg/makefs/ext4.go
  pkg/makefs/vfat.go
Labels: status/ok-to-test, status/ok-to-merge

#11760 fix: don't bootstrap talos cluster if there's no config present
  cmd/talosctl/cmd/mgmt/cluster/create/create.go
Labels: status/ok-to-test, status/ok-to-merge

#11706 refactor create cluster commands internal logic
  cmd/talosctl/cmd/mgmt/cluster/create/cmd.go
  cmd/talosctl/cmd/mgmt/cluster/create/cmd_dev.go
  cmd/talosctl/cmd/mgmt/cluster/create/cmd_docker.go
  cmd/talosctl/cmd/mgmt/cluster/create/cmd_qemu.go
  cmd/talosctl/cmd/mgmt/cluster/create/create.go
  cmd/talosctl/cmd/mgmt/cluster/create/create_dev.go
  cmd/talosctl/cmd/mgmt/cluster/create/create_docker.go
  cmd/talosctl/cmd/mgmt/cluster/create/create_qemu.go
Labels: status/ok-to-test, status/ok-to-merge

#11771 feat: update runc to 1.3.1
  Makefile
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu

#11748 Update hetzner.md
  website/content/v1.11/talos-guides/install/cloud-platforms/hetzner.md
  website/content/v1.12/talos-guides/install/cloud-platforms/hetzner.md
Labels: status/ok-to-merge

#11656 feat: support configuring PCR states to bind disk encryption
  .github/workflows/ci.yaml
  .github/workflows/integration-trusted-boot-enforcing-cron.yaml
  .kres.yaml
  Dockerfile
  api/resource/definitions/block/block.proto
  cmd/talosctl/cmd/mgmt/cluster/create/create_dev.go
  hack/release.toml
  internal/app/machined/pkg/controllers/block/internal/volumes/encrypt.go
  internal/app/machined/pkg/controllers/block/volume_config.go
  internal/integration/api/discovery.go
  internal/integration/api/trustedboot.go
  internal/pkg/encryption/encryption.go
  internal/pkg/encryption/keys/keys.go
  internal/pkg/encryption/keys/tpm2.go
  internal/pkg/secureboot/tpm2/pcr.go
  internal/pkg/secureboot/tpm2/policy.go
  internal/pkg/secureboot/tpm2/policy_test.go
  internal/pkg/secureboot/tpm2/seal.go
  internal/pkg/secureboot/tpm2/tpm2.go
  internal/pkg/secureboot/tpm2/unseal.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/block/block_vtproto.pb.go
  pkg/machinery/config/config/machine.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/block/block_doc.go
  pkg/machinery/config/types/block/deep_copy.generated.go
  pkg/machinery/config/types/block/encryption.go
  pkg/machinery/config/types/block/testdata/volumeconfig_tpm_encryption_no_options.yaml
  pkg/machinery/config/types/block/testdata/volumeconfig_tpm_encryption_with_pcr_settings.yaml
  pkg/machinery/config/types/block/testdata/volumeconfig_tpm_encryption_with_pcrs_disabled.yaml
  pkg/machinery/config/types/block/volume_config_test.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/constants/constants.go
  pkg/machinery/resources/block/deep_copy.generated.go
  pkg/machinery/resources/block/volume_config.go
  pkg/machinery/resources/block/volume_status.go
  pkg/provision/providers/qemu/launch.go
  website/content/v1.11/talos-guides/configuration/disk-management/system.md
  website/content/v1.12/reference/api.md
  website/content/v1.12/reference/configuration/block/rawvolumeconfig.md
  website/content/v1.12/reference/configuration/block/swapvolumeconfig.md
  website/content/v1.12/reference/configuration/block/uservolumeconfig.md
  website/content/v1.12/reference/configuration/block/volumeconfig.md
  website/content/v1.12/schemas/config.schema.json
  website/content/v1.12/talos-guides/configuration/disk-management/system.md
Labels: status/ok-to-test, status/ok-to-merge

#11777 docs: Replace Raspberry Pi 5 links with Talos builder
  website/content/v1.10/talos-guides/install/single-board-computers/unofficial.md
  website/content/v1.11/talos-guides/install/single-board-computers/unofficial.md
  website/content/v1.12/talos-guides/install/single-board-computers/unofficial.md
Labels: status/ok-to-merge

#11786 docs: document talos vip failover behaviour
  website/content/v1.10/talos-guides/network/vip.md
  website/content/v1.11/talos-guides/network/vip.md
  website/content/v1.12/talos-guides/network/vip.md
Labels: status/ok-to-test, status/ok-to-merge

#11794 test: improve test stability
  internal/integration/api/apply-config.go
  internal/integration/api/volumes.go
Labels: status/ok-to-test, status/ok-to-merge

#11833 fix: use correct order to determine SideroV1 keys directory path
  pkg/machinery/client/config/path.go
Labels: status/ok-to-test, status/ok-to-merge

#11834 docs: remove 'ceph-data' from volume examples/docs
  pkg/machinery/config/types/block/raw_volume_config.go
  pkg/machinery/config/types/block/user_volume_config.go
  website/content/v1.11/talos-guides/configuration/disk-management/layout.md
  website/content/v1.11/talos-guides/configuration/disk-management/raw.md
  website/content/v1.11/talos-guides/configuration/disk-management/user.md
  website/content/v1.12/reference/configuration/block/rawvolumeconfig.md
  website/content/v1.12/reference/configuration/block/uservolumeconfig.md
  website/content/v1.12/talos-guides/configuration/disk-management/layout.md
  website/content/v1.12/talos-guides/configuration/disk-management/raw.md
  website/content/v1.12/talos-guides/configuration/disk-management/user.md
Labels: status/ok-to-test, status/ok-to-merge

#11759 feat: create detached tmpfs
  Dockerfile
  internal/app/machined/pkg/controllers/files/cri_config_parts.go
  internal/app/machined/pkg/controllers/files/cri_registry_config.go
  internal/app/machined/pkg/controllers/files/etcfile.go
  internal/app/machined/pkg/controllers/files/etcfile_test.go
  internal/app/machined/pkg/controllers/files/iqn.go
  internal/app/machined/pkg/controllers/files/nqn.go
  internal/app/machined/pkg/controllers/network/etcfile.go
  internal/app/machined/pkg/controllers/network/etcfile_test.go
  internal/app/machined/pkg/controllers/network/watch/rtnetlink.go
  internal/app/machined/pkg/runtime/kernel.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/integration/api/selinux.go
  internal/integration/k8s/tink.go
  internal/pkg/containers/cri/containerd/containerd.go
  internal/pkg/mount/v3/mount.go
  internal/pkg/selinux/selinux.go
  internal/pkg/xfs/fsopen_test.go
  internal/pkg/xfs/opentree_test.go
  internal/pkg/xfs/osroot.go
  internal/pkg/xfs/osroot_test.go
  internal/pkg/xfs/root.go
  internal/pkg/xfs/root_test.go
  internal/pkg/xfs/root_unix.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#11839 test: fix several issues with tests
  internal/integration/api/apply-config.go
  internal/integration/api/update-hostname.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu, integration/aws, integration/gcp

#11842 chore: pass in github token to imager
  Makefile
Labels: status/ok-to-test, status/ok-to-merge

#11845 chore: drop docs folder
  docs/.DS_Store
  docs/community/project-layout.md
  docs/proposals/20190704-AutomatedUpgrades.md
  docs/proposals/20190708-MachineConfig.md
  docs/proposals/YYYYMMDD-TEMPLATE.md
Labels: status/ok-to-test, status/ok-to-merge

#11849 feat: record last log the failed service
  internal/app/machined/pkg/system/runner/containerd/containerd.go
  internal/app/machined/pkg/system/runner/internal/lastlog/lastlog.go
  internal/app/machined/pkg/system/runner/internal/lastlog/lastlog_test.go
  internal/app/machined/pkg/system/runner/internal/lastlog/testdata/kubelet.log
  internal/app/machined/pkg/system/runner/process/process.go
Labels: status/ok-to-test, status/ok-to-merge

#11850 feat: ship nft binary with Talos rootfs
  Dockerfile
  Makefile
  hack/release.toml
  internal/app/machined/pkg/controllers/network/nftables_chain_test.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu, integration/aws-nvidia-oss-lts

#11880 refactor: efivars mock and tests
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/efivars.go
  internal/pkg/efivarfs/boot.go
  internal/pkg/efivarfs/devicepath.go
  internal/pkg/efivarfs/efivarfs.go
  internal/pkg/efivarfs/efivarfs_test.go
  internal/pkg/efivarfs/mock.go
  internal/pkg/efivarfs/osindications.go
  internal/pkg/efivarfs/variables.go
Labels: status/ok-to-test, status/ok-to-merge

#11889 release(v1.11.2): prepare release
  CHANGELOG.md
  go.mod
  hack/release.toml
  pkg/machinery/gendata/data/tag
  pkg/machinery/version/os-release
  website/content/v1.11/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#11898 docs: update secureboot docs
  website/content/v1.12/talos-guides/install/bare-metal-platforms/secureboot.md
Labels: status/ok-to-test, status/ok-to-merge

#11897 fix: provide refreshing CA pool (resolvers)
  internal/pkg/containers/image/resolver.go
Labels: status/ok-to-test, status/ok-to-merge

#11907 docs: deprecate JSON6902 patches and interactive installer
  internal/app/machined/pkg/controllers/runtime/maintenance_service.go
  website/content/v1.12/talos-guides/configuration/editing-machine-configuration.md
  website/content/v1.12/talos-guides/configuration/patching.md
  website/content/v1.12/talos-guides/install/virtualized-platforms/vmware.md
Labels: status/ok-to-test, status/ok-to-merge

#11875 feat: release cloud image using factory
  .github/workflows/ci.yaml
  .github/workflows/dispatch.yaml
  .kres.yaml
  hack/cloud-image-uploader/factory.go
  hack/cloud-image-uploader/main.go
  hack/cloud-image-uploader/options.go
Labels: status/ok-to-test, status/ok-to-merge

#11912 chore: use new mount/v3 package in efivarfs
  internal/pkg/efivarfs/efivarfs.go
Labels: status/ok-to-test, status/ok-to-merge

#11917 fix: stop returning EINVAL on remount of detached mounts
  internal/pkg/mount/v3/point.go
Labels: status/ok-to-test, status/ok-to-merge
