Repository siderolabs/talos, pull requests merged in 2025-03, with the labels that each got.

#10445 chore: fix shutdown typo in shutdown sequence
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
Labels: status/ok-to-merge

#10451 Update deprecated command in README.md
  website/content/v1.10/talos-guides/install/virtualized-platforms/vagrant-libvirt.md
  website/content/v1.9/talos-guides/install/virtualized-platforms/vagrant-libvirt.md
Labels: status/ok-to-merge

#10455 feat: update Kubernetes to 1.33.0-alpha.2
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  internal/integration/provision/upgrade.go
  pkg/machinery/constants/constants.go
  website/content/v1.10/reference/cli.md
  website/content/v1.10/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge, integration/provision, integration/misc

#10456 feat: add support for qla2xx
  Makefile
  hack/modules-amd64.txt
  hack/modules-arm64.txt
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#10443 feat: prefer sd-boot for UEFI
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/bootloader.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/sdboot.go
Labels: status/ok-to-test, status/ok-to-merge

#10465 test: enable image-cache in the cron
  .github/workflows/integration-image-cache-cron.yaml
  .github/workflows/slack-notify.yaml
  .kres.yaml
Labels: status/ok-to-test, status/ok-to-merge

#10466 test: fix UKI preserving talos.config and image cache
  Makefile
  internal/integration/cli/image.go
  internal/integration/cli/list.go
  pkg/provision/providers/qemu/launch.go
Labels: status/ok-to-test, status/ok-to-merge, integration/image-cache

#10463 fix(ci): fix integration tests
  .github/workflows/ci.yaml
  .github/workflows/integration-qemu-csi-longhorn-cron.yaml
  .github/workflows/integration-qemu-race-cron.yaml
  .kres.yaml
  Makefile
  hack/release.toml
  internal/integration/k8s/longhorn.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu-csi-longhorn

#10471 release(v1.10.0-alpha.2): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  pkg/machinery/version/os-release
  website/content/v1.10/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#10475 chore: add installer-base to the list of signed images
  Makefile
Labels: status/ok-to-test, status/ok-to-merge

#10472 Update nvidia-gpu-proprietary.md
  website/content/v1.9/talos-guides/configuration/nvidia-gpu-proprietary.md
Labels: status/ok-to-merge

#10478 chore: update Go to 1.24.1
  Makefile
  go.mod
  go.sum
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/docgen/go.mod
  hack/docgen/go.sum
  hack/release.toml
  pkg/machinery/api/cluster/cluster.pb.go
  pkg/machinery/api/cluster/cluster_grpc.pb.go
  pkg/machinery/api/common/common.pb.go
  pkg/machinery/api/inspect/inspect.pb.go
  pkg/machinery/api/inspect/inspect_grpc.pb.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/machine/machine_grpc.pb.go
  pkg/machinery/api/resource/config/config.pb.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/cluster/cluster.pb.go
  pkg/machinery/api/resource/definitions/cri/cri.pb.go
  pkg/machinery/api/resource/definitions/enums/enums.pb.go
  pkg/machinery/api/resource/definitions/etcd/etcd.pb.go
  pkg/machinery/api/resource/definitions/extensions/extensions.pb.go
  pkg/machinery/api/resource/definitions/files/files.pb.go
  pkg/machinery/api/resource/definitions/hardware/hardware.pb.go
  pkg/machinery/api/resource/definitions/k8s/k8s.pb.go
  pkg/machinery/api/resource/definitions/kubeaccess/kubeaccess.pb.go
  pkg/machinery/api/resource/definitions/kubespan/kubespan.pb.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/perf/perf.pb.go
  pkg/machinery/api/resource/definitions/proto/proto.pb.go
  pkg/machinery/api/resource/definitions/runtime/runtime.pb.go
  pkg/machinery/api/resource/definitions/secrets/secrets.pb.go
  pkg/machinery/api/resource/definitions/siderolink/siderolink.pb.go
  pkg/machinery/api/resource/definitions/time/time.pb.go
  pkg/machinery/api/resource/definitions/v1alpha1/v1alpha1.pb.go
  pkg/machinery/api/resource/network/device_config.pb.go
  pkg/machinery/api/security/security.pb.go
  pkg/machinery/api/security/security_grpc.pb.go
  pkg/machinery/api/storage/storage.pb.go
  pkg/machinery/api/storage/storage_grpc.pb.go
  pkg/machinery/api/time/time.pb.go
  pkg/machinery/api/time/time_grpc.pb.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/extras
  pkg/machinery/gendata/data/pkgs
  pkg/machinery/gendata/data/tools
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/amd64/snp.efi
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/arm64/snp.efi
Labels: status/ok-to-test, status/ok-to-merge

#10482 test: fix dns test in race mode
  internal/pkg/dns/dns_test.go
Labels: status/ok-to-test, status/ok-to-merge

#10481 feat: update etcd to 3.5.19
  hack/release.toml
  pkg/machinery/constants/constants.go
  website/content/v1.10/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#10480 Update proxmox.md
  website/content/v1.10/talos-guides/install/virtualized-platforms/proxmox.md
  website/content/v1.9/talos-guides/install/virtualized-platforms/proxmox.md
Labels: status/ok-to-merge

#10484 feat: update Flannel to 0.26.5
  pkg/flannel/template.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#10490 fix(ci): image-cache cron
  .github/workflows/ci.yaml
  .github/workflows/integration-image-cache-cron.yaml
  .kres.yaml
Labels: status/ok-to-test, status/ok-to-merge

#10489 feat: update Kubernetes to v1.33.0-alpha.3
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
  internal/app/machined/pkg/controllers/k8s/endpoint.go
  internal/app/machined/pkg/controllers/k8s/kubelet_spec.go
  internal/app/machined/pkg/controllers/kubeaccess/endpoint.go
  pkg/machinery/constants/constants.go
  website/content/v1.10/reference/cli.md
  website/content/v1.10/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#10492 test: use standard installer for e2e-iso
  hack/test/e2e-iso.sh
Labels: status/ok-to-test, status/ok-to-merge

#10494 fix: change from "init6" to "inet6" in docs
  website/content/v1.10/advanced/metal-network-configuration.md
  website/content/v1.4/advanced/metal-network-configuration.md
  website/content/v1.5/advanced/metal-network-configuration.md
  website/content/v1.6/advanced/metal-network-configuration.md
  website/content/v1.7/advanced/metal-network-configuration.md
  website/content/v1.8/advanced/metal-network-configuration.md
  website/content/v1.9/advanced/metal-network-configuration.md
Labels: status/ok-to-test, status/ok-to-merge

#10485 fix: ensure no goroutines escape in dns controller
  go.mod
  go.sum
  hack/structprotogen/go.sum
  internal/app/machined/pkg/controllers/network/dns_resolve_cache_test.go
  internal/app/machined/pkg/controllers/network/dns_upstream.go
  internal/app/machined/pkg/xcontext/xcontext.go
  internal/pkg/dns/dns_test.go
  internal/pkg/dns/manager.go
  internal/pkg/dns/runnner.go
  pkg/machinery/go.mod
  pkg/machinery/resources/network/dns_upstream.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu

#10502 fix: qemu: archive cluster logs only after stopping VMs
  .github/workflows/ci.yaml
  .github/workflows/integration-misc-2-cron.yaml
  .github/workflows/integration-qemu-cron.yaml
  .golangci.yml
  .kres.yaml
  hack/test/e2e-qemu.sh
  pkg/provision/providers/qemu/destroy.go
Labels: status/ok-to-test, status/ok-to-merge, integration/misc-2

#10503 fix: typo in machinery CloudPlatforms
  pkg/machinery/platforms/platforms.go
Labels: status/ok-to-merge

#10506 feat: update Linux to 6.12.18
  Makefile
  hack/modules-amd64.txt
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#10496 docs: add instructions for differing network interface name
  website/content/v1.10/talos-guides/install/virtualized-platforms/vagrant-libvirt.md
  website/content/v1.9/talos-guides/install/virtualized-platforms/vagrant-libvirt.md
Labels: status/ok-to-merge

#10379 refactor: ephemeral mount
  api/resource/definitions/block/block.proto
  go.mod
  go.sum
  internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
  internal/app/machined/pkg/controllers/block/internal/volumes/encrypt.go
  internal/app/machined/pkg/controllers/block/internal/volumes/volumes.go
  internal/app/machined/pkg/controllers/block/mount.go
  internal/app/machined/pkg/controllers/block/volume_config.go
  internal/app/machined/pkg/controllers/block/volume_manager.go
  internal/app/machined/pkg/controllers/runtime/mount_status.go
  internal/app/machined/pkg/runtime/sequencer.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/system/integration_test.go
  internal/app/machined/pkg/system/mocks_test.go
  internal/app/machined/pkg/system/service.go
  internal/app/machined/pkg/system/service_runner.go
  internal/app/machined/pkg/system/services/apid.go
  internal/app/machined/pkg/system/services/auditd.go
  internal/app/machined/pkg/system/services/containerd.go
  internal/app/machined/pkg/system/services/cri.go
  internal/app/machined/pkg/system/services/dashboard.go
  internal/app/machined/pkg/system/services/etcd.go
  internal/app/machined/pkg/system/services/extension.go
  internal/app/machined/pkg/system/services/kubelet.go
  internal/app/machined/pkg/system/services/machined.go
  internal/app/machined/pkg/system/services/registryd.go
  internal/app/machined/pkg/system/services/syslogd.go
  internal/app/machined/pkg/system/services/trustd.go
  internal/app/machined/pkg/system/services/udevd.go
  internal/app/machined/pkg/system/volumes.go
  internal/pkg/meta/meta.go
  pkg/conditions/all.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/block/block_vtproto.pb.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/machinery/resources/block/block.go
  pkg/machinery/resources/block/deep_copy.generated.go
  pkg/machinery/resources/block/mount_request.go
  pkg/machinery/resources/block/mount_status.go
  pkg/machinery/resources/block/volume_config.go
  pkg/machinery/resources/block/volume_mount_request.go
  pkg/machinery/resources/block/volume_mount_status.go
  pkg/machinery/resources/block/volume_status.go
  website/content/v1.10/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge

#10512 feat: update Kubernetes to 1.33.0-beta.0
  Makefile
  go.mod
  go.sum
  hack/release.toml
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/v1.10/reference/cli.md
  website/content/v1.10/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge, integration/provision

#10507 fix(ci): image-cache cron
  .github/workflows/ci.yaml
  .github/workflows/integration-aws-cron.yaml
  .github/workflows/integration-aws-nvidia-nonfree-cron.yaml
  .github/workflows/integration-aws-nvidia-oss-cron.yaml
  .github/workflows/integration-azure-cron.yaml
  .github/workflows/integration-gcp-cron.yaml
  .github/workflows/integration-image-cache-cron.yaml
  .kres.yaml
Labels: status/ok-to-test, status/ok-to-merge

#10515 release(v1.9.5): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#10514 test(ci): use k8s websocket executor for tests
  internal/integration/api/extensions_qemu.go
  internal/integration/base/k8s.go
Labels: status/ok-to-test, status/ok-to-merge

#10517 fix: reconnect on SideroLink tunnel on/off change
  api/resource/definitions/siderolink/siderolink.proto
  cmd/talosctl/cmd/mgmt/cluster/create.go
  internal/app/machined/pkg/controllers/siderolink/manager.go
  internal/app/machined/pkg/controllers/siderolink/siderolink.go
  internal/app/machined/pkg/controllers/siderolink/status.go
  internal/integration/api/siderolink.go
  pkg/machinery/api/resource/definitions/siderolink/siderolink.pb.go
  pkg/machinery/api/resource/definitions/siderolink/siderolink_vtproto.pb.go
  pkg/machinery/constants/constants.go
  pkg/machinery/resources/siderolink/siderolink_status.go
  pkg/machinery/resources/siderolink/siderolink_tunnel.go
  website/content/v1.10/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge, integration/misc-4

#10519 chore: extraKernelArgs validation for UKI's
  .github/workflows/ci.yaml
  .github/workflows/integration-image-cache-cron.yaml
  .kres.yaml
  hack/release.toml
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  website/content/v1.10/reference/configuration/v1alpha1/config.md
  website/content/v1.10/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge

#10527 fix: kexec when using sd-boot
  .github/workflows/ci.yaml
  .github/workflows/integration-misc-2-cron.yaml
  .kres.yaml
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/sdboot.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Labels: status/ok-to-test, status/ok-to-merge

#10526 feat: talosctl kubeconfig write to stdout option
  cmd/talosctl/cmd/talos/kubeconfig.go
  website/content/v1.10/reference/cli.md
Labels: status/ok-to-merge

#10528 docs: add documentation on unofficial SBC forks
  website/content/v1.10/talos-guides/install/single-board-computers/unofficial.md
  website/content/v1.9/talos-guides/install/single-board-computers/unofficial.md
Labels: status/ok-to-test, status/ok-to-merge

#10523 feat: deprecate `.machine.install.extensions`
  Dockerfile
  cmd/installer/pkg/install/extensions.go
  cmd/installer/pkg/install/install.go
  hack/release.toml
  internal/pkg/extensions/pull.go
  internal/pkg/install/install.go
  pkg/machinery/config/config/machine.go
  pkg/machinery/config/schemas/config.schema.json
  pkg/machinery/config/types/v1alpha1/v1alpha1_examples.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
  pkg/machinery/constants/constants.go
  website/content/v1.10/reference/configuration/v1alpha1/config.md
  website/content/v1.10/schemas/config.schema.json
Labels: status/ok-to-test, status/ok-to-merge

#10531 chore: bump go-kubernetes
  go.mod
  go.sum
Labels: status/ok-to-test, status/ok-to-merge, integration/aws

#10545 feat: pull in Intel STTMAC network drivers
  Makefile
  hack/modules-amd64.txt
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#10532 docs: fix typo cluser -> cluster
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  website/content/v1.10/reference/configuration/v1alpha1/config.md
  website/content/v1.9/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-merge

#10546 fix(ci): fix image cache test
  internal/integration/cli/list.go
Labels: status/ok-to-test, status/ok-to-merge, integration/image-cache

#10552 chore: fix conformance artifact name
  .github/workflows/ci.yaml
  .github/workflows/integration-conformance-cron.yaml
  .kres.yaml
Labels: status/ok-to-test, status/ok-to-merge

#10550 fix: correct structprotogen example
  hack/structprotogen/main.go
Labels: status/ok-to-merge

#10560 feat: update Linux 6.12.19, containerd 2.0.4
  Makefile
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge, integration/conformance

#10576 fix: kata extension
  Makefile
  internal/integration/api/extensions_qemu.go
Labels: status/ok-to-test, status/ok-to-merge, integration/extensions

#10588 docs: add information about Cilium exclusive CNI
  website/content/v1.10/kubernetes-guides/network/multus.md
  website/content/v1.9/kubernetes-guides/network/multus.md
Labels: status/ok-to-test, status/ok-to-merge

#10562 docs: clarify custom CA certificate compatibility with KMS STATE partition encryption
  website/content/v1.10/reference/kernel.md
  website/content/v1.10/talos-guides/configuration/certificate-authorities.md
  website/content/v1.10/talos-guides/configuration/disk-encryption.md
  website/content/v1.9/reference/kernel.md
  website/content/v1.9/talos-guides/configuration/certificate-authorities.md
  website/content/v1.9/talos-guides/configuration/disk-encryption.md
Labels: status/ok-to-merge

#10589 release(v1.10.0-alpha.3): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  pkg/machinery/version/os-release
  website/content/v1.10/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#10590 test: drop Azure CI pipelines
  .github/workflows/ci.yaml
  .github/workflows/integration-azure-cron.yaml
  .github/workflows/slack-notify.yaml
  .kres.yaml
  Makefile
  hack/cloud-image-uploader/README.md
  hack/cloud-image-uploader/azure.go
  hack/cloud-image-uploader/go.mod
  hack/cloud-image-uploader/go.sum
  hack/cloud-image-uploader/main.go
  hack/cloud-image-uploader/options.go
  hack/test/e2e-azure-prepare.sh
  website/content/v1.10/introduction/support-matrix.md
  website/content/v1.10/talos-guides/install/cloud-platforms/azure.md
Labels: status/ok-to-test, status/ok-to-merge

#10600 chore: drop runc memfd bind
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/cri/runc_memfd_bind.go
Labels: status/ok-to-test, status/ok-to-merge

#10599 Update hetzner.md
  website/content/v1.10/talos-guides/install/cloud-platforms/hetzner.md
  website/content/v1.9/talos-guides/install/cloud-platforms/hetzner.md
Labels: status/ok-to-merge

#10594 chore: fix typo in aws docs
  website/content/v1.10/talos-guides/install/cloud-platforms/aws.md
  website/content/v1.9/talos-guides/install/cloud-platforms/aws.md
Labels: status/ok-to-merge

#10604 doc: Fix version typo in kube-proxy manual upgrade
  website/content/v1.1/kubernetes-guides/upgrading-kubernetes.md
  website/content/v1.10/kubernetes-guides/upgrading-kubernetes.md
  website/content/v1.2/kubernetes-guides/upgrading-kubernetes.md
  website/content/v1.3/kubernetes-guides/upgrading-kubernetes.md
  website/content/v1.4/kubernetes-guides/upgrading-kubernetes.md
  website/content/v1.5/kubernetes-guides/upgrading-kubernetes.md
  website/content/v1.6/kubernetes-guides/upgrading-kubernetes.md
  website/content/v1.7/kubernetes-guides/upgrading-kubernetes.md
  website/content/v1.8/kubernetes-guides/upgrading-kubernetes.md
  website/content/v1.9/kubernetes-guides/upgrading-kubernetes.md
Labels: status/ok-to-merge

#10607 feat: update etcd to 3.5.21
  go.mod
  go.sum
  pkg/machinery/constants/constants.go
  website/content/v1.10/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#10592 test: test NVIDIA drivers 570.x
  Makefile
  internal/app/machined/pkg/controllers/k8s/kubelet_spec.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge, integration/aws-nvidia-oss

#10613 docs: Add docs for configuring Containerd CDI spec dirs
  website/content/v1.10/talos-guides/configuration/containerd.md
  website/content/v1.9/talos-guides/configuration/containerd.md
Labels: status/ok-to-merge

#10581 fix: upgrades with kexec
  cmd/installer/pkg/install/errata.go
  cmd/installer/pkg/install/install.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/sdboot.go
Labels: status/ok-to-test, status/ok-to-merge

#10614 docs: update development docs.
  website/content/v1.10/advanced/building-images.md
  website/content/v1.10/advanced/developing-talos.md
Labels: status/ok-to-test, status/ok-to-merge
