Repository siderolabs/talos, pull requests merged in 2025-01, with the labels that each got.

#10079 chore(ci): better zfs checks
  internal/app/syslogd/internal/parser/parse_test.go
  internal/integration/api/extensions_qemu.go
Labels: status/ok-to-test, status/ok-to-merge, integration/extensions

#10061 feat: bring in partity with sd-257
  internal/pkg/secureboot/measure/measure_test.go
  internal/pkg/secureboot/secureboot.go
Labels: status/ok-to-test, status/ok-to-merge

#10085 feat: enable `configfs`
  internal/pkg/mount/v2/pseudo.go
Labels: status/ok-to-test, status/ok-to-merge

#10084 fix: mount selinuxfs only when SELinux is enabled
  internal/pkg/mount/v2/pseudo.go
Labels: status/ok-to-test, status/ok-to-merge

#10089 chore: drop deprecated allowSchedulingOnMasters
  hack/release.toml
  pkg/machinery/config/generate/init.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
Labels: status/ok-to-test, status/ok-to-merge

#10066 ceph-with-rook.md: Fixed command to wait for ceph-rook HEALTH_OK
  website/content/v1.10/kubernetes-guides/configuration/ceph-with-rook.md
  website/content/v1.9/kubernetes-guides/configuration/ceph-with-rook.md
Labels: status/ok-to-merge

#10100 chore: revert: drop deprecated allowSchedulingOnMasters
  hack/release.toml
  pkg/machinery/config/generate/init.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
  pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
Labels: status/ok-to-test, status/ok-to-merge

#10091 docs: Update Cilium Installation Guide to include Gateway API
  website/content/v1.10/kubernetes-guides/network/deploying-cilium.md
  website/content/v1.9/kubernetes-guides/network/deploying-cilium.md
Labels: status/ok-to-merge

#10106 fix: disable NRI plugin in a different way
  hack/cri-containerd.toml
  hack/cri-plugin.part
  website/content/v1.10/talos-guides/configuration/containerd.md
Labels: status/ok-to-test, status/ok-to-merge

#10107 fix: yet another dashboard panic
  internal/pkg/dashboard/apidata/node.go
Labels: status/ok-to-test, status/ok-to-merge

#10109 fix: partition alignment on disks with 4k sectors
  cmd/talosctl/cmd/mgmt/cluster/create.go
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/qemu/node.go
  pkg/provision/request.go
  website/content/v1.10/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#10112 feat: support generating unsigned UKIs
  cmd/talosctl/cmd/mgmt/cluster/create.go
  internal/pkg/secureboot/uki/generate.go
  internal/pkg/secureboot/uki/uki.go
  pkg/imager/imager.go
  pkg/imager/profile/default.go
  pkg/imager/profile/input.go
  pkg/imager/profile/profile.go
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/qemu/node.go
  pkg/provision/request.go
  website/content/v1.10/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#10114 feat: update Linux to 6.12.8
  Makefile
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#10115 fix: merge of VolumeConfig documents with sizes
  pkg/machinery/config/types/block/byte_size.go
  pkg/machinery/config/types/block/volume_config_test.go
Labels: status/ok-to-test, status/ok-to-merge

#10116 fix: extfs repair and resize
  hack/test/patches/image-cache.yaml
  internal/pkg/mount/v2/repair.go
  pkg/makefs/ext4.go
  pkg/makefs/xfs.go
Labels: status/ok-to-test, status/ok-to-merge, integration/image-cache

#10102 refactor: drop usage of objcopy to generate UKIs
  Makefile
  internal/pkg/secureboot/uki/assemble.go
  internal/pkg/secureboot/uki/internal/pe/native.go
  internal/pkg/secureboot/uki/internal/pe/objcopy.go
  internal/pkg/secureboot/uki/internal/pe/pe.go
  internal/pkg/secureboot/uki/internal/pe/pe_test.go
  internal/pkg/secureboot/uki/internal/pe/testdata/sd-stub-amd64.efi
  internal/pkg/secureboot/uki/uki.go
Labels: status/ok-to-test, status/ok-to-merge, integration/trusted-boot

#10121 fix: detect GPT before ZFS
  go.mod
  go.sum
  pkg/machinery/go.mod
  pkg/machinery/go.sum
Labels: status/ok-to-test, status/ok-to-merge, integration/extensions

#10124 fix: a couple of imager panics/crashes
  pkg/imager/profile/profile.go
  pkg/machinery/extensions/extensions_test.go
  pkg/machinery/extensions/validate.go
  pkg/machinery/imager/quirks/quirks.go
Labels: status/ok-to-test, status/ok-to-merge

#10123 feat: update Linux to 6.12.9
  Makefile
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#10127 feat: add a kernel parameter to disable built-in auditd
  hack/release.toml
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/pkg/install/install.go
  pkg/machinery/constants/constants.go
  website/content/v1.10/reference/kernel.md
Labels: status/ok-to-test, status/ok-to-merge

#10125 fix: kube-apiserver authorizers order
  hack/release.toml
  internal/app/machined/pkg/controllers/k8s/control_plane.go
  internal/app/machined/pkg/controllers/k8s/control_plane_test.go
Labels: status/ok-to-test, status/ok-to-merge

#10130 fix: add informer resync period for node status watcher
  internal/app/machined/pkg/controllers/k8s/endpoint.go
  internal/app/machined/pkg/controllers/k8s/internal/nodewatch/nodewatch.go
  internal/app/machined/pkg/controllers/k8s/node_status.go
  internal/integration/base/k8s.go
  internal/pkg/discovery/registry/kubernetes.go
  pkg/machinery/constants/constants.go
Labels: status/ok-to-test, status/ok-to-merge

#10134 feat: update containerd to 2.0.2
  Makefile
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#10135 test: update `talosctl debug air-gapped`
  cmd/talosctl/cmd/mgmt/debug/air-gapped.go
  website/content/v1.10/advanced/developing-talos.md
Labels: status/ok-to-test, status/ok-to-merge

#10140 chore(ci): add test for OpenEBS MayaStor
  .github/workflows/ci.yaml
  .github/workflows/integration-qemu-csi-openebs-cron.yaml
  .github/workflows/slack-notify.yaml
  .kres.yaml
  hack/test/patches/openebs-cp.yaml
  hack/test/patches/openebs.yaml
  internal/integration/api/extensions_qemu.go
  internal/integration/api/volumes.go
  internal/integration/api/wipe.go
  internal/integration/base/api.go
  internal/integration/k8s/constants.go
  internal/integration/k8s/openebs.go
  internal/integration/k8s/testdata/openebs-diskpool.yaml
  internal/integration/k8s/testdata/openebs-values.yaml
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu-csi-openebs

#10146 chore(ci): save csi tests fio results
  .github/workflows/ci.yaml
  .github/workflows/integration-qemu-csi-longhorn-cron.yaml
  .github/workflows/integration-qemu-csi-openebs-cron.yaml
  .github/workflows/integration-qemu-csi-rook-ceph-cron.yaml
  .kres.yaml
  internal/integration/base/k8s.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu-csi-openebs

#10139 docs: add Radxa ROCK 5B docs to Single Board Computer section
  website/content/v1.10/introduction/support-matrix.md
  website/content/v1.10/talos-guides/configuration/disk-management.md
  website/content/v1.10/talos-guides/configuration/logging.md
  website/content/v1.10/talos-guides/install/single-board-computers/rock5b.md
  website/content/v1.9/introduction/support-matrix.md
  website/content/v1.9/talos-guides/configuration/disk-management.md
  website/content/v1.9/talos-guides/install/single-board-computers/rock5b.md
Labels: status/ok-to-merge

#10150 docs: update OpenEBS Mayastor installation
  website/content/v1.10/kubernetes-guides/configuration/replicated-local-storage-with-openebs.md
  website/content/v1.10/kubernetes-guides/configuration/storage.md
  website/content/v1.9/kubernetes-guides/configuration/replicated-local-storage-with-openebs.md
  website/content/v1.9/kubernetes-guides/configuration/storage.md
Labels: status/ok-to-test, status/ok-to-merge

#10149 feat: update Kubernetes to 1.32.1
  .github/workflows/ci.yaml
  .kres.yaml
  Makefile
  go.mod
  go.sum
  hack/test/e2e.sh
  pkg/machinery/constants/constants.go
  website/content/v1.10/reference/cli.md
  website/content/v1.10/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge, integration/image-cache

#10152 release(v1.9.2): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#10156 chore: clear cache after updating upstreams
  go.mod
  go.sum
  internal/pkg/dns/dns.go
  internal/pkg/dns/manager.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu, integration/misc-0

#10158 docs: update SideroLinkConfig example
  pkg/machinery/config/types/siderolink/siderolink.go
  pkg/machinery/config/types/siderolink/siderolink_doc.go
  pkg/machinery/config/types/siderolink/siderolink_test.go
  pkg/machinery/config/types/siderolink/testdata/document.yaml
  website/content/v1.10/reference/configuration/siderolink/siderolinkconfig.md
Labels: status/ok-to-test, status/ok-to-merge

#10155 fix: make etc binds read-only
  internal/app/machined/pkg/controllers/files/cri_registry_config.go
  internal/app/machined/pkg/controllers/files/etcfile.go
Labels: status/ok-to-test, status/ok-to-merge

#10161 fix: ignore forbidden error when waiting for pod eviction
  pkg/kubernetes/kubernetes.go
Labels: status/ok-to-test, status/ok-to-merge

#10170 chore: update Go to 1.23.5
  Makefile
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#10166 docs: update troubleshooting.md
  cmd/talosctl/cmd/talos/etcd.go
  website/content/v1.10/introduction/troubleshooting.md
  website/content/v1.9/introduction/troubleshooting.md
Labels: status/ok-to-merge

#10162 feat: generate iqn and nqn files.
  Dockerfile
  hack/release.toml
  internal/app/machined/pkg/controllers/cluster/node_identity.go
  internal/app/machined/pkg/controllers/files/iqn.go
  internal/app/machined/pkg/controllers/files/nqn.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
Labels: status/ok-to-test, status/ok-to-merge

#10173 refactor: extract platform metadata into Talos machinery
  pkg/machinery/platforms/platforms.go
  pkg/machinery/platforms/platforms_test.go
  pkg/machinery/platforms/sbcs.go
  pkg/machinery/platforms/sbcs_test.go
Labels: status/ok-to-test, status/ok-to-merge

#10175 fix: abort node watch on hostname change
  internal/app/machined/pkg/controllers/k8s/internal/nodewatch/nodewatch.go
  internal/app/machined/pkg/controllers/k8s/node_status.go
Labels: status/ok-to-test, status/ok-to-merge

#10186 chore(ci): fio benchmark results as separate artifacts
  .github/workflows/ci.yaml
  .github/workflows/integration-qemu-csi-longhorn-cron.yaml
  .github/workflows/integration-qemu-csi-openebs-cron.yaml
  .github/workflows/integration-qemu-csi-rook-ceph-cron.yaml
  .kres.yaml
Labels: status/ok-to-test, status/ok-to-merge

#10179 Documentation fix typo "an MacOS" to "on MacOS"
  website/content/v1.10/introduction/getting-started.md
  website/content/v1.10/talos-guides/install/local-platforms/qemu.md
  website/content/v1.10/talos-guides/install/local-platforms/virtualbox.md
  website/content/v1.10/talos-guides/install/virtualized-platforms/proxmox.md
  website/content/v1.7/introduction/getting-started.md
  website/content/v1.7/talos-guides/install/local-platforms/qemu.md
  website/content/v1.7/talos-guides/install/local-platforms/virtualbox.md
  website/content/v1.7/talos-guides/install/virtualized-platforms/proxmox.md
  website/content/v1.8/introduction/getting-started.md
  website/content/v1.8/talos-guides/install/local-platforms/qemu.md
  website/content/v1.8/talos-guides/install/local-platforms/virtualbox.md
  website/content/v1.8/talos-guides/install/virtualized-platforms/proxmox.md
  website/content/v1.9/introduction/getting-started.md
  website/content/v1.9/talos-guides/install/local-platforms/qemu.md
  website/content/v1.9/talos-guides/install/local-platforms/virtualbox.md
  website/content/v1.9/talos-guides/install/virtualized-platforms/proxmox.md
Labels: status/ok-to-merge

#10183 docs: remove the last mentions of `preserve` flag for Talos 1.8+
  website/content/v1.10/advanced/proprietary-kernel-modules.md
  website/content/v1.10/kubernetes-guides/configuration/ceph-with-rook.md
  website/content/v1.10/kubernetes-guides/configuration/local-storage.md
  website/content/v1.10/learn-more/architecture.md
  website/content/v1.10/talos-guides/upgrading-talos.md
  website/content/v1.8/talos-guides/upgrading-talos.md
  website/content/v1.9/talos-guides/upgrading-talos.md
Labels: status/ok-to-test, status/ok-to-merge

#10193 feat: update tools/pkgs/extras
  Makefile
  hack/release.toml
  internal/app/machined/pkg/controllers/secrets/data/ca-certificates
  pkg/machinery/api/cluster/cluster.pb.go
  pkg/machinery/api/cluster/cluster_grpc.pb.go
  pkg/machinery/api/common/common.pb.go
  pkg/machinery/api/inspect/inspect.pb.go
  pkg/machinery/api/inspect/inspect_grpc.pb.go
  pkg/machinery/api/machine/machine.pb.go
  pkg/machinery/api/machine/machine_grpc.pb.go
  pkg/machinery/api/resource/config/config.pb.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/cluster/cluster.pb.go
  pkg/machinery/api/resource/definitions/cri/cri.pb.go
  pkg/machinery/api/resource/definitions/enums/enums.pb.go
  pkg/machinery/api/resource/definitions/etcd/etcd.pb.go
  pkg/machinery/api/resource/definitions/extensions/extensions.pb.go
  pkg/machinery/api/resource/definitions/files/files.pb.go
  pkg/machinery/api/resource/definitions/hardware/hardware.pb.go
  pkg/machinery/api/resource/definitions/k8s/k8s.pb.go
  pkg/machinery/api/resource/definitions/kubeaccess/kubeaccess.pb.go
  pkg/machinery/api/resource/definitions/kubespan/kubespan.pb.go
  pkg/machinery/api/resource/definitions/network/network.pb.go
  pkg/machinery/api/resource/definitions/perf/perf.pb.go
  pkg/machinery/api/resource/definitions/proto/proto.pb.go
  pkg/machinery/api/resource/definitions/runtime/runtime.pb.go
  pkg/machinery/api/resource/definitions/secrets/secrets.pb.go
  pkg/machinery/api/resource/definitions/siderolink/siderolink.pb.go
  pkg/machinery/api/resource/definitions/time/time.pb.go
  pkg/machinery/api/resource/definitions/v1alpha1/v1alpha1.pb.go
  pkg/machinery/api/resource/network/device_config.pb.go
  pkg/machinery/api/security/security.pb.go
  pkg/machinery/api/security/security_grpc.pb.go
  pkg/machinery/api/storage/storage.pb.go
  pkg/machinery/api/storage/storage_grpc.pb.go
  pkg/machinery/api/time/time.pb.go
  pkg/machinery/api/time/time_grpc.pb.go
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/extras
  pkg/machinery/gendata/data/pkgs
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/amd64/snp.efi
  pkg/provision/providers/vm/internal/ipxe/data/ipxe/arm64/snp.efi
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu, integration/qemu-csi, integration/extensions, integration/aws-nvidia-oss

#10197 fix: disks with 4k sector size and systemd-boot
  .github/workflows/ci.yaml
  .github/workflows/integration-misc-0-cron.yaml
  .kres.yaml
  Makefile
  go.mod
  go.sum
  hack/test/e2e-qemu.sh
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/provision/providers/qemu/launch.go
Labels: status/ok-to-test, status/ok-to-merge

#10201 fix: bring back disk UUID
  api/resource/definitions/block/block.proto
  go.mod
  go.sum
  internal/app/machined/pkg/controllers/block/disks.go
  internal/app/storaged/server.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/block/block_vtproto.pb.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
  pkg/machinery/config/types/v1alpha1/v1alpha1_provider_test.go
  pkg/machinery/go.mod
  pkg/machinery/go.sum
  pkg/machinery/resources/block/disk.go
  website/content/v1.10/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge

#10207 fix: invalid date field in iqn/nqn
  internal/app/machined/pkg/controllers/files/iqn.go
  internal/app/machined/pkg/controllers/files/nqn.go
Labels: status/ok-to-merge

#10195 docs: fix typos and add more explanations in docs
  website/content/v1.10/introduction/getting-started.md
  website/content/v1.10/introduction/prodnotes.md
  website/content/v1.10/kubernetes-guides/configuration/local-storage.md
  website/content/v1.10/talos-guides/install/local-platforms/qemu.md
  website/content/v1.10/talos-guides/install/local-platforms/virtualbox.md
  website/content/v1.10/talos-guides/install/virtualized-platforms/hyper-v.md
  website/content/v1.10/talos-guides/install/virtualized-platforms/proxmox.md
  website/content/v1.7/introduction/getting-started.md
  website/content/v1.7/introduction/prodnotes.md
  website/content/v1.7/talos-guides/install/local-platforms/qemu.md
  website/content/v1.7/talos-guides/install/local-platforms/virtualbox.md
  website/content/v1.7/talos-guides/install/virtualized-platforms/hyper-v.md
  website/content/v1.7/talos-guides/install/virtualized-platforms/proxmox.md
  website/content/v1.8/introduction/getting-started.md
  website/content/v1.8/introduction/prodnotes.md
  website/content/v1.8/kubernetes-guides/configuration/local-storage.md
  website/content/v1.8/talos-guides/install/local-platforms/qemu.md
  website/content/v1.8/talos-guides/install/local-platforms/virtualbox.md
  website/content/v1.8/talos-guides/install/virtualized-platforms/hyper-v.md
  website/content/v1.8/talos-guides/install/virtualized-platforms/proxmox.md
  website/content/v1.9/introduction/getting-started.md
  website/content/v1.9/introduction/prodnotes.md
  website/content/v1.9/kubernetes-guides/configuration/local-storage.md
  website/content/v1.9/talos-guides/install/local-platforms/qemu.md
  website/content/v1.9/talos-guides/install/local-platforms/virtualbox.md
  website/content/v1.9/talos-guides/install/virtualized-platforms/hyper-v.md
  website/content/v1.9/talos-guides/install/virtualized-platforms/proxmox.md
Labels: status/ok-to-merge

#10194 docs: update disk-encryption.md
  website/content/v1.10/talos-guides/configuration/disk-encryption.md
  website/content/v1.8/talos-guides/configuration/disk-encryption.md
  website/content/v1.9/talos-guides/configuration/disk-encryption.md
Labels: status/ok-to-merge

#10216 fix(ci): wait for longhorn node resource
  internal/integration/base/k8s.go
  internal/integration/k8s/longhorn.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu-csi-longhorn

#10210 feat: provide stable symlinks in disk resources
  api/resource/definitions/block/block.proto
  internal/app/machined/pkg/controllers/block/devices.go
  internal/app/machined/pkg/controllers/block/disks.go
  internal/app/machined/pkg/controllers/block/internal/inotify/inotify.go
  internal/app/machined/pkg/controllers/block/internal/inotify/inotify_test.go
  internal/app/machined/pkg/controllers/block/symlinks.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
  internal/integration/api/volumes.go
  pkg/machinery/api/resource/definitions/block/block.pb.go
  pkg/machinery/api/resource/definitions/block/block_vtproto.pb.go
  pkg/machinery/resources/block/block.go
  pkg/machinery/resources/block/block_test.go
  pkg/machinery/resources/block/deep_copy.generated.go
  pkg/machinery/resources/block/disk.go
  pkg/machinery/resources/block/symlink.go
  website/content/v1.10/reference/api.md
Labels: status/ok-to-test, status/ok-to-merge

#10217 feat: generate iso's with both UKI and grub
  .github/workflows/ci.yaml
  .github/workflows/integration-misc-2-cron.yaml
  .kres.yaml
  Makefile
  hack/release.toml
  hack/test/e2e-iso.sh
  hack/test/e2e-qemu.sh
  pkg/imager/imager.go
  pkg/imager/iso/grub.go
  pkg/imager/iso/hybrid.go
  pkg/imager/iso/iso.go
  pkg/imager/iso/uefi.go
  pkg/imager/out.go
  pkg/provision/providers/qemu/launch.go
  pkg/provision/providers/qemu/node.go
Labels: status/ok-to-test, status/ok-to-merge

#10224 fix(ci): k8s integration suite wait for resource.
  internal/integration/base/k8s.go
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu-csi-longhorn

#10220 refactor: all network merge controllers
  internal/app/machined/pkg/controllers/network/address_merge.go
  internal/app/machined/pkg/controllers/network/address_merge_test.go
  internal/app/machined/pkg/controllers/network/generic_merge.go
  internal/app/machined/pkg/controllers/network/hostname_merge.go
  internal/app/machined/pkg/controllers/network/hostname_merge_test.go
  internal/app/machined/pkg/controllers/network/link_merge.go
  internal/app/machined/pkg/controllers/network/link_merge_test.go
  internal/app/machined/pkg/controllers/network/operator_merge.go
  internal/app/machined/pkg/controllers/network/operator_merge_test.go
  internal/app/machined/pkg/controllers/network/resolver_merge.go
  internal/app/machined/pkg/controllers/network/resolver_merge_test.go
  internal/app/machined/pkg/controllers/network/route_merge.go
  internal/app/machined/pkg/controllers/network/route_merge_test.go
  internal/app/machined/pkg/controllers/network/timeserver_merge.go
  internal/app/machined/pkg/controllers/network/timeserver_merge_test.go
  internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
Labels: status/ok-to-test, status/ok-to-merge

#10223 Update multus.md
  website/content/v1.10/kubernetes-guides/network/multus.md
  website/content/v1.9/kubernetes-guides/network/multus.md
Labels: status/ok-to-merge

#10230 fix: pe uki extract
  internal/pkg/uki/internal/pe/extract.go
  internal/pkg/uki/internal/pe/extract_test.go
Labels: status/ok-to-test, status/ok-to-merge

#10233 feat: update etcd to 3.5.18
  go.mod
  go.sum
  hack/release.toml
  pkg/machinery/constants/constants.go
  website/content/v1.10/reference/configuration/v1alpha1/config.md
Labels: status/ok-to-test, status/ok-to-merge

#10235 feat: update Linux to 6.2.11
  Makefile
  hack/release.toml
  pkg/machinery/constants/constants.go
  pkg/machinery/gendata/data/pkgs
Labels: status/ok-to-test, status/ok-to-merge

#10236 feat: add Orange Pi 5 to Image Factory platforms and documentation
  pkg/machinery/platforms/sbcs.go
  website/content/v1.10/introduction/support-matrix.md
  website/content/v1.10/talos-guides/install/single-board-computers/orangepi_5.md
  website/content/v1.9/introduction/support-matrix.md
  website/content/v1.9/talos-guides/install/single-board-computers/orangepi_5.md
Labels: status/ok-to-merge

#10228 feat: support kexec from uki
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/bootloader.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/kexec/kexec.go
  internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/sdboot.go
  internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
  internal/pkg/uki/internal/pe/extract.go
Labels: status/ok-to-test, status/ok-to-merge, integration/misc-0, integration/misc-2

#10242 release(v1.9.3): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  website/content/v1.9/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge

#10241 Add iscsi-tools extension to Prerequisites
  website/content/v1.10/kubernetes-guides/configuration/synology-csi.md
  website/content/v1.9/kubernetes-guides/configuration/synology-csi.md
Labels: status/ok-to-merge

#10238 docs: add note about vmxnet and flannel conflict
  website/content/v1.10/talos-guides/install/virtualized-platforms/vmware.md
  website/content/v1.9/talos-guides/install/virtualized-platforms/vmware.md
Labels: status/ok-to-merge

#10251 fix: handling of PE sections with duplicate names
  internal/pkg/uki/internal/pe/native.go
  internal/pkg/uki/internal/pe/pe_test.go
Labels: status/ok-to-test, status/ok-to-merge

#10255 fix: ensure proper closure of client.Client.conn with finalizer
  pkg/machinery/client/client.go
  pkg/machinery/client/client_test.go
  pkg/machinery/client/export_test.go
Labels: status/ok-to-test, status/ok-to-merge

#10256 fix: use local NTP for AWS platform
  internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
  internal/app/machined/pkg/runtime/v1alpha1/platform/aws/testdata/expected.yaml
Labels: status/ok-to-test, status/ok-to-merge

#10259 Update hyper-v.md
  website/content/v1.10/talos-guides/install/virtualized-platforms/hyper-v.md
  website/content/v1.9/talos-guides/install/virtualized-platforms/hyper-v.md
Labels: status/ok-to-merge

#10263 fix: do not close client.Client.conn with finalizer
  pkg/machinery/client/client.go
  pkg/machinery/client/client_test.go
  pkg/machinery/client/export_test.go
Labels: status/ok-to-test, status/ok-to-merge

#10261 release(v1.10.0-alpha.1): prepare release
  CHANGELOG.md
  go.mod
  pkg/machinery/gendata/data/tag
  pkg/machinery/version/os-release
  website/content/v1.10/reference/cli.md
Labels: status/ok-to-test, status/ok-to-merge, integration/qemu
